// isms-core-platform/frontend/src/pages/MitreHeatmap.tsx
import { useMemo, useState } from 'react'
import {
  Alert, Autocomplete, Box, Chip, CircularProgress, FormControlLabel,
  Paper, Switch, TextField, ToggleButton, ToggleButtonGroup, Tooltip, Typography,
} from '@mui/material'
import { useQuery } from '@tanstack/react-query'
import { feedsApi, type MitreGroup, type MitreHeatmapTechnique } from '../api/feedsApi'
import PageHeader from '../components/PageHeader'

const INTEL_COLOR = '#B84F00'
const CELL_W = 128
const CELL_H = 20

// Canonical tactic display labels
const TACTIC_LABELS: Record<string, string> = {
  'reconnaissance':       'Reconnaissance',
  'resource-development': 'Resource Dev.',
  'initial-access':       'Initial Access',
  'execution':            'Execution',
  'persistence':          'Persistence',
  'privilege-escalation': 'Priv. Escalation',
  'defense-evasion':      'Defense Evasion',
  'credential-access':    'Credential Access',
  'discovery':            'Discovery',
  'lateral-movement':     'Lateral Movement',
  'collection':           'Collection',
  'command-and-control':  'C2',
  'exfiltration':         'Exfiltration',
  'impact':               'Impact',
}

// 5-level color ramp (0 = uncovered)
function cellBg(count: number, max: number): string {
  if (count === 0) return 'transparent'
  const ratio = Math.min(count / Math.max(max, 1), 1)
  if (ratio < 0.1) return '#FFE0C8'
  if (ratio < 0.25) return '#FFBC8A'
  if (ratio < 0.5)  return '#F09050'
  if (ratio < 0.75) return '#D06020'
  return INTEL_COLOR
}

function cellTextColor(count: number, max: number): string {
  const ratio = Math.min(count / Math.max(max, 1), 1)
  return ratio >= 0.5 ? '#fff' : 'inherit'
}

// Build per-tactic rows: parents first, then subs grouped under their parent
function buildTacticRows(
  techniques: MitreHeatmapTechnique[],
  tactic: string,
  showSubs: boolean,
): MitreHeatmapTechnique[] {
  const inTactic = techniques.filter(t => t.tactics.includes(tactic))
  const parents = inTactic
    .filter(t => !t.is_subtechnique)
    .sort((a, b) => a.technique_id.localeCompare(b.technique_id))

  if (!showSubs) return parents

  const subs = inTactic.filter(t => t.is_subtechnique)
  const rows: MitreHeatmapTechnique[] = []
  for (const p of parents) {
    rows.push(p)
    const mySubs = subs
      .filter(s => s.technique_id.startsWith(p.technique_id + '.'))
      .sort((a, b) => a.technique_id.localeCompare(b.technique_id))
    rows.push(...mySubs)
  }
  return rows
}

interface TechCellProps {
  tech: MitreHeatmapTechnique
  maxCount: number
  selected: boolean
  onSelect: (t: MitreHeatmapTechnique) => void
}

function TechCell({ tech, maxCount, selected, onSelect }: TechCellProps) {
  const bg = cellBg(tech.usage_count, maxCount)
  const fg = tech.usage_count > 0 ? cellTextColor(tech.usage_count, maxCount) : 'text.disabled'
  const isSub = tech.is_subtechnique

  return (
    <Tooltip
      title={`${tech.technique_id} — ${tech.name}${tech.usage_count > 0 ? ` (${tech.usage_count} actor${tech.usage_count !== 1 ? 's' : ''})` : ''}`}
      placement="right"
      arrow
    >
      <Box
        onClick={() => onSelect(tech)}
        sx={{
          width: CELL_W,
          height: CELL_H,
          px: 0.5,
          display: 'flex',
          alignItems: 'center',
          cursor: 'pointer',
          backgroundColor: bg,
          borderRadius: '2px',
          mb: '1px',
          border: selected ? `1.5px solid ${INTEL_COLOR}` : '1px solid',
          borderColor: selected ? INTEL_COLOR : tech.usage_count > 0 ? 'transparent' : 'divider',
          pl: isSub ? 1.5 : 0.5,
          '&:hover': { opacity: 0.8, borderColor: INTEL_COLOR },
        }}
      >
        <Typography
          noWrap
          sx={{
            fontSize: isSub ? '0.6rem' : '0.63rem',
            fontWeight: isSub ? 400 : 600,
            color: tech.usage_count > 0 ? fg : 'text.disabled',
            fontFamily: 'monospace',
            lineHeight: 1,
          }}
        >
          {tech.technique_id}
        </Typography>
      </Box>
    </Tooltip>
  )
}

export default function MitreHeatmap() {
  const [source, setSource] = useState<'attack_v18' | 'attack_v19'>('attack_v18')
  const [selectedGroups, setSelectedGroups] = useState<MitreGroup[]>([])
  const [includeSoftware, setIncludeSoftware] = useState(true)
  const [showSubs, setShowSubs] = useState(true)
  const [selected, setSelected] = useState<MitreHeatmapTechnique | null>(null)

  // Load all groups for the autocomplete
  const { data: groupData } = useQuery({
    queryKey: ['feeds', 'groups', 'all', source],
    queryFn: () => feedsApi.getMitreGroups({ source, deprecated: false, per_page: 200 }),
  })
  const allGroups = groupData?.items ?? []

  const groupIdsParam = selectedGroups.length > 0
    ? selectedGroups.map(g => g.group_id).join(',')
    : undefined

  const { data, isLoading, error } = useQuery({
    queryKey: ['feeds', 'heatmap', source, groupIdsParam ?? 'all', includeSoftware],
    queryFn: () => feedsApi.getMitreHeatmap({
      source,
      group_ids: groupIdsParam,
      include_software: includeSoftware,
    }),
    staleTime: 60_000,
  })

  const tactics = data?.tactic_order ?? []
  const techniques = data?.techniques ?? []

  // Max usage_count across all techniques — for color scaling
  const maxCount = useMemo(
    () => Math.max(...techniques.map(t => t.usage_count), 1),
    [techniques],
  )

  // Per-tactic rows (memoised)
  const tacticRows = useMemo(() => {
    const map: Record<string, MitreHeatmapTechnique[]> = {}
    for (const tac of tactics) {
      map[tac] = buildTacticRows(techniques, tac, showSubs)
    }
    return map
  }, [tactics, techniques, showSubs])

  function handleSelect(tech: MitreHeatmapTechnique) {
    setSelected(prev => prev?.stix_id === tech.stix_id ? null : tech)
  }

  const coveragePct = data
    ? Math.round((data.covered / Math.max(data.total_techniques, 1)) * 100)
    : 0

  return (
    <Box sx={{ p: 3 }}>
      <PageHeader
        title="MITRE ATT&CK Heatmap"
        subtitle="Technique coverage by threat actor group — click any technique to inspect"
        helpSection="mitre-attack"
      />

      {/* ── Controls ── */}
      <Box sx={{ display: 'flex', gap: 1.5, mb: 2, flexWrap: 'wrap', alignItems: 'center' }}>
        <ToggleButtonGroup
          size="small"
          value={source}
          exclusive
          onChange={(_, v) => v && (setSource(v), setSelected(null))}
        >
          <ToggleButton value="attack_v18" sx={{ fontSize: '0.72rem', px: 1.5 }}>v18</ToggleButton>
          <ToggleButton value="attack_v19" sx={{ fontSize: '0.72rem', px: 1.5 }}>v19</ToggleButton>
        </ToggleButtonGroup>

        <Autocomplete
          multiple
          size="small"
          options={allGroups}
          value={selectedGroups}
          onChange={(_, v) => { setSelectedGroups(v); setSelected(null) }}
          getOptionLabel={g => `${g.group_id} — ${g.name}`}
          isOptionEqualToValue={(a, b) => a.group_id === b.group_id}
          renderInput={params => (
            <TextField
              {...params}
              placeholder={selectedGroups.length === 0 ? 'All groups (aggregate view)' : ''}
              sx={{ minWidth: 340 }}
            />
          )}
          renderTags={(value, getTagProps) =>
            value.map((g, i) => (
              <Chip
                {...getTagProps({ index: i })}
                key={g.group_id}
                label={g.group_id}
                size="small"
                sx={{ fontSize: '0.65rem', height: 18 }}
              />
            ))
          }
          sx={{ minWidth: 340 }}
          limitTags={4}
        />

        <FormControlLabel
          control={
            <Switch
              size="small"
              checked={includeSoftware}
              onChange={e => setIncludeSoftware(e.target.checked)}
            />
          }
          label={<Typography variant="caption">Include software</Typography>}
        />

        <FormControlLabel
          control={
            <Switch
              size="small"
              checked={showSubs}
              onChange={e => setShowSubs(e.target.checked)}
            />
          }
          label={<Typography variant="caption">Sub-techniques</Typography>}
        />
      </Box>

      {/* ── Stats bar ── */}
      {data && (
        <Box sx={{ display: 'flex', gap: 3, mb: 2, flexWrap: 'wrap', alignItems: 'center' }}>
          <Box>
            <Typography variant="h6" sx={{ fontWeight: 700, color: INTEL_COLOR, lineHeight: 1 }}>
              {data.covered.toLocaleString()} / {data.total_techniques.toLocaleString()}
            </Typography>
            <Typography variant="caption" color="text.secondary">Techniques covered ({coveragePct}%)</Typography>
          </Box>
          <Box>
            <Typography variant="h6" sx={{ fontWeight: 700, color: INTEL_COLOR, lineHeight: 1 }}>
              {data.selected_actors.toLocaleString()}
            </Typography>
            <Typography variant="caption" color="text.secondary">
              {selectedGroups.length > 0 ? 'Selected actors' : `Actors in scope${includeSoftware ? ' (groups + software)' : ''}`}
            </Typography>
          </Box>
          <Box>
            <Typography variant="h6" sx={{ fontWeight: 700, color: INTEL_COLOR, lineHeight: 1 }}>
              {maxCount}
            </Typography>
            <Typography variant="caption" color="text.secondary">Max actors / technique</Typography>
          </Box>

          {/* Color legend */}
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5, ml: 'auto' }}>
            <Typography variant="caption" color="text.secondary" sx={{ mr: 0.5 }}>Coverage:</Typography>
            {[0, 0.1, 0.3, 0.6, 1].map((ratio, i) => (
              <Tooltip key={i} title={i === 0 ? 'Not covered' : `${Math.round(ratio * maxCount)}+ actors`}>
                <Box sx={{
                  width: 20, height: 14, borderRadius: '2px',
                  backgroundColor: cellBg(Math.round(ratio * maxCount), maxCount),
                  border: '1px solid', borderColor: 'divider',
                }} />
              </Tooltip>
            ))}
            <Typography variant="caption" color="text.secondary" sx={{ ml: 0.5 }}>High</Typography>
          </Box>
        </Box>
      )}

      {isLoading && (
        <Box sx={{ display: 'flex', justifyContent: 'center', py: 8 }}>
          <CircularProgress size={32} />
        </Box>
      )}
      {error && <Alert severity="error" sx={{ mb: 2 }}>Failed to load heatmap data</Alert>}

      {/* ── Main heatmap + detail panel ── */}
      {data && !isLoading && (
        <Box sx={{ display: 'flex', gap: 2, alignItems: 'flex-start' }}>
          {/* Heatmap grid — horizontally scrollable */}
          <Box sx={{ overflowX: 'auto', flex: 1, minWidth: 0 }}>
            <Box sx={{ display: 'flex', gap: '2px', minWidth: tactics.length * (CELL_W + 2) }}>
              {tactics.map(tac => {
                const rows = tacticRows[tac] ?? []
                return (
                  <Box key={tac} sx={{ width: CELL_W, flexShrink: 0 }}>
                    {/* Tactic header */}
                    <Box sx={{
                      height: 32,
                      display: 'flex',
                      alignItems: 'center',
                      px: 0.5,
                      mb: 0.5,
                      backgroundColor: 'action.hover',
                      borderRadius: '4px 4px 0 0',
                      borderBottom: `2px solid ${INTEL_COLOR}`,
                    }}>
                      <Typography sx={{ fontSize: '0.65rem', fontWeight: 700, color: INTEL_COLOR, lineHeight: 1.1 }}>
                        {TACTIC_LABELS[tac] ?? tac}
                      </Typography>
                    </Box>

                    {/* Technique cells */}
                    {rows.map(tech => (
                      <TechCell
                        key={`${tac}-${tech.stix_id}`}
                        tech={tech}
                        maxCount={maxCount}
                        selected={selected?.stix_id === tech.stix_id}
                        onSelect={handleSelect}
                      />
                    ))}

                    {rows.length === 0 && (
                      <Typography variant="caption" color="text.disabled" sx={{ px: 0.5, fontSize: '0.6rem' }}>
                        No data
                      </Typography>
                    )}
                  </Box>
                )
              })}
            </Box>
          </Box>

          {/* ── Detail panel ── */}
          {selected && (
            <Paper variant="outlined" sx={{ width: 300, flexShrink: 0, borderRadius: 2, p: 2, position: 'sticky', top: 24, maxHeight: '80vh', overflowY: 'auto' }}>
              <Box sx={{ display: 'flex', alignItems: 'baseline', gap: 1, mb: 0.5 }}>
                <Typography variant="subtitle2" sx={{ fontFamily: 'monospace', color: INTEL_COLOR, fontWeight: 700 }}>
                  {selected.technique_id}
                </Typography>
                {selected.is_subtechnique && (
                  <Chip label="sub" size="small" sx={{ fontSize: '0.6rem', height: 16 }} />
                )}
              </Box>
              <Typography variant="body2" fontWeight={600} sx={{ mb: 1 }}>{selected.name}</Typography>

              {/* Tactics */}
              <Box sx={{ mb: 1.5 }}>
                {selected.tactics.map(t => (
                  <Chip
                    key={t}
                    label={TACTIC_LABELS[t] ?? t}
                    size="small"
                    sx={{ fontSize: '0.62rem', height: 18, mr: 0.25, mb: 0.25 }}
                  />
                ))}
              </Box>

              {/* Coverage */}
              <Box sx={{ mb: 1.5, p: 1, backgroundColor: `${INTEL_COLOR}18`, borderRadius: 1 }}>
                <Typography variant="caption" display="block" color="text.secondary">
                  Used by
                </Typography>
                <Typography variant="h6" sx={{ fontWeight: 700, color: INTEL_COLOR, lineHeight: 1.2 }}>
                  {selected.usage_count}
                </Typography>
                <Typography variant="caption" color="text.secondary">
                  {selected.usage_count === 1 ? 'actor' : 'actors'} in scope
                </Typography>
              </Box>

              {/* Actor list */}
              {selected.used_by.length > 0 && (
                <Box>
                  <Typography variant="caption" color="text.secondary" display="block" sx={{ mb: 0.5, fontWeight: 600 }}>
                    Actors ({selected.used_by.length}{selected.usage_count > 30 ? '+' : ''}):
                  </Typography>
                  {selected.used_by.map(name => (
                    <Typography
                      key={name}
                      variant="caption"
                      display="block"
                      sx={{ fontSize: '0.7rem', py: 0.1, color: 'text.primary' }}
                    >
                      · {name}
                    </Typography>
                  ))}
                </Box>
              )}

              {selected.usage_count === 0 && (
                <Typography variant="caption" color="text.disabled">
                  Not attributed to any actor in the current scope.
                </Typography>
              )}
            </Paper>
          )}
        </Box>
      )}
    </Box>
  )
}

// isms-core-platform/frontend/src/app/pages/mitre-heatmap/mitre-heatmap.component.ts
import { Component, inject, signal, computed } from '@angular/core'
import { DecimalPipe } from '@angular/common'
import { FormsModule } from '@angular/forms'
import { firstValueFrom } from 'rxjs'
import { injectQuery } from '@tanstack/angular-query-experimental'

import { MatFormFieldModule } from '@angular/material/form-field'
import { MatInputModule } from '@angular/material/input'
import { MatSelectModule } from '@angular/material/select'
import { MatIconModule } from '@angular/material/icon'
import { MatTooltipModule } from '@angular/material/tooltip'
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner'
import { MatSlideToggleModule } from '@angular/material/slide-toggle'

import { FeedsApiService, MitreHeatmapTechnique } from '../../api/feeds-api.service'
import { ThemeService } from '../../core/services/theme.service'
import { PageHeaderComponent } from '../../shared/components/page-header.component'

const INTEL_DARK  = '#e06030'
const INTEL_LIGHT = '#c64227'

const TACTIC_SHORT: Record<string, string> = {
  'reconnaissance':       'Recon',
  'resource-development': 'Resource Dev',
  'initial-access':       'Initial Access',
  'execution':            'Execution',
  'persistence':          'Persistence',
  'privilege-escalation': 'Priv. Escalation',
  'defense-evasion':      'Defense Evasion',
  'defense-impairment':   'Def. Impairment',
  'credential-access':    'Credential Access',
  'discovery':            'Discovery',
  'lateral-movement':     'Lateral Movement',
  'collection':           'Collection',
  'command-and-control':  'C2',
  'exfiltration':         'Exfiltration',
  'impact':               'Impact',
}

function heatColor(count: number, max: number, isDark: boolean): string {
  if (count === 0) return isDark ? 'rgba(255,255,255,0.04)' : 'rgba(44,44,42,0.06)'
  const ratio = Math.min(count / Math.max(max, 1), 1)
  if (isDark) {
    if (ratio < 0.15) return 'rgba(224,96,48,0.20)'
    if (ratio < 0.35) return 'rgba(224,96,48,0.40)'
    if (ratio < 0.60) return 'rgba(224,96,48,0.65)'
    if (ratio < 0.85) return 'rgba(224,96,48,0.85)'
    return '#e06030'
  } else {
    if (ratio < 0.15) return 'rgba(186,117,23,0.18)'
    if (ratio < 0.35) return 'rgba(186,117,23,0.38)'
    if (ratio < 0.60) return 'rgba(186,117,23,0.60)'
    if (ratio < 0.85) return 'rgba(186,117,23,0.80)'
    return '#c64227'
  }
}

function textColor(count: number, max: number): string {
  const ratio = Math.min(count / Math.max(max, 1), 1)
  return ratio >= 0.5 ? '#fff' : 'inherit'
}

@Component({
  selector: 'app-mitre-heatmap',
  standalone: true,
  imports: [
    DecimalPipe, FormsModule, PageHeaderComponent,
    MatFormFieldModule, MatInputModule, MatSelectModule,
    MatIconModule, MatTooltipModule, MatProgressSpinnerModule,
    MatSlideToggleModule,
  ],
  template: `
<div class="hm-page">
  <app-page-header
    title="ATT&CK Heatmap"
    subtitle="MITRE ATT&CK — technique coverage by threat actor group"
  />

  <!-- Controls -->
  <div class="hm-controls">
    <mat-form-field appearance="outline" subscriptSizing="dynamic" class="hm-group-field">
      <mat-label>Filter by group</mat-label>
      <mat-icon matPrefix>filter_list</mat-icon>
      <mat-select [ngModel]="selectedGroupIds()" (ngModelChange)="onGroupChange($event)" multiple>
        @for (g of allGroups(); track g.group_id) {
          <mat-option [value]="g.group_id">{{ g.group_id }} — {{ g.name }}</mat-option>
        }
      </mat-select>
    </mat-form-field>
    <mat-slide-toggle [checked]="includeSoftware()" (change)="includeSoftware.set($event.checked)">
      Include software
    </mat-slide-toggle>
    <mat-slide-toggle [checked]="showSubs()" (change)="showSubs.set($event.checked)">
      Sub-techniques
    </mat-slide-toggle>
  </div>

  <!-- Stats + legend -->
  @if (heatmapQuery.data(); as hm) {
    <div class="hm-stats-row">
      <div class="mitre-stats" style="margin-bottom:0">
        <div>
          <div class="mitre-stat__val" [style.color]="intelColor">{{ hm.covered | number }} / {{ hm.total_techniques | number }}</div>
          <div class="mitre-stat__lbl">Techniques covered ({{ coveragePct() }}%)</div>
        </div>
        <div>
          <div class="mitre-stat__val" [style.color]="intelColor">{{ hm.selected_actors | number }}</div>
          <div class="mitre-stat__lbl">{{ selectedGroupIds().length > 0 ? 'Selected actors' : 'Actors in scope' }}</div>
        </div>
        <div>
          <div class="mitre-stat__val" [style.color]="intelColor">{{ maxCount() }}</div>
          <div class="mitre-stat__lbl">Max actors / technique</div>
        </div>
      </div>
      <!-- Legend -->
      <div class="hm-legend">
        <span class="hm-legend__label">Coverage:</span>
        @for (s of legendSwatches(); track $index) {
          <div class="hm-legend__swatch" [matTooltip]="s.label" [style.background]="s.bg" [style.border]="'1px solid rgba(0,0,0,0.1)'"></div>
        }
        <span class="hm-legend__label">High</span>
      </div>
    </div>
  }

  @if (heatmapQuery.isLoading()) {
    <div class="hm-spinner"><mat-spinner diameter="32" /></div>
  }
  @if (heatmapQuery.isError()) {
    <div class="mitre-error">Failed to load heatmap data.</div>
  }

  <!-- HEATMAP GRID -->
  @if (!heatmapQuery.isLoading() && heatmapQuery.data(); as hm) {
    <div class="hm-outer">
      <div class="hm-grid-wrap">
        <div class="hm-grid" [style.grid-template-columns]="'repeat(' + hm.tactic_order.length + ', minmax(80px, 1fr))'">

          <!-- Tactic headers -->
          @for (tac of hm.tactic_order; track tac) {
            <div class="hm-tactic-hdr" [matTooltip]="tac.replace(/-/g, ' ')">
              {{ tacticShort(tac) }}
            </div>
          }

          <!-- Technique cells per tactic column -->
          @for (tac of hm.tactic_order; track tac) {
            <div class="hm-col">
              @for (tech of techsByTactic()[tac]; track tech.stix_id) {
                <div class="hm-cell"
                  [class.hm-cell--sub]="tech.is_subtechnique"
                  [class.hm-cell--selected]="selectedTech()?.stix_id === tech.stix_id"
                  [style.background]="heatColor(tech.usage_count, maxCount())"
                  [style.color]="textColor(tech.usage_count, maxCount())"
                  [matTooltip]="tech.technique_id + ' — ' + tech.name + (tech.usage_count > 0 ? ' (' + tech.usage_count + ' actors)' : '')"
                  (click)="onCellClick(tech)">
                  <span class="hm-cell__id">{{ tech.technique_id }}</span>
                </div>
              }
            </div>
          }
        </div>
      </div>

      <!-- Detail panel -->
      @if (selectedTech(); as tech) {
        <div class="mitre-detail hm-detail">
          <div class="mitre-detail__id" [style.color]="intelColor">{{ tech.technique_id }}</div>
          <div class="mitre-detail__name">{{ tech.name }}</div>
          @if (tech.is_subtechnique) {
            <span class="mitre-chip" style="margin-bottom:8px;display:inline-block">Sub-technique</span>
          }
          <div class="mitre-detail__label">Tactics</div>
          <div class="chip-row" style="gap:4px;margin-bottom:10px">
            @for (t of tech.tactics; track t) {
              <span class="mitre-chip">{{ tacticShort(t) }}</span>
            }
          </div>

          <!-- Coverage box -->
          <div class="hm-coverage-box" [style.background]="intelColor + '18'">
            <div class="hm-coverage__count" [style.color]="intelColor">{{ tech.usage_count }}</div>
            <div class="hm-coverage__lbl">{{ tech.usage_count === 1 ? 'actor' : 'actors' }} in scope</div>
          </div>

          @if (tech.used_by.length > 0) {
            <div class="mitre-detail__label">Used by</div>
            <div class="mitre-detail__actors">
              @for (name of tech.used_by; track name) {
                <div class="mitre-detail__actor">{{ name }}</div>
              }
            </div>
          }
          @if (tech.usage_count === 0) {
            <div class="hm-no-actors">Not attributed to any actor in the current scope.</div>
          }
        </div>
      }
    </div>
  }
</div>
  `,
  styles: [`
    .hm-page { display: flex; flex-direction: column; gap: 16px; }

    .hm-controls {
      display: flex; gap: 12px; align-items: center; flex-wrap: wrap;
    }
    .hm-group-field { flex: 1; min-width: 260px; max-width: 400px; }

    .hm-stats-row {
      display: flex; justify-content: space-between; align-items: center;
      flex-wrap: wrap; gap: 12px;
    }
    .hm-legend {
      display: flex; align-items: center; gap: 4px;
    }
    .hm-legend__label { font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); }
    .hm-legend__swatch { width: 22px; height: 14px; border-radius: 2px; }

    .hm-spinner { display: flex; justify-content: center; padding: 64px; }

    .hm-outer { display: flex; gap: 16px; align-items: flex-start; }

    .hm-grid-wrap {
      flex: 1; min-width: 0; overflow-x: auto;
      border: 1px solid var(--mat-sys-outline-variant);
      border-radius: 8px; background: var(--mat-sys-surface-container);
    }

    .hm-grid {
      display: grid;
      gap: 0;
    }

    .hm-tactic-hdr {
      padding: 6px 4px; font-size: 0.65rem; font-weight: 700;
      text-transform: uppercase; letter-spacing: 0.04em;
      color: var(--mat-sys-on-surface-variant);
      background: var(--mat-sys-surface-container);
      border-bottom: 1px solid var(--mat-sys-outline-variant);
      border-right: 1px solid var(--mat-sys-outline-variant);
      text-align: center; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
      position: sticky; top: 0; z-index: 2;
    }
    .hm-tactic-hdr:last-child { border-right: none; }

    .hm-col {
      display: flex; flex-direction: column;
      border-right: 1px solid var(--mat-sys-outline-variant);
    }
    .hm-col:last-child { border-right: none; }

    .hm-cell {
      padding: 3px 4px; font-size: 0.6rem; cursor: pointer;
      border-bottom: 1px solid rgba(255,255,255,0.04);
      transition: filter 0.1s; min-height: 22px;
      display: flex; align-items: center;
    }
    .hm-cell:hover { filter: brightness(1.3); }
    .hm-cell--sub { padding-left: 10px; opacity: 0.85; }
    .hm-cell--selected { outline: 2px solid var(--mat-sys-primary); outline-offset: -2px; z-index: 1; position: relative; }
    .hm-cell__id { font-family: monospace; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; font-size: 0.58rem; }

    html[data-theme='light'] .hm-cell { border-bottom-color: rgba(44,44,42,0.06); }

    .hm-detail { width: 280px; flex-shrink: 0; }

    .hm-coverage-box {
      padding: 10px; border-radius: 6px; margin-bottom: 12px; text-align: center;
    }
    .hm-coverage__count { font-size: 2rem; font-weight: 800; line-height: 1; }
    .hm-coverage__lbl   { font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); margin-top: 2px; }

    .hm-no-actors { font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); font-style: italic; }

    .chip-row { display: flex; flex-wrap: wrap; }
  `],
})
export class MitreHeatmapComponent {
  private feedsApi = inject(FeedsApiService)
  private readonly theme = inject(ThemeService)

  get intelColor() { return this.theme.isDark() ? INTEL_DARK : INTEL_LIGHT }

  selectedGroupIds = signal<string[]>([])
  includeSoftware  = signal(true)
  showSubs         = signal(false)
  selectedTech     = signal<MitreHeatmapTechnique | null>(null)

  readonly groupsQuery = injectQuery(() => ({
    queryKey: ['feeds', 'groups', 'all', 'attack_v19'],
    queryFn: () => firstValueFrom(this.feedsApi.getMitreGroups({ source: 'attack_v19', deprecated: false, per_page: 200 })),
  }))

  readonly allGroups = computed(() => this.groupsQuery.data()?.items ?? [])

  readonly heatmapQuery = injectQuery(() => ({
    queryKey: ['feeds', 'heatmap', 'attack_v19', this.selectedGroupIds().join(','), this.includeSoftware()],
    queryFn: () => firstValueFrom(this.feedsApi.getMitreHeatmap({
      source: 'attack_v19',
      group_ids: this.selectedGroupIds().length > 0 ? this.selectedGroupIds().join(',') : undefined,
      include_software: this.includeSoftware(),
    })),
    staleTime: 60_000,
  }))

  readonly maxCount = computed(() => {
    const techs = this.heatmapQuery.data()?.techniques ?? []
    return Math.max(...techs.map(t => t.usage_count), 1)
  })

  readonly coveragePct = computed(() => {
    const hm = this.heatmapQuery.data()
    return hm ? Math.round((hm.covered / Math.max(hm.total_techniques, 1)) * 100) : 0
  })

  readonly legendSwatches = computed(() => {
    const max = this.maxCount()
    const isDark = this.theme.isDark()
    return [0, 0.15, 0.4, 0.7, 1].map((r, i) => ({
      bg: heatColor(Math.round(r * max), max, isDark),
      label: i === 0 ? 'Not covered' : `~${Math.round(r * max)}+ actors`,
    }))
  })

  // Group techniques by tactic, respecting showSubs toggle
  readonly techsByTactic = computed(() => {
    const hm = this.heatmapQuery.data()
    if (!hm) return {} as Record<string, MitreHeatmapTechnique[]>
    const showSubs = this.showSubs()
    const result: Record<string, MitreHeatmapTechnique[]> = {}
    for (const tac of hm.tactic_order) {
      const inTactic = hm.techniques.filter(t => t.tactics.includes(tac))
      const parents = inTactic.filter(t => !t.is_subtechnique)
        .sort((a, b) => a.technique_id.localeCompare(b.technique_id))
      if (showSubs) {
        const subs = inTactic.filter(t => t.is_subtechnique)
        const rows: MitreHeatmapTechnique[] = []
        for (const p of parents) {
          rows.push(p)
          const mySubs = subs.filter(s => s.technique_id.startsWith(p.technique_id + '.'))
            .sort((a, b) => a.technique_id.localeCompare(b.technique_id))
          rows.push(...mySubs)
        }
        result[tac] = rows
      } else {
        result[tac] = parents
      }
    }
    return result
  })

  tacticShort(tac: string): string { return TACTIC_SHORT[tac] ?? tac }
  heatColor(count: number, max: number): string { return heatColor(count, max, this.theme.isDark()) }
  textColor(count: number, max: number): string { return textColor(count, max) }

  onGroupChange(ids: string[]) { this.selectedGroupIds.set(ids); this.selectedTech.set(null) }
  onCellClick(tech: MitreHeatmapTechnique) {
    this.selectedTech.update(s => s?.stix_id === tech.stix_id ? null : tech)
  }
}
