// isms-core-platform/frontend/src/pages/MitreCampaigns.tsx
import { useState } from 'react'
import {
  Alert, Box, Chip, CircularProgress, InputAdornment, Paper,
  Table, TableBody, TableCell, TableHead, TableRow, TextField,
  ToggleButton, ToggleButtonGroup, Tooltip, Typography,
} from '@mui/material'
import { SearchOutlined } from '@mui/icons-material'
import { useQuery } from '@tanstack/react-query'
import { feedsApi, type MitreCampaign } from '../api/feedsApi'
import PageHeader from '../components/PageHeader'

const PER_PAGE = 50
const INTEL_COLOR = '#B84F00'

export default function MitreCampaigns() {
  const [source] = useState<'attack_v19'>('attack_v19')
  const [search, setSearch] = useState('')
  const [page, setPage] = useState(1)
  const [selected, setSelected] = useState<MitreCampaign | null>(null)

  const { data, isLoading, error } = useQuery({
    queryKey: ['feeds', 'campaigns', source, search, page],
    queryFn: () => feedsApi.getMitreCampaigns({
      source,
      search: search || undefined,
      deprecated: false,
      page,
      per_page: PER_PAGE,
    }),
  })

  const totalPages = data ? Math.ceil(data.total / PER_PAGE) : 0

  function handleSearch(v: string) {
    setSearch(v)
    setPage(1)
  }

  const noData = !isLoading && data?.total === 0

  return (
    <Box sx={{ p: 3 }}>
      <PageHeader
        title="MITRE ATT&CK Campaigns"
        subtitle="Targeted intrusion activity clusters — time-bound adversary operations"
        helpSection="mitre-attack"
      />

      {/* ── Total pill ── */}
      {data && (
        <Box sx={{ display: 'flex', gap: 3, mb: 2.5 }}>
          <Box>
            <Typography variant="h6" sx={{ fontWeight: 700, color: INTEL_COLOR, lineHeight: 1 }}>
              {data.total.toLocaleString()}
            </Typography>
            <Typography variant="caption" color="text.secondary">Campaigns</Typography>
          </Box>
        </Box>
      )}

      {/* ── Filters ── */}
      <Box sx={{ display: 'flex', gap: 1.5, mb: 2, flexWrap: 'wrap', alignItems: 'center' }}>
        <ToggleButtonGroup
          size="small"
          value={source}
          exclusive
          onChange={(_, v) => v && setSource(v)}
        >
          <ToggleButton value="attack_v19" sx={{ fontSize: '0.72rem', px: 1.5 }}>v19</ToggleButton>
        </ToggleButtonGroup>

        <TextField
          size="small"
          placeholder="Search by ID or name…"
          value={search}
          onChange={e => handleSearch(e.target.value)}
          sx={{ width: 240 }}
          InputProps={{
            startAdornment: <InputAdornment position="start"><SearchOutlined sx={{ fontSize: 16 }} /></InputAdornment>,
          }}
        />
      </Box>

      {/* ── Table + detail panel ── */}
      <Box sx={{ display: 'flex', gap: 2 }}>
        <Paper variant="outlined" sx={{ flex: 1, borderRadius: 2, overflow: 'hidden', minWidth: 0 }}>
          {isLoading && (
            <Box sx={{ display: 'flex', justifyContent: 'center', py: 6 }}>
              <CircularProgress size={28} />
            </Box>
          )}
          {error && <Alert severity="error" sx={{ m: 2 }}>Failed to load campaigns</Alert>}
          {noData && (
            <Alert severity="info" sx={{ m: 2 }}>
              {source === 'attack_v19'
                ? 'ATT&CK v19 data not yet available. Check back after the scheduled weekly pull.'
                : 'No campaigns match the current filters.'}
            </Alert>
          )}
          {!isLoading && data && data.items.length > 0 && (
            <>
              <Table size="small" stickyHeader>
                <TableHead>
                  <TableRow>
                    <TableCell sx={{ fontWeight: 600, fontSize: '0.72rem', width: 80 }}>ID</TableCell>
                    <TableCell sx={{ fontWeight: 600, fontSize: '0.72rem' }}>Name</TableCell>
                    <TableCell sx={{ fontWeight: 600, fontSize: '0.72rem', width: 100 }}>First Seen</TableCell>
                    <TableCell sx={{ fontWeight: 600, fontSize: '0.72rem', width: 100 }}>Last Seen</TableCell>
                    <TableCell sx={{ fontWeight: 600, fontSize: '0.72rem' }}>Aliases</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {data.items.map(c => (
                    <TableRow
                      key={c.id}
                      hover
                      selected={selected?.id === c.id}
                      onClick={() => setSelected(selected?.id === c.id ? null : c)}
                      sx={{ cursor: 'pointer' }}
                    >
                      <TableCell sx={{ fontFamily: 'monospace', fontSize: '0.75rem', color: INTEL_COLOR, fontWeight: 600 }}>
                        {c.campaign_id}
                      </TableCell>
                      <TableCell sx={{ fontSize: '0.78rem' }}>
                        <Typography noWrap variant="inherit">{c.name}</Typography>
                      </TableCell>
                      <TableCell sx={{ fontSize: '0.75rem', fontFamily: 'monospace' }}>
                        {c.first_seen ?? '—'}
                      </TableCell>
                      <TableCell sx={{ fontSize: '0.75rem', fontFamily: 'monospace' }}>
                        {c.last_seen ?? '—'}
                      </TableCell>
                      <TableCell sx={{ maxWidth: 200 }}>
                        {c.aliases.length > 0 ? (
                          <Box>
                            {c.aliases.slice(0, 2).map(a => (
                              <Chip key={a} label={a} size="small" variant="outlined"
                                sx={{ fontSize: '0.62rem', height: 16, mr: 0.25, mb: 0.25 }} />
                            ))}
                            {c.aliases.length > 2 && (
                              <Tooltip title={c.aliases.slice(2).join(', ')}>
                                <Chip label={`+${c.aliases.length - 2}`} size="small"
                                  sx={{ fontSize: '0.62rem', height: 16 }} />
                              </Tooltip>
                            )}
                          </Box>
                        ) : (
                          <Typography variant="caption" color="text.disabled">—</Typography>
                        )}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>

              {/* Pagination */}
              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', px: 2, py: 1, borderTop: '1px solid', borderColor: 'divider' }}>
                <Typography variant="caption" color="text.secondary">
                  {data.total.toLocaleString()} campaigns
                </Typography>
                <Box sx={{ display: 'flex', gap: 1, alignItems: 'center' }}>
                  <Typography
                    variant="caption"
                    sx={{ cursor: page > 1 ? 'pointer' : 'default', color: page > 1 ? 'primary.main' : 'text.disabled' }}
                    onClick={() => page > 1 && setPage(p => p - 1)}
                  >
                    ← Prev
                  </Typography>
                  <Typography variant="caption" color="text.secondary">
                    {page} / {totalPages}
                  </Typography>
                  <Typography
                    variant="caption"
                    sx={{ cursor: page < totalPages ? 'pointer' : 'default', color: page < totalPages ? 'primary.main' : 'text.disabled' }}
                    onClick={() => page < totalPages && setPage(p => p + 1)}
                  >
                    Next →
                  </Typography>
                </Box>
              </Box>
            </>
          )}
        </Paper>

        {/* ── Detail panel ── */}
        {selected && (
          <Paper variant="outlined" sx={{ width: 320, flexShrink: 0, borderRadius: 2, p: 2, height: 'fit-content', position: 'sticky', top: 24 }}>
            <Typography variant="subtitle2" sx={{ fontFamily: 'monospace', color: INTEL_COLOR, fontWeight: 700, mb: 0.5 }}>
              {selected.campaign_id}
            </Typography>
            <Typography variant="body2" fontWeight={600} sx={{ mb: 1 }}>{selected.name}</Typography>
            <Box sx={{ display: 'flex', gap: 2, mb: 1 }}>
              {selected.first_seen && (
                <Box>
                  <Typography variant="caption" color="text.secondary" display="block">First seen</Typography>
                  <Typography variant="caption" fontFamily="monospace">{selected.first_seen}</Typography>
                </Box>
              )}
              {selected.last_seen && (
                <Box>
                  <Typography variant="caption" color="text.secondary" display="block">Last seen</Typography>
                  <Typography variant="caption" fontFamily="monospace">{selected.last_seen}</Typography>
                </Box>
              )}
            </Box>
            {selected.aliases.length > 0 && (
              <Box sx={{ mb: 1 }}>
                <Typography variant="caption" color="text.secondary" display="block" sx={{ mb: 0.5 }}>Also known as:</Typography>
                {selected.aliases.map(a => (
                  <Chip key={a} label={a} size="small" variant="outlined"
                    sx={{ fontSize: '0.62rem', height: 16, mr: 0.25, mb: 0.25 }} />
                ))}
              </Box>
            )}
            {selected.description && (
              <Typography variant="caption" color="text.secondary" display="block" sx={{ mt: 1.5, lineHeight: 1.5, maxHeight: 300, overflowY: 'auto' }}>
                {selected.description.slice(0, 700)}{selected.description.length > 700 ? '…' : ''}
              </Typography>
            )}
            {selected.url && (
              <Typography variant="caption" sx={{ mt: 1, display: 'block' }}>
                <a href={selected.url} target="_blank" rel="noopener noreferrer"
                  style={{ color: INTEL_COLOR }}>
                  View on attack.mitre.org →
                </a>
              </Typography>
            )}
          </Paper>
        )}
      </Box>
    </Box>
  )
}

// isms-core-platform/frontend/src/app/pages/mitre-campaigns/mitre-campaigns.component.ts
import { Component, inject, signal, computed } from '@angular/core'
import { DecimalPipe } from '@angular/common'
import { FormsModule } from '@angular/forms'
import { firstValueFrom } from 'rxjs'
import { injectQuery } from '@tanstack/angular-query-experimental'

import { MatFormFieldModule } from '@angular/material/form-field'
import { MatInputModule } from '@angular/material/input'
import { MatIconModule } from '@angular/material/icon'
import { MatTooltipModule } from '@angular/material/tooltip'
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner'

import { FeedsApiService, MitreCampaign } from '../../api/feeds-api.service'
import { ThemeService } from '../../core/services/theme.service'
import { PageHeaderComponent } from '../../shared/components/page-header.component'

const INTEL_DARK  = '#e06030'
const INTEL_LIGHT = '#c64227'
const PER_PAGE = 50

@Component({
  selector: 'app-mitre-campaigns',
  standalone: true,
  imports: [
    DecimalPipe, FormsModule, PageHeaderComponent,
    MatFormFieldModule, MatInputModule,
    MatIconModule, MatTooltipModule, MatProgressSpinnerModule,
  ],
  template: `
<div class="cmp-page">
  <app-page-header
    title="Campaigns"
    subtitle="MITRE ATT&CK — time-bound targeted intrusion activity clusters"
  />

  @if (listQuery.data(); as data) {
    <div class="mitre-stats">
      <div><div class="mitre-stat__val" [style.color]="INTEL_COLOR">{{ data.total | number }}</div><div class="mitre-stat__lbl">Campaigns</div></div>
    </div>
  }

  <div class="mitre-filters">
    <mat-form-field appearance="outline" subscriptSizing="dynamic" class="mitre-search">
      <mat-label>Search campaigns…</mat-label>
      <mat-icon matPrefix>search</mat-icon>
      <input matInput [ngModel]="search()" (ngModelChange)="onSearch($event)" />
    </mat-form-field>
  </div>

  <div class="mitre-layout">
    <div class="mitre-table-box">
      @if (listQuery.isLoading()) {
        <div class="mitre-empty"><mat-spinner diameter="28" /></div>
      }
      @if (listQuery.isError()) {
        <div class="mitre-error">Failed to load campaigns.</div>
      }
      @if (!listQuery.isLoading() && listQuery.data()?.total === 0) {
        <div class="mitre-empty">No ATT&CK v19 data yet — check back after the scheduled weekly pull.</div>
      }
      @if (!listQuery.isLoading() && (listQuery.data()?.items?.length ?? 0) > 0) {
        <table class="mitre-table">
          <thead><tr>
            <th class="col-id">ID</th>
            <th class="col-name">Name</th>
            <th class="col-date">First Seen</th>
            <th class="col-date">Last Seen</th>
            <th>Aliases</th>
          </tr></thead>
          <tbody>
            @for (c of listQuery.data()!.items; track c.id) {
              <tr class="mitre-row" [class.mitre-row--selected]="selected()?.id === c.id" (click)="onRowClick(c)">
                <td class="mono" [style.color]="INTEL_COLOR">{{ c.campaign_id }}</td>
                <td class="cell-name">{{ c.name }}</td>
                <td class="cell-date mono">{{ c.first_seen ?? '—' }}</td>
                <td class="cell-date mono">{{ c.last_seen ?? '—' }}</td>
                <td>
                  <div class="alias-row">
                    @for (a of c.aliases.slice(0, 2); track a) {
                      <span class="alias-chip" [matTooltip]="a">{{ a }}</span>
                    }
                    @if (c.aliases.length > 2) {
                      <span class="alias-chip" [matTooltip]="c.aliases.slice(2).join(', ')">+{{ c.aliases.length - 2 }}</span>
                    }
                  </div>
                </td>
              </tr>
            }
          </tbody>
        </table>
        <div class="mitre-pagination">
          <span>{{ listQuery.data()!.total | number }} campaigns</span>
          <div class="mitre-pagination__nav">
            <span class="mitre-pagination__btn" [class.disabled]="page() <= 1" (click)="page() > 1 && setPage(page() - 1)">← Prev</span>
            <span>{{ page() }} / {{ totalPages() }}</span>
            <span class="mitre-pagination__btn" [class.disabled]="page() >= totalPages()" (click)="page() < totalPages() && setPage(page() + 1)">Next →</span>
          </div>
        </div>
      }
    </div>

    @if (selected(); as c) {
      <div class="mitre-detail">
        <div class="mitre-detail__id" [style.color]="INTEL_COLOR">{{ c.campaign_id }}</div>
        <div class="mitre-detail__name">{{ c.name }}</div>
        @if (c.first_seen || c.last_seen) {
          <div class="dates-row">
            @if (c.first_seen) {
              <div><div class="mitre-detail__label">First seen</div><div class="date-val mono">{{ c.first_seen }}</div></div>
            }
            @if (c.last_seen) {
              <div><div class="mitre-detail__label">Last seen</div><div class="date-val mono">{{ c.last_seen }}</div></div>
            }
          </div>
        }
        @if (c.aliases.length > 0) {
          <div class="mitre-detail__label">Also known as</div>
          <div class="alias-row alias-row--wrap">
            @for (a of c.aliases; track a) {
              <span class="alias-chip">{{ a }}</span>
            }
          </div>
        }
        @if (c.description) {
          <div class="mitre-detail__desc">{{ c.description.slice(0, 700) }}{{ c.description.length > 700 ? '…' : '' }}</div>
        }
        @if (c.url) {
          <a [href]="c.url" target="_blank" rel="noopener noreferrer" class="mitre-detail__link" [style.color]="INTEL_COLOR">View on attack.mitre.org →</a>
        }
      </div>
    }
  </div>
</div>
  `,
  styles: [`
    .cmp-page { display: flex; flex-direction: column; gap: 16px; }
    .col-id   { width: 80px; }
    .col-name { width: 180px; }
    .col-date { width: 100px; }
    .cell-name { font-size: 0.78rem; font-weight: 500; max-width: 200px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
    .cell-date { font-size: 0.72rem; }
    .mono { font-family: monospace; font-weight: 600; }
    .alias-row { display: flex; gap: 3px; align-items: center; flex-wrap: nowrap; overflow: hidden; }
    .alias-row--wrap { flex-wrap: wrap; gap: 4px; margin-top: 4px; }
    .alias-chip {
      display: inline-flex; align-items: center; font-size: 0.62rem; height: 16px;
      padding: 0 6px; border-radius: 8px; white-space: nowrap;
      max-width: 100px; overflow: hidden; text-overflow: ellipsis; flex-shrink: 0;
      background: var(--mat-sys-surface-container-high);
      color: var(--mat-sys-on-surface-variant);
    }
    :host-context(html[data-theme='light']) .alias-chip { background: #C4C2B8; color: #2C2C2A; }
    .dates-row { display: flex; gap: 16px; margin-bottom: 8px; }
    .date-val { font-size: 0.72rem; margin-top: 2px; }
  `],
})
export class MitreCampaignsComponent {
  private feedsApi = inject(FeedsApiService)
  private readonly theme = inject(ThemeService)

  get INTEL_COLOR() { return this.theme.isDark() ? INTEL_DARK : INTEL_LIGHT }

  search   = signal('')
  page     = signal(1)
  selected = signal<MitreCampaign | null>(null)

  readonly listQuery = injectQuery(() => ({
    queryKey: ['feeds', 'campaigns', 'attack_v19', this.search(), this.page()],
    queryFn: () => firstValueFrom(this.feedsApi.getMitreCampaigns({
      source: 'attack_v19', search: this.search() || undefined,
      deprecated: false, page: this.page(), per_page: PER_PAGE,
    })),
  }))

  readonly totalPages = computed(() => Math.ceil((this.listQuery.data()?.total ?? 0) / PER_PAGE) || 1)

  onSearch(v: string) { this.search.set(v); this.page.set(1) }
  setPage(p: number)  { this.page.set(p) }
  onRowClick(c: MitreCampaign) { this.selected.update(s => s?.id === c.id ? null : c) }
}
