// isms-core-platform/frontend/src/pages/ThreatIntelDashboard.tsx
import { useQuery, useMutation } from '@tanstack/react-query'
import {
  Alert, Box, Chip, CircularProgress, Grid, Paper,
  Table, TableBody, TableCell, TableHead, TableRow,
  Tooltip, Typography,
} from '@mui/material'
import {
  CheckCircleOutlined, CoronavirusOutlined, ErrorOutlined,
  HourglassEmptyOutlined, PlayArrowOutlined, RouterOutlined,
  StreamOutlined, SyncOutlined, TrackChangesOutlined,
} from '@mui/icons-material'
import { useNavigate } from 'react-router-dom'
import PageHeader from '../components/PageHeader'
import { threatIntelApi, TiSourceStatus } from '../api/threatIntelApi'
import { useAuth } from '../store/AuthContext'

const INTEL_COLOR = '#B84F00'

function fmt(iso: string | null): string {
  if (!iso) return '—'
  return new Date(iso).toLocaleString(undefined, {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  })
}

function StatusChip({ status }: { status: string | null }) {
  if (!status)
    return <Chip label="Never run" size="small" sx={{ fontSize: '0.7rem' }} />
  if (status === 'success')
    return <Chip icon={<CheckCircleOutlined sx={{ fontSize: 13 }} />} label="OK" size="small" color="success" sx={{ fontSize: '0.7rem' }} />
  if (status === 'running')
    return <Chip icon={<SyncOutlined sx={{ fontSize: 13 }} />} label="Running" size="small" color="info" sx={{ fontSize: '0.7rem' }} />
  return <Chip icon={<ErrorOutlined sx={{ fontSize: 13 }} />} label="Error" size="small" color="error" sx={{ fontSize: '0.7rem' }} />
}

const SOURCE_ICONS: Record<string, React.ReactNode> = {
  circl_misp:   <StreamOutlined sx={{ fontSize: 26, color: INTEL_COLOR }} />,
  botvrij_misp: <StreamOutlined sx={{ fontSize: 26, color: '#8b5a00' }} />,
  abuseipdb:    <RouterOutlined sx={{ fontSize: 26, color: '#1565c0' }} />,
  malpedia:     <CoronavirusOutlined sx={{ fontSize: 26, color: '#6a0dad' }} />,
}

function StatCard({ label, value, icon, onClick }: {
  label: string; value: number | string; icon: React.ReactNode; onClick?: () => void
}) {
  return (
    <Paper
      variant="outlined"
      onClick={onClick}
      sx={{
        p: 2, display: 'flex', alignItems: 'center', gap: 1.5,
        cursor: onClick ? 'pointer' : 'default',
        '&:hover': onClick ? { borderColor: INTEL_COLOR, bgcolor: `${INTEL_COLOR}08` } : {},
        transition: 'border-color 0.15s',
      }}
    >
      {icon}
      <Box>
        <Typography variant="h5" fontWeight={700} sx={{ lineHeight: 1 }}>{value}</Typography>
        <Typography variant="caption" color="text.secondary">{label}</Typography>
      </Box>
    </Paper>
  )
}

function SourceRow({ src, onTrigger, isAdmin }: {
  src: TiSourceStatus; onTrigger: (s: string) => void; isAdmin: boolean
}) {
  return (
    <TableRow hover>
      <TableCell>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          {SOURCE_ICONS[src.source] ?? <StreamOutlined sx={{ fontSize: 20, color: 'text.secondary' }} />}
          <Box>
            <Typography variant="body2" fontWeight={600} sx={{ fontSize: '0.82rem' }}>{src.display_name}</Typography>
            <Typography variant="caption" color="text.secondary" sx={{ fontFamily: 'monospace' }}>{src.source}</Typography>
          </Box>
        </Box>
      </TableCell>
      <TableCell>
        <Chip
          label={src.enabled ? 'Enabled' : 'Disabled'}
          size="small"
          color={src.enabled ? 'success' : 'default'}
          sx={{ fontSize: '0.68rem', height: 18 }}
        />
      </TableCell>
      <TableCell><StatusChip status={src.last_run_status} /></TableCell>
      <TableCell sx={{ fontFamily: 'monospace', fontSize: '0.75rem', color: 'text.secondary' }}>
        {fmt(src.last_run_at)}
      </TableCell>
      <TableCell sx={{ fontWeight: 600, fontSize: '0.82rem' }}>
        {src.ioc_count.toLocaleString()}
      </TableCell>
      <TableCell>
        {isAdmin && src.enabled && (
          <Tooltip title={`Trigger ${src.display_name} now`}>
            <Chip
              icon={<PlayArrowOutlined sx={{ fontSize: 13 }} />}
              label="Run"
              size="small"
              onClick={() => onTrigger(src.source)}
              sx={{ fontSize: '0.68rem', height: 20, cursor: 'pointer' }}
            />
          </Tooltip>
        )}
      </TableCell>
    </TableRow>
  )
}

export default function ThreatIntelDashboard() {
  const navigate = useNavigate()
  const { user } = useAuth()
  const isAdmin = user?.role === 'super_admin' || user?.role === 'admin'

  const { data, isLoading, error } = useQuery({
    queryKey: ['threat-intel', 'summary'],
    queryFn: threatIntelApi.getSummary,
    staleTime: 60_000,
    refetchInterval: 60_000,
  })

  const triggerMutation = useMutation({
    mutationFn: (source: string) => threatIntelApi.triggerFeed(source),
  })

  if (isLoading) return (
    <Box sx={{ display: 'flex', justifyContent: 'center', mt: 8 }}>
      <CircularProgress size={32} sx={{ color: INTEL_COLOR }} />
    </Box>
  )

  if (!data?.active) return (
    <Box sx={{ p: 3 }}>
      <PageHeader title="Threat Intelligence" subtitle="OSINT IOC feeds, malware families, and actor attribution" />
      <Alert severity="info" sx={{ mt: 2 }}>
        Threat Intelligence module is not active.
        Start the platform with <code style={{ fontFamily: 'monospace' }}>--profile threat-intel</code> and set{' '}
        <code style={{ fontFamily: 'monospace' }}>THREAT_INTEL_ENABLED=true</code> to enable it.
      </Alert>
    </Box>
  )

  if (error) return (
    <Box sx={{ p: 3 }}>
      <Alert severity="error">Could not load threat intelligence data.</Alert>
    </Box>
  )

  return (
    <Box sx={{ p: 3, display: 'flex', flexDirection: 'column', gap: 3 }}>
      <PageHeader
        title="Threat Intelligence"
        subtitle="OSINT IOC feeds · Malware families · Actor attribution"
      />

      {/* ── Stat cards ── */}
      <Grid container spacing={2}>
        <Grid item xs={12} sm={4}>
          <StatCard
            label="Total IOCs"
            value={(data?.total_iocs ?? 0).toLocaleString()}
            icon={<TrackChangesOutlined sx={{ fontSize: 32, color: INTEL_COLOR }} />}
            onClick={() => navigate('/ioc-explorer')}
          />
        </Grid>
        <Grid item xs={12} sm={4}>
          <StatCard
            label="Malware Families"
            value={(data?.total_families ?? 0).toLocaleString()}
            icon={<CoronavirusOutlined sx={{ fontSize: 32, color: '#6a0dad' }} />}
            onClick={() => navigate('/malware-atlas')}
          />
        </Grid>
        <Grid item xs={12} sm={4}>
          <StatCard
            label="Threat Actors"
            value={(data?.total_actors ?? 0).toLocaleString()}
            icon={<HourglassEmptyOutlined sx={{ fontSize: 32, color: '#c62828' }} />}
            onClick={() => navigate('/malware-atlas')}
          />
        </Grid>
      </Grid>

      {/* ── Source table ── */}
      <Paper variant="outlined">
        <Box sx={{ px: 2, pt: 2, pb: 1 }}>
          <Typography variant="subtitle2" fontWeight={700} sx={{ fontSize: '0.85rem', color: INTEL_COLOR }}>
            Feed Sources
          </Typography>
        </Box>
        <Table size="small">
          <TableHead>
            <TableRow>
              <TableCell sx={{ fontWeight: 700, fontSize: '0.75rem' }}>Source</TableCell>
              <TableCell sx={{ fontWeight: 700, fontSize: '0.75rem' }}>Status</TableCell>
              <TableCell sx={{ fontWeight: 700, fontSize: '0.75rem' }}>Last Run</TableCell>
              <TableCell sx={{ fontWeight: 700, fontSize: '0.75rem' }}>Last Run At</TableCell>
              <TableCell sx={{ fontWeight: 700, fontSize: '0.75rem' }}>IOCs</TableCell>
              <TableCell />
            </TableRow>
          </TableHead>
          <TableBody>
            {(data?.sources ?? []).map(src => (
              <SourceRow
                key={src.source}
                src={src}
                isAdmin={isAdmin}
                onTrigger={s => triggerMutation.mutate(s)}
              />
            ))}
          </TableBody>
        </Table>
      </Paper>

      {triggerMutation.isSuccess && (
        <Alert severity="success" onClose={() => triggerMutation.reset()}>
          Feed triggered — check status in a few minutes.
        </Alert>
      )}
      {triggerMutation.isError && (
        <Alert severity="error" onClose={() => triggerMutation.reset()}>
          Could not reach TI trigger server.
        </Alert>
      )}
    </Box>
  )
}

// isms-core-platform/frontend-angular/src/app/pages/threat-intel-dashboard/threat-intel-dashboard.component.ts
import { Component, inject, computed } from '@angular/core'
import { NgClass } from '@angular/common'
import { Router } from '@angular/router'
import { firstValueFrom } from 'rxjs'
import { injectQuery, injectMutation } from '@tanstack/angular-query-experimental'

import { MatIconModule } from '@angular/material/icon'
import { MatButtonModule } from '@angular/material/button'
import { MatChipsModule } from '@angular/material/chips'
import { MatTooltipModule } from '@angular/material/tooltip'
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner'

import { ThreatIntelApiService } from '../../api/threat-intel-api.service'
import { AuthService } from '../../core/services/auth.service'
import { PageHeaderComponent } from '../../shared/components/page-header.component'

const INTEL_COLOR = '#FFA726'

function fmt(iso: string | null): string {
  if (!iso) return '—'
  return new Date(iso).toLocaleString(undefined, {
    year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit',
  })
}

function statusLabel(s: string | null): string {
  if (!s) return 'Never run'
  if (s === 'success') return 'OK'
  if (s === 'running') return 'Running'
  return 'Error'
}

function statusClass(s: string | null): string {
  if (!s) return 'chip-default'
  if (s === 'success') return 'chip-success'
  if (s === 'running') return 'chip-info'
  return 'chip-error'
}

function statusIcon(s: string | null): string {
  if (!s) return 'schedule'
  if (s === 'success') return 'check_circle'
  if (s === 'running') return 'sync'
  return 'error'
}

@Component({
  selector: 'app-threat-intel-dashboard',
  standalone: true,
  imports: [
    NgClass,
    PageHeaderComponent,
    MatIconModule, MatButtonModule, MatChipsModule,
    MatTooltipModule, MatProgressSpinnerModule,
  ],
  template: `
<div class="tid-page">
  <app-page-header
    title="Threat Intelligence"
    subtitle="OSINT IOC feeds · Malware families · Actor attribution"
  />

  @if (summaryQuery.isLoading()) {
    <div class="loading-center">
      <mat-spinner diameter="32" />
    </div>
  }

  @if (!summaryQuery.isLoading() && !summaryQuery.data()?.active) {
    <div class="alert alert-info">
      <mat-icon>info</mat-icon>
      Threat Intelligence module is not active.
      Start the platform with <code>--profile threat-intel</code> and set
      <code>THREAT_INTEL_ENABLED=true</code> to enable it.
    </div>
  }

  @if (summaryQuery.isError()) {
    <div class="alert alert-error">
      <mat-icon>error</mat-icon> Could not load threat intelligence data.
    </div>
  }

  @if (summaryQuery.data()?.active) {
    <!-- Stat cards -->
    <div class="stat-cards">
      <div class="stat-card clickable" (click)="router.navigate(['/ioc-explorer'])">
        <mat-icon class="stat-icon stat-icon-ioc">track_changes</mat-icon>
        <div>
          <div class="stat-val">{{ (summaryQuery.data()?.total_iocs ?? 0).toLocaleString() }}</div>
          <div class="stat-lbl">Total IOCs</div>
        </div>
      </div>
      <div class="stat-card clickable" (click)="router.navigate(['/malware-atlas'])">
        <mat-icon class="stat-icon stat-icon-malware">coronavirus</mat-icon>
        <div>
          <div class="stat-val">{{ (summaryQuery.data()?.total_families ?? 0).toLocaleString() }}</div>
          <div class="stat-lbl">Malware Families</div>
        </div>
      </div>
      <div class="stat-card clickable" (click)="router.navigate(['/malware-atlas'])">
        <mat-icon class="stat-icon stat-icon-actor">person_outline</mat-icon>
        <div>
          <div class="stat-val">{{ (summaryQuery.data()?.total_actors ?? 0).toLocaleString() }}</div>
          <div class="stat-lbl">Threat Actors</div>
        </div>
      </div>
      <div class="stat-card">
        <mat-icon class="stat-icon stat-icon-tools">build</mat-icon>
        <div>
          <div class="stat-val">{{ (summaryQuery.data()?.total_tools ?? 0).toLocaleString() }}</div>
          <div class="stat-lbl">Tools</div>
        </div>
      </div>
    </div>

    <!-- Source table -->
    <div class="table-box">
      <div class="table-box__header">
        <span class="table-box__title" [style.color]="INTEL_COLOR">Feed Sources</span>
      </div>
      <table>
        <thead>
          <tr>
            <th>Source</th>
            <th>Enabled</th>
            <th>Last Run</th>
            <th>Last Run At</th>
            <th>IOCs</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          @for (src of summaryQuery.data()?.sources ?? []; track src.source) {
            <tr>
              <td>
                <div class="src-cell">
                  <mat-icon class="src-icon">stream</mat-icon>
                  <div>
                    <div class="src-name">{{ src.display_name }}</div>
                    <div class="src-slug">{{ src.source }}</div>
                  </div>
                </div>
              </td>
              <td>
                <span class="chip" [class.chip-success]="src.enabled" [class.chip-default]="!src.enabled">
                  {{ src.enabled ? 'Enabled' : 'Disabled' }}
                </span>
              </td>
              <td>
                <span class="chip" [ngClass]="statusClass(src.last_run_status)">
                  <mat-icon>{{ statusIcon(src.last_run_status) }}</mat-icon>
                  {{ statusLabel(src.last_run_status) }}
                </span>
              </td>
              <td class="mono dim">{{ fmt(src.last_run_at) }}</td>
              <td class="bold">{{ src.ioc_count.toLocaleString() }}</td>
              <td>
                @if (isAdmin() && src.enabled) {
                  <button mat-icon-button class="run-btn"
                    [disabled]="triggerMutation.isPending()"
                    [matTooltip]="'Trigger ' + src.display_name + ' now'"
                    (click)="triggerFeed(src.source)">
                    <mat-icon>play_arrow</mat-icon>
                  </button>
                }
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>

    @if (triggerMutation.isSuccess()) {
      <div class="alert alert-success">
        <mat-icon>check_circle</mat-icon>
        Feed triggered — check status in a few minutes.
      </div>
    }
    @if (triggerMutation.isError()) {
      <div class="alert alert-error">
        <mat-icon>error</mat-icon> Could not reach TI trigger server.
      </div>
    }
  }
</div>
  `,
  styles: [`
    .tid-page {
      display: flex;
      flex-direction: column;
      gap: 16px;
    }

    .loading-center { display: flex; justify-content: center; margin-top: 48px; }

    .alert {
      display: flex; align-items: center; gap: 8px;
      padding: 10px 14px; border-radius: 6px; font-size: 0.82rem;
    }
    .alert mat-icon { font-size: 18px; flex-shrink: 0; }
    .alert code { background: var(--mat-sys-surface-container-high); padding: 1px 5px; border-radius: 3px; font-size: 0.78rem; }
    .alert-info    { background: var(--mat-sys-surface-container); border: 1px solid var(--mat-sys-outline-variant); }
    .alert-error   { background: rgba(192,0,0,0.08); color: var(--mat-sys-error); border: 1px solid rgba(192,0,0,0.2); }
    .alert-success { background: rgba(46,125,50,0.08); color: #2e7d32; border: 1px solid rgba(46,125,50,0.2); }

    .stat-cards {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));
      gap: 12px;
    }
    .stat-card {
      border: 1px solid var(--mat-sys-outline-variant);
      border-radius: 8px;
      padding: 14px;
      display: flex;
      align-items: center;
      gap: 12px;
      transition: border-color 0.15s;
    }
    .stat-card.clickable { cursor: pointer; }
    .stat-card.clickable:hover { border-color: #FFA726; background: rgba(184,79,0,0.04); }
    .stat-icon { font-size: 32px; width: 32px; height: 32px; flex-shrink: 0; }
    .stat-icon-ioc    { color: #FFA726; }
    .stat-icon-malware{ color: #6a0dad; }
    .stat-icon-actor  { color: #c62828; }
    .stat-icon-tools  { color: #1565c0; }
    .stat-val { font-size: 1.5rem; font-weight: 700; line-height: 1; }
    .stat-lbl { font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); margin-top: 2px; }

    .table-box { border: 1px solid var(--mat-sys-outline-variant); border-radius: 8px; overflow: hidden; }
    .table-box__header { padding: 8px 14px; border-bottom: 1px solid var(--mat-sys-outline-variant); }
    .table-box__title { font-size: 0.85rem; font-weight: 700; }

    table { width: 100%; border-collapse: collapse; }
    thead { background: var(--mat-sys-surface-container); }
    th { font-size: 0.72rem; font-weight: 700; padding: 6px 10px; text-align: left; }
    td { font-size: 0.78rem; padding: 6px 10px; border-top: 1px solid var(--mat-sys-outline-variant); }
    tr:hover td { background: var(--mat-sys-surface-container); }

    .src-cell { display: flex; align-items: center; gap: 8px; }
    .src-icon { font-size: 20px; width: 20px; height: 20px; color: var(--mat-sys-on-surface-variant); }
    .src-name { font-size: 0.82rem; font-weight: 600; }
    .src-slug { font-family: monospace; font-size: 0.7rem; color: var(--mat-sys-on-surface-variant); }

    .chip {
      display: inline-flex; align-items: center; gap: 2px;
      font-size: 0.68rem; height: 20px; padding: 0 6px; border-radius: 10px;
    }
    .chip mat-icon { font-size: 12px; width: 12px; height: 12px; }
    .chip-default { background: var(--mat-sys-surface-container-high); color: var(--mat-sys-on-surface-variant); }
    .chip-success { background: rgba(46,125,50,0.15); color: #2e7d32; }
    .chip-info    { background: rgba(21,101,192,0.15); color: #1565c0; }
    .chip-error   { background: rgba(192,0,0,0.15); color: #9e0000; }

    .run-btn { width: 28px; height: 28px; }

    .mono  { font-family: monospace; }
    .dim   { color: var(--mat-sys-on-surface-variant); font-size: 0.75rem; }
    .bold  { font-weight: 600; }
  `],
})
export class ThreatIntelDashboardComponent {
  readonly router = inject(Router)
  private tiApi   = inject(ThreatIntelApiService)
  private auth    = inject(AuthService)

  readonly INTEL_COLOR = INTEL_COLOR
  readonly fmt = fmt
  readonly statusLabel = statusLabel
  readonly statusClass = statusClass
  readonly statusIcon  = statusIcon

  readonly isAdmin = computed(() => {
    const role = this.auth.user()?.role
    return role === 'admin' || role === 'super_admin'
  })

  readonly summaryQuery = injectQuery(() => ({
    queryKey: ['threat-intel', 'summary'],
    queryFn:  () => firstValueFrom(this.tiApi.getSummary()),
    staleTime: 60_000,
    refetchInterval: 60_000,
  }))

  readonly triggerMutation = injectMutation(() => ({
    mutationFn: (source: string) => firstValueFrom(this.tiApi.triggerFeed(source)),
  }))

  triggerFeed(source: string) { this.triggerMutation.mutate(source) }
}
