// isms-core-platform/frontend/src/pages/Policies.tsx
import { useState, useRef } from 'react'
import { useTheme } from '@mui/material/styles'
import { useProduct, PRODUCT_COLORS } from '../store/ProductContext'
import {
  Box,
  Card,
  CardContent,
  Typography,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Chip,
  Skeleton,
  Alert,
  Grid,
  TextField,
  InputAdornment,
  Button,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  CircularProgress,
  Tooltip,
  IconButton,
} from '@mui/material'
import { SearchOutlined, PolicyOutlined, UploadFileOutlined, DeleteOutlined } from '@mui/icons-material'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useNavigate } from 'react-router-dom'
import { policiesApi } from '../api/policiesApi'
import { controlsApi } from '../api/controls'
import PageHeader from '../components/PageHeader'
import MetricCard from '../components/MetricCard'

export default function Policies() {
  const { palette } = useTheme()
  const isLight = palette.mode === 'light'
  const { product, ismsTier } = useProduct()
  const [externalOnly, setExternalOnly] = useState(false)
  const [typeFilter, setTypeFilter] = useState('')
  const [langFilter, setLangFilter] = useState('')
  const [search, setSearch] = useState('')
  const [importOpen, setImportOpen] = useState(false)
  const [deleteTarget, setDeleteTarget] = useState<{ id: string; title: string } | null>(null)
  const navigate = useNavigate()
  const queryClient = useQueryClient()

  const deleteMutation = useMutation({
    mutationFn: (id: string) => policiesApi.delete(id),
    onSuccess: () => {
      setDeleteTarget(null)
      queryClient.invalidateQueries({ queryKey: ['policies'] })
    },
  })

  // When ISMS tier filter is active, map it to API product param; otherwise pass 'isms' (fw+op only)
  const tieredProduct = product === 'isms' && ismsTier !== 'all' ? ismsTier : 'isms'
  const effectiveProduct = externalOnly ? 'external' : (product === 'isms' ? tieredProduct : product)

  // Reset type filter when switching products to avoid stale ISMS types on PRIV/CLD
  const [prevProduct, setPrevProduct] = useState(product)
  if (product !== prevProduct) {
    setPrevProduct(product)
    setTypeFilter('')
  }

  const { data, isLoading, error } = useQuery({
    queryKey: ['policies', effectiveProduct, typeFilter],
    queryFn: () =>
      policiesApi.list({
        product: effectiveProduct,
        policy_type: typeFilter || undefined,
      }),
  })

  const filtered = (data ?? []).filter((p) => {
    if (langFilter && (p.language ?? 'en') !== langFilter) return false
    if (!search) return true
    const q = search.toLowerCase()
    return (
      p.document_id.toLowerCase().includes(q) ||
      p.title.toLowerCase().includes(q) ||
      p.group_code.toLowerCase().includes(q)
    )
  })

  const langCounts = (data ?? []).reduce<Record<string, number>>((acc, p) => {
    const l = p.language ?? 'en'
    acc[l] = (acc[l] ?? 0) + 1
    return acc
  }, {})

  const frameworkCount = (data ?? []).filter((p) => p.product_type === 'framework').length
  const operationalCount = (data ?? []).filter((p) => p.product_type === 'operational').length
  const privacyCount = (data ?? []).filter((p) => p.product_type === 'privacy').length
  const cloudCount = (data ?? []).filter((p) => p.product_type === 'cloud').length
  const aiCount = (data ?? []).filter((p) => p.product_type === 'ai').length
  const externalCount = (data ?? []).filter((p) => p.product_type === 'external').length
  const totalReqs = (data ?? []).reduce((s, p) => s + (p.requirements_count ?? 0), 0)

  const STANDARD_LABELS: Record<string, string> = {
    isms: 'ISO 27001:2022', privacy: 'ISO 27701:2025', cloud: 'ISO 27018:2025', ai: 'ISO 42001:2023',
  }

  const productChipStyle = (type: string) => {
    if (type === 'external')    return { bgcolor: isLight ? 'rgba(230,160,0,0.15)' : 'rgba(255,192,0,0.15)', color: isLight ? '#7a4800' : '#FFC000' }
    if (type === 'framework')   return { bgcolor: 'rgba(68,114,196,0.15)',                     color: '#4472C4' }
    if (type === 'operational') return { bgcolor: 'rgba(112,173,71,0.15)',                     color: '#70AD47' }
    if (type === 'privacy')     return { bgcolor: `${PRODUCT_COLORS.privacy}22`,               color: PRODUCT_COLORS.privacy }
    if (type === 'cloud')       return { bgcolor: `${PRODUCT_COLORS.cloud}22`,                 color: PRODUCT_COLORS.cloud }
    if (type === 'ai')          return { bgcolor: `${PRODUCT_COLORS.ai}22`,                    color: PRODUCT_COLORS.ai }
    return { bgcolor: 'rgba(112,173,71,0.15)', color: '#70AD47' }
  }

  return (
    <Box>
      <PageHeader
        title="Policies"
        subtitle={`${data?.length ?? 0} policy documents · ${STANDARD_LABELS[product] ?? 'ISO 27001:2022'}`}
        actions={
          <Button
            variant="outlined"
            size="small"
            startIcon={<UploadFileOutlined />}
            onClick={() => setImportOpen(true)}
            sx={{ fontSize: '0.78rem' }}
          >
            Import External Doc
          </Button>
        }
      />

      {/* Summary */}
      {data && (
        <Grid container spacing={2} sx={{ mb: 2 }}>
          <Grid item xs={6} sm={3}>
            <MetricCard title="Total" value={data.length} icon={<PolicyOutlined fontSize="small" />} />
          </Grid>
          {product === 'isms' && (
            <>
              <Grid item xs={6} sm={3}>
                <MetricCard title="Framework" value={frameworkCount} />
              </Grid>
              <Grid item xs={6} sm={3}>
                <MetricCard title="Operational" value={operationalCount} />
              </Grid>
            </>
          )}
          {product === 'privacy' && (
            <Grid item xs={6} sm={3}>
              <MetricCard title="Privacy" value={privacyCount} sx={{ borderTop: `2px solid ${PRODUCT_COLORS.privacy}` }} />
            </Grid>
          )}
          {product === 'cloud' && (
            <Grid item xs={6} sm={3}>
              <MetricCard title="Cloud" value={cloudCount} sx={{ borderTop: `2px solid ${PRODUCT_COLORS.cloud}` }} />
            </Grid>
          )}
          {product === 'ai' && (
            <Grid item xs={6} sm={3}>
              <MetricCard title="AI" value={aiCount} sx={{ borderTop: `2px solid ${PRODUCT_COLORS.ai}` }} />
            </Grid>
          )}
          <Grid item xs={6} sm={3}>
            <Tooltip title="Third-party or customer documents imported via External Doc import">
              <Box>
                <MetricCard title="External" value={externalCount} sx={externalCount > 0 ? { borderTop: `2px solid ${isLight ? '#9a6500' : '#FFC000'}` } : {}} />
              </Box>
            </Tooltip>
          </Grid>
        </Grid>
      )}

      {/* Filters */}
      <Card sx={{ mb: 2 }}>
        <CardContent sx={{ pb: '12px !important' }}>
          <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap', alignItems: 'center' }}>
            <Chip
              label={
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
                  <Box sx={{ width: 6, height: 6, borderRadius: '50%', bgcolor: isLight ? '#9a6500' : '#FFC000' }} />
                  External only
                </Box>
              }
              size="small"
              onClick={() => setExternalOnly(v => !v)}
              sx={{
                fontSize: '0.75rem', height: 28, cursor: 'pointer',
                bgcolor: externalOnly ? (isLight ? 'rgba(230,160,0,0.15)' : 'rgba(255,192,0,0.15)') : 'transparent',
                color: externalOnly ? (isLight ? '#7a4800' : '#FFC000') : 'text.secondary',
                border: '1px solid',
                borderColor: externalOnly ? (isLight ? 'rgba(180,110,0,0.4)' : 'rgba(255,192,0,0.5)') : (isLight ? 'rgba(0,0,0,0.15)' : 'rgba(255,255,255,0.1)'),
                fontWeight: externalOnly ? 700 : 400,
                '&:hover': { bgcolor: isLight ? 'rgba(230,160,0,0.12)' : 'rgba(255,192,0,0.1)', color: isLight ? '#7a4800' : '#FFC000' },
              }}
            />

            <FormControl size="small" sx={{ minWidth: 160 }}>
              <InputLabel>Type</InputLabel>
              <Select value={typeFilter} onChange={(e) => setTypeFilter(e.target.value)} label="Type">
                <MenuItem value="">All types</MenuItem>
                {product === 'isms' && [
                  <MenuItem key="POL" value="POL">POL</MenuItem>,
                  <MenuItem key="OP-POL" value="OP-POL">OP-POL</MenuItem>,
                  <MenuItem key="INS" value="INS">INS</MenuItem>,
                  <MenuItem key="REF" value="REF">REF</MenuItem>,
                  <MenuItem key="CTX" value="CTX">CTX</MenuItem>,
                  <MenuItem key="FORM" value="FORM">FORM</MenuItem>,
                ]}
                {product === 'privacy' && <MenuItem value="PRIV-POL">PRIV-POL</MenuItem>}
                {product === 'cloud'   && <MenuItem value="CLD-POL">CLD-POL</MenuItem>}
                {product === 'ai'      && <MenuItem value="AI-POL">AI-POL</MenuItem>}
              </Select>
            </FormControl>

            <TextField
              size="small"
              placeholder="Search policies..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              sx={{ flex: 1, minWidth: 200 }}
              InputProps={{
                startAdornment: (
                  <InputAdornment position="start">
                    <SearchOutlined fontSize="small" sx={{ color: 'text.secondary' }} />
                  </InputAdornment>
                ),
              }}
            />

            {/* Language filter — only show if multiple languages present */}
            {Object.keys(langCounts).length > 1 && (
              <Box sx={{ display: 'flex', gap: 0.5, alignItems: 'center' }}>
                {(['', 'en', 'de', 'fr', 'it'] as const).map((l) => {
                  if (l !== '' && !langCounts[l]) return null
                  const label = l === '' ? 'All' : l.toUpperCase()
                  const count = l === '' ? (data?.length ?? 0) : (langCounts[l] ?? 0)
                  const active = langFilter === l
                  return (
                    <Chip
                      key={l}
                      label={`${label} ${count}`}
                      size="small"
                      onClick={() => setLangFilter(l)}
                      sx={{
                        fontSize: '0.68rem', height: 22, cursor: 'pointer',
                        bgcolor: active ? 'rgba(68,114,196,0.25)' : 'rgba(255,255,255,0.05)',
                        color: active ? 'primary.light' : 'text.secondary',
                        border: active ? '1px solid rgba(68,114,196,0.4)' : '1px solid transparent',
                      }}
                    />
                  )
                })}
              </Box>
            )}
          </Box>
        </CardContent>
      </Card>

      {error && <Alert severity="error" sx={{ mb: 2 }}>Failed to load policies.</Alert>}

      <TableContainer component={Card}>
        <Table size="small">
          <TableHead>
            <TableRow>
              <TableCell>Control Group</TableCell>
              <TableCell>Document</TableCell>
              <TableCell sx={{ width: 110 }}>Product</TableCell>
              <TableCell sx={{ width: 70 }}>Type</TableCell>
              <TableCell sx={{ width: 80, textAlign: 'right' }}>Words</TableCell>
              <TableCell sx={{ width: 80, textAlign: 'right' }}>Reqs</TableCell>
              <TableCell sx={{ width: 40 }} />
            </TableRow>
          </TableHead>
          <TableBody>
            {isLoading &&
              [...Array(10)].map((_, i) => (
                <TableRow key={i}>
                  {[...Array(6)].map((_, j) => (
                    <TableCell key={j}><Skeleton variant="text" /></TableCell>
                  ))}
                </TableRow>
              ))}
            {filtered.map((p) => {
              const isExternal = p.product_type === 'external'
              return (
                <TableRow
                  key={p.id}
                  hover
                  sx={{
                    cursor: 'pointer',
                    ...(isExternal && { bgcolor: isLight ? 'rgba(230,160,0,0.05)' : 'rgba(255,192,0,0.03)', '&:hover': { bgcolor: `${isLight ? 'rgba(230,160,0,0.1)' : 'rgba(255,192,0,0.07)'} !important` } }),
                  }}
                  onClick={() => navigate(`/controls/${p.control_group_id}`)}
                >
                  <TableCell>
                    <Typography variant="caption" sx={{ fontFamily: 'monospace', color: p.group_code === '00' ? (isLight ? '#7a4800' : '#FFC000') : 'primary.light', fontWeight: 700 }}>
                      {p.group_code === '00' ? '00' : p.group_code.toUpperCase()}
                    </Typography>
                    <Typography variant="caption" color="text.secondary" sx={{ display: 'block', lineHeight: 1.3 }}>
                      {p.group_name}
                    </Typography>
                  </TableCell>
                  <TableCell>
                    <Typography variant="caption" sx={{ fontFamily: 'monospace', color: isExternal ? (isLight ? '#7a4800' : '#FFC000') : 'text.secondary', fontSize: '0.68rem' }}>
                      {p.document_id}
                    </Typography>
                    <Typography variant="body2" fontWeight={600} sx={{ lineHeight: 1.3 }}>{p.title}</Typography>
                    {isExternal && p.source_label && (
                      <Typography variant="caption" sx={{ color: isLight ? '#7a4800' : '#FFC000', fontSize: '0.65rem' }}>
                        External — {p.source_label}
                      </Typography>
                    )}
                    {p.language && p.language !== 'en' && (
                      <Chip label={p.language.toUpperCase()} size="small" sx={{ fontSize: '0.6rem', height: 14, mt: 0.25, bgcolor: 'rgba(255,255,255,0.06)', color: 'text.secondary' }} />
                    )}
                  </TableCell>
                  <TableCell>
                    <Chip
                      label={p.product_type}
                      size="small"
                      sx={{ fontSize: '0.65rem', height: 18, ...productChipStyle(p.product_type) }}
                    />
                  </TableCell>
                  <TableCell>
                    <Chip label={p.policy_type.toUpperCase()} size="small" sx={{ fontSize: '0.65rem', height: 18 }} />
                  </TableCell>
                  <TableCell align="right">
                    <Typography variant="caption" color="text.secondary">
                      {p.word_count?.toLocaleString() ?? '—'}
                    </Typography>
                  </TableCell>
                  <TableCell align="right">
                    <Typography variant="caption" color={p.requirements_count > 0 ? 'primary.light' : 'text.secondary'} fontWeight={p.requirements_count > 0 ? 600 : 400}>
                      {p.requirements_count > 0 ? p.requirements_count : '—'}
                    </Typography>
                  </TableCell>
                  <TableCell onClick={(e) => e.stopPropagation()}>
                    {isExternal && (
                      <Tooltip title="Delete external document">
                        <IconButton
                          size="small"
                          onClick={() => setDeleteTarget({ id: p.id, title: p.title })}
                          sx={{ color: 'error.main', opacity: 0.5, '&:hover': { opacity: 1 } }}
                        >
                          <DeleteOutlined sx={{ fontSize: 16 }} />
                        </IconButton>
                      </Tooltip>
                    )}
                  </TableCell>
                </TableRow>
              )
            })}
            {!isLoading && filtered.length === 0 && (
              <TableRow>
                <TableCell colSpan={7} align="center">
                  <Typography variant="body2" color="text.secondary" sx={{ py: 3 }}>
                    No policies match the current filters.
                  </Typography>
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </TableContainer>

      {/* Delete confirm dialog */}
      <Dialog open={!!deleteTarget} onClose={() => setDeleteTarget(null)} maxWidth="xs" fullWidth>
        <DialogTitle>Delete External Document?</DialogTitle>
        <DialogContent>
          <Typography variant="body2">
            <strong>{deleteTarget?.title}</strong> will be permanently removed from the platform.
            This cannot be undone.
          </Typography>
          {deleteMutation.isError && (
            <Alert severity="error" sx={{ mt: 1.5 }}>Delete failed. Try again.</Alert>
          )}
        </DialogContent>
        <DialogActions sx={{ px: 3, pb: 2 }}>
          <Button onClick={() => setDeleteTarget(null)} disabled={deleteMutation.isPending}>Cancel</Button>
          <Button
            variant="contained"
            color="error"
            disabled={deleteMutation.isPending}
            startIcon={deleteMutation.isPending ? <CircularProgress size={14} /> : <DeleteOutlined />}
            onClick={() => deleteTarget && deleteMutation.mutate(deleteTarget.id)}
          >
            {deleteMutation.isPending ? 'Deleting…' : 'Delete'}
          </Button>
        </DialogActions>
      </Dialog>

      {/* Import External Document Dialog */}
      <ImportExternalDialog
        open={importOpen}
        onClose={() => setImportOpen(false)}
        onSuccess={() => {
          setImportOpen(false)
          queryClient.invalidateQueries({ queryKey: ['policies'] })
        }}
      />
    </Box>
  )
}

// ---------------------------------------------------------------------------
// Import External Document Dialog
// ---------------------------------------------------------------------------
function ImportExternalDialog({
  open,
  onClose,
  onSuccess,
}: {
  open: boolean
  onClose: () => void
  onSuccess: () => void
}) {
  const fileRef = useRef<HTMLInputElement>(null)
  const [file, setFile] = useState<File | null>(null)
  const [groupCode, setGroupCode] = useState('')
  const [sourceLabel, setSourceLabel] = useState('')
  const [language, setLanguage] = useState('en')
  const [result, setResult] = useState<{ document_id: string; title: string; word_count: number; requirements_extracted: number } | null>(null)

  const { data: groups } = useQuery({
    queryKey: ['control-groups-list'],
    queryFn: () => controlsApi.list(),
    enabled: open,
  })

  const importMutation = useMutation({
    mutationFn: () => policiesApi.importExternal(file!, groupCode, sourceLabel, language),
    onSuccess: (data) => setResult(data),
  })

  const handleClose = () => {
    setFile(null)
    setGroupCode('')
    setSourceLabel('')
    setLanguage('en')
    setResult(null)
    onClose()
  }

  const canSubmit = !!file && !!groupCode && !!sourceLabel && !importMutation.isPending

  return (
    <Dialog open={open} onClose={handleClose} maxWidth="sm" fullWidth>
      <DialogTitle sx={{ pb: 1 }}>
        Import External Document
        <Typography variant="caption" color="text.secondary" display="block">
          PDF, DOCX, or Markdown — any format, no ISMS CORE watermark required
        </Typography>
      </DialogTitle>
      <DialogContent sx={{ display: 'flex', flexDirection: 'column', gap: 2, pt: '8px !important' }}>
        {result ? (
          <Alert severity="success">
            <Typography variant="body2" fontWeight={600}>{result.title}</Typography>
            <Typography variant="caption" sx={{ fontFamily: 'monospace', display: 'block' }}>{result.document_id}</Typography>
            <Typography variant="caption">{result.word_count.toLocaleString()} words · {result.requirements_extracted} requirements extracted</Typography>
          </Alert>
        ) : (
          <>
            {importMutation.isError && (
              <Alert severity="error" sx={{ mb: 1 }}>
                Import failed. Check file format and try again.
              </Alert>
            )}

            {/* File picker */}
            <Box
              onClick={() => fileRef.current?.click()}
              sx={{
                border: '1px dashed',
                borderColor: file ? 'primary.main' : 'divider',
                borderRadius: 2,
                p: 2,
                cursor: 'pointer',
                textAlign: 'center',
                bgcolor: file ? 'rgba(68,114,196,0.07)' : 'transparent',
                '&:hover': { borderColor: 'primary.main', bgcolor: 'rgba(68,114,196,0.05)' },
              }}
            >
              <UploadFileOutlined sx={{ color: 'text.secondary', mb: 0.5 }} />
              <Typography variant="body2" color={file ? 'primary.light' : 'text.secondary'}>
                {file ? file.name : 'Click to select a file (.pdf, .docx, .md)'}
              </Typography>
              {file && (
                <Typography variant="caption" color="text.secondary">
                  {(file.size / 1024).toFixed(1)} KB
                </Typography>
              )}
              <input
                ref={fileRef}
                type="file"
                accept=".pdf,.docx,.doc,.md"
                style={{ display: 'none' }}
                onChange={(e) => setFile(e.target.files?.[0] ?? null)}
              />
            </Box>

            {/* Control group */}
            <FormControl size="small" fullWidth required>
              <InputLabel>Control Group *</InputLabel>
              <Select value={groupCode} onChange={(e) => setGroupCode(e.target.value)} label="Control Group *">
                <MenuItem value=""><em>Select control group…</em></MenuItem>
                {(groups ?? []).map((g) => (
                  <MenuItem key={g.group_code} value={g.group_code}>
                    <Typography component="span" sx={{ fontFamily: 'monospace', fontSize: '0.75rem', color: 'primary.light', mr: 1 }}>
                      {g.group_code.toUpperCase()}
                    </Typography>
                    {g.group_name}
                  </MenuItem>
                ))}
              </Select>
            </FormControl>

            {/* Source label */}
            <TextField
              size="small"
              label="Source / Organisation *"
              placeholder="e.g. Previous consultant, Acme Corp, ISO 27001 Toolkit"
              value={sourceLabel}
              onChange={(e) => setSourceLabel(e.target.value)}
              fullWidth
              required
              helperText="Shown as amber 'External Document — [source]' banner throughout the platform"
            />

            {/* Language */}
            <FormControl size="small" sx={{ width: 160 }}>
              <InputLabel>Language</InputLabel>
              <Select value={language} onChange={(e) => setLanguage(e.target.value)} label="Language">
                <MenuItem value="en">EN — English</MenuItem>
                <MenuItem value="de">DE — Deutsch</MenuItem>
                <MenuItem value="fr">FR — Français</MenuItem>
                <MenuItem value="it">IT — Italiano</MenuItem>
              </Select>
            </FormControl>
          </>
        )}
      </DialogContent>
      <DialogActions sx={{ px: 3, pb: 2 }}>
        {result ? (
          <>
            <Button onClick={handleClose}>Close</Button>
            <Button variant="contained" onClick={onSuccess}>View in Policies</Button>
          </>
        ) : (
          <>
            <Button onClick={handleClose} disabled={importMutation.isPending}>Cancel</Button>
            <Button
              variant="contained"
              disabled={!canSubmit}
              onClick={() => importMutation.mutate()}
              startIcon={importMutation.isPending ? <CircularProgress size={14} /> : <UploadFileOutlined />}
            >
              {importMutation.isPending ? 'Importing…' : 'Import'}
            </Button>
          </>
        )}
      </DialogActions>
    </Dialog>
  )
}

// isms-core-platform/frontend/src/app/pages/policies/policies.component.ts
import { Component, inject, signal, computed, effect, ElementRef, viewChild } from '@angular/core'
import { NgStyle } from '@angular/common'
import { Router } from '@angular/router'
import { FormsModule } from '@angular/forms'
import { firstValueFrom } from 'rxjs'

import { injectQuery, injectMutation, injectQueryClient } from '@tanstack/angular-query-experimental'

import { MatCardModule } from '@angular/material/card'
import { MatTableModule } from '@angular/material/table'
import { MatFormFieldModule } from '@angular/material/form-field'
import { MatInputModule } from '@angular/material/input'
import { MatSelectModule } from '@angular/material/select'
import { MatChipsModule } from '@angular/material/chips'
import { MatButtonModule } from '@angular/material/button'
import { MatIconModule } from '@angular/material/icon'
import { MatDialogModule, MatDialog, MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog'
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner'
import { MatTooltipModule } from '@angular/material/tooltip'

import { PoliciesApiService, PolicyRead } from '../../api/policies-api.service'
import { ControlsApiService } from '../../api/controls-api.service'
import { ProductService, PRODUCT_COLORS } from '../../core/services/product.service'
import { ThemeService } from '../../core/services/theme.service'
import { PageHeaderComponent } from '../../shared/components/page-header.component'
import { MetricCardComponent } from '../../shared/components/metric-card.component'

// ─── Delete Confirm Dialog ────────────────────────────────────────────────────

@Component({
  selector: 'app-policies-delete-dialog',
  standalone: true,
  imports: [MatButtonModule, MatDialogModule, MatIconModule],
  template: `
    <h2 mat-dialog-title>Delete External Document?</h2>
    <mat-dialog-content>
      <strong>{{ data.title }}</strong> will be permanently removed from the platform. This cannot be undone.
    </mat-dialog-content>
    <mat-dialog-actions>
      <button mat-stroked-button [mat-dialog-close]="false">Cancel</button>
      <button mat-raised-button color="warn" [mat-dialog-close]="true">
        <mat-icon>delete</mat-icon> Delete
      </button>
    </mat-dialog-actions>
  `,
})
export class PoliciesDeleteDialogComponent {
  readonly data = inject<{ title: string }>(MAT_DIALOG_DATA)
}

// ─── Import External Dialog ───────────────────────────────────────────────────
@Component({
  selector: 'app-import-external-dialog',
  standalone: true,
  imports: [
    FormsModule,
    MatButtonModule, MatDialogModule, MatFormFieldModule, MatInputModule,
    MatSelectModule, MatIconModule, MatProgressSpinnerModule,
  ],
  template: `
    <h2 mat-dialog-title>
      Import External Document
      <small class="dialog-subtitle">
        PDF, DOCX, or Markdown — any format, no ISMS CORE watermark required
      </small>
    </h2>

    <mat-dialog-content>
      @if (result()) {
        <div class="import-success">
          <mat-icon class="success-icon">check_circle</mat-icon>
          <div>
            <div class="result-title">{{ result()!.title }}</div>
            <div class="result-doc-id">{{ result()!.document_id }}</div>
            <div class="result-meta">
              {{ result()!.word_count.toLocaleString() }} words · {{ result()!.requirements_extracted }} requirements extracted
            </div>
          </div>
        </div>
      } @else {
        @if (importMutation.isError()) {
          <div class="alert-error">Import failed. Check file format and try again.</div>
        }

        <div
          class="file-drop"
          [class.file-drop--active]="selectedFile()"
          (click)="fileInput.click()"
        >
          <input
            #fileInput
            type="file"
            accept=".pdf,.docx,.doc,.md"
            class="file-input-hidden"
            (change)="onFileChange($event)"
          />
          <mat-icon class="upload-icon">upload_file</mat-icon>
          <span [style.color]="selectedFile() ? 'var(--mat-sys-primary)' : 'var(--mat-sys-on-surface-variant)'">
            {{ selectedFile() ? selectedFile()!.name : 'Click to select a file (.pdf, .docx, .md)' }}
          </span>
          @if (selectedFile()) {
            <small class="file-size-hint">{{ (selectedFile()!.size / 1024).toFixed(1) }} KB</small>
          }
        </div>

        <mat-form-field appearance="outline" class="full-width">
          <mat-label>Control Group *</mat-label>
          <mat-select [(ngModel)]="groupCode">
            <mat-option value=""><em>Select control group…</em></mat-option>
            @for (g of controlGroups.data() ?? []; track g.id) {
              <mat-option [value]="g.group_code">
                <span class="group-code-option">{{ g.group_code.toUpperCase() }}</span>
                {{ g.group_name }}
              </mat-option>
            }
          </mat-select>
        </mat-form-field>

        <mat-form-field appearance="outline" class="full-width">
          <mat-label>Source / Organisation *</mat-label>
          <input matInput [(ngModel)]="sourceLabel" placeholder="e.g. Previous consultant, Acme Corp" />
          <mat-hint>Shown as amber 'External — [source]' label throughout the platform</mat-hint>
        </mat-form-field>

        <mat-form-field appearance="outline" class="lang-select-field">
          <mat-label>Language</mat-label>
          <mat-select [(ngModel)]="language">
            <mat-option value="en">EN — English</mat-option>
            <mat-option value="de">DE — Deutsch</mat-option>
            <mat-option value="fr">FR — Français</mat-option>
            <mat-option value="it">IT — Italiano</mat-option>
          </mat-select>
        </mat-form-field>
      }
    </mat-dialog-content>

    <mat-dialog-actions align="end">
      @if (result()) {
        <button mat-button (click)="matDialog.closeAll()">Close</button>
        <button mat-raised-button color="primary" (click)="matDialog.closeAll()">View in Policies</button>
      } @else {
        <button mat-button [disabled]="importMutation.isPending()" (click)="matDialog.closeAll()">Cancel</button>
        <button mat-raised-button color="primary" [disabled]="!canSubmit()" (click)="doImport()">
          @if (importMutation.isPending()) {
            Importing…
          } @else {
            <mat-icon>upload_file</mat-icon>
            Import
          }
        </button>
      }
    </mat-dialog-actions>
  `,
  styles: [`
    mat-dialog-content {
      display: flex; flex-direction: column; gap: 16px;
      padding-top: 8px !important; min-width: 460px;
    }
    .full-width { width: 100%; }
    .lang-select-field { width: 160px; }
    .dialog-subtitle {
      display: block; font-size: 0.75rem; font-weight: 400;
      color: var(--mat-sys-on-surface-variant); margin-top: 2px;
    }
    .file-input-hidden { display: none; }
    .upload-icon { color: var(--mat-sys-on-surface-variant); }
    .file-size-hint { color: var(--mat-sys-on-surface-variant); }
    .group-code-option {
      font-family: monospace; font-size: 0.75rem;
      color: var(--mat-sys-primary); margin-right: 8px;
    }
    .success-icon { color: var(--mat-sys-primary); }
    .result-title { font-weight: 600; font-size: 0.9rem; }
    .result-doc-id { font-family: monospace; font-size: 0.75rem; color: var(--mat-sys-on-surface-variant); }
    .result-meta { font-size: 0.78rem; color: var(--mat-sys-on-surface-variant); }
    .file-drop {
      display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 6px;
      border: 1px dashed var(--mat-sys-outline); border-radius: 8px; padding: 20px;
      cursor: pointer; text-align: center; transition: border-color 0.2s, background 0.2s;
    }
    .file-drop:hover { border-color: var(--mat-sys-primary); background: color-mix(in srgb, var(--mat-sys-primary) 5%, transparent); }
    .file-drop--active { border-color: var(--mat-sys-primary); background: color-mix(in srgb, var(--mat-sys-primary) 7%, transparent); }
    .import-success {
      display: flex; align-items: flex-start; gap: 12px;
      background: rgba(46,125,50,0.1); border: 1px solid rgba(46,125,50,0.3);
      border-radius: 6px; padding: 14px;
    }
    .alert-error {
      background: rgba(192,0,0,0.1); border: 1px solid rgba(192,0,0,0.3);
      border-radius: 6px; padding: 10px 14px; font-size: 0.85rem;
      color: var(--mat-sys-error);
    }
  `],
})
export class ImportExternalDialogComponent {
  matDialog = inject(MatDialog)
  private policiesApi = inject(PoliciesApiService)
  private controlsApi = inject(ControlsApiService)
  private queryClient = injectQueryClient()

  fileInput = viewChild.required<ElementRef<HTMLInputElement>>('fileInput')

  selectedFile = signal<File | null>(null)
  groupCode = ''
  sourceLabel = ''
  language = 'en'
  result = signal<{ document_id: string; title: string; word_count: number; requirements_extracted: number } | null>(null)

  controlGroups = injectQuery(() => ({
    queryKey: ['control-groups-list'],
    queryFn: () => firstValueFrom(this.controlsApi.list()),
  }))

  importMutation = injectMutation(() => ({
    mutationFn: () => firstValueFrom(
      this.policiesApi.importExternal(this.selectedFile()!, this.groupCode, this.sourceLabel, this.language)
    ),
    onSuccess: (data: any) => {
      this.result.set(data)
      this.queryClient.invalidateQueries({ queryKey: ['policies'] })
    },
  }))

  canSubmit = computed(() =>
    !!this.selectedFile() && !!this.groupCode && !!this.sourceLabel && !this.importMutation.isPending()
  )

  onFileChange(event: Event): void {
    const input = event.target as HTMLInputElement
    this.selectedFile.set(input.files?.[0] ?? null)
  }

  doImport(): void {
    if (!this.canSubmit()) return
    this.importMutation.mutate(undefined)
  }
}

// ─── Main Component ───────────────────────────────────────────────────────────
@Component({
  selector: 'app-policies',
  standalone: true,
  imports: [
    NgStyle, FormsModule,
    MatCardModule, MatTableModule, MatFormFieldModule, MatInputModule,
    MatSelectModule, MatChipsModule, MatButtonModule, MatIconModule,
    MatDialogModule, MatProgressSpinnerModule, MatTooltipModule,
    PageHeaderComponent, MetricCardComponent,
    PoliciesDeleteDialogComponent,
  ],
  template: `
    <app-page-header [title]="'Policies'" [subtitle]="headerSubtitle()">
      <div actions>
        <button mat-stroked-button (click)="openImport()">
          <mat-icon>upload_file</mat-icon>
          Import External Doc
        </button>
      </div>
    </app-page-header>

    <!-- Metric cards -->
    @if (!policiesQuery.isLoading()) {
      <div class="metrics-row">
        <app-metric-card title="Total" [value]="allPolicies().length" icon="policy" />
        @if (product() === 'isms') {
          <app-metric-card title="Framework" [value]="frameworkCount()" />
          <app-metric-card title="Operational" [value]="operationalCount()" />
        }
        @if (product() === 'privacy') {
          <app-metric-card title="Privacy" [value]="privacyCount()" />
        }
        @if (product() === 'cloud') {
          <app-metric-card title="Cloud" [value]="cloudCount()" />
        }
        @if (product() === 'ai') {
          <app-metric-card title="AI" [value]="aiCount()" />
        }
        <app-metric-card title="External" [value]="externalCount()" />
      </div>
    }

    <!-- Filters -->
    <mat-card class="filter-card">
      <mat-card-content>
        <div class="filter-row">

          <!-- External only toggle chip -->
          <div
            class="ext-chip"
            [class.ext-chip--active]="externalOnly()"
            (click)="toggleExternalOnly()"
          >
            <span class="dot" [style.background]="isDark() ? '#FFC000' : '#9a6500'"></span>
            External only
          </div>

          <!-- Type -->
          <mat-form-field appearance="outline" subscriptSizing="dynamic" class="type-filter-field">
            <mat-label>Type</mat-label>
            <mat-select [ngModel]="typeFilter()" (ngModelChange)="typeFilter.set($event)">
              <mat-option value="">All types</mat-option>
              @if (product() === 'isms') {
                <mat-option value="POL">POL</mat-option>
                <mat-option value="OP-POL">OP-POL</mat-option>
                <mat-option value="INS">INS</mat-option>
                <mat-option value="REF">REF</mat-option>
                <mat-option value="CTX">CTX</mat-option>
                <mat-option value="FORM">FORM</mat-option>
              }
              @if (product() === 'privacy') { <mat-option value="PRIV-POL">PRIV-POL</mat-option> }
              @if (product() === 'cloud')   { <mat-option value="CLD-PII-POL">CLD-PII-POL</mat-option> }
              @if (product() === 'ai')      { <mat-option value="AI-POL">AI-POL</mat-option> }
            </mat-select>
          </mat-form-field>

          <!-- Search -->
          <mat-form-field appearance="outline" subscriptSizing="dynamic" class="search-field">
            <mat-label>Search policies</mat-label>
            <mat-icon matPrefix class="icon-md">search</mat-icon>
            <input matInput [ngModel]="search()" (ngModelChange)="search.set($event)" placeholder="document ID, title, group…" />
          </mat-form-field>

          <!-- Language chips — only when multi-lang -->
          @if (hasMultiLang()) {
            <div class="lang-chips">
              @for (l of langOptions(); track l.value) {
                <div
                  class="lang-chip"
                  [class.lang-chip--active]="langFilter() === l.value"
                  (click)="langFilter.set(l.value)"
                >{{ l.label }} {{ l.count }}</div>
              }
            </div>
          }
        </div>
      </mat-card-content>
    </mat-card>

    <!-- Error banner -->
    @if (policiesQuery.isError()) {
      <div class="alert-error alert-error-banner">Failed to load policies.</div>
    }

    <!-- Table -->
    <mat-card class="table-card">
      <table mat-table [dataSource]="tableData()" class="full-table">

        <!-- Control Group -->
        <ng-container matColumnDef="group">
          <th mat-header-cell *matHeaderCellDef>Control Group</th>
          <td mat-cell *matCellDef="let p" class="clickable" (click)="navigateToControl(p)">
            <span class="group-code" [style.color]="groupCodeColor(p)">
              {{ p.group_code === '00' ? '00' : (p.group_code ?? '—').toUpperCase() }}
            </span>
            <span class="group-name">{{ p.group_name ?? '' }}</span>
          </td>
        </ng-container>

        <!-- Document -->
        <ng-container matColumnDef="document">
          <th mat-header-cell *matHeaderCellDef>Document</th>
          <td mat-cell *matCellDef="let p" class="clickable" (click)="navigateToControl(p)">
            <span class="doc-id"
              [style.color]="p.product_type === 'external' ? (isDark() ? '#FFC000' : '#7a4800') : 'var(--mat-sys-on-surface-variant)'">
              {{ p.document_id }}
            </span>
            <span class="doc-title">{{ p.title }}</span>
            @if (p.product_type === 'external' && p.source_label) {
              <span class="source-lbl" [style.color]="isDark() ? '#FFC000' : '#7a4800'">External — {{ p.source_label }}</span>
            }
            @if (p.language && p.language !== 'en') {
              <span class="lang-badge">{{ p.language.toUpperCase() }}</span>
            }
          </td>
        </ng-container>

        <!-- Product -->
        <ng-container matColumnDef="product">
          <th mat-header-cell *matHeaderCellDef class="col-product">Product</th>
          <td mat-cell *matCellDef="let p" class="clickable" (click)="navigateToControl(p)">
            <span class="product-chip" [ngStyle]="productChipStyle(p.product_type)">{{ p.product_type }}</span>
          </td>
        </ng-container>

        <!-- Type -->
        <ng-container matColumnDef="type">
          <th mat-header-cell *matHeaderCellDef class="col-type">Type</th>
          <td mat-cell *matCellDef="let p" class="clickable" (click)="navigateToControl(p)">
            <span class="type-chip">{{ p.policy_type.toUpperCase() }}</span>
          </td>
        </ng-container>

        <!-- Words -->
        <ng-container matColumnDef="words">
          <th mat-header-cell *matHeaderCellDef class="col-words col-right">Words</th>
          <td mat-cell *matCellDef="let p" class="col-right clickable" (click)="navigateToControl(p)">
            <span class="cell-secondary">{{ p.word_count != null ? p.word_count.toLocaleString() : '—' }}</span>
          </td>
        </ng-container>

        <!-- Reqs -->
        <ng-container matColumnDef="reqs">
          <th mat-header-cell *matHeaderCellDef class="col-reqs col-right">Reqs</th>
          <td mat-cell *matCellDef="let p" class="col-right clickable" (click)="navigateToControl(p)">
            <span class="reqs-value"
              [style.color]="(p.requirements_count ?? 0) > 0 ? 'var(--mat-sys-primary)' : 'var(--mat-sys-on-surface-variant)'"
              [style.font-weight]="(p.requirements_count ?? 0) > 0 ? '600' : '400'"
            >{{ (p.requirements_count ?? 0) > 0 ? p.requirements_count : '—' }}</span>
          </td>
        </ng-container>

        <!-- Actions -->
        <ng-container matColumnDef="actions">
          <th mat-header-cell *matHeaderCellDef class="col-actions"></th>
          <td mat-cell *matCellDef="let p">
            @if (p.product_type === 'external') {
              <button mat-icon-button class="del-btn"
                matTooltip="Delete external document"
                (click)="$event.stopPropagation(); openDelete(p)">
                <mat-icon class="icon-sm">delete</mat-icon>
              </button>
            }
          </td>
        </ng-container>

        <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
        <tr mat-row *matRowDef="let p; columns: displayedColumns"
          class="policy-row"
          [class.policy-row--external]="p.product_type === 'external'"></tr>

        <tr class="mat-row" *matNoDataRow>
          <td [attr.colspan]="displayedColumns.length" class="no-data-cell">
            @if (policiesQuery.isLoading()) {
              <span class="no-data-text">Loading…</span>
            } @else {
              <span class="no-data-text">No policies match the current filters.</span>
            }
          </td>
        </tr>
      </table>
    </mat-card>

  `,
  styles: [`
    :host { display: block; }

    .metrics-row { display: flex; gap: 16px; margin-top: 16px; margin-bottom: 16px; }
    .metrics-row > * { flex: 1; }

    .filter-card { margin-bottom: 16px; }
    .filter-card mat-card-content { padding-bottom: 12px !important; }
    .filter-row { display: flex; gap: 12px; flex-wrap: wrap; align-items: center; }

    .type-filter-field { width: 160px; }
    .search-field { flex: 1; min-width: 200px; }

    .ext-chip {
      display: flex; align-items: center; gap: 6px;
      height: 28px; padding: 0 12px; border-radius: 14px; cursor: pointer;
      font-size: 0.75rem; border: 1px solid var(--mat-sys-outline-variant);
      color: var(--mat-sys-on-surface-variant); white-space: nowrap;
      transition: all 0.15s;
    }
    .ext-chip:hover { background: rgba(255,192,0,0.1); color: #FFC000; }
    .ext-chip--active { background: rgba(255,192,0,0.15); color: #FFC000; border-color: rgba(255,192,0,0.5); font-weight: 700; }
    .dot { width: 6px; height: 6px; border-radius: 50%; flex-shrink: 0; }

    .lang-chips { display: flex; gap: 4px; align-items: center; }
    .lang-chip {
      height: 22px; padding: 0 8px; border-radius: 11px; cursor: pointer;
      font-size: 0.68rem; border: 1px solid transparent;
      background: rgba(0,0,0,0.04); color: var(--mat-sys-on-surface-variant);
      display: flex; align-items: center; white-space: nowrap;
    }
    .lang-chip--active { background: color-mix(in srgb, var(--mat-sys-primary) 22%, transparent); color: var(--mat-sys-primary); border-color: color-mix(in srgb, var(--mat-sys-primary) 40%, transparent); }

    .table-card { overflow: hidden; }
    .full-table { width: 100%; }

    .clickable { cursor: pointer; }
    .col-right { text-align: right; }
    .col-product { width: 110px; }
    .col-type { width: 70px; }
    .col-words { width: 80px; }
    .col-reqs { width: 80px; }
    .col-actions { width: 40px; }

    .no-data-cell { text-align: center; padding: 24px; }
    .no-data-text { color: var(--mat-sys-on-surface-variant); font-size: 0.875rem; }
    .reqs-value { font-size: 0.78rem; }

    .group-code { display: block; font-family: monospace; font-weight: 700; font-size: 0.78rem; }
    .group-name { display: block; font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); line-height: 1.3; }
    .doc-id { display: block; font-family: monospace; font-size: 0.68rem; }
    .doc-title { display: block; font-weight: 600; font-size: 0.875rem; line-height: 1.3; }
    .source-lbl { display: block; font-size: 0.65rem; }
    .lang-badge {
      display: inline-block; font-size: 0.6rem; height: 14px; padding: 0 4px;
      border-radius: 3px; background: rgba(0,0,0,0.05); color: var(--mat-sys-on-surface-variant);
      vertical-align: middle; margin-top: 2px; line-height: 14px;
    }
    .product-chip {
      font-size: 0.65rem; height: 18px; line-height: 18px; padding: 0 6px;
      border-radius: 9px; display: inline-block; font-weight: 600;
    }
    .type-chip {
      font-size: 0.65rem; height: 18px; line-height: 18px; padding: 0 6px;
      border-radius: 9px; display: inline-block;
      background: var(--mat-sys-surface-variant); color: var(--mat-sys-on-surface-variant);
    }
    .cell-secondary { font-size: 0.78rem; color: var(--mat-sys-on-surface-variant); }

    .policy-row:hover td { background: rgba(255,255,255,0.04); }
    .policy-row--external { background: rgba(255,192,0,0.03); }

    .del-btn { color: var(--mat-sys-error); opacity: 0.5; }
    .del-btn:hover { opacity: 1; }

    .alert-error {
      padding: 10px 14px; border-radius: 6px; font-size: 0.85rem;
      background: rgba(192,0,0,0.1); border: 1px solid rgba(192,0,0,0.3); color: var(--mat-sys-error);
    }
    .alert-error-banner { margin-bottom: 16px; }
    .alert-error-mb { margin-bottom: 12px; }
  `],
})
export class PoliciesComponent {
  private router = inject(Router)
  private dialog = inject(MatDialog)
  private policiesApi = inject(PoliciesApiService)
  private productService = inject(ProductService)
  private themeService = inject(ThemeService)
  private queryClient = injectQueryClient()

  externalOnly = signal(false)
  typeFilter   = signal('')
  langFilter   = signal('')
  search       = signal('')

  product   = this.productService.product
  ismsTier  = this.productService.ismsTier
  isDark    = computed(() => this.themeService.isDark())

  displayedColumns = ['group', 'document', 'product', 'type', 'words', 'reqs', 'actions']

  private STANDARD_LABELS: Record<string, string> = {
    isms: 'ISO 27001:2022', privacy: 'ISO 27701:2025', cloud: 'ISO 27018:2025', ai: 'ISO 42001:2023',
  }

  effectiveProduct = computed(() => {
    if (this.externalOnly()) return 'external'
    const p = this.product()
    if (p === 'isms') {
      const tier = this.ismsTier()
      return tier !== 'all' ? tier : 'isms'
    }
    return p
  })

  private prevProduct = this.product()
  constructor() {
    effect(() => {
      const p = this.product()
      if (p !== this.prevProduct) {
        this.prevProduct = p
        this.typeFilter.set('')
      }
    })
  }

  policiesQuery = injectQuery(() => ({
    queryKey: ['policies', this.effectiveProduct(), this.typeFilter()],
    queryFn: () => firstValueFrom(this.policiesApi.list({
      product: this.effectiveProduct(),
      policy_type: this.typeFilter() || undefined,
    })),
  }))

  allPolicies = computed(() => this.policiesQuery.data() ?? [])

  tableData = computed(() => {
    const lf = this.langFilter()
    const s = this.search().toLowerCase()
    const list = this.allPolicies()
    if (!lf && !s) return list
    return list.filter(p => {
      if (lf && (p.language ?? 'en') !== lf) return false
      if (!s) return true
      return (
        (p.document_id ?? '').toLowerCase().includes(s) ||
        (p.title ?? '').toLowerCase().includes(s) ||
        (p.group_code ?? '').toLowerCase().includes(s)
      )
    })
  })

  langCounts = computed(() =>
    this.allPolicies().reduce<Record<string, number>>((acc, p) => {
      const l = p.language ?? 'en'
      acc[l] = (acc[l] ?? 0) + 1
      return acc
    }, {})
  )

  hasMultiLang  = computed(() => Object.keys(this.langCounts()).length > 1)

  langOptions = computed(() => {
    const counts = this.langCounts()
    const total  = this.allPolicies().length
    const opts: { value: string; label: string; count: number }[] = [{ value: '', label: 'All', count: total }]
    for (const l of ['en', 'de', 'fr', 'it']) {
      if (counts[l]) opts.push({ value: l, label: l.toUpperCase(), count: counts[l] })
    }
    return opts
  })

  frameworkCount   = computed(() => this.allPolicies().filter(p => p.product_type === 'framework').length)
  operationalCount = computed(() => this.allPolicies().filter(p => p.product_type === 'operational').length)
  privacyCount     = computed(() => this.allPolicies().filter(p => p.product_type === 'privacy').length)
  cloudCount       = computed(() => this.allPolicies().filter(p => p.product_type === 'cloud').length)
  aiCount          = computed(() => this.allPolicies().filter(p => p.product_type === 'ai').length)
  externalCount    = computed(() => this.allPolicies().filter(p => p.product_type === 'external').length)

  headerSubtitle = computed(() =>
    `${this.allPolicies().length} policy documents · ${this.STANDARD_LABELS[this.product()] ?? 'ISO 27001:2022'}`
  )

  deleteMutation = injectMutation(() => ({
    mutationFn: (id: string) => firstValueFrom(this.policiesApi.delete(id)),
    onSuccess: () => this.queryClient.invalidateQueries({ queryKey: ['policies'] }),
  }))

  productChipStyle(type: string): Record<string, string> {
    const dark = this.isDark()
    if (type === 'external')    return { background: dark ? 'rgba(255,192,0,0.15)' : 'rgba(230,160,0,0.15)', color: dark ? '#FFC000' : '#7a4800' }
    if (type === 'framework')   return { background: 'rgba(50,125,244,0.15)',            color: '#327df4' }
    if (type === 'operational') return { background: 'rgba(112,173,71,0.15)',             color: '#70AD47' }
    if (type === 'privacy')     return { background: `${PRODUCT_COLORS.privacy}22`,       color: PRODUCT_COLORS.privacy }
    if (type === 'cloud')       return { background: `${PRODUCT_COLORS.cloud}22`,         color: PRODUCT_COLORS.cloud }
    if (type === 'ai')          return { background: `${PRODUCT_COLORS.ai}22`,            color: PRODUCT_COLORS.ai }
    return { background: 'rgba(112,173,71,0.15)', color: '#70AD47' }
  }

  groupCodeColor(p: PolicyRead): string {
    if (p.group_code === '00') return this.isDark() ? '#FFC000' : '#7a4800'
    const prod = this.product()
    const c = (p.group_code ?? '').toUpperCase()
    if (prod === 'isms') {
      if (c.startsWith('A.5')) return '#9E9E9E'
      if (c.startsWith('A.6')) return '#70AD47'
      if (c.startsWith('A.7')) return '#FFC000'
      if (c.startsWith('A.8')) return '#C00000'
    }
    if (prod === 'privacy') {
      if (c.startsWith('A.1')) return '#ba68c8'
      if (c.startsWith('A.2')) return '#5c6bc0'
      if (c.startsWith('A.3')) return '#4db6ac'
    }
    return PRODUCT_COLORS[prod] ?? 'var(--mat-sys-primary)'
  }

  navigateToControl(p: PolicyRead): void {
    if (p.control_group_id) this.router.navigate(['/controls', p.control_group_id])
  }

  toggleExternalOnly(): void { this.externalOnly.update(v => !v) }

  openDelete(p: PolicyRead): void {
    const ref = this.dialog.open(PoliciesDeleteDialogComponent, { data: { title: p.title } })
    ref.afterClosed().subscribe((ok: boolean) => { if (ok) this.deleteMutation.mutate(p.id) })
  }

  openImport(): void {
    this.dialog.open(ImportExternalDialogComponent, { maxWidth: '560px', width: '100%' })
  }
}
