// isms-core-platform/frontend/src/pages/MitreAtlas.tsx
import { useState } from 'react'
import {
  Alert, Box, Chip, CircularProgress, FormControl, InputAdornment,
  InputLabel, MenuItem, Paper, Select, Table, TableBody, TableCell,
  TableHead, TableRow, TextField, Typography,
} from '@mui/material'
import { SearchOutlined } from '@mui/icons-material'
import { useQuery } from '@tanstack/react-query'
import { feedsApi, type MitreTechnique } from '../api/feedsApi'
import PageHeader from '../components/PageHeader'

const PER_PAGE = 50
const INTEL_COLOR = '#B84F00'

function TacticChip({ tactic }: { tactic: string }) {
  return (
    <Chip label={tactic} size="small"
      sx={{ fontSize: '0.65rem', height: 18, mr: 0.25, mb: 0.25 }} />
  )
}

export default function MitreAtlas() {
  const [search, setSearch] = useState('')
  const [tactic, setTactic] = useState<string>('')
  const [page, setPage] = useState(1)
  const [selected, setSelected] = useState<MitreTechnique | null>(null)

  const { data: stats } = useQuery({
    queryKey: ['feeds', 'atlas', 'stats'],
    queryFn: feedsApi.getAtlasStats,
  })

  const tactics = stats ? Object.keys(stats.tactic_counts).sort() : []

  const { data, isLoading, error } = useQuery({
    queryKey: ['feeds', 'atlas', tactic, search, page],
    queryFn: () => feedsApi.getAtlasTechniques({
      tactic: tactic || undefined,
      search: search || undefined,
      page,
      per_page: PER_PAGE,
    }),
  })

  const totalPages = data ? Math.ceil(data.total / PER_PAGE) : 0

  function handleSearch(v: string) { setSearch(v); setPage(1) }
  function handleTactic(v: string) { setTactic(v); setPage(1) }

  const noData = !isLoading && data?.total === 0

  return (
    <Box sx={{ p: 3 }}>
      <PageHeader
        title="MITRE ATLAS"
        subtitle="Adversarial Threat Landscape for AI Systems — tactics & techniques targeting ML"
        helpSection="mitre-atlas"
      />

      {/* ── Stats ── */}
      {stats && (
        <Box sx={{ display: 'flex', gap: 3, mb: 2.5, flexWrap: 'wrap' }}>
          <Box>
            <Typography variant="h6" sx={{ fontWeight: 700, color: INTEL_COLOR, lineHeight: 1 }}>
              {stats.total_techniques.toLocaleString()}
            </Typography>
            <Typography variant="caption" color="text.secondary">Techniques</Typography>
          </Box>
          <Box>
            <Typography variant="h6" sx={{ fontWeight: 700, color: INTEL_COLOR, lineHeight: 1 }}>
              {Object.keys(stats.tactic_counts).length}
            </Typography>
            <Typography variant="caption" color="text.secondary">Tactics</Typography>
          </Box>
        </Box>
      )}

      {/* ── Context banner ── */}
      <Alert severity="info" variant="outlined" sx={{ mb: 2, fontSize: '0.8rem' }}>
        MITRE ATLAS covers adversarial ML attacks — model evasion, poisoning, inversion, and theft.
        Relevant for AI Act compliance (A.8.28), DORA AI risk, and ISO 42001 controls.
      </Alert>

      {/* ── Filters ── */}
      <Box sx={{ display: 'flex', gap: 1.5, mb: 2, flexWrap: 'wrap', alignItems: 'center' }}>
        <TextField
          size="small"
          placeholder="Search by ID or name…"
          value={search}
          onChange={e => handleSearch(e.target.value)}
          sx={{ width: 240 }}
          InputProps={{
            startAdornment: <InputAdornment position="start"><SearchOutlined sx={{ fontSize: 16 }} /></InputAdornment>,
          }}
        />

        <FormControl size="small" sx={{ minWidth: 220 }}>
          <InputLabel sx={{ fontSize: '0.8rem' }}>Tactic</InputLabel>
          <Select
            label="Tactic"
            value={tactic}
            onChange={e => handleTactic(e.target.value)}
            sx={{ fontSize: '0.8rem' }}
          >
            <MenuItem value="">All tactics</MenuItem>
            {tactics.map(t => (
              <MenuItem key={t} value={t} sx={{ fontSize: '0.8rem' }}>{t}</MenuItem>
            ))}
          </Select>
        </FormControl>
      </Box>

      {/* ── Table + detail panel ── */}
      <Box sx={{ display: 'flex', gap: 2 }}>
        <Paper variant="outlined" sx={{ flex: 1, borderRadius: 2, overflow: 'hidden', minWidth: 0 }}>
          {isLoading && (
            <Box sx={{ display: 'flex', justifyContent: 'center', py: 6 }}>
              <CircularProgress size={28} />
            </Box>
          )}
          {error && <Alert severity="error" sx={{ m: 2 }}>Failed to load ATLAS techniques</Alert>}
          {noData && (
            <Alert severity="info" sx={{ m: 2 }}>
              No ATLAS data yet — the feeds container will populate data on its first run (Sunday 02:30 UTC).
            </Alert>
          )}

          {!isLoading && data && data.items.length > 0 && (
            <>
              <Table size="small" stickyHeader>
                <TableHead>
                  <TableRow>
                    <TableCell sx={{ fontWeight: 600, fontSize: '0.72rem', width: 110 }}>ID</TableCell>
                    <TableCell sx={{ fontWeight: 600, fontSize: '0.72rem' }}>Name</TableCell>
                    <TableCell sx={{ fontWeight: 600, fontSize: '0.72rem' }}>Tactics</TableCell>
                    <TableCell sx={{ fontWeight: 600, fontSize: '0.72rem', width: 90 }}>Type</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {data.items.map(t => (
                    <TableRow
                      key={t.id}
                      hover
                      selected={selected?.id === t.id}
                      onClick={() => setSelected(selected?.id === t.id ? null : t)}
                      sx={{ cursor: 'pointer' }}
                    >
                      <TableCell sx={{ fontFamily: 'monospace', fontSize: '0.75rem', color: INTEL_COLOR, fontWeight: 600 }}>
                        {t.technique_id}
                      </TableCell>
                      <TableCell sx={{ fontSize: '0.78rem', maxWidth: 280 }}>
                        <Box sx={{ pl: t.is_subtechnique ? 2 : 0 }}>
                          <Typography noWrap variant="inherit">{t.name}</Typography>
                        </Box>
                      </TableCell>
                      <TableCell sx={{ maxWidth: 200 }}>
                        <Box>{t.tactics.map(tac => <TacticChip key={tac} tactic={tac} />)}</Box>
                      </TableCell>
                      <TableCell>
                        {t.is_subtechnique
                          ? <Chip label="Sub" size="small" sx={{ fontSize: '0.65rem', height: 18 }} />
                          : <Chip label="Tech" size="small" variant="outlined" sx={{ fontSize: '0.65rem', height: 18 }} />}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>

              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', px: 2, py: 1, borderTop: '1px solid', borderColor: 'divider' }}>
                <Typography variant="caption" color="text.secondary">
                  {data.total.toLocaleString()} techniques
                </Typography>
                <Box sx={{ display: 'flex', gap: 1, alignItems: 'center' }}>
                  <Typography
                    variant="caption"
                    sx={{ cursor: page > 1 ? 'pointer' : 'default', color: page > 1 ? 'primary.main' : 'text.disabled' }}
                    onClick={() => page > 1 && setPage(p => p - 1)}
                  >
                    ← Prev
                  </Typography>
                  <Typography variant="caption" color="text.secondary">{page} / {totalPages}</Typography>
                  <Typography
                    variant="caption"
                    sx={{ cursor: page < totalPages ? 'pointer' : 'default', color: page < totalPages ? 'primary.main' : 'text.disabled' }}
                    onClick={() => page < totalPages && setPage(p => p + 1)}
                  >
                    Next →
                  </Typography>
                </Box>
              </Box>
            </>
          )}
        </Paper>

        {/* ── Detail panel ── */}
        {selected && (
          <Paper variant="outlined" sx={{ width: 320, flexShrink: 0, borderRadius: 2, p: 2, height: 'fit-content', position: 'sticky', top: 24 }}>
            <Typography variant="subtitle2" sx={{ fontFamily: 'monospace', color: INTEL_COLOR, fontWeight: 700, mb: 0.5 }}>
              {selected.technique_id}
            </Typography>
            <Typography variant="body2" fontWeight={600} sx={{ mb: 1 }}>{selected.name}</Typography>
            <Box sx={{ mb: 1 }}>
              {selected.tactics.map(t => <TacticChip key={t} tactic={t} />)}
            </Box>
            {selected.is_subtechnique && (
              <Chip label="Sub-technique" size="small" sx={{ fontSize: '0.65rem', height: 18, mb: 1 }} />
            )}
            {selected.description && (
              <Typography variant="caption" color="text.secondary" display="block" sx={{ mt: 1, lineHeight: 1.5, maxHeight: 300, overflowY: 'auto' }}>
                {selected.description.slice(0, 600)}{selected.description.length > 600 ? '…' : ''}
              </Typography>
            )}
          </Paper>
        )}
      </Box>
    </Box>
  )
}

// isms-core-platform/frontend/src/app/pages/mitre-atlas/mitre-atlas.component.ts
import { Component, inject, signal, computed } from '@angular/core'
import { DecimalPipe } from '@angular/common'
import { FormsModule } from '@angular/forms'
import { firstValueFrom } from 'rxjs'
import { injectQuery } from '@tanstack/angular-query-experimental'

import { MatFormFieldModule } from '@angular/material/form-field'
import { MatInputModule } from '@angular/material/input'
import { MatSelectModule } from '@angular/material/select'
import { MatIconModule } from '@angular/material/icon'
import { MatTooltipModule } from '@angular/material/tooltip'
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner'

import { FeedsApiService, MitreTechnique } from '../../api/feeds-api.service'
import { ThemeService } from '../../core/services/theme.service'
import { PageHeaderComponent } from '../../shared/components/page-header.component'

const INTEL_DARK  = '#e06030'
const INTEL_LIGHT = '#c64227'
const PER_PAGE = 50

@Component({
  selector: 'app-mitre-atlas',
  standalone: true,
  imports: [
    DecimalPipe, FormsModule, PageHeaderComponent,
    MatFormFieldModule, MatInputModule, MatSelectModule,
    MatIconModule, MatTooltipModule, MatProgressSpinnerModule,
  ],
  template: `
<div class="atlas-page">
  <app-page-header
    title="ATLAS"
    subtitle="MITRE ATLAS — adversarial ML attacks targeting AI/ML systems"
  />

  @if (statsQuery.data(); as s) {
    <div class="mitre-stats">
      <div><div class="mitre-stat__val" [style.color]="INTEL_COLOR">{{ s.total_techniques | number }}</div><div class="mitre-stat__lbl">Techniques</div></div>
      <div><div class="mitre-stat__val" [style.color]="INTEL_COLOR">{{ tacticCount() }}</div><div class="mitre-stat__lbl">Tactics</div></div>
    </div>
  }

  <div class="context-banner">
    <mat-icon>info</mat-icon>
    Covers model evasion, data poisoning, inversion and theft attacks.
    Relevant for AI Act (A.8.28), DORA AI risk, and ISO 42001.
  </div>

  <div class="mitre-filters">
    <mat-form-field appearance="outline" subscriptSizing="dynamic" class="mitre-search">
      <mat-label>Search techniques…</mat-label>
      <mat-icon matPrefix>search</mat-icon>
      <input matInput [(ngModel)]="search" (ngModelChange)="onSearch($event)" />
    </mat-form-field>
    <mat-form-field appearance="outline" subscriptSizing="dynamic" class="mitre-select">
      <mat-label>Tactic</mat-label>
      <mat-select [(ngModel)]="tactic" (ngModelChange)="onTactic($event)">
        <mat-option value="">All tactics</mat-option>
        @for (t of tactics(); track t) {
          <mat-option [value]="t">{{ t }}</mat-option>
        }
      </mat-select>
    </mat-form-field>
  </div>

  <div class="mitre-layout">
    <div class="mitre-table-box">
      @if (techQuery.isLoading()) {
        <div class="mitre-empty"><mat-spinner diameter="28" /></div>
      }
      @if (techQuery.isError()) {
        <div class="mitre-error">Failed to load ATLAS techniques.</div>
      }
      @if (!techQuery.isLoading() && techQuery.data()?.total === 0) {
        <div class="mitre-empty">No ATLAS data yet — check back after the scheduled weekly pull.</div>
      }
      @if (techQuery.data(); as d) {
        @if (d.items.length > 0) {
          <table class="mitre-table">
            <thead><tr>
              <th class="col-id">ID</th>
              <th>Name</th>
              <th class="col-tactics">Tactics</th>
              <th class="col-type">Type</th>
            </tr></thead>
            <tbody>
              @for (t of d.items; track t.id) {
                <tr class="mitre-row" [class.mitre-row--selected]="selected()?.id === t.id" (click)="toggleSelected(t)">
                  <td class="mono" [style.color]="INTEL_COLOR">{{ t.technique_id }}</td>
                  <td>
                    <div [style.padding-left]="t.is_subtechnique ? '14px' : '0'">
                      <span class="tech-name">{{ t.name }}</span>
                    </div>
                  </td>
                  <td class="col-tactics">
                    <div class="chip-row">
                      @for (tac of t.tactics.slice(0, 2); track tac) {
                        <span class="mitre-chip">{{ tac }}</span>
                      }
                    </div>
                  </td>
                  <td>
                    @if (t.is_subtechnique) {
                      <span class="mitre-chip">Sub</span>
                    } @else {
                      <span class="mitre-chip mitre-chip--outline">Tech</span>
                    }
                  </td>
                </tr>
              }
            </tbody>
          </table>
          <div class="mitre-pagination">
            <span>{{ d.total | number }} techniques</span>
            <div class="mitre-pagination__nav">
              <span class="mitre-pagination__btn" [class.disabled]="page() === 1" (click)="prevPage()">← Prev</span>
              <span>{{ page() }} / {{ totalPages() }}</span>
              <span class="mitre-pagination__btn" [class.disabled]="page() === totalPages()" (click)="nextPage()">Next →</span>
            </div>
          </div>
        }
      }
    </div>

    @if (selected(); as sel) {
      <div class="mitre-detail">
        <div class="mitre-detail__id" [style.color]="INTEL_COLOR">{{ sel.technique_id }}</div>
        <div class="mitre-detail__name">{{ sel.name }}</div>
        @if (sel.is_subtechnique) {
          <span class="mitre-chip" style="margin-bottom:8px">Sub-technique</span>
        }
        <div class="mitre-detail__label">Tactics</div>
        <div class="chip-row chip-row--gap">
          @for (t of sel.tactics; track t) {
            <span class="mitre-chip">{{ t }}</span>
          }
        </div>
        @if (sel.description) {
          <div class="mitre-detail__desc">{{ sel.description.slice(0, 700) }}{{ sel.description.length > 700 ? '…' : '' }}</div>
        }
        @if (sel.url) {
          <a [href]="sel.url" target="_blank" rel="noopener noreferrer" class="mitre-detail__link" [style.color]="INTEL_COLOR">View on atlas.mitre.org →</a>
        }
      </div>
    }
  </div>
</div>
  `,
  styles: [`
    .atlas-page { display: flex; flex-direction: column; gap: 16px; }
    .context-banner {
      display: flex; align-items: flex-start; gap: 8px;
      padding: 10px 14px; border-radius: 6px; font-size: 0.8rem;
      border: 1px solid var(--mat-sys-outline-variant);
      background: var(--mat-sys-surface-container);
      color: var(--mat-sys-on-surface);
    }
    .context-banner mat-icon { font-size: 18px; flex-shrink: 0; margin-top: 1px; color: var(--mat-sys-primary); }
    .col-id      { width: 110px; }
    .col-tactics { width: 200px; }
    .col-type    { width: 70px; }
    .tech-name   { font-size: 0.78rem; font-weight: 500; }
    .chip-row { display: flex; flex-wrap: wrap; gap: 2px; }
    .chip-row--gap { gap: 4px; margin-bottom: 2px; }
    .mono { font-family: monospace; font-weight: 600; }
  `],
})
export class MitreAtlasComponent {
  private feedsApi = inject(FeedsApiService)
  private readonly theme = inject(ThemeService)

  get INTEL_COLOR() { return this.theme.isDark() ? INTEL_DARK : INTEL_LIGHT }

  search = ''
  tactic = ''
  private _page = signal(1)
  readonly page = computed(() => this._page())
  selected = signal<MitreTechnique | null>(null)

  readonly statsQuery = injectQuery(() => ({
    queryKey: ['feeds', 'atlas', 'stats'],
    queryFn:  () => firstValueFrom(this.feedsApi.getAtlasStats()),
  }))

  readonly tactics = computed(() => Object.keys(this.statsQuery.data()?.tactic_counts ?? {}).sort())
  readonly tacticCount = computed(() => Object.keys(this.statsQuery.data()?.tactic_counts ?? {}).length)

  readonly techQuery = injectQuery(() => ({
    queryKey: ['feeds', 'atlas', this.tactic, this.search, this._page()],
    queryFn:  () => firstValueFrom(this.feedsApi.getAtlasTechniques({
      tactic: this.tactic || undefined,
      search: this.search || undefined,
      page: this._page(), per_page: PER_PAGE,
    })),
  }))

  readonly totalPages = computed(() => Math.max(1, Math.ceil((this.techQuery.data()?.total ?? 0) / PER_PAGE)))

  onSearch(v: string) { this.search = v; this._page.set(1) }
  onTactic(v: string) { this.tactic = v; this._page.set(1) }
  prevPage() { if (this._page() > 1) this._page.update(p => p - 1) }
  nextPage() { if (this._page() < this.totalPages()) this._page.update(p => p + 1) }
  toggleSelected(t: MitreTechnique) { this.selected.update(s => s?.id === t.id ? null : t) }
}
