// isms-core-platform/frontend-angular/src/app/pages/controls/controls.component.ts
import { Component, inject, signal, computed } from '@angular/core'
import { Router } from '@angular/router'
import { FormsModule } from '@angular/forms'
import { firstValueFrom } from 'rxjs'
import { injectQuery } from '@tanstack/angular-query-experimental'

import { MatCardModule } from '@angular/material/card'
import { MatFormFieldModule } from '@angular/material/form-field'
import { MatInputModule } from '@angular/material/input'
import { MatSelectModule } from '@angular/material/select'
import { MatButtonToggleModule } from '@angular/material/button-toggle'
import { MatIconModule } from '@angular/material/icon'
import { MatChipsModule } from '@angular/material/chips'
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner'
import { MatTooltipModule } from '@angular/material/tooltip'
import { MatButtonModule } from '@angular/material/button'

import { ControlsApiService } from '../../api/controls-api.service'
import { ProductService } from '../../core/services/product.service'
import { ThemeService } from '../../core/services/theme.service'
import { ControlGroupList } from '../../shared/types'
import { PageHeaderComponent } from '../../shared/components/page-header.component'

const ISMS_SECTION_COLORS: Record<string, string> = {
  'A.5': '#4472C4',
  'A.6': '#70AD47',
  'A.7': '#FFC000',
  'A.8': '#C00000',
}

const PRIVACY_SECTION_COLORS: Record<string, string> = {
  'A.1': '#9B72CF',
  'A.2': '#4472C4',
  'A.3': '#2E86AB',
}

const HEATMAP_DARK: Record<string, string> = {
  complete:   '#C6EFCE',
  partial:    '#FFEB9C',
  basic:      '#FFD580',
  incomplete: '#FFC7CE',
}

const HEATMAP_LIGHT: Record<string, string> = {
  complete:   '#4caf50',
  partial:    '#ff9800',
  basic:      '#f57c00',
  incomplete: '#f44336',
}

type ViewMode = 'grid' | 'heatmap'

function getSectionKey(cg: ControlGroupList): string {
  return cg.section
}

function deriveSectionName(cg: ControlGroupList): string {
  const names: Record<string, string> = {
    'A.5': 'Organisational Controls',
    'A.6': 'People Controls',
    'A.7': 'Physical Controls',
    'A.8': 'Technological Controls',
    'A.1': 'Privacy Controller',
    'A.2': 'Privacy Processor',
    'A.3': 'Privacy Shared',
  }
  return (cg as unknown as Record<string, string>)['section_name'] ?? names[cg.section] ?? cg.section
}

function getSectionColor(product: string, section: string): string {
  if (product === 'isms') return ISMS_SECTION_COLORS[section] ?? '#4472C4'
  if (product === 'privacy') return PRIVACY_SECTION_COLORS[section] ?? '#7030A0'
  if (product === 'cloud') return '#FFC000'
  return '#ff6b35'
}

function getHeatmapStatus(cg: ControlGroupList): string {
  const cgExt = cg as unknown as Record<string, unknown>
  const fw = cgExt['framework_status'] as string | undefined
  const op = cgExt['operational_status'] as string | undefined
  if (fw === 'complete' && op === 'complete') return 'complete'
  if (fw === 'complete' || op === 'complete') return 'partial'
  if (fw || op) return 'basic'
  return 'incomplete'
}

@Component({
  selector: 'app-controls',
  standalone: true,
  imports: [
    FormsModule,
    MatCardModule, MatFormFieldModule, MatInputModule, MatSelectModule,
    MatButtonToggleModule, MatIconModule, MatChipsModule,
    MatProgressSpinnerModule, MatTooltipModule, MatButtonModule,
    PageHeaderComponent,
  ],
  template: `
<div class="controls-page">

  <app-page-header
    title="Controls Library"
    [subtitle]="controlsSubtitle()"
  />

  <!-- Toolbar -->
  <div class="controls-toolbar">
    <mat-form-field appearance="outline" subscriptSizing="dynamic" class="search-field">
      <mat-label>Search</mat-label>
      <mat-icon matPrefix>search</mat-icon>
      <input matInput placeholder="Search controls…" [ngModel]="searchTerm()" (ngModelChange)="searchTerm.set($event)" />
    </mat-form-field>

    @if (showSectionFilter()) {
      <mat-form-field appearance="outline" subscriptSizing="dynamic" class="section-field">
        <mat-label>Section</mat-label>
        <mat-select [ngModel]="selectedSection()" (ngModelChange)="selectedSection.set($event)">
          <mat-option value="">All Sections</mat-option>
          @for (s of availableSections(); track s.key) {
            <mat-option [value]="s.key">{{ s.label }}</mat-option>
          }
        </mat-select>
      </mat-form-field>
    }

    @if (product.product() === 'isms') {
      <mat-button-toggle-group [ngModel]="selectedTier()" (ngModelChange)="selectedTier.set($event)" class="tier-toggle">
        <mat-button-toggle value="all">All</mat-button-toggle>
        <mat-button-toggle value="framework">Framework</mat-button-toggle>
        <mat-button-toggle value="operational">Operational</mat-button-toggle>
      </mat-button-toggle-group>
    }

    <mat-button-toggle-group [ngModel]="viewMode()" (ngModelChange)="viewMode.set($event)" class="view-toggle">
      <mat-button-toggle value="grid">
        <mat-icon>grid_view</mat-icon>
      </mat-button-toggle>
      @if (product.product() === 'isms') {
        <mat-button-toggle value="heatmap">
          <mat-icon>grid_on</mat-icon>
        </mat-button-toggle>
      }
    </mat-button-toggle-group>
  </div>

  <!-- Loading -->
  @if (controlsQuery.isLoading()) {
    <div class="controls-loading">
      <mat-spinner diameter="40" />
    </div>
  }

  <!-- Error -->
  @if (controlsQuery.isError()) {
    <div class="controls-error">Failed to load controls.</div>
  }

  <!-- Grid view -->
  @if (controlsQuery.isSuccess() && viewMode() === 'grid') {
    @for (section of groupedSections(); track section.key) {
      <div class="section-group">
        <div class="section-group__header"
             [style.border-left-color]="getSectionColorForProduct(section.key)">
          <span class="section-group__title">{{ section.key }} — {{ section.label }}</span>
          <span class="section-group__count">{{ section.items.length }}</span>
        </div>
        <div class="section-group__grid">
          @for (cg of section.items; track cg.id) {
            <mat-card class="control-card"
                      [style.border-left-color]="getSectionColorForProduct(cg.section)"
                      (click)="openControl(cg)">
              <mat-card-content>
                <div class="control-card__code"
                     [style.color]="getSectionColorForProduct(cg.section)">
                  {{ cg.group_code.toUpperCase() }}
                </div>
                <div class="control-card__name">{{ cg.group_name }}</div>
                <div class="control-card__section">{{ deriveSectionName(cg) }}</div>
                @if (product.product() === 'isms') {
                  <div class="control-card__pills">
                    <span class="pill" [class.pill--fw]="hasFw(cg)">FW</span>
                    <span class="pill" [class.pill--op]="hasOp(cg)">OP</span>
                  </div>
                }
              </mat-card-content>
            </mat-card>
          }
        </div>
      </div>
    }
  }

  <!-- Heatmap view (ISMS only) -->
  @if (controlsQuery.isSuccess() && viewMode() === 'heatmap' && product.product() === 'isms') {
    <div class="heatmap">
      <div class="heatmap__legend">
        @for (entry of heatmapLegend(); track entry.label) {
          <div class="heatmap__legend-item">
            <span class="heatmap__legend-swatch" [style.background]="entry.color"></span>
            <span>{{ entry.label }}</span>
          </div>
        }
      </div>
      <div class="heatmap__grid">
        @for (cg of filteredControls(); track cg.id) {
          <div class="heatmap__cell"
               [style.background]="heatmapColor(cg)"
               [matTooltip]="cg.group_code.toUpperCase() + ' — ' + cg.group_name"
               (click)="openControl(cg)">
          </div>
        }
      </div>
    </div>
  }

  <!-- Empty state -->
  @if (controlsQuery.isSuccess() && filteredControls().length === 0) {
    <div class="controls-empty">
      <mat-icon>search_off</mat-icon>
      <span>No controls match your filters.</span>
    </div>
  }

</div>
  `,
  styles: [`
    .controls-page {
      display: flex;
      flex-direction: column;
      gap: 16px;
    }

    /* Toolbar */
    .controls-toolbar {
      display: flex;
      align-items: center;
      gap: 12px;
      flex-wrap: wrap;
      padding-top: 12px;
    }
    .search-field { flex: 1; min-width: 200px; }
    .section-field { width: 200px; }
    .tier-toggle, .view-toggle { flex-shrink: 0; }

    /* Loading / error / empty */
    .controls-loading {
      display: flex;
      justify-content: center;
      padding: 48px;
    }
    .controls-error {
      color: var(--mat-sys-error);
      padding: 16px;
      text-align: center;
    }
    .controls-empty {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 8px;
      color: var(--mat-sys-on-surface-variant);
      padding: 48px;
    }

    /* Section group */
    .section-group { display: flex; flex-direction: column; gap: 8px; }
    .section-group__header {
      display: flex;
      align-items: center;
      gap: 12px;
      padding: 6px 12px;
      background: var(--mat-sys-surface-container);
      border-radius: 4px;
      border-left: 4px solid transparent;
    }
    .section-group__title {
      font-size: 0.85rem;
      font-weight: 600;
      color: var(--mat-sys-on-surface);
      flex: 1;
    }
    .section-group__count {
      font-size: 0.75rem;
      color: var(--mat-sys-on-surface-variant);
    }

    /* Card grid */
    .section-group__grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
      gap: 8px;
    }

    /* Control card */
    .control-card {
      cursor: pointer;
      border-left: 3px solid transparent;
      transition: box-shadow 0.15s;
    }
    .control-card:hover { box-shadow: 0 2px 8px rgba(0,0,0,0.25); }
    mat-card-content { padding: 12px !important; }

    .control-card__code {
      font-family: monospace;
      font-size: 0.75rem;
      font-weight: 700;
      letter-spacing: 0.04em;
      margin-bottom: 4px;
    }
    .control-card__name {
      font-size: 0.8rem;
      font-weight: 600;
      color: var(--mat-sys-on-surface);
      margin-bottom: 2px;
      line-height: 1.3;
    }
    .control-card__section {
      font-size: 0.7rem;
      color: var(--mat-sys-on-surface-variant);
      margin-bottom: 8px;
    }

    /* Pills */
    .control-card__pills {
      display: flex;
      gap: 4px;
    }
    .pill {
      font-size: 0.6rem;
      font-weight: 700;
      padding: 1px 6px;
      border-radius: 10px;
      background: var(--mat-sys-surface-container-high);
      color: var(--mat-sys-on-surface-variant);
      border: 1px solid var(--mat-sys-outline-variant);
    }
    .pill--fw {
      background: rgba(50,125,244,0.15);
      color: #327df4;
      border-color: rgba(50,125,244,0.4);
    }
    .pill--op {
      background: rgba(0,199,82,0.15);
      color: #00c752;
      border-color: rgba(0,199,82,0.4);
    }

    /* Heatmap */
    .heatmap { display: flex; flex-direction: column; gap: 12px; }
    .heatmap__legend {
      display: flex;
      gap: 16px;
      flex-wrap: wrap;
    }
    .heatmap__legend-item {
      display: flex;
      align-items: center;
      gap: 6px;
      font-size: 0.75rem;
      color: var(--mat-sys-on-surface-variant);
    }
    .heatmap__legend-swatch {
      width: 16px;
      height: 16px;
      border-radius: 2px;
      flex-shrink: 0;
    }
    .heatmap__grid {
      display: flex;
      flex-wrap: wrap;
      gap: 4px;
    }
    .heatmap__cell {
      width: 60px;
      height: 60px;
      border-radius: 4px;
      cursor: pointer;
      transition: transform 0.1s;
    }
    .heatmap__cell:hover { transform: scale(1.08); }
  `],
})
export class ControlsComponent {
  readonly router  = inject(Router)
  readonly product = inject(ProductService)
  readonly theme   = inject(ThemeService)
  private  ctrlApi = inject(ControlsApiService)

  searchTerm      = signal('')
  selectedSection = signal('')
  selectedTier    = signal('all')
  viewMode        = signal<ViewMode>('grid')

  readonly deriveSectionName = deriveSectionName

  private get productFamily(): string {
    const p = this.product.product()
    if (p === 'privacy') return 'PRIVACY'
    if (p === 'cloud')   return 'CLOUD'
    if (p === 'ai')      return 'AI'
    return 'ISMS'
  }

  readonly controlsQuery = injectQuery(() => ({
    queryKey: ['controls', this.product.product()],
    queryFn: () => firstValueFrom(this.ctrlApi.list({ product_family: this.productFamily })),
    staleTime: 60_000,
  }))

  readonly filteredControls = computed((): ControlGroupList[] => {
    const items = this.controlsQuery.data() ?? []
    const search = this.searchTerm().toLowerCase()
    const section = this.selectedSection()
    const tier = this.selectedTier()
    const prod = this.product.product()

    return items.filter(cg => {
      if (search && !cg.group_code.toLowerCase().includes(search) && !cg.group_name.toLowerCase().includes(search)) {
        return false
      }
      if (section && cg.section !== section) return false
      if (prod === 'isms' && tier !== 'all') {
        if (tier === 'framework'   && !cg.has_framework)   return false
        if (tier === 'operational' && !cg.has_operational) return false
      }
      return true
    })
  })

  readonly groupedSections = computed(() => {
    const map = new Map<string, { key: string; label: string; items: ControlGroupList[] }>()
    for (const cg of this.filteredControls()) {
      const key = cg.section
      if (!map.has(key)) {
        map.set(key, { key, label: deriveSectionName(cg), items: [] })
      }
      map.get(key)!.items.push(cg)
    }
    return Array.from(map.values()).sort((a, b) => a.key.localeCompare(b.key))
  })

  readonly availableSections = computed(() => {
    const all = this.controlsQuery.data() ?? []
    const seen = new Map<string, string>()
    for (const cg of all) {
      if (!seen.has(cg.section)) seen.set(cg.section, deriveSectionName(cg))
    }
    return Array.from(seen.entries())
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([key, label]) => ({ key, label }))
  })

  readonly showSectionFilter = computed(() => this.product.product() !== 'ai')

  readonly controlsSubtitle = computed(() => {
    const subtitles: Record<string, string> = {
      isms:    'ISO 27001:2022 Annex A control groups and implementation status',
      privacy: 'ISO 27701:2025 privacy control groups and implementation status',
      cloud:   'ISO 27018:2025 cloud control groups and implementation status',
      ai:      'ISO 42001:2023 AI control groups and implementation status',
    }
    return subtitles[this.product.product()] ?? subtitles['isms']
  })

  readonly heatmapLegend = computed(() => {
    const colors = this.theme.isDark() ? HEATMAP_DARK : HEATMAP_LIGHT
    return [
      { label: 'Complete',   color: colors['complete'] },
      { label: 'Partial',    color: colors['partial'] },
      { label: 'Basic',      color: colors['basic'] },
      { label: 'Incomplete', color: colors['incomplete'] },
    ]
  })

  getSectionColorForProduct(section: string): string {
    return getSectionColor(this.product.product(), section)
  }

  heatmapColor(cg: ControlGroupList): string {
    const status = getHeatmapStatus(cg)
    const colors = this.theme.isDark() ? HEATMAP_DARK : HEATMAP_LIGHT
    return colors[status] ?? colors['incomplete']
  }

  hasFw(cg: ControlGroupList): boolean { return cg.has_framework }
  hasOp(cg: ControlGroupList): boolean { return cg.has_operational }

  openControl(cg: ControlGroupList): void {
    this.router.navigate(['/controls', cg.id])
  }
}

// isms-core-platform/frontend/src/pages/Controls.tsx
import { useState, useEffect, useMemo } from 'react'
import { useLocation } from 'react-router-dom'
import {
  Box,
  Card,
  CardContent,
  Typography,
  Grid,
  TextField,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  Skeleton,
  Alert,
  InputAdornment,
  ToggleButtonGroup,
  ToggleButton,
} from '@mui/material'
import { SearchOutlined, AccountTreeOutlined, GridViewOutlined, ViewListOutlined } from '@mui/icons-material'
import { useQuery } from '@tanstack/react-query'
import { useNavigate } from 'react-router-dom'
import { controlsApi } from '../api/controls'
import PageHeader from '../components/PageHeader'
import { useProduct, PRODUCT_COLORS } from '../store/ProductContext'

const STATUS_HM_COLOR: Record<string, string> = {
  complete:   '#C6EFCE',
  partial:    '#FFEB9C',
  basic:      '#FFD580',
  incomplete: '#FFC7CE',
}

function HeatmapCell({ cg }: { cg: CgItem }) {
  const navigate = useNavigate()
  const sectionKey = cg.section?.match(/A\.\d/)?.[0] ?? ''
  const sectionColor = SECTION_COLOR[sectionKey] ?? '#4472C4'
  const statusColor = STATUS_HM_COLOR[cg.framework_status] ?? STATUS_HM_COLOR.incomplete
  return (
    <Box
      title={`${cg.group_code.toUpperCase()} — ${cg.name}\nStatus: ${cg.framework_status}`}
      onClick={() => navigate(`/controls/${cg.id}`)}
      sx={{
        width: 60, height: 60, borderRadius: 1.5, cursor: 'pointer',
        bgcolor: `${statusColor}18`,
        border: `1px solid ${statusColor}50`,
        borderTop: `3px solid ${sectionColor}`,
        display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
        gap: 0.25, transition: 'all 0.12s',
        '&:hover': { bgcolor: `${statusColor}30`, borderColor: statusColor, transform: 'scale(1.04)' },
      }}
    >
      <Typography sx={{ color: statusColor, fontWeight: 700, fontFamily: 'monospace', fontSize: '0.6rem', lineHeight: 1.2, textAlign: 'center' }}>
        {cg.group_code.replace(/^a\./i, '').toUpperCase()}
      </Typography>
      <Box sx={{ width: 6, height: 6, borderRadius: '50%', bgcolor: cg.has_framework ? '#4472C4' : 'transparent', border: '1px solid #4472C440' }} />
    </Box>
  )
}

const SECTION_COLOR: Record<string, string> = {
  'A.5': '#4472C4',
  'A.6': '#70AD47',
  'A.7': '#FFC000',
  'A.8': '#C00000',
}

// Privacy (ISO 27701) section colours
const PRIVACY_SECTION_COLOR: Record<string, string> = {
  'A.1': '#9B72CF',
  'A.2': '#4472C4',
  'A.3': '#2E86AB',
}

// Cloud/ISO 27018 section colours (one flat palette, A.1–A.12)
const CLOUD_SECTION_COLOR: Record<string, string> = {
  'A.1':  '#FFC000', 'A.2':  '#FFC000', 'A.3':  '#FFC000', 'A.4':  '#FFC000',
  'A.5':  '#FFC000', 'A.6':  '#FFC000', 'A.7':  '#FFC000', 'A.8':  '#FFC000',
  'A.9':  '#FFC000', 'A.10': '#FFC000', 'A.11': '#FFC000', 'A.12': '#FFC000',
}



interface CgItem {
  id: string
  group_code: string
  name: string
  section: string
  section_name: string
  is_stacked: boolean
  has_framework: boolean
  has_operational: boolean
  framework_status: string
  operational_status: string
}

function ProductPill({ active, label, color }: { active: boolean; label: string; color: string }) {
  return (
    <Box
      sx={{
        px: 0.75,
        py: 0.1,
        borderRadius: 0.75,
        fontSize: '0.6rem',
        fontWeight: 700,
        letterSpacing: '0.04em',
        bgcolor: active ? `${color}25` : 'rgba(255,255,255,0.04)',
        color: active ? color : '#4a5070',
        border: `1px solid ${active ? `${color}50` : 'transparent'}`,
        lineHeight: 1.6,
      }}
    >
      {label}
    </Box>
  )
}

function ControlCard({ cg, colorOverride }: { cg: CgItem; colorOverride?: string }) {
  const navigate = useNavigate()
  const sectionKey = cg.section?.match(/A\.\d/)?.[0] ?? ''
  const color = colorOverride ?? SECTION_COLOR[sectionKey] ?? '#4472C4'

  return (
    <Card
      sx={{
        cursor: 'pointer',
        transition: 'border-color 0.15s',
        borderLeft: `3px solid ${color}`,
        '&:hover': { borderColor: `${color}cc`, bgcolor: 'rgba(68,114,196,0.04)' },
      }}
      onClick={() => navigate(`/controls/${cg.id}`)}
    >
      <CardContent sx={{ pb: '10px !important', pt: 1.25, px: 1.5 }}>
        <Box sx={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', mb: 0.4 }}>
          <Typography variant="caption" sx={{ color, fontWeight: 700, fontFamily: 'monospace', fontSize: '0.75rem' }}>
            {cg.group_code.toUpperCase()}
          </Typography>
          <Box sx={{ display: 'flex', gap: 0.5 }}>
            <ProductPill active={cg.has_framework} label="FW" color="#4472C4" />
            <ProductPill active={cg.has_operational} label="OP" color="#70AD47" />
          </Box>
        </Box>
        <Typography variant="body2" fontWeight={600} sx={{ lineHeight: 1.3, mb: 0.4 }}>
          {cg.name}
        </Typography>
        <Typography variant="caption" color="text.secondary">
          {cg.section_name}
        </Typography>
      </CardContent>
    </Card>
  )
}

type ViewMode = 'grid' | 'heatmap'

export default function Controls() {
  const location = useLocation()
  const { product, ismsTier } = useProduct()
  const [search, setSearch] = useState('')
  const [viewMode, setViewMode] = useState<ViewMode>('grid')
  const [section, setSection] = useState(() => {
    const params = new URLSearchParams(location.search)
    return params.get('section') ?? ''
  })
  useEffect(() => {
    const params = new URLSearchParams(location.search)
    setSection(params.get('section') ?? '')
  }, [location.search])

  useEffect(() => { setSection('') }, [product])

  const isIsms = product === 'isms'
  const isPrivacy = product === 'privacy'
  const isCloud = product === 'cloud'
  // product_family for the DB control groups query — always explicit to avoid cross-product pollution
  const productFamily = isPrivacy ? 'PRIVACY' : isCloud ? 'CLOUD' : 'ISMS'

  const { data: cgData, isLoading: cgLoading, error: cgError } = useQuery({
    queryKey: ['controls', productFamily],
    queryFn: () => controlsApi.list({ product_family: productFamily }),
    enabled: isIsms || isPrivacy || isCloud,
  })

  const allControls = cgData as unknown as CgItem[] | undefined

  const filtered = useMemo(() => {
    return (allControls ?? []).filter((cg) => {
      if (isIsms) {
        if (!cg.has_framework && !cg.has_operational) return false
        if (ismsTier === 'framework' && !cg.has_framework) return false
        if (ismsTier === 'operational' && !cg.has_operational) return false
      }
      if (section && !cg.section.startsWith(section)) return false
      if (search) {
        const q = search.toLowerCase()
        return cg.group_code.toLowerCase().includes(q) || cg.name.toLowerCase().includes(q)
      }
      return true
    })
  }, [allControls, isIsms, ismsTier, section, search])

  const grouped = useMemo(() => {
    const g: Record<string, CgItem[]> = {}
    for (const cg of filtered) {
      const s = `${cg.section} — ${cg.section_name}`
      if (!g[s]) g[s] = []
      g[s].push(cg)
    }
    return g
  }, [filtered])

  const sectionColorFor = (sec: string): string => {
    if (isPrivacy) return PRIVACY_SECTION_COLOR[sec.match(/A\.\d+/)?.[0] ?? ''] ?? '#9B72CF'
    if (isCloud)   return CLOUD_SECTION_COLOR[sec.match(/A\.\d+/)?.[0] ?? '']  ?? '#FFC000'
    return SECTION_COLOR[sec.match(/A\.\d/)?.[0] ?? ''] ?? '#4472C4'
  }

  const productColor = PRODUCT_COLORS[product] ?? '#4472C4'
  const subtitle = isIsms
    ? `${filtered.length} control groups · ISO 27001:2022 Annex A`
    : isPrivacy
      ? `${filtered.length} control packs · ISO 27701:2025 Ed. 2`
      : `${filtered.length} control packs · ISO 27018:2025 Ed. 3`

  return (
    <Box>
      <PageHeader title="Control Groups" subtitle={subtitle} />


      {/* Filters */}
      <Card sx={{ mb: 3 }}>
        <CardContent sx={{ pb: '12px !important' }}>
          <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap', alignItems: 'center' }}>
            <TextField size="small" placeholder="Search controls..." value={search}
              onChange={(e) => setSearch(e.target.value)} sx={{ flex: 1, minWidth: 200 }}
              InputProps={{ startAdornment: <InputAdornment position="start"><SearchOutlined fontSize="small" sx={{ color: 'text.secondary' }} /></InputAdornment> }} />

            {/* Section filter — ISMS hardcoded, PRIVACY dynamic, CLOUD hidden (few controls) */}
            {isIsms && (
              <FormControl size="small" sx={{ minWidth: 160 }}>
                <InputLabel>Section</InputLabel>
                <Select value={section} onChange={(e) => setSection(e.target.value)} label="Section">
                  <MenuItem value="">All sections</MenuItem>
                  <MenuItem value="A.5">A.5 — Organisational</MenuItem>
                  <MenuItem value="A.6">A.6 — People</MenuItem>
                  <MenuItem value="A.7">A.7 — Physical</MenuItem>
                  <MenuItem value="A.8">A.8 — Technological</MenuItem>
                </Select>
              </FormControl>
            )}
            {isPrivacy && (
              <FormControl size="small" sx={{ minWidth: 180 }}>
                <InputLabel>Section</InputLabel>
                <Select value={section} onChange={(e) => setSection(e.target.value)} label="Section">
                  <MenuItem value="">All sections</MenuItem>
                  <MenuItem value="A.1">A.1 — Controller</MenuItem>
                  <MenuItem value="A.2">A.2 — Processor</MenuItem>
                  <MenuItem value="A.3">A.3 — Shared</MenuItem>
                </Select>
              </FormControl>
            )}
            {isCloud && (
              <FormControl size="small" sx={{ minWidth: 200 }}>
                <InputLabel>Section</InputLabel>
                <Select value={section} onChange={(e) => setSection(e.target.value)} label="Section">
                  <MenuItem value="">All sections (ISO 27018)</MenuItem>
                  <MenuItem value="A.1">A.1 — General</MenuItem>
                  <MenuItem value="A.2">A.2 — Consent and Choice</MenuItem>
                  <MenuItem value="A.3">A.3 — Purpose</MenuItem>
                  <MenuItem value="A.4">A.4 — Collection</MenuItem>
                  <MenuItem value="A.5">A.5 — Minimisation</MenuItem>
                  <MenuItem value="A.6">A.6 — Use / Retention</MenuItem>
                  <MenuItem value="A.7">A.7 — Accuracy</MenuItem>
                  <MenuItem value="A.8">A.8 — Transparency</MenuItem>
                  <MenuItem value="A.9">A.9 — Individual Rights</MenuItem>
                  <MenuItem value="A.10">A.10 — Accountability</MenuItem>
                  <MenuItem value="A.11">A.11 — Information Security</MenuItem>
                  <MenuItem value="A.12">A.12 — Compliance</MenuItem>
                </Select>
              </FormControl>
            )}

            {isIsms && (
              <ToggleButtonGroup value={viewMode} exclusive onChange={(_, v) => v && setViewMode(v)}
                size="small" sx={{ ml: 'auto', '& .MuiToggleButton-root': { px: 1.25, py: 0.4 } }}>
                <ToggleButton value="grid" title="Card view"><ViewListOutlined fontSize="small" /></ToggleButton>
                <ToggleButton value="heatmap" title="Heatmap view"><GridViewOutlined fontSize="small" /></ToggleButton>
              </ToggleButtonGroup>
            )}
          </Box>
        </CardContent>
      </Card>

      {isIsms && viewMode === 'heatmap' && (
        <Box sx={{ display: 'flex', gap: 2, mb: 2, flexWrap: 'wrap', alignItems: 'center' }}>
          <Typography variant="caption" color="text.secondary">Status:</Typography>
          {Object.entries(STATUS_HM_COLOR).map(([status, color]) => (
            <Box key={status} sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
              <Box sx={{ width: 10, height: 10, borderRadius: 0.5, bgcolor: `${color}40`, border: `1px solid ${color}` }} />
              <Typography variant="caption" color="text.secondary">{status}</Typography>
            </Box>
          ))}
        </Box>
      )}

      {cgError && <Alert severity="error">Failed to load controls.</Alert>}

      {cgLoading && (
        <Grid container spacing={1.5}>
          {[...Array(12)].map((_, i) => (
            <Grid item xs={12} sm={6} md={4} lg={3} key={i}>
              <Skeleton variant="rectangular" height={85} sx={{ borderRadius: 2 }} />
            </Grid>
          ))}
        </Grid>
      )}

      {/* ── Unified render (ISMS + Privacy + Cloud all use control groups) ── */}
      {Object.entries(grouped).sort().map(([sec, items]) => {
        const color = sectionColorFor(sec)
        return (
          <Box key={sec} sx={{ mb: 3 }}>
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1.5 }}>
              <AccountTreeOutlined sx={{ color, fontSize: 18 }} />
              <Typography variant="h6" sx={{ color: isIsms ? undefined : color }}>{sec}</Typography>
              <Typography variant="caption" color="text.secondary">({items.length})</Typography>
            </Box>
            {isIsms && viewMode === 'heatmap' ? (
              <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.75 }}>
                {items.map((cg) => <HeatmapCell key={cg.id} cg={cg} />)}
              </Box>
            ) : (
              <Grid container spacing={1.5}>
                {items.map((cg) => (
                  <Grid item xs={12} sm={6} md={4} lg={3} key={cg.id}>
                    <ControlCard cg={cg} colorOverride={isIsms ? undefined : color} />
                  </Grid>
                ))}
              </Grid>
            )}
          </Box>
        )
      })}

      {filtered.length === 0 && !cgLoading && (
        <Alert severity="info">No controls match the current filters.</Alert>
      )}
    </Box>
  )
}
