// isms-core-platform/frontend/src/app/pages/coverage/coverage.component.ts
import { Component, inject, signal, computed, effect } from '@angular/core'
import { DecimalPipe } from '@angular/common'
import { FormsModule } from '@angular/forms'
import { Router } from '@angular/router'

import { injectQuery } from '@tanstack/angular-query-experimental'

import { MatCardModule } from '@angular/material/card'
import { MatButtonModule } from '@angular/material/button'
import { MatIconModule } from '@angular/material/icon'
import { MatChipsModule } from '@angular/material/chips'
import { MatFormFieldModule } from '@angular/material/form-field'
import { MatSelectModule } from '@angular/material/select'
import { MatProgressBarModule } from '@angular/material/progress-bar'
import { MatTooltipModule } from '@angular/material/tooltip'
import { MatSlideToggleModule } from '@angular/material/slide-toggle'
import { MatPaginatorModule, PageEvent } from '@angular/material/paginator'
import { MatTabsModule } from '@angular/material/tabs'

import { DashboardApiService } from '../../api/dashboard-api.service'
import { ProductService, PRODUCT_COLORS } from '../../core/services/product.service'
import { ThemeService } from '../../core/services/theme.service'
import { TokenStoreService } from '../../core/services/token-store.service'
import { PageHeaderComponent } from '../../shared/components/page-header.component'

// ── Types ─────────────────────────────────────────────────────────────────────

interface CoverageMapping {
  framework: string
  framework_code: string
  control_id: string
  control_title: string
  mapping_type: string
  confidence: number
}

interface CoverageRow {
  iso_control_id: string
  iso_control_title: string
  control_group_code: string
  mappings: CoverageMapping[]
}

interface RealCoverage {
  frameworks: string[]
  total_iso_controls: number
  total_mappings: number
  by_framework: Record<string, number>
  rows: CoverageRow[]
}

interface InferredResult {
  framework: string
  framework_code: string
  total_controls: number
  covered_controls: number
  uncovered_controls: number
  coverage_pct: number
}

// ── Constants ─────────────────────────────────────────────────────────────────

const PRODUCT_SOURCE_FRAMEWORK: Record<string, string> = {
  isms: 'ISO27001', privacy: 'ISO27701', cloud: 'ISO27018', ai: 'ISO42001',
}
const SOURCE_CONTROL_LABEL: Record<string, string> = {
  isms: 'ISO 27001 Control', privacy: 'ISO 27701 Control',
  cloud: 'ISO 27018 Control', ai: 'ISO 42001 Control',
}
const ISO_EXTENSIONS = new Set(['ISO27017', 'ISO27018', 'ISO27701'])
const ROWS_PER_PAGE = 25

function pctColor(pct: number, dark: boolean): string {
  if (pct === 100) return dark ? '#00c752' : '#0F6E56'
  if (pct >= 50)   return dark ? '#AED581' : '#558b2f'
  if (pct >= 1)    return dark ? '#FFB300' : '#E65100'
  return dark ? '#F44336' : '#c62828'
}

function confColor(c: number, dark: boolean): { bg: string; color: string } {
  if (dark) {
    if (c >= 0.8) return { bg: 'rgba(198,239,206,.15)', color: '#C6EFCE' }
    if (c >= 0.6) return { bg: 'rgba(255,193,7,.20)',   color: '#FFC107' }
    return { bg: 'rgba(255,199,206,.12)', color: '#FFC7CE' }
  }
  if (c >= 0.8) return { bg: 'rgba(29,158,117,.15)',  color: '#0F6E56' }
  if (c >= 0.6) return { bg: 'rgba(230,145,0,.15)',  color: '#9a6500' }
  return { bg: 'rgba(192,0,0,.12)', color: '#9e0000' }
}

// ── Component ─────────────────────────────────────────────────────────────────

@Component({
  selector: 'app-coverage',
  standalone: true,
  imports: [
    FormsModule, DecimalPipe,
    MatCardModule, MatButtonModule, MatIconModule, MatChipsModule,
    MatProgressBarModule, MatTooltipModule,
    MatFormFieldModule, MatSelectModule,
    MatSlideToggleModule, MatPaginatorModule, MatTabsModule,
    PageHeaderComponent,
  ],
  template: `
<div class="page-root">
  <app-page-header
    title="Framework Coverage"
    [subtitle]="activeTab() === 1
      ? 'Inferred compliance coverage across target frameworks based on project assessments'
      : covData() ? (covData()!.frameworks.length + ' frameworks · ' + covData()!.total_mappings.toLocaleString() + ' total mappings') : 'Loading…'">
    @if (activeTab() === 0 && covData()) {
      <mat-form-field appearance="outline" class="header-fw-select" subscriptSizing="dynamic">
        <mat-label>Framework</mat-label>
        <mat-select [ngModel]="activeFramework()" (ngModelChange)="activeFramework.set($event); page.set(0)">
          @for (f of sortedFrameworks(); track f) {
            <mat-option [value]="f">
              {{ f }}
              <span class="option-count">{{ covData()!.by_framework[f] }}</span>
            </mat-option>
          }
        </mat-select>
      </mat-form-field>
    }
  </app-page-header>

  <!-- Tabs -->
  <mat-tab-group [selectedIndex]="activeTab()" (selectedIndexChange)="activeTab.set($event)" class="tab-group" animationDuration="0" style="margin-top: 16px">

    <!-- ── Mapping Matrix ── -->
    <mat-tab label="Mapping Matrix">
      <div class="tab-body">

    <!-- Summary cards -->
    @if (covData()) {
      <div class="summary-grid">
        @for (c of summaryCards(); track c.label) {
          <mat-card>
            <mat-card-content class="summary-card-content">
              <div class="summary-card-label">{{ c.label }}</div>
              <div class="summary-card-value">{{ c.value }}</div>
            </mat-card-content>
          </mat-card>
        }
      </div>
    }

    <!-- Unmapped toggle -->
    @if (covData()) {
      <div class="toggle-row">
        <mat-slide-toggle [checked]="showUnmapped()" (change)="onUnmappedToggle($event.checked)" class="unmapped-toggle">
          Show unmapped only
        </mat-slide-toggle>
      </div>
    }

    <!-- Framework pills -->
    @if (covData()) {
      <mat-card class="fw-pills-card">
        <mat-card-content class="summary-card-content">
          <div class="fw-pills-heading">All Frameworks</div>
          <div class="fw-pills-row">
            @for (f of sortedFrameworks(); track f) {
              <div (click)="activeFramework.set(f); page.set(0)"
                class="fw-pill"
                [class.fw-pill-active]="f === activeFramework()"
                [class.fw-pill-iso-ext]="isIsoExt(f) && f !== activeFramework()"
                [style.background]="(covData()!.by_framework[f]) > 0 && f !== activeFramework() ? packColor() + '18' : null"
                [style.borderColor]="(covData()!.by_framework[f]) > 0 && f !== activeFramework() ? packColor() + '40' : null">
                {{ f }} <span class="fw-pill-count" [style.opacity]="(covData()!.by_framework[f]) > 0 ? '0.8' : '0.35'">· {{ covData()!.by_framework[f] }}</span>
              </div>
            }
          </div>
        </mat-card-content>
      </mat-card>
    }

    @if (coverageQuery.isError()) {
      <div class="error-banner">
        Failed to load coverage data.
      </div>
    }

    <!-- Table -->
    <mat-card>
      <div class="table-scroll">
        <table class="cov-table">
          <thead>
            <tr class="thead-row">
              <th class="th-cell th-col-control">{{ sourceLabel() }}</th>
              <th class="th-cell th-col-group">Control Group</th>
              <th class="th-cell">{{ activeFramework() || 'Framework' }} Mappings</th>
              <th class="th-cell th-col-hit th-center">Hit</th>
            </tr>
          </thead>
          <tbody>
            @if (coverageQuery.isLoading()) {
              @for (i of [1,2,3,4,5,6,7,8]; track i) {
                <tr>
                  @for (j of [1,2,3,4]; track j) {
                    <td class="td-cell td-loading">
                      <div class="skeleton-cell"></div>
                    </td>
                  }
                </tr>
              }
            }
            @for (row of pagedRows(); track row.iso_control_id) {
              @let fwMaps = frameworkMappings(row);
              <tr class="tbody-row">
                <td class="td-cell">
                  <div class="control-id" [style.color]="isoControlColor(row.iso_control_id)">{{ row.iso_control_id }}</div>
                  <div class="control-title">{{ row.iso_control_title }}</div>
                </td>
                <td class="td-cell">
                  <span class="group-code">{{ row.control_group_code }}</span>
                </td>
                <td class="td-cell">
                  <div class="mapping-chips">
                    @for (m of fwMaps.slice(0, 6); track m.control_id; let idx = $index) {
                      @let cc = getConfColor(m.confidence);
                      <span [title]="m.control_title + ' · ' + (m.confidence * 100 | number:'1.0-0') + '% · ' + m.mapping_type"
                        class="conf-chip"
                        [style.background]="cc.bg"
                        [style.color]="cc.color">
                        {{ m.control_id }}
                      </span>
                    }
                    @if (fwMaps.length > 6) {
                      <span class="mapping-overflow">+{{ fwMaps.length - 6 }} more</span>
                    }
                    @if (fwMaps.length === 0) {
                      <span class="mapping-empty">—</span>
                    }
                  </div>
                </td>
                <td class="td-cell td-center">
                  <div class="hit-dot"
                    [style.background]="fwMaps.length > 0 ? (isDark() ? '#C6EFCE' : '#2e7d32') : (isDark() ? '#FFC7CE' : '#c62828')">
                  </div>
                </td>
              </tr>
            }
            @if (!coverageQuery.isLoading() && filteredRows().length === 0) {
              <tr>
                <td colspan="4" class="td-empty">
                  No mappings found{{ activeFramework() ? ' for ' + activeFramework() : '' }}.
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
      @if (filteredRows().length > rowsPerPage) {
        <mat-paginator [length]="filteredRows().length" [pageSize]="rowsPerPage"
          [pageIndex]="page()" (page)="onPage($event)" hidePageSize>
        </mat-paginator>
      }
    </mat-card>

      </div>
    </mat-tab>

    <!-- ── Inferred Coverage ── -->
    <mat-tab label="Inferred Coverage">
      <div class="tab-body">

        @if (inferredQuery.isLoading()) {
          @for (i of [1,2,3,4,5]; track i) {
            <div class="skeleton-row"></div>
          }
        }

        @for (r of inferredQuery.data()?.frameworks ?? []; track r.framework_code) {
          @if (r.total_controls > 0) {
            <div class="infer-card">
              <div class="infer-card-header" (click)="toggleInferred(r.framework_code)">
                <div class="infer-card-info">
                  <div class="infer-fw-name">{{ r.framework }}</div>
                  <div class="infer-fw-sub">{{ r.covered_controls }} / {{ r.total_controls }} controls covered</div>
                </div>
                <div class="infer-progress-wrap">
                  <mat-progress-bar mode="determinate" [value]="r.coverage_pct" class="infer-progress-bar"></mat-progress-bar>
                </div>
                <span class="infer-pct" [style.color]="getPctColor(r.coverage_pct)">{{ r.coverage_pct }}%</span>
                <mat-icon class="icon-sm infer-expand-icon">{{ openInferred()[r.framework_code] ? 'expand_less' : 'expand_more' }}</mat-icon>
              </div>
              @if (openInferred()[r.framework_code]) {
                <div class="infer-card-detail">
                  <span class="infer-detail-text">{{ r.uncovered_controls }} uncovered controls · {{ r.coverage_pct }}% covered</span>
                </div>
              }
            </div>
          }
        }

        @if (inferredQuery.data()?.frameworks?.length === 0) {
          <div class="no-crosswalk-banner">
            No crosswalk data loaded — run the dataset bootstrap to load framework mappings.
          </div>
        }
      </div>
    </mat-tab>

  </mat-tab-group>

</div>
`,
  styles: [`:host { display: block; }

    /* Page root */
    .page-root { padding: 0 4px; }

    /* Header form field */
    .header-fw-select { min-width: 240px; }
    .option-count { margin-left: 8px; font-size: .75rem; opacity: .5; }

    /* Tab group */
    .tab-group { margin-bottom: 20px; }

    /* Inferred Coverage tab */
    .skeleton-row { height: 52px; background: rgba(255,255,255,.05); border-radius: 6px; margin-bottom: 8px; }
    .infer-card { border: 1px solid rgba(128,128,128,.2); border-radius: 6px; overflow: hidden; margin-bottom: 8px; }
    .infer-card-header { display: flex; align-items: center; gap: 16px; padding: 10px 16px; cursor: pointer; }
    .infer-card-info { flex: 1; }
    .infer-fw-name { font-weight: 600; font-size: .82rem; }
    .infer-fw-sub { font-size: .65rem; color: var(--mat-sys-on-surface-variant); }
    .infer-progress-wrap { width: 160px; }
    .infer-progress-bar { height: 6px; border-radius: 3px; }
    .infer-pct { font-weight: 700; min-width: 44px; text-align: right; font-size: .9rem; }
    .infer-expand-icon { opacity: .4; }
    .infer-card-detail { padding: 12px 16px; border-top: 1px solid rgba(255,255,255,.08); }
    .infer-detail-text { font-size: .72rem; color: var(--mat-sys-on-surface-variant); }
    .no-crosswalk-banner { padding: 16px; background: rgba(21,101,192,.1); border-radius: 6px; font-size: .85rem; }

    /* Summary cards */
    .tab-body { padding-top: 16px; }
    .summary-grid { display: grid; grid-template-columns: repeat(4,1fr); gap: 16px; margin-bottom: 16px; }
    .summary-card-content { padding-bottom: 12px !important; }
    .summary-card-label { font-size: .72rem; opacity: .5; margin-bottom: 4px; }
    .summary-card-value { font-size: 1.5rem; font-weight: 700; }

    /* Unmapped toggle */
    .toggle-row { display: flex; justify-content: flex-end; margin-bottom: 8px; }
    .unmapped-toggle { font-size: .72rem; }

    /* Framework pills */
    .fw-pills-card { margin-bottom: 16px; }
    .fw-pills-heading { font-size: .78rem; font-weight: 600; margin-bottom: 8px; }
    .fw-pills-row { display: flex; gap: 6px; flex-wrap: wrap; }
    .fw-pill {
      cursor: pointer;
      padding: 3px 10px;
      border-radius: 4px;
      font-size: .72rem;
      font-weight: 400;
      background: var(--mat-sys-surface-container);
      border: 1px solid transparent;
    }
    .fw-pill-active {
      font-weight: 700;
      background: color-mix(in srgb, var(--mat-sys-primary) 20%, transparent);
      border-color: color-mix(in srgb, var(--mat-sys-primary) 45%, transparent);
    }
    .fw-pill-iso-ext { background: rgba(255,192,0,.07); }
    .fw-pill-count { margin-left: 6px; opacity: .4; }

    /* Error banner */
    .error-banner { color: #f44336; padding: 12px; margin-bottom: 12px; border-radius: 6px; background: rgba(244,67,54,.1); }

    /* Coverage table */
    .table-scroll { overflow-x: auto; }
    .cov-table { width: 100%; border-collapse: collapse; font-size: .8rem; }
    .thead-row { border-bottom: 1px solid rgba(255,255,255,.1); }
    .tbody-row { border-bottom: 1px solid rgba(255,255,255,.04); }
    .tbody-row-click { cursor: pointer; }
    .th-cell { padding: 10px 12px; text-align: left; font-size: .72rem; font-weight: 600; opacity: .6; }
    .th-center { text-align: center; }
    .th-col-control { width: 140px; }
    .th-col-group { width: 140px; }
    .th-col-hit { width: 60px; }
    .th-col-code { width: 90px; }
    .td-cell { padding: 7px 12px; }
    .td-loading { padding: 8px 12px; border-bottom: 1px solid rgba(255,255,255,.04); }
    .td-center { text-align: center; }
    .td-bold { font-weight: 600; }
    .td-sm { font-size: .82rem; }
    .td-muted { font-size: .72rem; opacity: .5; }
    .td-xs { font-size: .72rem; }
    .td-empty { padding: 32px; text-align: center; opacity: .4; }
    .skeleton-cell { height: 12px; background: rgba(255,255,255,.07); border-radius: 4px; }

    /* Control ID cell */
    .control-id { font-family: monospace; font-size: .75rem; font-weight: 600; }
    .control-title { font-size: .68rem; opacity: .65; line-height: 1.3; }
    .group-code { font-family: monospace; font-size: .72rem; opacity: .65; }
    html[data-theme='light'] .gap-code { color: #185FA5; }


    /* Mapping chips */
    .mapping-chips { display: flex; flex-wrap: wrap; gap: 4px; }
    .conf-chip {
      font-size: .68rem;
      padding: 0 5px;
      height: 18px;
      border-radius: 9px;
      display: inline-flex;
      align-items: center;
    }
    .mapping-overflow { font-size: .68rem; opacity: .5; align-self: center; }
    .mapping-empty { opacity: .3; }

    /* Hit dot */
    .hit-dot { width: 10px; height: 10px; border-radius: 50%; margin: 0 auto; }

    /* Gaps table */
    .gap-code { font-family: monospace; font-size: .72rem; color: #9DC3E6; }
    .missing-chips { display: flex; gap: 4px; flex-wrap: wrap; }
    .missing-chip {
      font-size: .65rem;
      padding: 0 5px;
      height: 18px;
      border-radius: 9px;
      display: inline-flex;
      align-items: center;
      background: rgba(255,199,206,.15);
      color: #FFC7CE;
    }
  `],
})
export class CoverageComponent {
  readonly product  = inject(ProductService)
  readonly router   = inject(Router)
  private theme     = inject(ThemeService)
  private dashboard   = inject(DashboardApiService)
  private tokenStore  = inject(TokenStoreService)

  // ── State ──────────────────────────────────────────────────────────────────
  activeTab       = signal(0)
  activeFramework = signal('')
  showUnmapped    = signal(false)
  page            = signal(0)
  openInferred    = signal<Record<string, boolean>>({})
  readonly rowsPerPage = ROWS_PER_PAGE

  constructor() {
    // Reset framework selection when the active product changes (different source framework)
    effect(() => {
      this.product.product()
      this.activeFramework.set('')
      this.page.set(0)
    })
  }

  // ── Queries ────────────────────────────────────────────────────────────────
  coverageQuery = injectQuery(() => ({
    queryKey: ['dashboard-coverage', PRODUCT_SOURCE_FRAMEWORK[this.product.product()] ?? 'ISO27001'],
    queryFn: () => fetch(
      `/api/v1/dashboard/coverage?source_framework=${PRODUCT_SOURCE_FRAMEWORK[this.product.product()] ?? 'ISO27001'}`,
      { headers: { Authorization: 'Bearer ' + (this.tokenStore.get() ?? '') } }
    ).then(r => r.json()) as Promise<RealCoverage>,
  }))

  inferredQuery = injectQuery(() => ({
    queryKey: ['coverage-inferred', PRODUCT_SOURCE_FRAMEWORK[this.product.product()] ?? 'ISO27001'],
    queryFn: () => fetch(
      `/api/v1/coverage/multi-framework?source_framework=${PRODUCT_SOURCE_FRAMEWORK[this.product.product()] ?? 'ISO27001'}`,
      { headers: { Authorization: 'Bearer ' + (this.tokenStore.get() ?? '') } }
    ).then(r => r.json()) as Promise<{ assessed_controls: number; frameworks: InferredResult[] }>,
    enabled: this.activeTab() === 1,
  }))

  // ── Computed ───────────────────────────────────────────────────────────────
  covData = computed((): RealCoverage | null => this.coverageQuery.data() ?? null)
  isDark  = computed(() => this.theme.isDark())

  sortedFrameworks = computed((): string[] => {
    const c = this.covData()
    if (!c) return []
    return [...new Set(c.frameworks)].sort((a, b) => (c.by_framework[b] ?? 0) - (c.by_framework[a] ?? 0))
  })

  filteredRows = computed((): CoverageRow[] => {
    const c = this.covData()
    if (!c) return []
    if (this.showUnmapped()) return c.rows.filter(row => !row.mappings.some(m => m.framework === this.activeFramework()))
    if (!this.activeFramework()) return c.rows
    return c.rows.filter(row => row.mappings.some(m => m.framework === this.activeFramework()))
  })

  pagedRows = computed((): CoverageRow[] => {
    const p = this.page()
    return this.filteredRows().slice(p * ROWS_PER_PAGE, (p + 1) * ROWS_PER_PAGE)
  })

  summaryCards = computed(() => {
    const c = this.covData()
    if (!c) return []
    return [
      { label: 'Frameworks',    value: c.frameworks.length },
      { label: 'Total Mappings', value: c.total_mappings.toLocaleString() },
      { label: this.activeFramework() || 'Selected', value: this.activeFramework() ? (c.by_framework[this.activeFramework()] ?? 0) : '—' },
      { label: this.showUnmapped() ? 'Unmapped Controls' : 'Controls Shown', value: this.filteredRows().length },
    ]
  })

  sourceLabel = computed((): string => SOURCE_CONTROL_LABEL[this.product.product()] ?? 'ISO Control')
  packColor   = computed((): string => PRODUCT_COLORS[this.product.product()] ?? '#327df4')

  isoControlColor(controlId: string): string {
    if (this.product.product() !== 'isms') return this.packColor()
    if (controlId.startsWith('A.5')) return '#9E9E9E'
    if (controlId.startsWith('A.6')) return '#70AD47'
    if (controlId.startsWith('A.7')) return '#FFC000'
    if (controlId.startsWith('A.8')) return '#C00000'
    return this.packColor()
  }

  // ── Helpers ────────────────────────────────────────────────────────────────
  isIsoExt(f: string): boolean { return ISO_EXTENSIONS.has(f) }

  getPctColor(pct: number): string { return pctColor(pct, this.isDark()) }

  getConfColor(c: number): { bg: string; color: string } { return confColor(c, this.isDark()) }

  frameworkMappings(row: CoverageRow): CoverageMapping[] {
    if (!this.activeFramework()) return row.mappings
    return row.mappings.filter(m => m.framework === this.activeFramework())
  }

  // ── Actions ────────────────────────────────────────────────────────────────
  onUnmappedToggle(v: boolean): void { this.showUnmapped.set(v); this.page.set(0) }
  onPage(e: PageEvent): void { this.page.set(e.pageIndex) }
  toggleInferred(code: string): void { this.openInferred.update(m => ({ ...m, [code]: !m[code] })) }
}

// isms-core-platform/frontend/src/pages/Coverage.tsx
import { useState, useMemo } from 'react'
import { useProduct, PRODUCT_SUBTITLES, PRODUCT_COLORS } from '../store/ProductContext'
import { LockPersonOutlined, CloudOutlined, ExpandMoreOutlined, ExpandLessOutlined } from '@mui/icons-material'
import {
  Box,
  Card,
  CardContent,
  Collapse,
  IconButton,
  LinearProgress,
  Tab,
  Tabs,
  Typography,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Chip,
  Skeleton,
  Alert,
  Grid,
  TablePagination,
  Switch,
  FormControlLabel,
  Tooltip,
} from '@mui/material'
import { useQuery } from '@tanstack/react-query'
import { useNavigate } from 'react-router-dom'
import { dashboardApi, type CoverageGap } from '../api/dashboard'
import { projectsApi, type ProjectRead } from '../api/projectsApi'
import { client } from '../api/client'
import PageHeader from '../components/PageHeader'

interface CoverageMapping {
  framework: string
  framework_code: string
  control_id: string
  control_title: string
  mapping_type: string
  confidence: number
}

interface CoverageRow {
  iso_control_id: string
  iso_control_title: string
  control_group_code: string
  mappings: CoverageMapping[]
}

interface RealCoverage {
  frameworks: string[]
  total_iso_controls: number
  total_mappings: number
  by_framework: Record<string, number>
  rows: CoverageRow[]
}

// Map product → source framework code prefix sent to the API
const PRODUCT_SOURCE_FRAMEWORK: Record<string, string> = {
  isms:    'ISO27001',
  privacy: 'ISO27701',
  cloud:   'ISO27017',
}

// Human-readable label for the source control column
const SOURCE_CONTROL_LABEL: Record<string, string> = {
  isms:     'ISO 27001 Control',
  privacy:  'ISO 27701 Control',
  cloud:    'ISO 27017 Control',
  ISO27017: 'ISO 27017 Control',
  ISO27018: 'ISO 27018 Control',
}

// ISO 27000-family extension standards — shown with amber accent in framework pills
const ISO_EXTENSIONS = new Set(['ISO27017', 'ISO27018', 'ISO27701'])

const CONFIDENCE_COLOR = (c: number) =>
  c >= 0.8 ? { bg: 'rgba(198,239,206,0.15)', color: '#C6EFCE' }
  : c >= 0.6 ? { bg: 'rgba(255,235,156,0.12)', color: '#FFEB9C' }
  : { bg: 'rgba(255,199,206,0.12)', color: '#FFC7CE' }

const MISSING_CHIP: Record<string, { bg: string; color: string }> = {
  policy:      { bg: 'rgba(192,0,0,0.15)',    color: '#FFC7CE' },
  UG:          { bg: 'rgba(255,192,0,0.12)',   color: '#FFEB9C' },
  TG:          { bg: 'rgba(255,192,0,0.12)',   color: '#FFEB9C' },
  assessment:  { bg: 'rgba(192,0,0,0.15)',    color: '#FFC7CE' },
}

// ── Inferred Coverage tab ─────────────────────────────────────────────────────

interface InferredResult {
  framework: string
  framework_code: string
  total_controls: number
  covered_controls: number
  uncovered_controls: number
  coverage_pct: number
}

interface GapEntry {
  target_control_id: string
  target_control_title: string
  iso_controls_needed: { id: string; title: string }[]
}

const PCT_COLOR = (pct: number) =>
  pct >= 75 ? '#4CAF50' : pct >= 40 ? '#FF9800' : '#F44336'

function FrameworkCoverageCard({ result, projectId }: { result: InferredResult; projectId: string }) {
  const [expanded, setExpanded] = useState(false)
  const color = PCT_COLOR(result.coverage_pct)

  const { data: gapData, isLoading: gapLoading } = useQuery({
    queryKey: ['coverage-gap-map', result.framework_code, projectId],
    queryFn: () => client.get('/coverage/gap-map', { params: { target_framework: result.framework_code, project_id: projectId || undefined } }).then(r => r.data as { gaps: GapEntry[]; gap_count: number }),
    enabled: expanded,
  })

  return (
    <Box sx={{ border: '1px solid', borderColor: `${color}30`, borderRadius: 1.5, overflow: 'hidden', mb: 1 }}>
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, px: 2, py: 1.25, bgcolor: `${color}08`, cursor: 'pointer' }} onClick={() => setExpanded(e => !e)}>
        <Box sx={{ flex: 1 }}>
          <Typography variant="body2" sx={{ fontWeight: 600, fontSize: '0.82rem' }}>{result.framework}</Typography>
          <Typography variant="caption" sx={{ fontSize: '0.65rem', color: 'text.disabled' }}>
            {result.covered_controls} / {result.total_controls} controls covered
          </Typography>
        </Box>
        <Box sx={{ width: 160 }}>
          <LinearProgress variant="determinate" value={result.coverage_pct}
            sx={{ height: 6, borderRadius: 3, bgcolor: `${color}20`, '& .MuiLinearProgress-bar': { bgcolor: color } }} />
        </Box>
        <Typography variant="body2" sx={{ fontWeight: 700, color, minWidth: 44, textAlign: 'right', fontSize: '0.9rem' }}>
          {result.coverage_pct}%
        </Typography>
        <IconButton size="small" sx={{ p: 0.25 }}>
          {expanded ? <ExpandLessOutlined sx={{ fontSize: 16 }} /> : <ExpandMoreOutlined sx={{ fontSize: 16 }} />}
        </IconButton>
      </Box>

      <Collapse in={expanded}>
        <Box sx={{ px: 2, py: 1.5, borderTop: '1px solid', borderColor: 'divider' }}>
          {gapLoading && <Skeleton height={40} />}
          {gapData && gapData.gap_count === 0 && (
            <Typography variant="caption" sx={{ color: 'success.main' }}>✓ Full coverage — all controls addressed</Typography>
          )}
          {gapData && gapData.gaps.length > 0 && (
            <>
              <Typography variant="caption" sx={{ fontWeight: 600, fontSize: '0.68rem', color: 'text.secondary', textTransform: 'uppercase', display: 'block', mb: 1 }}>
                {gapData.gap_count} uncovered controls
              </Typography>
              <Box sx={{ maxHeight: 280, overflowY: 'auto' }}>
                {gapData.gaps.map((g: GapEntry) => (
                  <Box key={g.target_control_id} sx={{ mb: 1, pb: 1, borderBottom: '1px solid', borderColor: 'divider', '&:last-child': { borderBottom: 'none', mb: 0, pb: 0 } }}>
                    <Typography variant="caption" sx={{ fontWeight: 600, fontSize: '0.72rem' }}>
                      {g.target_control_id} — {g.target_control_title}
                    </Typography>
                    {g.iso_controls_needed.length > 0 && (
                      <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5, mt: 0.5 }}>
                        {g.iso_controls_needed.slice(0, 4).map(iso => (
                          <Chip key={iso.id} label={iso.id} size="small"
                            sx={{ height: 16, fontSize: '0.58rem', bgcolor: 'rgba(255,152,0,0.1)', color: '#FF9800' }} />
                        ))}
                        {g.iso_controls_needed.length > 4 && (
                          <Typography variant="caption" sx={{ fontSize: '0.6rem', color: 'text.disabled', alignSelf: 'center' }}>
                            +{g.iso_controls_needed.length - 4} more
                          </Typography>
                        )}
                      </Box>
                    )}
                  </Box>
                ))}
              </Box>
            </>
          )}
        </Box>
      </Collapse>
    </Box>
  )
}

function InferredCoverage() {
  const [projectId, setProjectId] = useState('')

  const { data: projects } = useQuery({
    queryKey: ['projects-list'],
    queryFn: () => projectsApi.list(),
  })

  const { data, isLoading } = useQuery({
    queryKey: ['coverage-inferred', projectId],
    queryFn: () => client.get('/coverage/multi-framework', { params: { project_id: projectId || undefined } }).then(r => r.data as { assessed_controls: number; frameworks: InferredResult[] }),
  })

  return (
    <Box>
      <Box sx={{ display: 'flex', gap: 2, alignItems: 'center', mb: 2.5 }}>
        <FormControl size="small" sx={{ minWidth: 260 }}>
          <InputLabel>Project scope</InputLabel>
          <Select value={projectId} label="Project scope" onChange={e => setProjectId(e.target.value)}>
            <MenuItem value="">Org-wide (all assessments)</MenuItem>
            {(projects ?? []).map((p: ProjectRead) => (
              <MenuItem key={p.id} value={p.id}>{p.name}</MenuItem>
            ))}
          </Select>
        </FormControl>
        {data && (
          <Typography variant="caption" sx={{ color: 'text.disabled' }}>
            Based on {data.assessed_controls} assessed ISO 27001 control groups
          </Typography>
        )}
      </Box>

      {isLoading && [0,1,2,3,4].map(i => <Skeleton key={i} height={52} sx={{ mb: 1 }} />)}

      {data?.frameworks.filter(f => f.total_controls > 0).map(r => (
        <FrameworkCoverageCard key={r.framework_code} result={r} projectId={projectId} />
      ))}

      {data?.frameworks.length === 0 && (
        <Alert severity="info" sx={{ mt: 2 }}>No crosswalk data loaded — run the dataset bootstrap to load framework mappings.</Alert>
      )}
    </Box>
  )
}

// ── Main page ─────────────────────────────────────────────────────────────────

export default function Coverage() {
  const { product, ismsTier } = useProduct()
  const [activeTab, setActiveTab] = useState(0)
  const [selectedFramework, setSelectedFramework] = useState('')
  const [showUnmapped, setShowUnmapped] = useState(false)
  const [page, setPage] = useState(0)
  const [cloudSub, setCloudSub] = useState<'ISO27017' | 'ISO27018'>('ISO27017')
  const [gapProduct, setGapProduct] = useState<'framework' | 'operational'>(
    ismsTier === 'operational' ? 'operational' : 'framework'
  )
  const ROWS_PER_PAGE = 25
  const navigate = useNavigate()

  const sourceFramework = product === 'cloud'
    ? cloudSub
    : (PRODUCT_SOURCE_FRAMEWORK[product] ?? 'ISO27001')

  const { data, isLoading, error } = useQuery({
    queryKey: ['dashboard', 'coverage', sourceFramework],
    queryFn: () => dashboardApi.getCoverage({ source_framework: sourceFramework }),
  })

  const { data: gapsData } = useQuery({
    queryKey: ['coverage-gaps', gapProduct],
    queryFn: () => dashboardApi.getCoverageGaps(gapProduct),
  })
  const gaps: CoverageGap[] = gapsData ?? []

  const cov = data as unknown as RealCoverage | undefined

  const activeFramework = selectedFramework || (cov?.frameworks[0] ?? '')

  const sortedFrameworks = useMemo(() => {
    if (!cov?.frameworks || !cov?.by_framework) return cov?.frameworks ?? []
    return [...cov.frameworks].sort(
      (a, b) => (cov.by_framework[b] ?? 0) - (cov.by_framework[a] ?? 0)
    )
  }, [cov])

  const filteredRows = useMemo(() => {
    if (!cov?.rows) return []
    if (showUnmapped) {
      // Show rows with NO mappings for the active framework
      return cov.rows.filter((row) =>
        !row.mappings.some((m) => m.framework === activeFramework)
      )
    }
    if (!activeFramework) return cov.rows
    return cov.rows.filter((row) =>
      row.mappings.some((m) => m.framework === activeFramework)
    )
  }, [cov, activeFramework, showUnmapped])

  const pagedRows = useMemo(() =>
    filteredRows.slice(page * ROWS_PER_PAGE, (page + 1) * ROWS_PER_PAGE),
    [filteredRows, page]
  )

  const frameworkCount = activeFramework ? (cov?.by_framework[activeFramework] ?? 0) : 0

  return (
    <Box>
      <PageHeader
        title="Framework Coverage"
        subtitle={activeTab === 0
          ? `${PRODUCT_SUBTITLES[product]} mapped to ${cov?.frameworks.length ?? '...'} frameworks · ${(cov?.total_mappings ?? 0).toLocaleString()} total mappings`
          : 'Inferred compliance coverage across target frameworks based on project assessments'}
        actions={
          activeTab === 0 && cov && (
            <FormControl size="small" sx={{ minWidth: 240 }}>
              <InputLabel>Framework</InputLabel>
              <Select
                value={activeFramework}
                onChange={(e) => setSelectedFramework(e.target.value)}
                label="Framework"
              >
                {sortedFrameworks.map((f) => (
                  <MenuItem key={f} value={f}>
                    <Box sx={{ display: 'flex', justifyContent: 'space-between', width: '100%', gap: 2 }}>
                      <span>{f}</span>
                      <Typography component="span" variant="caption" color="text.secondary">
                        {cov.by_framework[f] ?? 0}
                      </Typography>
                    </Box>
                  </MenuItem>
                ))}
              </Select>
            </FormControl>
          )
        }
      />

      <Tabs
        value={activeTab}
        onChange={(_, v) => setActiveTab(v)}
        sx={{ mb: 2.5, borderBottom: '1px solid', borderColor: 'divider', minHeight: 36, '& .MuiTab-root': { minHeight: 36, py: 0.75, fontSize: '0.8rem' } }}
      >
        <Tab label="Mapping Matrix" />
        <Tab label="Inferred Coverage" />
      </Tabs>

      {activeTab === 1 && <InferredCoverage />}

      {activeTab === 0 && <>

      {/* Cloud sub-framework toggle */}
      {product === 'cloud' && (
        <Box sx={{ display: 'flex', gap: 1, mb: 2 }}>
          {([
            { value: 'ISO27017' as const, label: 'ISO 27017', desc: 'Cloud Security' },
            { value: 'ISO27018' as const, label: 'ISO 27018', desc: 'PII in Cloud' },
          ]).map(({ value, label, desc }) => (
            <Box
              key={value}
              onClick={() => { setCloudSub(value); setSelectedFramework(''); setPage(0) }}
              sx={{
                px: 1.5, py: 0.75, borderRadius: 1, cursor: 'pointer',
                bgcolor: cloudSub === value ? 'rgba(255,192,0,0.15)' : 'rgba(255,255,255,0.04)',
                border: `1px solid ${cloudSub === value ? '#FFC00050' : 'rgba(255,255,255,0.08)'}`,
                '&:hover': { bgcolor: 'rgba(255,192,0,0.1)' },
              }}
            >
              <Typography variant="caption" fontWeight={cloudSub === value ? 700 : 400}
                color={cloudSub === value ? '#FFC000' : 'text.secondary'}>
                {label}
              </Typography>
              <Typography variant="caption" sx={{ ml: 1, opacity: 0.6 }}
                color={cloudSub === value ? '#FFC000' : 'text.disabled'}>
                {desc}
              </Typography>
            </Box>
          ))}
        </Box>
      )}

      {/* Summary cards */}
      {cov && (
        <Grid container spacing={2} sx={{ mb: 2 }}>
          <Grid item xs={6} sm={3}>
            <Card>
              <CardContent sx={{ pb: '12px !important' }}>
                <Typography variant="caption" color="text.secondary">Frameworks</Typography>
                <Typography variant="h4">{cov.frameworks.length}</Typography>
              </CardContent>
            </Card>
          </Grid>
          <Grid item xs={6} sm={3}>
            <Card>
              <CardContent sx={{ pb: '12px !important' }}>
                <Typography variant="caption" color="text.secondary">Total Mappings</Typography>
                <Typography variant="h4">{cov.total_mappings.toLocaleString()}</Typography>
              </CardContent>
            </Card>
          </Grid>
          <Grid item xs={6} sm={3}>
            <Card>
              <CardContent sx={{ pb: '12px !important' }}>
                <Typography variant="caption" color="text.secondary" noWrap>{activeFramework}</Typography>
                <Typography variant="h4">{frameworkCount}</Typography>
              </CardContent>
            </Card>
          </Grid>
          <Grid item xs={6} sm={3}>
            <Card>
              <CardContent sx={{ pb: '12px !important' }}>
                <Typography variant="caption" color="text.secondary">
                  {showUnmapped ? 'Unmapped Controls' : 'Controls Shown'}
                </Typography>
                <Typography variant="h4" color={showUnmapped ? 'error.light' : 'inherit'}>
                  {filteredRows.length}
                </Typography>
              </CardContent>
            </Card>
          </Grid>
        </Grid>
      )}

      {/* Unmapped toggle */}
      {cov && (
        <Box sx={{ mb: 1, display: 'flex', justifyContent: 'flex-end' }}>
          <FormControlLabel
            control={
              <Switch
                checked={showUnmapped}
                onChange={(e) => { setShowUnmapped(e.target.checked); setPage(0) }}
                size="small"
                sx={{ '& .MuiSwitch-thumb': { bgcolor: showUnmapped ? '#FFC7CE' : undefined } }}
              />
            }
            label={
              <Typography variant="caption" color={showUnmapped ? 'error.light' : 'text.secondary'}>
                Show unmapped only
              </Typography>
            }
          />
        </Box>
      )}

      {/* Framework selector pills */}
      {cov && (
        <Card sx={{ mb: 2 }}>
          <CardContent sx={{ pb: '12px !important' }}>
            <Typography variant="subtitle2" sx={{ mb: 1 }}>All Frameworks</Typography>
            <Box sx={{ display: 'flex', gap: 0.75, flexWrap: 'wrap' }}>
              {sortedFrameworks.map((f) => {
                const count = cov.by_framework[f] ?? 0
                const isActive = f === activeFramework
                const isExt = ISO_EXTENSIONS.has(f)
                return (
                  <Tooltip key={f} title={isExt ? 'ISO 27000-family extension standard' : ''} placement="top">
                    <Box
                      onClick={() => setSelectedFramework(f)}
                      sx={{
                        px: 1.25,
                        py: 0.4,
                        borderRadius: 1,
                        cursor: 'pointer',
                        bgcolor: isActive
                          ? (isExt ? 'rgba(255,192,0,0.2)' : 'rgba(68,114,196,0.2)')
                          : (isExt ? 'rgba(255,192,0,0.07)' : 'rgba(68,114,196,0.06)'),
                        border: `1px solid ${isActive ? (isExt ? '#FFC00050' : '#4472C450') : 'transparent'}`,
                        '&:hover': { bgcolor: isExt ? 'rgba(255,192,0,0.14)' : 'rgba(68,114,196,0.15)' },
                      }}
                    >
                      <Typography
                        variant="caption"
                        fontWeight={isActive ? 700 : 400}
                        color={isActive ? (isExt ? '#FFC000' : 'primary.light') : (isExt ? '#FFC00099' : 'text.secondary')}
                      >
                        {f}
                      </Typography>
                      <Typography
                        variant="caption"
                        sx={{ ml: 0.75, opacity: 0.6, color: isActive ? (isExt ? '#FFC000' : 'primary.light') : 'text.secondary' }}
                      >
                        {count}
                      </Typography>
                    </Box>
                  </Tooltip>
                )
              })}
            </Box>
          </CardContent>
        </Card>
      )}

      {error && <Alert severity="error" sx={{ mb: 2 }}>Failed to load coverage data.</Alert>}

      <TableContainer component={Card}>
        <Table size="small">
          <TableHead>
            <TableRow>
              <TableCell sx={{ width: 120 }}>
                {product === 'cloud' ? SOURCE_CONTROL_LABEL[sourceFramework] : (SOURCE_CONTROL_LABEL[product] ?? 'ISO Control')}
              </TableCell>
              <TableCell sx={{ width: 140 }}>Control Group</TableCell>
              <TableCell>{activeFramework || 'Framework'} Mappings</TableCell>
              <TableCell align="center" sx={{ width: 60 }}>Count</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {isLoading &&
              [...Array(8)].map((_, i) => (
                <TableRow key={i}>
                  {[...Array(4)].map((_, j) => (
                    <TableCell key={j}>
                      <Skeleton variant="text" />
                    </TableCell>
                  ))}
                </TableRow>
              ))}

            {pagedRows.map((row) => {
              const fwMappings = activeFramework
                ? row.mappings.filter((m) => m.framework === activeFramework)
                : row.mappings
              return (
                <TableRow key={row.iso_control_id} hover>
                  <TableCell
                    sx={product !== 'isms' ? { cursor: 'pointer' } : undefined}
                    onClick={product !== 'isms' ? () => navigate(`/framework-controls/${sourceFramework}/${row.iso_control_id}`) : undefined}
                  >
                    <Typography
                      variant="body2"
                      fontWeight={600}
                      color="primary.light"
                      sx={{ fontFamily: 'monospace', fontSize: '0.75rem' }}
                    >
                      {row.iso_control_id}
                    </Typography>
                    <Typography variant="caption" color="text.secondary" sx={{ display: 'block', lineHeight: 1.3 }}>
                      {row.iso_control_title}
                    </Typography>
                  </TableCell>
                  <TableCell>
                    <Typography variant="caption" color="text.secondary" sx={{ fontFamily: 'monospace' }}>
                      {row.control_group_code}
                    </Typography>
                  </TableCell>
                  <TableCell>
                    <Box sx={{ display: 'flex', gap: 0.5, flexWrap: 'wrap' }}>
                      {fwMappings.slice(0, 6).map((m, idx) => {
                        const cc = CONFIDENCE_COLOR(m.confidence)
                        return (
                          <Chip
                            key={idx}
                            label={m.control_id}
                            size="small"
                            title={`${m.control_title} · ${Math.round(m.confidence * 100)}% confidence · ${m.mapping_type}`}
                            sx={{ fontSize: '0.68rem', height: 18, bgcolor: cc.bg, color: cc.color, cursor: 'default' }}
                          />
                        )
                      })}
                      {fwMappings.length > 6 && (
                        <Typography variant="caption" color="text.secondary" sx={{ alignSelf: 'center' }}>
                          +{fwMappings.length - 6} more
                        </Typography>
                      )}
                      {fwMappings.length === 0 && (
                        <Typography variant="caption" color="text.secondary">—</Typography>
                      )}
                    </Box>
                  </TableCell>
                  <TableCell align="center">
                    <Box sx={{ width: 10, height: 10, borderRadius: '50%', mx: 'auto', bgcolor: fwMappings.length > 0 ? '#C6EFCE' : '#FFC7CE' }} />
                  </TableCell>
                </TableRow>
              )
            })}

            {!isLoading && filteredRows.length === 0 && (
              <TableRow>
                <TableCell colSpan={4} align="center">
                  <Typography variant="body2" color="text.secondary" sx={{ py: 3 }}>
                    No mappings found{activeFramework ? ` for ${activeFramework}` : ''}.
                  </Typography>
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
        {filteredRows.length > ROWS_PER_PAGE && (
          <TablePagination
            component="div"
            count={filteredRows.length}
            page={page}
            onPageChange={(_, p) => setPage(p)}
            rowsPerPage={ROWS_PER_PAGE}
            rowsPerPageOptions={[ROWS_PER_PAGE]}
            sx={{ borderTop: '1px solid', borderColor: 'divider' }}
          />
        )}
      </TableContainer>

      {/* ── Content Coverage Gaps ─────────────────────────────────── */}
      <Box sx={{ mt: 4 }}>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, mb: 1.5 }}>
          <Typography variant="h6" fontWeight={700}>
            Content Coverage Gaps
          </Typography>
          {product === 'isms' && (
            <>
              <Chip
                label={`${gaps.length} control${gaps.length !== 1 ? 's' : ''} affected`}
                size="small"
                sx={{ bgcolor: gaps.length === 0 ? 'rgba(198,239,206,0.15)' : 'rgba(255,199,206,0.15)', color: gaps.length === 0 ? '#C6EFCE' : '#FFC7CE' }}
              />
              <Box sx={{ ml: 'auto', display: 'flex', gap: 0.75 }}>
                {([
                  { value: 'framework' as const,   label: 'FW',  color: PRODUCT_COLORS.isms },
                  { value: 'operational' as const,  label: 'OP',  color: '#70AD47' },
                ]).map(({ value, label, color }) => (
                  <Chip
                    key={value}
                    label={label}
                    size="small"
                    onClick={() => setGapProduct(value)}
                    sx={{
                      cursor: 'pointer', fontSize: '0.72rem',
                      bgcolor: gapProduct === value ? `${color}30` : 'rgba(255,255,255,0.05)',
                      color: gapProduct === value ? color : 'text.secondary',
                      border: gapProduct === value ? `1px solid ${color}50` : '1px solid transparent',
                    }}
                  />
                ))}
              </Box>
            </>
          )}
        </Box>

        {(product === 'privacy' || product === 'cloud') && (
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, py: 3, pl: 1 }}>
            {product === 'privacy'
              ? <LockPersonOutlined sx={{ color: `${PRODUCT_COLORS.privacy}50`, fontSize: 20 }} />
              : <CloudOutlined sx={{ color: `${PRODUCT_COLORS.cloud}50`, fontSize: 20 }} />
            }
            <Typography variant="body2" color="text.disabled">
              Content coverage gaps for {PRODUCT_SUBTITLES[product]} will appear here once control groups are imported.
            </Typography>
          </Box>
        )}

        {product === 'isms' && gaps.length === 0 && (
          <Alert severity="success" sx={{ fontSize: '0.85rem' }}>
            All controls have complete {gapProduct === 'framework' ? 'FW' : 'OP'} coverage — no artefacts missing.
          </Alert>
        )}
        {product === 'isms' && gaps.length > 0 && (
          <TableContainer component={Card} variant="outlined">
            <Table size="small">
              <TableHead>
                <TableRow>
                  <TableCell sx={{ fontWeight: 700, width: 90 }}>Code</TableCell>
                  <TableCell sx={{ fontWeight: 700 }}>Control Group</TableCell>
                  <TableCell sx={{ fontWeight: 700 }}>Section</TableCell>
                  <TableCell sx={{ fontWeight: 700 }}>Missing Artefacts</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {gaps.map((gap) => (
                  <TableRow
                    key={gap.id}
                    hover
                    sx={{ cursor: 'pointer' }}
                    onClick={() => navigate(`/controls/${gap.id}`)}
                  >
                    <TableCell>
                      <Typography variant="caption" sx={{ fontFamily: 'monospace', color: 'primary.light' }}>
                        {gap.group_code}
                      </Typography>
                    </TableCell>
                    <TableCell>
                      <Typography variant="body2" fontWeight={600}>{gap.name}</Typography>
                    </TableCell>
                    <TableCell>
                      <Typography variant="caption" color="text.secondary">{gap.section_name}</Typography>
                    </TableCell>
                    <TableCell>
                      <Box sx={{ display: 'flex', gap: 0.5, flexWrap: 'wrap' }}>
                        {gap.missing.map((m) => (
                          <Chip
                            key={m}
                            label={m}
                            size="small"
                            sx={{
                              fontSize: '0.65rem', height: 18,
                              bgcolor: MISSING_CHIP[m]?.bg ?? 'rgba(255,199,206,0.15)',
                              color: MISSING_CHIP[m]?.color ?? '#FFC7CE',
                            }}
                          />
                        ))}
                      </Box>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        )}
      </Box>

      </>}
    </Box>
  )
}
