// isms-core-platform/frontend-angular/src/app/pages/help/help.component.ts
import { Component, inject, signal, effect, ElementRef, viewChild } from '@angular/core'
import { HttpClient } from '@angular/common/http'
import { firstValueFrom } from 'rxjs'
import { Router } from '@angular/router'

import { MatButtonModule } from '@angular/material/button'
import { MatIconModule } from '@angular/material/icon'
import { MatListModule } from '@angular/material/list'
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner'
import { MatTooltipModule } from '@angular/material/tooltip'
import { MatSidenavModule } from '@angular/material/sidenav'

// ── Types ─────────────────────────────────────────────────────────────────────

interface TocEntry {
  id: string
  label: string
  level: number
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function extractToc(md: string): TocEntry[] {
  const entries: TocEntry[] = []
  for (const line of md.split('\n')) {
    const m = line.match(/^(#{1,3})\s+(.+?)(?:\s+\{#[\w-]+\})?$/)
    if (!m) continue
    const level = m[1].length
    const rawLabel = m[2].replace(/\*\*/g, '').replace(/`/g, '').trim()
    const anchorMatch = line.match(/\{#([\w-]+)\}/)
    const id = anchorMatch
      ? anchorMatch[1]
      : rawLabel.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
    entries.push({ id, label: rawLabel, level })
  }
  return entries
}

/**
 * Convert markdown to lightweight HTML.
 * Only handles the constructs used in the ISMS user manual:
 * headings, bold, code spans, code blocks, blockquotes, tables,
 * ordered/unordered lists, horizontal rules, paragraphs.
 */
function markdownToHtml(md: string): string {
  const lines = md.split('\n')
  const out: string[] = []
  let inCodeBlock = false
  let inTable = false
  let inList = false
  let listType = ''

  const closePending = () => {
    if (inTable)  { out.push('</tbody></table>'); inTable = false }
    if (inList)   { out.push(`</${listType}>`);   inList = false; listType = '' }
  }

  const escape = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

  const inline = (s: string): string => {
    s = s
      .replace(/`([^`]+)`/g, '<code>$1</code>')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')
    return s
  }

  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i]

    if (raw.startsWith('```')) {
      if (!inCodeBlock) { closePending(); out.push('<pre><code>'); inCodeBlock = true }
      else              { out.push('</code></pre>'); inCodeBlock = false }
      continue
    }
    if (inCodeBlock) { out.push(escape(raw)); continue }

    // blank line
    if (raw.trim() === '') { closePending(); continue }

    // headings
    const hm = raw.match(/^(#{1,3})\s+(.+?)(?:\s+\{#[\w-]+\})?$/)
    if (hm) {
      closePending()
      const level = hm[1].length
      const text = hm[2].replace(/\{#[\w-]+\}/g, '').trim()
      const anchorMatch = raw.match(/\{#([\w-]+)\}/)
      const id = anchorMatch
        ? anchorMatch[1]
        : text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
      out.push(`<h${level} id="${id}" style="scroll-margin-top:80px">${inline(text)}</h${level}>`)
      continue
    }

    // horizontal rule
    if (/^---+$/.test(raw.trim())) { closePending(); out.push('<hr>'); continue }

    // blockquote
    if (raw.startsWith('> ')) { closePending(); out.push(`<blockquote>${inline(raw.slice(2))}</blockquote>`); continue }

    // table row
    if (raw.includes('|')) {
      const cells = raw.split('|').map(c => c.trim()).filter((_, i, a) => i > 0 && i < a.length - 1)
      if (/^[\s|:-]+$/.test(raw)) { /* separator row — skip */ continue }
      if (!inTable) {
        closePending()
        out.push('<table><thead><tr>')
        cells.forEach(c => out.push(`<th>${inline(c)}</th>`))
        out.push('</tr></thead><tbody>')
        inTable = true
        // peek: if next line is separator, skip it
        if (i + 1 < lines.length && /^[\s|:-]+$/.test(lines[i + 1])) i++
      } else {
        out.push('<tr>')
        cells.forEach(c => out.push(`<td>${inline(c)}</td>`))
        out.push('</tr>')
      }
      continue
    }

    // unordered list
    const ulm = raw.match(/^[-*+]\s+(.+)/)
    if (ulm) {
      if (!inList || listType !== 'ul') { closePending(); out.push('<ul>'); inList = true; listType = 'ul' }
      out.push(`<li>${inline(ulm[1])}</li>`)
      continue
    }

    // ordered list
    const olm = raw.match(/^\d+\.\s+(.+)/)
    if (olm) {
      if (!inList || listType !== 'ol') { closePending(); out.push('<ol>'); inList = true; listType = 'ol' }
      out.push(`<li>${inline(olm[1])}</li>`)
      continue
    }

    // paragraph
    closePending()
    out.push(`<p>${inline(raw)}</p>`)
  }
  closePending()
  return out.join('\n')
}

// ── Component ─────────────────────────────────────────────────────────────────

@Component({
  selector: 'app-help',
  standalone: true,
  imports: [
    MatButtonModule, MatIconModule, MatListModule,
    MatProgressSpinnerModule, MatTooltipModule, MatSidenavModule,
  ],
  template: `
<div class="help-layout">

  <!-- Sidebar TOC -->
  <div class="toc-sidebar">
    <div class="toc-inner">
      <div class="toc-label">Contents</div>
      <nav>
        @for (entry of toc(); track entry.id) {
          <div class="toc-entry"
            (click)="scrollTo(entry.id)"
            [style.padding-left.px]="entry.level === 1 ? 8 : entry.level === 2 ? 16 : 24"
            [style.font-size]="entry.level === 1 ? '0.82rem' : '0.77rem'"
            [style.font-weight]="entry.level === 1 ? '600' : '400'"
            [style.background]="activeId() === entry.id ? 'rgba(68,114,196,.15)' : 'transparent'"
            [style.border-left-color]="activeId() === entry.id ? '#4472C4' : 'transparent'"
            [style.color]="activeId() === entry.id ? '#9DC3E6' : 'inherit'"
            [style.opacity]="entry.level === 1 ? 1 : 0.7">
            {{ entry.label }}
          </div>
        }
      </nav>
    </div>
  </div>

  <!-- Main content -->
  <div #contentArea class="content-area">
    <!-- Header -->
    <div class="content-header">
      <h4 class="content-title">User Guide</h4>
      <span class="content-version">v1.0</span>
    </div>
    <hr class="content-divider">

    @if (error()) {
      <div class="error-msg">{{ error() }}</div>
    }

    @if (!html() && !error()) {
      <div class="spinner-wrap">
        <mat-spinner></mat-spinner>
      </div>
    }

    @if (html()) {
      <div [innerHTML]="html()" class="user-manual"></div>
    }
  </div>
</div>
`,
  styles: [`
    :host { display: flex; height: 100%; }
    .user-manual h1 { font-size: 1.6rem; font-weight: 700; margin: 32px 0 12px; }
    .user-manual h2 { font-size: 1.25rem; font-weight: 700; margin: 28px 0 8px; padding-bottom: 4px; border-bottom: 1px solid rgba(255,255,255,.08); }
    .user-manual h3 { font-size: 1.05rem; font-weight: 700; margin: 20px 0 6px; }
    .user-manual p  { line-height: 1.7; margin-bottom: 12px; opacity: .75; }
    .user-manual ul, .user-manual ol { padding-left: 24px; margin-bottom: 12px; }
    .user-manual li { line-height: 1.6; margin-bottom: 4px; opacity: .75; }
    .user-manual code { font-family: monospace; font-size: .82rem; background: rgba(255,255,255,.08); padding: 1px 5px; border-radius: 3px; color: #9DC3E6; }
    .user-manual pre { background: rgba(0,0,0,.3); border: 1px solid rgba(255,255,255,.1); border-radius: 6px; padding: 16px; overflow: auto; margin-bottom: 16px; }
    .user-manual pre code { background: transparent; color: inherit; }
    .user-manual table { border-collapse: collapse; width: 100%; margin-bottom: 16px; font-size: .82rem; }
    .user-manual th { text-align: left; padding: 6px 12px; border-bottom: 2px solid rgba(255,255,255,.1); font-size: .75rem; font-weight: 600; opacity: .6; text-transform: uppercase; }
    .user-manual td { padding: 6px 12px; border-bottom: 1px solid rgba(255,255,255,.06); opacity: .75; }
    .user-manual blockquote { border-left: 3px solid #4472C4; padding-left: 16px; margin: 16px 0; font-style: italic; opacity: .7; }
    .user-manual a { color: #9DC3E6; text-decoration: none; }
    .user-manual a:hover { text-decoration: underline; }
    .user-manual hr { border: none; border-top: 1px solid rgba(255,255,255,.08); margin: 24px 0; }
    .user-manual strong { font-weight: 700; }

    /* ── Layout ── */
    .help-layout { display: flex; height: 100%; overflow: hidden; }
    .toc-sidebar {
      width: 260px;
      flex-shrink: 0;
      border-right: 1px solid var(--mat-sys-outline-variant);
      overflow-y: auto;
      height: 100%;
    }
    .toc-inner { padding: 16px; }
    .toc-label {
      font-size: .65rem;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: .1em;
      opacity: .4;
      margin-bottom: 8px;
      padding-left: 8px;
    }
    .toc-entry {
      cursor: pointer;
      padding-top: 4px;
      padding-bottom: 4px;
      border-radius: 4px;
      margin-bottom: 1px;
      border-left: 2px solid transparent;
    }
    .content-area {
      flex: 1;
      overflow-y: auto;
      padding: 32px 40px;
      max-width: 860px;
    }
    .content-header { display: flex; align-items: center; gap: 8px; margin-bottom: 16px; }
    .content-title { margin: 0; font-weight: 700; }
    .content-version { font-size: .72rem; opacity: .4; margin-top: 4px; }
    .content-divider { border: none; border-top: 1px solid rgba(255,255,255,.08); margin-bottom: 24px; }
    .error-msg {
      color: #f44336;
      padding: 12px;
      background: rgba(244,67,54,.1);
      border-radius: 6px;
      margin-bottom: 16px;
    }
    .spinner-wrap { display: flex; justify-content: center; padding: 64px; }
  `],
})
export class HelpComponent {
  private http   = inject(HttpClient)
  private router = inject(Router)

  toc      = signal<TocEntry[]>([])
  html     = signal<string>('')
  error    = signal<string | null>(null)
  activeId = signal<string>('')

  readonly contentArea = viewChild<ElementRef<HTMLDivElement>>('contentArea')

  constructor() {
    // Load markdown on init
    firstValueFrom(this.http.get('/docs/user-manual.md', { responseType: 'text' }))
      .then(text => {
        this.toc.set(extractToc(text))
        this.html.set(markdownToHtml(text))
        // scroll to hash after render
        setTimeout(() => {
          const hash = window.location.hash.replace('#', '')
          if (hash) { this.scrollTo(hash) }
          this.setupObserver()
        }, 150)
      })
      .catch(e => this.error.set(`Failed to load manual: ${e.message}`))
  }

  scrollTo(id: string): void {
    this.activeId.set(id)
    const el = document.getElementById(id)
    if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' })
    this.router.navigate([], { fragment: id, replaceUrl: true })
  }

  private setupObserver(): void {
    const observer = new IntersectionObserver(
      entries => {
        for (const entry of entries) {
          if (entry.isIntersecting) this.activeId.set(entry.target.id)
        }
      },
      { rootMargin: '-10% 0px -80% 0px' }
    )
    document.querySelectorAll('h1[id], h2[id], h3[id]').forEach(h => observer.observe(h))
  }
}

// isms-core-platform/frontend/src/pages/Help.tsx
import { useState, useEffect, useRef } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import {
  Box,
  Typography,
  CircularProgress,
  Alert,
  Divider,
  List,
  ListItemButton,
  ListItemText,
  useTheme,
  useMediaQuery,
  IconButton,
  Drawer,
  Tooltip,
} from '@mui/material'
import { MenuOutlined } from '@mui/icons-material'

interface TocEntry {
  id: string
  label: string
  level: number
}

// Extract TOC from markdown text
function extractToc(md: string): TocEntry[] {
  const entries: TocEntry[] = []
  const lines = md.split('\n')
  for (const line of lines) {
    const m = line.match(/^(#{1,3})\s+(.+?)(?:\s+\{#[\w-]+\})?$/)
    if (m) {
      const level = m[1].length
      const rawLabel = m[2].replace(/\*\*/g, '').replace(/`/g, '').trim()
      // Extract explicit anchor or derive from label
      const anchorMatch = line.match(/\{#([\w-]+)\}/)
      const id = anchorMatch
        ? anchorMatch[1]
        : rawLabel.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
      entries.push({ id, label: rawLabel, level })
    }
  }
  return entries
}

// Custom heading renderer — strips {#anchor} syntax, adds id
function HeadingRenderer(level: number) {
  return function Heading({ children }: { children?: React.ReactNode }) {
    const raw = String(children ?? '')
    // Extract explicit anchor if present, e.g. "Getting Started {#getting-started}"
    const anchorMatch = raw.match(/\{#([\w-]+)\}/)
    const id = anchorMatch
      ? anchorMatch[1]
      : raw.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
    // Strip {#...} from displayed text
    const display = raw.replace(/\s*\{#[\w-]+\}/g, '')
    const Tag = `h${level}` as keyof JSX.IntrinsicElements
    return (
      <Tag id={id} style={{ scrollMarginTop: '80px' }}>
        {display}
      </Tag>
    )
  }
}

export default function Help() {
  const [markdown, setMarkdown] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [toc, setToc] = useState<TocEntry[]>([])
  const [activeId, setActiveId] = useState<string>('')
  const [drawerOpen, setDrawerOpen] = useState(false)
  const contentRef = useRef<HTMLDivElement>(null)
  const location = useLocation()
  const navigate = useNavigate()
  const theme = useTheme()
  const isNarrow = useMediaQuery(theme.breakpoints.down('lg'))

  // Load markdown
  useEffect(() => {
    fetch('/docs/user-manual.md')
      .then(r => {
        if (!r.ok) throw new Error(`Failed to load manual (${r.status})`)
        return r.text()
      })
      .then(text => {
        setMarkdown(text)
        setToc(extractToc(text))
      })
      .catch(e => setError(e.message))
  }, [])

  // Scroll to hash after markdown loads
  useEffect(() => {
    if (!markdown) return
    const hash = location.hash.replace('#', '')
    if (!hash) return
    // Short delay to let DOM render
    setTimeout(() => {
      const el = document.getElementById(hash)
      if (el) {
        el.scrollIntoView({ behavior: 'smooth', block: 'start' })
        setActiveId(hash)
      }
    }, 100)
  }, [markdown, location.hash])

  // Track active heading via IntersectionObserver
  useEffect(() => {
    if (!markdown) return
    const observer = new IntersectionObserver(
      entries => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            setActiveId(entry.target.id)
          }
        }
      },
      { rootMargin: '-10% 0px -80% 0px' }
    )
    const headings = document.querySelectorAll('h1[id], h2[id], h3[id]')
    headings.forEach(h => observer.observe(h))
    return () => observer.disconnect()
  }, [markdown])

  function handleTocClick(id: string) {
    navigate(`/help#${id}`, { replace: true })
    const el = document.getElementById(id)
    if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' })
    setActiveId(id)
    setDrawerOpen(false)
  }

  const tocContent = (
    <Box sx={{ width: 260, flexShrink: 0, p: 2 }}>
      <Typography variant="overline" color="text.secondary" sx={{ px: 1, display: 'block', mb: 1 }}>
        Contents
      </Typography>
      <List dense disablePadding>
        {toc.map(entry => (
          <ListItemButton
            key={entry.id}
            selected={activeId === entry.id}
            onClick={() => handleTocClick(entry.id)}
            sx={{
              borderRadius: 1,
              py: 0.4,
              pl: entry.level === 1 ? 1 : entry.level === 2 ? 2 : 3,
              '&.Mui-selected': {
                bgcolor: 'action.selected',
                borderLeft: '2px solid',
                borderLeftColor: 'primary.main',
              },
            }}
          >
            <ListItemText
              primary={entry.label}
              primaryTypographyProps={{
                variant: 'body2',
                sx: {
                  fontSize: entry.level === 1 ? '0.82rem' : '0.77rem',
                  fontWeight: entry.level === 1 ? 600 : 400,
                  color: activeId === entry.id ? 'primary.main' : 'text.secondary',
                  lineHeight: 1.4,
                },
              }}
            />
          </ListItemButton>
        ))}
      </List>
    </Box>
  )

  return (
    <Box sx={{ display: 'flex', height: '100%', overflow: 'hidden' }}>
      {/* Sidebar TOC — fixed on large screens */}
      {!isNarrow ? (
        <Box
          sx={{
            width: 260,
            flexShrink: 0,
            borderRight: '1px solid',
            borderColor: 'divider',
            overflowY: 'auto',
            height: '100%',
            position: 'sticky',
            top: 0,
          }}
        >
          {tocContent}
        </Box>
      ) : (
        <Drawer
          open={drawerOpen}
          onClose={() => setDrawerOpen(false)}
          PaperProps={{ sx: { bgcolor: 'background.paper' } }}
        >
          {tocContent}
        </Drawer>
      )}

      {/* Main content */}
      <Box
        ref={contentRef}
        sx={{
          flex: 1,
          overflowY: 'auto',
          px: { xs: 2, md: 5 },
          py: 4,
          maxWidth: 860,
        }}
      >
        {/* Header */}
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 3 }}>
          {isNarrow && (
            <Tooltip title="Table of contents">
              <IconButton onClick={() => setDrawerOpen(true)} size="small">
                <MenuOutlined />
              </IconButton>
            </Tooltip>
          )}
          <Typography variant="h4" sx={{ fontWeight: 700 }}>
            User Guide
          </Typography>
          <Typography variant="caption" color="text.secondary" sx={{ ml: 1, mt: 0.5 }}>
            v1.0
          </Typography>
        </Box>
        <Divider sx={{ mb: 3 }} />

        {error && (
          <Alert severity="error" sx={{ mb: 2 }}>
            {error}
          </Alert>
        )}

        {!markdown && !error && (
          <Box sx={{ display: 'flex', justifyContent: 'center', pt: 8 }}>
            <CircularProgress />
          </Box>
        )}

        {markdown && (
          <Box
            sx={{
              '& h1': { ...theme.typography.h3, mt: 4, mb: 1.5, color: 'text.primary' },
              '& h2': { ...theme.typography.h4, mt: 3.5, mb: 1, color: 'text.primary', borderBottom: '1px solid', borderColor: 'divider', pb: 0.5 },
              '& h3': { ...theme.typography.h5, mt: 2.5, mb: 0.75, color: 'text.primary' },
              '& p': { ...theme.typography.body1, mb: 1.5, lineHeight: 1.7, color: 'text.secondary' },
              '& ul, & ol': { pl: 3, mb: 1.5 },
              '& li': { ...theme.typography.body1, mb: 0.5, color: 'text.secondary' },
              '& table': { borderCollapse: 'collapse', width: '100%', mb: 2, fontSize: '0.82rem' },
              '& th': {
                textAlign: 'left',
                p: '6px 12px',
                bgcolor: 'background.paper',
                borderBottom: '2px solid',
                borderColor: 'divider',
                fontWeight: 600,
                color: 'text.secondary',
                fontSize: '0.75rem',
                textTransform: 'uppercase',
                letterSpacing: '0.04em',
              },
              '& td': {
                p: '6px 12px',
                borderBottom: '1px solid',
                borderColor: 'divider',
                color: 'text.secondary',
              },
              '& tr:last-child td': { borderBottom: 'none' },
              '& code': {
                fontFamily: 'monospace',
                fontSize: '0.82rem',
                bgcolor: 'action.hover',
                px: 0.6,
                py: 0.2,
                borderRadius: 0.5,
                color: 'primary.main',
              },
              '& pre': {
                bgcolor: 'background.paper',
                border: '1px solid',
                borderColor: 'divider',
                borderRadius: 1,
                p: 2,
                overflow: 'auto',
                mb: 2,
                '& code': { bgcolor: 'transparent', px: 0, py: 0, color: 'text.primary' },
              },
              '& blockquote': {
                borderLeft: '3px solid',
                borderColor: 'primary.main',
                pl: 2,
                ml: 0,
                my: 2,
                color: 'text.secondary',
                fontStyle: 'italic',
              },
              '& a': { color: 'primary.main', textDecoration: 'none', '&:hover': { textDecoration: 'underline' } },
              '& hr': { border: 'none', borderTop: '1px solid', borderColor: 'divider', my: 3 },
            }}
          >
            <ReactMarkdown
              remarkPlugins={[remarkGfm]}
              components={{
                h1: HeadingRenderer(1),
                h2: HeadingRenderer(2),
                h3: HeadingRenderer(3),
              }}
            >
              {markdown}
            </ReactMarkdown>
          </Box>
        )}
      </Box>
    </Box>
  )
}
