// isms-core-platform/frontend-angular/src/app/pages/metrics/metrics.component.ts
import { Component, inject, signal, computed } from '@angular/core'
import { FormsModule } from '@angular/forms'
import { firstValueFrom } from 'rxjs'
import { injectQuery, injectMutation, injectQueryClient } from '@tanstack/angular-query-experimental'

import { MatCardModule } from '@angular/material/card'
import { MatButtonModule } from '@angular/material/button'
import { MatFormFieldModule } from '@angular/material/form-field'
import { MatSelectModule } from '@angular/material/select'
import { MatIconModule } from '@angular/material/icon'
import { MatProgressBarModule } from '@angular/material/progress-bar'
import { MatTableModule } from '@angular/material/table'
import { MatTooltipModule } from '@angular/material/tooltip'
import { MatTabsModule } from '@angular/material/tabs'
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar'

import { MetricsApiService, type MetricSnapshot } from '../../api/metrics-api.service'
import { ProjectsApiService } from '../../api/projects-api.service'
import { ProjectService } from '../../core/services/project.service'
import { AuthService } from '../../core/services/auth.service'
import { PageHeaderComponent } from '../../shared/components/page-header.component'
import { type ProjectRead } from '../../shared/types'

// ── Helpers ───────────────────────────────────────────────────────────────────

function pct(num: number, denom: number): number {
  if (!denom) return 0
  return Math.round(num / denom * 100)
}

function fmtDate(d: string): string {
  return new Date(d).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
}

interface KpiCard {
  icon: string
  label: string
  value: number
  unit: 'percent' | 'count'
  color: string
  trend?: number | null   // last snapshot value for comparison
}

function metricColor(unit: 'percent' | 'count', value: number, lowerIsBetter = false): string {
  if (unit === 'count') {
    if (lowerIsBetter) return value === 0 ? '#4CAF50' : value <= 3 ? '#FF9800' : '#F44336'
    return '#607D8B'
  }
  return value >= 75 ? '#4CAF50' : value >= 40 ? '#FF9800' : '#F44336'
}

// ── Component ─────────────────────────────────────────────────────────────────

@Component({
  selector: 'app-metrics',
  standalone: true,
  imports: [
    FormsModule,
    MatCardModule, MatButtonModule, MatFormFieldModule, MatSelectModule,
    MatIconModule, MatProgressBarModule, MatTableModule,
    MatTooltipModule, MatTabsModule, MatSnackBarModule,
    PageHeaderComponent,
  ],
  template: `
<app-page-header
  title="KPI Dashboard"
  subtitle="ISO 27001:2022 §9.1 — performance evaluation and measurement">
  <div actions>
    @if (activeTab() === 0) {
      <div class="header-actions">
        <button mat-icon-button matTooltip="Compute snapshot now"
          [disabled]="snapshotMut.isPending() || !selectedProjectId()"
          (click)="computeSnapshot()">
          @if (snapshotMut.isPending()) {
            <span class="pending-indicator">…</span>
          } @else {
            <mat-icon>refresh</mat-icon>
          }
        </button>
        <mat-form-field appearance="outline" subscriptSizing="dynamic" class="project-select-field">
          <mat-label>Project</mat-label>
          <mat-select [ngModel]="selectedProjectId()" (ngModelChange)="selectedProjectId.set($event)">
            <mat-option value="">Select a project</mat-option>
            @for (p of projectsQuery.data() ?? []; track p.id) {
              <mat-option [value]="p.id">{{ p.name }}</mat-option>
            }
          </mat-select>
        </mat-form-field>
      </div>
    }
  </div>
</app-page-header>

@if (auth.isSuperAdmin()) {
  <mat-tab-group [selectedIndex]="activeTab()" (selectedIndexChange)="activeTab.set($event)"
    class="tabs-no-margin-bottom">
    <mat-tab label="My Metrics" />
    <mat-tab label="Portfolio" />
  </mat-tab-group>
}

<!-- ── My Metrics ────────────────────────────────────────────────────────── -->
@if (activeTab() === 0) {

  @if (!selectedProjectId()) {
    <div class="empty-state empty-state-top-lg">
      <mat-icon>insights</mat-icon>
      <p>Select a project to view KPI metrics.</p>
    </div>
  } @else {

    @if (snapshotsQuery.isLoading()) {
      <div class="loading-grid">
        @for (i of [0,1,2,3,4,5,6,7,8]; track i) {
          <div class="skeleton-card"></div>
        }
      </div>
    } @else if (snapshotsQuery.isError()) {
      <div class="alert alert-error">Failed to load metrics.</div>
    } @else if (!latestSnapshot()) {
      <div class="empty-state empty-state-top-md">
        <mat-icon>bar_chart</mat-icon>
        <div>
          <p>No snapshots yet for this project.</p>
          <button mat-flat-button color="primary" class="compute-btn"
            [disabled]="snapshotMut.isPending()"
            (click)="computeSnapshot()">
            <mat-icon>add_chart</mat-icon>
            Compute First Snapshot
          </button>
        </div>
      </div>
    } @else {
      @let snap = latestSnapshot()!;

      <!-- Audit Readiness Hero -->
      <div class="audit-hero" [style.border-color]="auditColor() + '40'" [style.background]="auditColor() + '08'">
        <mat-icon class="audit-hero-icon" [style.color]="auditColor()">insights</mat-icon>
        <div>
          <p class="audit-hero-label">Audit Readiness Score</p>
          <p class="audit-hero-value" [style.color]="auditColor()">{{ snap.audit_readiness_score }}%</p>
          <p class="dim-sm">Composite of compliance, policy coverage, evidence freshness, open risks &amp; gaps</p>
        </div>
        <div class="audit-hero-date">
          <span class="dim-sm">Snapshot: {{ fmtDate(snap.snapshot_date) }}</span>
        </div>
      </div>

      <!-- KPI grid -->
      <div class="kpi-grid">
        @for (card of kpiCards(snap); track card.label) {
          <div class="kpi-card"
            [style.border-color]="card.color + '25'"
            [style.background]="card.color + '06'"
            [matTooltip]="'Snapshot: ' + fmtDate(snap.snapshot_date)">
            <div class="kpi-header">
              <mat-icon [style.color]="card.color">{{ card.icon }}</mat-icon>
              <div>
                <p class="kpi-label">{{ card.label }}</p>
                <p class="kpi-value" [style.color]="card.color">
                  {{ card.value }}{{ card.unit === 'percent' ? '%' : '' }}
                </p>
              </div>
            </div>
            <mat-progress-bar mode="determinate"
              [value]="card.unit === 'percent' ? card.value : 0"
              [style.display]="card.unit === 'percent' ? 'block' : 'none'"
              [style.--mat-progress-bar-active-indicator-color]="card.color"
              class="kpi-progress-bar" />
          </div>
        }
      </div>

      <!-- Trend table (last 30 days snapshots) -->
      @if (snapshotsQuery.data()!.length > 1) {
        <div class="trend-section">
          <p class="section-title">Snapshot History (last 30 days)</p>
          <div class="table-wrapper">
            <table mat-table [dataSource]="recentSnapshots()" class="trend-table">

              <ng-container matColumnDef="date">
                <th mat-header-cell *matHeaderCellDef>Date</th>
                <td mat-cell *matCellDef="let s">{{ fmtDate(s.snapshot_date) }}</td>
              </ng-container>

              <ng-container matColumnDef="audit">
                <th mat-header-cell *matHeaderCellDef class="col-right">Audit Readiness</th>
                <td mat-cell *matCellDef="let s" class="col-right">
                  <span [style.color]="metricColor('percent', s.audit_readiness_score)" class="fw-600">
                    {{ s.audit_readiness_score }}%
                  </span>
                </td>
              </ng-container>

              <ng-container matColumnDef="policy">
                <th mat-header-cell *matHeaderCellDef class="col-right">Policy Coverage</th>
                <td mat-cell *matCellDef="let s" class="col-right">
                  <span [style.color]="metricColor('percent', pct(s.controls_with_policy, s.total_controls))">
                    {{ pct(s.controls_with_policy, s.total_controls) }}%
                  </span>
                </td>
              </ng-container>

              <ng-container matColumnDef="impl">
                <th mat-header-cell *matHeaderCellDef class="col-right">Impl Coverage</th>
                <td mat-cell *matCellDef="let s" class="col-right">
                  <span [style.color]="metricColor('percent', pct(s.controls_with_impl, s.total_controls))">
                    {{ pct(s.controls_with_impl, s.total_controls) }}%
                  </span>
                </td>
              </ng-container>

              <ng-container matColumnDef="evidence">
                <th mat-header-cell *matHeaderCellDef class="col-right">Evidence</th>
                <td mat-cell *matCellDef="let s" class="col-right">
                  <span [style.color]="metricColor('percent', pct(s.controls_with_evidence, s.total_controls))">
                    {{ pct(s.controls_with_evidence, s.total_controls) }}%
                  </span>
                </td>
              </ng-container>

              <ng-container matColumnDef="gaps">
                <th mat-header-cell *matHeaderCellDef class="col-right">Open Gaps</th>
                <td mat-cell *matCellDef="let s" class="col-right">
                  <span [style.color]="metricColor('count', s.open_gaps, true)">{{ s.open_gaps }}</span>
                </td>
              </ng-container>

              <tr mat-header-row *matHeaderRowDef="trendCols"></tr>
              <tr mat-row *matRowDef="let row; columns: trendCols;"></tr>
            </table>
          </div>
        </div>
      }
    }
  }
}

<!-- ── Portfolio tab ──────────────────────────────────────────────────────── -->
@if (activeTab() === 1 && auth.isSuperAdmin()) {
  <div class="portfolio-section">
    @if (portfolioQuery.isLoading()) {
      <div class="loading-grid portfolio-loading-grid">
        @for (i of [0,1,2,3]; track i) { <div class="skeleton-card skeleton-card-sm"></div> }
      </div>
    } @else if (portfolioQuery.isError()) {
      <div class="alert alert-warn">Portfolio data unavailable.</div>
    } @else if (!portfolioQuery.data()?.length) {
      <div class="empty-state"><mat-icon>folder_open</mat-icon><p>No project snapshots yet.</p></div>
    } @else {
      <div class="table-wrapper">
        <table mat-table [dataSource]="portfolioQuery.data()!" class="trend-table">

          <ng-container matColumnDef="project">
            <th mat-header-cell *matHeaderCellDef>Project</th>
            <td mat-cell *matCellDef="let row" class="fw-500">{{ row.project_name }}</td>
          </ng-container>

          <ng-container matColumnDef="audit">
            <th mat-header-cell *matHeaderCellDef class="col-right">Audit Readiness</th>
            <td mat-cell *matCellDef="let row" class="col-right">
              <span [style.color]="metricColor('percent', row.audit_readiness_score)" class="fw-600">
                {{ row.audit_readiness_score }}%
              </span>
            </td>
          </ng-container>

          <ng-container matColumnDef="policy">
            <th mat-header-cell *matHeaderCellDef class="col-right">Policy</th>
            <td mat-cell *matCellDef="let row" class="col-right">
              <span [style.color]="metricColor('percent', pct(row.controls_with_policy, row.total_controls))">
                {{ pct(row.controls_with_policy, row.total_controls) }}%
              </span>
            </td>
          </ng-container>

          <ng-container matColumnDef="gaps">
            <th mat-header-cell *matHeaderCellDef class="col-right">Open Gaps</th>
            <td mat-cell *matCellDef="let row" class="col-right">
              <span [style.color]="metricColor('count', row.open_gaps, true)">{{ row.open_gaps }}</span>
            </td>
          </ng-container>

          <ng-container matColumnDef="snapshot_date">
            <th mat-header-cell *matHeaderCellDef class="col-right">Last Snapshot</th>
            <td mat-cell *matCellDef="let row" class="col-right">
              <span class="dim-sm">{{ fmtDate(row.snapshot_date) }}</span>
            </td>
          </ng-container>

          <tr mat-header-row *matHeaderRowDef="portfolioCols"></tr>
          <tr mat-row *matRowDef="let row; columns: portfolioCols;"></tr>
        </table>
      </div>
    }
  </div>
}
  `,
  styles: [`
    :host { display: block; padding: 24px; }

    .alert { padding: 10px 14px; border-radius: 6px; margin-bottom: 14px; font-size: 0.85rem; }
    .alert-error { background: rgba(192,0,0,0.12); color: #FFC7CE; }
    .alert-warn  { background: rgba(230,160,0,0.12); color: #FFEB9C; }

    /* Header actions */
    .header-actions { display: flex; align-items: center; gap: 8px; }
    .pending-indicator { font-size: 12px; }
    .project-select-field { min-width: 220px; }
    .tabs-no-margin-bottom { margin-bottom: 0; }

    /* Audit hero */
    .audit-hero {
      display: flex; align-items: center; gap: 24px;
      padding: 20px 24px; border-radius: 10px; border: 1px solid;
      margin-bottom: 24px; flex-wrap: wrap;
    }
    .audit-hero-icon { font-size: 36px; width: 36px; height: 36px; }
    .audit-hero-label {
      font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.08em;
      color: var(--mat-sys-on-surface-variant); margin: 0;
    }
    .audit-hero-value { font-size: 2.8rem; font-weight: 800; line-height: 1; margin: 0; }
    .audit-hero-date { margin-left: auto; }

    /* KPI grid */
    .kpi-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(210px, 1fr));
      gap: 16px;
    }
    .kpi-card {
      border: 1px solid; border-radius: 10px; padding: 16px;
    }
    .kpi-header { display: flex; align-items: flex-start; gap: 10px; }
    .kpi-header mat-icon { font-size: 20px; width: 20px; height: 20px; margin-top: 2px; flex-shrink: 0; }
    .kpi-label { font-size: 0.7rem; color: var(--mat-sys-on-surface-variant); line-height: 1.3; margin: 0; }
    .kpi-value { font-size: 1.8rem; font-weight: 700; line-height: 1.1; margin: 2px 0 0; }
    .kpi-progress-bar { height: 4px; border-radius: 2px; margin-top: 8px; }

    /* Skeleton */
    .loading-grid {
      display: grid; grid-template-columns: repeat(auto-fill, minmax(210px, 1fr)); gap: 16px;
    }
    .portfolio-loading-grid { grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); }
    .skeleton-card {
      height: 110px; border-radius: 10px; background: rgba(255,255,255,0.06);
      animation: pulse 1.5s ease-in-out infinite alternate;
    }
    .skeleton-card-sm { height: 80px; }
    @keyframes pulse { from { opacity: 0.4; } to { opacity: 1; } }

    /* Table */
    .table-wrapper { overflow-x: auto; }
    .trend-table { width: 100%; }
    .col-right { text-align: right; }
    .fw-600 { font-weight: 600; }
    .fw-500 { font-weight: 500; }

    .section-title { font-size: 0.85rem; font-weight: 600; margin: 0 0 12px; }
    .trend-section { margin-top: 28px; }
    .portfolio-section { padding-top: 16px; }

    .dim-sm { font-size: 0.68rem; color: var(--mat-sys-on-surface-variant); }

    .empty-state {
      display: flex; align-items: center; gap: 16px;
      padding: 48px 32px; color: var(--mat-sys-on-surface-variant);
      justify-content: center; flex-direction: column; text-align: center;
    }
    .empty-state mat-icon { font-size: 40px; width: 40px; height: 40px; }
    .empty-state p { margin: 4px 0; }
    .empty-state-top-lg { margin-top: 32px; }
    .empty-state-top-md { margin-top: 24px; }
    .compute-btn { margin-top: 12px; }
  `],
})
export class MetricsComponent {
  auth      = inject(AuthService)
  project   = inject(ProjectService)
  private metricsApi  = inject(MetricsApiService)
  private projectsApi = inject(ProjectsApiService)
  private snackBar    = inject(MatSnackBar)
  private qc          = injectQueryClient()

  activeTab         = signal(0)
  selectedProjectId = signal(this.project.activeProjectId() ?? '')

  trendCols     = ['date', 'audit', 'policy', 'impl', 'evidence', 'gaps']
  portfolioCols = ['project', 'audit', 'policy', 'gaps', 'snapshot_date']

  // ── Queries ────────────────────────────────────────────────────────────────

  projectsQuery = injectQuery(() => ({
    queryKey: ['projects-list'] as const,
    queryFn: () => firstValueFrom(this.projectsApi.list()),
  }))

  snapshotsQuery = injectQuery(() => ({
    queryKey: ['metrics-snapshots', this.selectedProjectId()] as const,
    queryFn: () => firstValueFrom(this.metricsApi.getSnapshots(this.selectedProjectId(), 30)),
    enabled: !!this.selectedProjectId() && this.activeTab() === 0,
  }))

  portfolioQuery = injectQuery(() => ({
    queryKey: ['metrics-portfolio-all'] as const,
    queryFn: async (): Promise<MetricSnapshot[]> => {
      // Fetch all projects and get the latest snapshot per project
      const projects = await firstValueFrom(this.projectsApi.list())
      const snaps = await Promise.allSettled(
        projects.map(p => firstValueFrom(this.metricsApi.getSnapshots(p.id, 7)))
      )
      const results: (MetricSnapshot & { project_name: string })[] = []
      snaps.forEach((r, i) => {
        if (r.status === 'fulfilled' && r.value.length > 0) {
          const latest = r.value[0]
          results.push({ ...latest, project_name: projects[i].name } as MetricSnapshot & { project_name: string })
        }
      })
      return results.sort((a, b) => b.audit_readiness_score - a.audit_readiness_score)
    },
    enabled: this.activeTab() === 1 && this.auth.isSuperAdmin(),
  }))

  // ── Mutations ──────────────────────────────────────────────────────────────

  snapshotMut = injectMutation(() => ({
    mutationFn: () => firstValueFrom(this.metricsApi.createSnapshot(this.selectedProjectId())),
    onSuccess: () => {
      this.qc.invalidateQueries({ queryKey: ['metrics-snapshots', this.selectedProjectId()] })
      this.snackBar.open('Snapshot computed.', '', { duration: 3000 })
    },
    onError: () => this.snackBar.open('Failed to compute snapshot.', 'Dismiss', { duration: 4000 }),
  }))

  // ── Computed ───────────────────────────────────────────────────────────────

  latestSnapshot = computed(() => {
    const snaps = this.snapshotsQuery.data()
    return snaps && snaps.length > 0 ? snaps[0] : null
  })

  recentSnapshots = computed(() => (this.snapshotsQuery.data() ?? []).slice(0, 30))

  auditColor = computed(() => {
    const s = this.latestSnapshot()
    if (!s) return '#607D8B'
    return metricColor('percent', s.audit_readiness_score)
  })

  // ── Methods ────────────────────────────────────────────────────────────────

  computeSnapshot() {
    if (!this.selectedProjectId()) return
    this.snapshotMut.mutate(undefined)
  }

  kpiCards(snap: MetricSnapshot): KpiCard[] {
    const total = snap.total_controls || 1
    const policyCov  = pct(snap.controls_with_policy,     total)
    const implCov    = pct(snap.controls_with_impl,       total)
    const assessCov  = pct(snap.controls_with_assessment, total)
    const evidenceCov = pct(snap.controls_with_evidence,  total)
    const gapClosed  = snap.closed_gaps + snap.open_gaps > 0
      ? pct(snap.closed_gaps, snap.closed_gaps + snap.open_gaps)
      : 0

    return [
      { icon: 'inventory',        label: 'Policy Coverage',    value: policyCov,  unit: 'percent', color: metricColor('percent', policyCov) },
      { icon: 'developer_guide',  label: 'Impl Coverage',      value: implCov,    unit: 'percent', color: metricColor('percent', implCov) },
      { icon: 'assignment_turned_in', label: 'Assessment Coverage', value: assessCov, unit: 'percent', color: metricColor('percent', assessCov) },
      { icon: 'verified',         label: 'Evidence Coverage',  value: evidenceCov, unit: 'percent', color: metricColor('percent', evidenceCov) },
      { icon: 'task_alt',         label: 'Gap Closure Rate',   value: gapClosed,  unit: 'percent', color: metricColor('percent', gapClosed) },
      { icon: 'security',         label: 'Open Gaps',          value: snap.open_gaps,  unit: 'count', color: metricColor('count', snap.open_gaps, true) },
      { icon: 'dns',              label: 'Total Controls',     value: snap.total_controls, unit: 'count', color: '#607D8B' },
    ]
  }

  metricColor = metricColor
  pct         = pct
  fmtDate     = fmtDate
}

// isms-core-platform/frontend/src/pages/Metrics.tsx
import { useState } from 'react'
import {
  Alert, Box, FormControl, InputLabel, MenuItem, Select,
  Skeleton, Tab, Tabs, Table, TableBody, TableCell, TableHead,
  TableRow, Tooltip, Typography,
} from '@mui/material'
import {
  AssessmentOutlined, ErrorOutlined, GppMaybeOutlined, InsightsOutlined,
  InventoryOutlined, RefreshOutlined, SecurityOutlined, ShieldOutlined,
  TaskAltOutlined, VerifiedOutlined,
} from '@mui/icons-material'
import { IconButton } from '@mui/material'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import {
  LineChart, Line, ResponsiveContainer, Tooltip as ChartTooltip,
} from 'recharts'
import { metricsApi, type MetricResult, type OrgMetricRow } from '../api/metricsApi'
import { projectsApi, type ProjectRead } from '../api/projectsApi'
import { useProject } from '../store/ProjectContext'
import { useAuth } from '../store/AuthContext'
import PageHeader from '../components/PageHeader'

// ── Config ────────────────────────────────────────────────────────────────────

const METRIC_ICON: Record<string, React.ReactNode> = {
  compliance_score:    <AssessmentOutlined sx={{ fontSize: 18 }} />,
  policy_coverage:     <InventoryOutlined sx={{ fontSize: 18 }} />,
  risk_score_avg:      <GppMaybeOutlined sx={{ fontSize: 18 }} />,
  risk_critical_count: <ErrorOutlined sx={{ fontSize: 18 }} />,
  evidence_freshness:  <VerifiedOutlined sx={{ fontSize: 18 }} />,
  gap_open_count:      <SecurityOutlined sx={{ fontSize: 18 }} />,
  gap_closure_rate:    <TaskAltOutlined sx={{ fontSize: 18 }} />,
  remediation_overdue: <ShieldOutlined sx={{ fontSize: 18 }} />,
  audit_readiness:     <InsightsOutlined sx={{ fontSize: 18 }} />,
}

// For count/numeric metrics: lower is better (red when high)
const LOWER_IS_BETTER = new Set(['risk_score_avg', 'risk_critical_count', 'gap_open_count', 'remediation_overdue'])

function metricColor(name: string, value: number, unit: string): string {
  if (unit === 'count' || name === 'risk_score_avg') {
    if (LOWER_IS_BETTER.has(name)) return value === 0 ? '#4CAF50' : value <= 3 ? '#FF9800' : '#F44336'
    return '#607D8B'
  }
  // percent: higher is better
  return value >= 75 ? '#4CAF50' : value >= 40 ? '#FF9800' : '#F44336'
}

function formatValue(value: number, unit: string): string {
  if (unit === 'percent') return `${value}%`
  if (unit === 'numeric') return value.toFixed(1)
  return String(Math.round(value))
}

// ── Sparkline ─────────────────────────────────────────────────────────────────

function Sparkline({ name, projectId, color }: { name: string; projectId?: string; color: string }) {
  const { data } = useQuery({
    queryKey: ['metric-history', name, projectId],
    queryFn: () => metricsApi.get(name, { project_id: projectId, days: 30 }),
  })

  if (!data?.history?.length) {
    return (
      <Typography variant="caption" sx={{ fontSize: '0.6rem', color: 'text.disabled' }}>
        No trend yet
      </Typography>
    )
  }

  return (
    <ResponsiveContainer width="100%" height={32}>
      <LineChart data={data.history}>
        <Line
          type="monotone"
          dataKey="value"
          stroke={color}
          strokeWidth={1.5}
          dot={false}
          isAnimationActive={false}
        />
        <ChartTooltip
          contentStyle={{ background: '#1a1a2e', border: 'none', fontSize: '0.65rem', padding: '2px 6px' }}
          labelFormatter={(l) => l}
          formatter={(v: number) => [v, '']}
        />
      </LineChart>
    </ResponsiveContainer>
  )
}

// ── Metric card ───────────────────────────────────────────────────────────────

function MetricCard({ metric, projectId }: { metric: MetricResult; projectId?: string }) {
  const color = metricColor(metric.name, metric.value, metric.unit)
  const icon = METRIC_ICON[metric.name]

  return (
    <Box sx={{
      border: '1px solid', borderColor: `${color}25`,
      borderRadius: 2, p: 2,
      bgcolor: `${color}06`,
      display: 'flex', flexDirection: 'column', gap: 1,
    }}>
      {/* Header */}
      <Box sx={{ display: 'flex', alignItems: 'flex-start', gap: 1 }}>
        <Box sx={{ color, mt: 0.25, flexShrink: 0 }}>{icon}</Box>
        <Box sx={{ flex: 1, minWidth: 0 }}>
          <Typography variant="caption" sx={{ fontSize: '0.68rem', color: 'text.secondary', lineHeight: 1.2, display: 'block' }}>
            {metric.label}
          </Typography>
          <Typography variant="h5" sx={{ fontWeight: 700, color, lineHeight: 1.1, fontSize: '1.6rem', mt: 0.25 }}>
            {formatValue(metric.value, metric.unit)}
          </Typography>
        </Box>
      </Box>

      {/* Sparkline */}
      <Sparkline name={metric.name} projectId={projectId} color={color} />
    </Box>
  )
}

// ── Audit readiness hero ──────────────────────────────────────────────────────

function AuditReadinessHero({ value, loading }: { value?: number; loading: boolean }) {
  const color = value !== undefined ? metricColor('audit_readiness', value, 'percent') : '#607D8B'
  return (
    <Box sx={{
      border: `1px solid ${color}40`, borderRadius: 2, p: 2.5, mb: 2.5,
      bgcolor: `${color}08`, display: 'flex', alignItems: 'center', gap: 3,
    }}>
      <InsightsOutlined sx={{ fontSize: 36, color, flexShrink: 0 }} />
      <Box>
        <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '0.75rem', textTransform: 'uppercase', letterSpacing: '0.08em' }}>
          Audit Readiness Score
        </Typography>
        {loading
          ? <Skeleton width={80} height={48} />
          : <Typography variant="h3" sx={{ fontWeight: 800, color, lineHeight: 1, fontSize: '2.8rem' }}>
              {value ?? '—'}{value !== undefined && '%'}
            </Typography>
        }
        <Typography variant="caption" sx={{ color: 'text.disabled', fontSize: '0.68rem' }}>
          Composite of compliance, policy coverage, evidence freshness, open risks &amp; gaps
        </Typography>
      </Box>
    </Box>
  )
}

// ── Portfolio table ───────────────────────────────────────────────────────────

const PORTFOLIO_COLS: { key: string; label: string; unit: string }[] = [
  { key: 'audit_readiness',    label: 'Audit Readiness',     unit: 'percent' },
  { key: 'compliance_score',   label: 'Compliance Score',    unit: 'percent' },
  { key: 'risk_score_avg',     label: 'Risk Score',          unit: 'numeric' },
  { key: 'gap_open_count',     label: 'Open Gaps',           unit: 'count'   },
  { key: 'remediation_overdue',label: 'Remediation Overdue', unit: 'count'   },
]

function PortfolioTab() {
  const { data, isLoading, error } = useQuery<OrgMetricRow[]>({
    queryKey: ['metrics-portfolio'],
    queryFn: metricsApi.portfolio,
    retry: false,
  })

  if (error) {
    return <Alert severity="warning" sx={{ mt: 2 }}>Portfolio data unavailable.</Alert>
  }

  const sorted = [...(data ?? [])].sort((a, b) => {
    const av = a.metrics['audit_readiness'] ?? -1
    const bv = b.metrics['audit_readiness'] ?? -1
    return bv - av
  })

  return (
    <Box sx={{ mt: 2, overflowX: 'auto' }}>
      <Table size="small">
        <TableHead>
          <TableRow>
            <TableCell sx={{ fontWeight: 600, color: 'text.secondary', fontSize: '0.72rem', textTransform: 'uppercase', letterSpacing: '0.06em' }}>
              Organisation
            </TableCell>
            {PORTFOLIO_COLS.map(col => (
              <TableCell key={col.key} align="right" sx={{ fontWeight: 600, color: 'text.secondary', fontSize: '0.72rem', textTransform: 'uppercase', letterSpacing: '0.06em' }}>
                {col.label}
              </TableCell>
            ))}
          </TableRow>
        </TableHead>
        <TableBody>
          {isLoading
            ? Array.from({ length: 4 }).map((_, i) => (
                <TableRow key={i}>
                  <TableCell><Skeleton width={160} /></TableCell>
                  {PORTFOLIO_COLS.map(col => (
                    <TableCell key={col.key} align="right"><Skeleton width={48} /></TableCell>
                  ))}
                </TableRow>
              ))
            : sorted.map(row => (
                <TableRow key={row.org_id} hover>
                  <TableCell sx={{ fontWeight: 500 }}>{row.org_name}</TableCell>
                  {PORTFOLIO_COLS.map(col => {
                    const val = row.metrics[col.key]
                    if (val === undefined) {
                      return (
                        <TableCell key={col.key} align="right" sx={{ color: 'text.disabled' }}>—</TableCell>
                      )
                    }
                    const color = metricColor(col.key, val, col.unit)
                    return (
                      <TableCell key={col.key} align="right" sx={{ color, fontWeight: 600 }}>
                        {formatValue(val, col.unit)}
                      </TableCell>
                    )
                  })}
                </TableRow>
              ))
          }
        </TableBody>
      </Table>
    </Box>
  )
}

// ── Main page ─────────────────────────────────────────────────────────────────

const OTHER_METRICS = [
  'compliance_score', 'policy_coverage', 'risk_score_avg', 'risk_critical_count',
  'evidence_freshness', 'gap_open_count', 'gap_closure_rate', 'remediation_overdue',
]

export default function Metrics() {
  const { activeProject } = useProject()
  const { user } = useAuth()
  const [projectId, setProjectId] = useState(activeProject?.id ?? '')
  const [tab, setTab] = useState(0)
  const qc = useQueryClient()
  const isSuperAdmin = user?.role === 'super_admin'

  const { data: projects } = useQuery({
    queryKey: ['projects-list'],
    queryFn: () => projectsApi.list(),
  })

  const { data, isLoading, error } = useQuery({
    queryKey: ['metrics', projectId],
    queryFn: () => metricsApi.list({ project_id: projectId || undefined }),
    enabled: tab === 0,
  })

  const byName = Object.fromEntries((data ?? []).map(m => [m.name, m]))
  const auditReadiness = byName['audit_readiness']
  const others = OTHER_METRICS.map(n => byName[n]).filter(Boolean)

  return (
    <Box sx={{ p: 3 }}>
      <PageHeader
        title="KPI Dashboard"
        subtitle="ISO 27001:2022 §9.1 — performance evaluation and measurement"
        actions={
          tab === 0
            ? (
              <Box sx={{ display: 'flex', gap: 1, alignItems: 'center' }}>
                <Tooltip title="Recompute metrics now">
                  <IconButton size="small" onClick={() => qc.invalidateQueries({ queryKey: ['metrics'], exact: false })}>
                    <RefreshOutlined sx={{ fontSize: 18 }} />
                  </IconButton>
                </Tooltip>
                <FormControl size="small" sx={{ minWidth: 240 }}>
                  <InputLabel>Scope</InputLabel>
                  <Select value={projectId} label="Scope" onChange={e => setProjectId(e.target.value)}>
                    <MenuItem value="">Org-wide</MenuItem>
                    {(projects ?? []).map((p: ProjectRead) => (
                      <MenuItem key={p.id} value={p.id}>{p.name}</MenuItem>
                    ))}
                  </Select>
                </FormControl>
              </Box>
            )
            : (
              <Tooltip title="Refresh portfolio">
                <IconButton size="small" onClick={() => qc.invalidateQueries({ queryKey: ['metrics-portfolio'] })}>
                  <RefreshOutlined sx={{ fontSize: 18 }} />
                </IconButton>
              </Tooltip>
            )
        }
      />

      {/* Tab bar — only shown to super_admin */}
      {isSuperAdmin && (
        <Tabs
          value={tab}
          onChange={(_, v) => setTab(v)}
          sx={{ mb: 2.5, borderBottom: '1px solid', borderColor: 'divider' }}
          textColor="primary"
          indicatorColor="primary"
        >
          <Tab label="My Metrics" />
          <Tab label="Portfolio" />
        </Tabs>
      )}

      {/* ── My Metrics tab ── */}
      {tab === 0 && (
        <>
          {error && <Alert severity="error" sx={{ mb: 2 }}>Failed to load metrics.</Alert>}

          {/* Audit readiness hero */}
          {isLoading
            ? <AuditReadinessHero loading />
            : <AuditReadinessHero value={auditReadiness?.value} loading={false} />
          }

          {/* KPI grid */}
          <Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))', gap: 2 }}>
            {isLoading
              ? Array.from({ length: 8 }).map((_, i) => (
                  <Box key={i} sx={{ border: '1px solid', borderColor: 'divider', borderRadius: 2, p: 2 }}>
                    <Skeleton height={20} width="60%" sx={{ mb: 1 }} />
                    <Skeleton height={40} width="40%" sx={{ mb: 1 }} />
                    <Skeleton height={32} />
                  </Box>
                ))
              : others.map(m => (
                  <Tooltip
                    key={m.name}
                    title={`Computed at ${new Date(m.computed_at).toLocaleString()}`}
                    placement="top"
                  >
                    <span>
                      <MetricCard metric={m} projectId={projectId || undefined} />
                    </span>
                  </Tooltip>
                ))
            }
          </Box>
        </>
      )}

      {/* ── Portfolio tab ── */}
      {tab === 1 && isSuperAdmin && <PortfolioTab />}
    </Box>
  )
}
