// isms-core-platform/frontend-angular/src/app/pages/mitre-heatmap/mitre-heatmap.component.ts
import { Component, inject, signal, computed } from '@angular/core'
import { CommonModule } from '@angular/common'
import { FormsModule } from '@angular/forms'
import { firstValueFrom } from 'rxjs'

import { injectQuery } from '@tanstack/angular-query-experimental'

import { MatTableModule } from '@angular/material/table'
import { MatChipsModule } from '@angular/material/chips'
import { MatTooltipModule } from '@angular/material/tooltip'
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner'
import { MatFormFieldModule } from '@angular/material/form-field'
import { MatInputModule } from '@angular/material/input'
import { MatSelectModule } from '@angular/material/select'
import { MatIconModule } from '@angular/material/icon'
import { MatButtonToggleModule } from '@angular/material/button-toggle'
import { MatSlideToggleModule } from '@angular/material/slide-toggle'

import { FeedsApiService, MitreGroup, MitreHeatmapTechnique } from '../../api/feeds-api.service'
import { ThemeService } from '../../core/services/theme.service'

const INTEL_DARK  = '#FFA726'
const INTEL_LIGHT = '#E65100'

const TACTIC_LABELS: Record<string, string> = {
  'reconnaissance':       'Reconnaissance',
  'resource-development': 'Resource Dev.',
  'initial-access':       'Initial Access',
  'execution':            'Execution',
  'persistence':          'Persistence',
  'privilege-escalation': 'Priv. Escalation',
  'defense-evasion':      'Stealth',
  'defense-impairment':   'Defense Impairment',
  'credential-access':    'Credential Access',
  'discovery':            'Discovery',
  'lateral-movement':     'Lateral Movement',
  'collection':           'Collection',
  'command-and-control':  'C2',
  'exfiltration':         'Exfiltration',
  'impact':               'Impact',
}

function cellBg(count: number, max: number, isDark: boolean): string {
  if (count === 0) return 'transparent'
  const ratio = Math.min(count / Math.max(max, 1), 1)
  if (isDark) {
    if (ratio < 0.1)  return '#FFE0C8'
    if (ratio < 0.25) return '#FFBC8A'
    if (ratio < 0.5)  return '#F09050'
    if (ratio < 0.75) return '#D06020'
    return INTEL_DARK
  } else {
    if (ratio < 0.1)  return '#FFD1A0'
    if (ratio < 0.25) return '#FFAB5A'
    if (ratio < 0.5)  return '#E07030'
    if (ratio < 0.75) return '#B05010'
    return INTEL_LIGHT
  }
}

function cellFg(count: number, max: number): string {
  const ratio = Math.min(count / Math.max(max, 1), 1)
  return ratio >= 0.25 ? '#fff' : '#7A3800'
}

const TIER_LABELS: Record<number, string> = { 1: 'Partial', 2: 'Risk Informed', 3: 'Repeatable', 4: 'Adaptive' }

@Component({
  selector: 'app-mitre-heatmap',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatTableModule,
    MatChipsModule,
    MatTooltipModule,
    MatProgressSpinnerModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatIconModule,
    MatButtonToggleModule,
    MatSlideToggleModule,
  ],
  template: `
<div class="page-wrap">

  <!-- Header -->
  <div class="page-header">
    <h2 class="page-title">MITRE ATT&amp;CK Heatmap</h2>
    <p class="page-subtitle">
      Technique coverage by threat actor — click any row to inspect
    </p>
  </div>

  <!-- Controls -->
  <div class="controls-row">
    <mat-button-toggle-group value="attack_v19" class="version-toggle">
      <mat-button-toggle value="attack_v19" class="version-btn">v19</mat-button-toggle>
    </mat-button-toggle-group>

    <!-- Group filter -->
    <mat-form-field appearance="outline" subscriptSizing="dynamic" class="group-filter">
      <mat-label>Filter by group</mat-label>
      <mat-select [ngModel]="selectedGroupIds()" (ngModelChange)="onGroupChange($event)" multiple>
        @for (g of allGroups(); track g.group_id) {
          <mat-option [value]="g.group_id" class="group-option">{{g.group_id}} — {{g.name}}</mat-option>
        }
      </mat-select>
    </mat-form-field>

    <mat-slide-toggle [checked]="includeSoftware()" (change)="includeSoftware.set($event.checked)" class="slide-label">
      Include software
    </mat-slide-toggle>

    <mat-slide-toggle [checked]="showSubs()" (change)="showSubs.set($event.checked)" class="slide-label">
      Sub-techniques
    </mat-slide-toggle>
  </div>

  <!-- Stats bar -->
  @if (heatmapQuery.data(); as hm) {
    <div class="stats-bar">
      <div>
        <div class="stat-value" [style.color]="intelColor">
          {{hm.covered | number}} / {{hm.total_techniques | number}}
        </div>
        <div class="stat-label">Techniques covered ({{coveragePct()}}%)</div>
      </div>
      <div>
        <div class="stat-value" [style.color]="intelColor">{{hm.selected_actors | number}}</div>
        <div class="stat-label">{{selectedGroupIds().length > 0 ? 'Selected actors' : 'Actors in scope'}}</div>
      </div>
      <div>
        <div class="stat-value" [style.color]="intelColor">{{maxCount()}}</div>
        <div class="stat-label">Max actors / technique</div>
      </div>

      <!-- Color legend -->
      <div class="legend-row">
        <span class="legend-label legend-label-left">Coverage:</span>
        @for (swatch of legendSwatches(); track $index) {
          <div [matTooltip]="swatch.label" class="legend-swatch"
            [style.background]="swatch.bg"></div>
        }
        <span class="legend-label legend-label-right">High</span>
      </div>
    </div>
  }

  @if (heatmapQuery.isLoading()) {
    <div class="spinner-center">
      <mat-spinner [diameter]="32" />
    </div>
  }

  @if (heatmapQuery.isError()) {
    <div class="error-msg">Failed to load heatmap data.</div>
  }

  <!-- Heatmap table view + detail panel -->
  @if (!heatmapQuery.isLoading() && heatmapQuery.data(); as hm) {
    <div class="content-row">

      <!-- Tactic/technique table -->
      <div class="table-panel">
        <table mat-table [dataSource]="tableRows()" class="full-width">

          <ng-container matColumnDef="tactic">
            <th mat-header-cell *matHeaderCellDef class="col-hdr col-tactic">Tactic</th>
            <td mat-cell *matCellDef="let row" class="cell-tactic">
              {{tacticLabel(row.tactic)}}</td>
          </ng-container>

          <ng-container matColumnDef="technique_id">
            <th mat-header-cell *matHeaderCellDef class="col-hdr col-technique-id">Technique</th>
            <td mat-cell *matCellDef="let row" class="cell-technique-id"
              [style.color]="intelColor"
              [style.paddingLeft]="row.tech.is_subtechnique ? '24px' : ''">
              {{row.tech.technique_id}}</td>
          </ng-container>

          <ng-container matColumnDef="name">
            <th mat-header-cell *matHeaderCellDef class="col-hdr">Name</th>
            <td mat-cell *matCellDef="let row" class="cell-name">
              {{row.tech.name}}</td>
          </ng-container>

          <ng-container matColumnDef="usage">
            <th mat-header-cell *matHeaderCellDef class="col-hdr col-actors">Actors</th>
            <td mat-cell *matCellDef="let row" class="col-actors">
              <div class="usage-cell">
                <div class="bar-track">
                  <div class="bar-fill"
                    [style.width]="barWidth(row.tech.usage_count) + '%'"
                    [style.background]="cellBg(row.tech.usage_count, maxCount())"></div>
                </div>
                <span class="bar-count"
                  [style.color]="row.tech.usage_count > 0 ? intelColor : '#bbb'">
                  {{row.tech.usage_count}}
                </span>
              </div>
            </td>
          </ng-container>

          <tr mat-header-row *matHeaderRowDef="displayedColumns" class="hdr-row"></tr>
          <tr mat-row *matRowDef="let row; columns: displayedColumns"
            class="data-row"
            [style.background]="selectedTech()?.stix_id === row.tech.stix_id ? 'rgba(184,79,0,0.08)' : ''"
            (click)="onTechClick(row.tech)"></tr>
        </table>
      </div>

      <!-- Detail panel -->
      @if (selectedTech(); as tech) {
        <div class="detail-panel">
          <div class="detail-id-row">
            <div class="detail-tech-id" [style.color]="intelColor">{{tech.technique_id}}</div>
            @if (tech.is_subtechnique) {
              <mat-chip class="chip-sub">sub</mat-chip>
            }
          </div>
          <div class="detail-name">{{tech.name}}</div>

          <!-- Tactics -->
          <div class="detail-tactics">
            @for (t of tech.tactics; track t) {
              <mat-chip class="chip-tactic">{{tacticLabel(t)}}</mat-chip>
            }
          </div>

          <!-- Coverage box -->
          <div class="coverage-box" [style.background]="intelColor + '18'">
            <div class="coverage-label">Used by</div>
            <div class="coverage-count" [style.color]="intelColor">{{tech.usage_count}}</div>
            <div class="coverage-label">{{tech.usage_count === 1 ? 'actor' : 'actors'}} in scope</div>
          </div>

          <!-- Actor list -->
          @if (tech.used_by.length > 0) {
            <div>
              <div class="actor-list-hdr">
                Actors ({{tech.used_by.length}}):
              </div>
              @for (name of tech.used_by; track name) {
                <div class="actor-item">· {{name}}</div>
              }
            </div>
          }

          @if (tech.usage_count === 0) {
            <div class="no-actor-msg">Not attributed to any actor in the current scope.</div>
          }
        </div>
      }
    </div>
  }
</div>
  `,
  styles: [`
    .mat-mdc-row:hover { background: rgba(0,0,0,0.04); }

    .page-wrap { padding: 24px; }

    .page-header { margin-bottom: 16px; }
    .page-title { margin: 0; font-size: 1.3rem; font-weight: 700; }
    .page-subtitle { margin: 4px 0 0; color: var(--mat-sys-on-surface-variant); font-size: 0.85rem; }

    .controls-row {
      display: flex; gap: 12px; margin-bottom: 16px;
      align-items: center; flex-wrap: wrap;
    }
    .version-toggle { height: 32px; }
    .version-btn { font-size: 0.72rem; padding: 0 12px; }
    ::ng-deep .version-btn .mat-button-toggle-label-content { display: flex; align-items: center; justify-content: center; gap: 4px; padding: 0; }
    .group-filter { min-width: 280px; }
    .group-option { font-size: 0.8rem; }
    .slide-label { font-size: 0.8rem; }

    .stats-bar {
      display: flex; gap: 24px; margin-bottom: 16px;
      flex-wrap: wrap; align-items: center;
    }
    .stat-value { font-size: 1.25rem; font-weight: 700; line-height: 1; }
    .stat-label { font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); }

    .legend-row { display: flex; align-items: center; gap: 4px; margin-left: auto; }
    .legend-label { font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); }
    .legend-label-left { margin-right: 4px; }
    .legend-label-right { margin-left: 4px; }
    .legend-swatch { width: 20px; height: 14px; border-radius: 2px; border: 1px solid rgba(0,0,0,0.1); }

    .spinner-center { display: flex; justify-content: center; padding: 64px; }
    .error-msg { padding: 16px; color: #d32f2f; font-size: 0.85rem; }

    .content-row { display: flex; gap: 16px; }

    .table-panel {
      flex: 1; min-width: 0;
      border: 1px solid var(--mat-sys-outline-variant); border-radius: 8px; overflow: hidden;
      background: var(--mat-sys-surface-container);
    }
    .full-width { width: 100%; }

    .col-hdr { font-size: 0.72rem; font-weight: 600; }
    .col-tactic { width: 140px; }
    .col-technique-id { width: 110px; }
    .col-actors { width: 100px; }

    .cell-tactic { font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); }
    .cell-technique-id { font-family: monospace; font-size: 0.72rem; font-weight: 600; }
    .cell-name {
      font-size: 0.78rem; max-width: 260px;
      overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
    }

    .usage-cell { display: flex; align-items: center; gap: 6px; }
    .bar-track { width: 56px; height: 10px; border-radius: 2px; overflow: hidden; background: var(--mat-sys-surface-container-high); }
    .bar-fill { height: 100%; border-radius: 2px; transition: width 0.2s; min-width: 3px; }
    .bar-count { font-size: 0.72rem; min-width: 20px; text-align: right; }

    .hdr-row { height: 36px; }
    .data-row { height: 32px; cursor: pointer; }

    .detail-panel {
      width: 300px; flex-shrink: 0;
      border: 1px solid var(--mat-sys-outline-variant); border-radius: 8px;
      padding: 16px; position: sticky; top: 24px;
      max-height: 80vh; overflow-y: auto;
      background: var(--mat-sys-surface-container);
    }
    .detail-id-row { display: flex; align-items: baseline; gap: 8px; margin-bottom: 4px; }
    .detail-tech-id { font-family: monospace; font-size: 0.85rem; font-weight: 700; }
    .chip-sub { font-size: 0.6rem; height: 16px; }
    .detail-name { font-size: 0.88rem; font-weight: 600; margin-bottom: 8px; }

    .detail-tactics { margin-bottom: 12px; }
    .chip-tactic { font-size: 0.62rem; height: 18px; margin: 0 2px 2px 0; }

    .coverage-box { margin-bottom: 12px; padding: 8px; border-radius: 4px; }
    .coverage-label { font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); }
    .coverage-count { font-size: 1.5rem; font-weight: 700; line-height: 1.2; }

    .actor-list-hdr { font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); font-weight: 600; margin-bottom: 4px; }
    .actor-item { font-size: 0.7rem; padding: 1px 0; }
    .no-actor-msg { font-size: 0.72rem; color: #bbb; }
  `],
})
export class MitreHeatmapComponent {
  private feedsApi = inject(FeedsApiService)
  private readonly theme = inject(ThemeService)

  get intelColor() { return this.theme.isDark() ? INTEL_DARK : INTEL_LIGHT }
  readonly displayedColumns = ['tactic', 'technique_id', 'name', 'usage']

  selectedGroupIds = signal<string[]>([])
  includeSoftware = signal(true)
  showSubs = signal(true)
  selectedTech = signal<MitreHeatmapTechnique | null>(null)

  groupsQuery = injectQuery(() => ({
    queryKey: ['feeds', 'groups', 'all', 'attack_v19'],
    queryFn: () => firstValueFrom(this.feedsApi.getMitreGroups({ source: 'attack_v19', deprecated: false, per_page: 200 })),
  }))

  allGroups = computed(() => this.groupsQuery.data()?.items ?? [])

  heatmapQuery = injectQuery(() => ({
    queryKey: ['feeds', 'heatmap', 'attack_v19', this.selectedGroupIds().join(','), this.includeSoftware()],
    queryFn: () => firstValueFrom(this.feedsApi.getMitreHeatmap({
      source: 'attack_v19',
      group_ids: this.selectedGroupIds().length > 0 ? this.selectedGroupIds().join(',') : undefined,
      include_software: this.includeSoftware(),
    })),
    staleTime: 60_000,
  }))

  maxCount = computed(() => {
    const techs = this.heatmapQuery.data()?.techniques ?? []
    return Math.max(...techs.map(t => t.usage_count), 1)
  })

  coveragePct = computed(() => {
    const hm = this.heatmapQuery.data()
    return hm ? Math.round((hm.covered / Math.max(hm.total_techniques, 1)) * 100) : 0
  })

  legendSwatches = computed(() => {
    const max = this.maxCount()
    const isDark = this.theme.isDark()
    return [0, 0.1, 0.3, 0.6, 1].map((ratio, i) => {
      const count = Math.round(ratio * max)
      return {
        bg: cellBg(count, max, isDark),
        label: i === 0 ? 'Not covered' : `${count}+ actors`,
      }
    })
  })

  // Flatten techniques into tactic-indexed rows, respecting showSubs
  tableRows = computed(() => {
    const hm = this.heatmapQuery.data()
    if (!hm) return []
    const showSubs = this.showSubs()
    const rows: { tactic: string; tech: MitreHeatmapTechnique }[] = []
    for (const tac of hm.tactic_order) {
      const inTactic = hm.techniques.filter(t => t.tactics.includes(tac))
      const parents = inTactic.filter(t => !t.is_subtechnique)
        .sort((a, b) => a.technique_id.localeCompare(b.technique_id))
      if (showSubs) {
        const subs = inTactic.filter(t => t.is_subtechnique)
        for (const p of parents) {
          rows.push({ tactic: tac, tech: p })
          const mySubs = subs.filter(s => s.technique_id.startsWith(p.technique_id + '.'))
            .sort((a, b) => a.technique_id.localeCompare(b.technique_id))
          for (const s of mySubs) rows.push({ tactic: tac, tech: s })
        }
      } else {
        for (const p of parents) rows.push({ tactic: tac, tech: p })
      }
    }
    return rows
  })

  tacticLabel(tac: string): string {
    return TACTIC_LABELS[tac] ?? tac
  }

  cellBg(count: number, max: number): string {
    return cellBg(count, max, this.theme.isDark())
  }

  barWidth(count: number): number {
    return Math.round((count / Math.max(this.maxCount(), 1)) * 100)
  }

  onGroupChange(ids: string[]) {
    this.selectedGroupIds.set(ids)
    this.selectedTech.set(null)
  }

  onTechClick(tech: MitreHeatmapTechnique) {
    this.selectedTech.set(this.selectedTech()?.stix_id === tech.stix_id ? null : tech)
  }
}

// isms-core-platform/frontend/src/pages/MitreHeatmap.tsx
import { useMemo, useState } from 'react'
import {
  Alert, Autocomplete, Box, Chip, CircularProgress, FormControlLabel,
  Paper, Switch, TextField, ToggleButton, ToggleButtonGroup, Tooltip, Typography,
} from '@mui/material'
import { useQuery } from '@tanstack/react-query'
import { feedsApi, type MitreGroup, type MitreHeatmapTechnique } from '../api/feedsApi'
import PageHeader from '../components/PageHeader'

const INTEL_COLOR = '#B84F00'
const CELL_W = 128
const CELL_H = 20

// Canonical tactic display labels
const TACTIC_LABELS: Record<string, string> = {
  'reconnaissance':       'Reconnaissance',
  'resource-development': 'Resource Dev.',
  'initial-access':       'Initial Access',
  'execution':            'Execution',
  'persistence':          'Persistence',
  'privilege-escalation': 'Priv. Escalation',
  'defense-evasion':      'Stealth',
  'defense-impairment':   'Defense Impairment',
  'credential-access':    'Credential Access',
  'discovery':            'Discovery',
  'lateral-movement':     'Lateral Movement',
  'collection':           'Collection',
  'command-and-control':  'C2',
  'exfiltration':         'Exfiltration',
  'impact':               'Impact',
}

// 5-level color ramp (0 = uncovered)
function cellBg(count: number, max: number): string {
  if (count === 0) return 'transparent'
  const ratio = Math.min(count / Math.max(max, 1), 1)
  if (ratio < 0.1) return '#FFE0C8'
  if (ratio < 0.25) return '#FFBC8A'
  if (ratio < 0.5)  return '#F09050'
  if (ratio < 0.75) return '#D06020'
  return INTEL_COLOR
}

function cellTextColor(count: number, max: number): string {
  const ratio = Math.min(count / Math.max(max, 1), 1)
  if (ratio >= 0.25) return '#fff'    // medium-dark backgrounds → white
  return '#7A3800'                    // pale peach/light orange → dark brown
}

// Build per-tactic rows: parents first, then subs grouped under their parent
function buildTacticRows(
  techniques: MitreHeatmapTechnique[],
  tactic: string,
  showSubs: boolean,
): MitreHeatmapTechnique[] {
  const inTactic = techniques.filter(t => t.tactics.includes(tactic))
  const parents = inTactic
    .filter(t => !t.is_subtechnique)
    .sort((a, b) => a.technique_id.localeCompare(b.technique_id))

  if (!showSubs) return parents

  const subs = inTactic.filter(t => t.is_subtechnique)
  const rows: MitreHeatmapTechnique[] = []
  for (const p of parents) {
    rows.push(p)
    const mySubs = subs
      .filter(s => s.technique_id.startsWith(p.technique_id + '.'))
      .sort((a, b) => a.technique_id.localeCompare(b.technique_id))
    rows.push(...mySubs)
  }
  return rows
}

interface TechCellProps {
  tech: MitreHeatmapTechnique
  maxCount: number
  selected: boolean
  onSelect: (t: MitreHeatmapTechnique) => void
}

function TechCell({ tech, maxCount, selected, onSelect }: TechCellProps) {
  const bg = cellBg(tech.usage_count, maxCount)
  const fg = tech.usage_count > 0 ? cellTextColor(tech.usage_count, maxCount) : 'text.disabled'
  const isSub = tech.is_subtechnique

  return (
    <Tooltip
      title={`${tech.technique_id} — ${tech.name}${tech.usage_count > 0 ? ` (${tech.usage_count} actor${tech.usage_count !== 1 ? 's' : ''})` : ''}`}
      placement="right"
      arrow
    >
      <Box
        onClick={() => onSelect(tech)}
        sx={{
          width: CELL_W,
          height: CELL_H,
          px: 0.5,
          display: 'flex',
          alignItems: 'center',
          cursor: 'pointer',
          backgroundColor: bg,
          borderRadius: '2px',
          mb: '1px',
          border: selected ? `1.5px solid ${INTEL_COLOR}` : '1px solid',
          borderColor: selected ? INTEL_COLOR : tech.usage_count > 0 ? 'transparent' : 'divider',
          pl: isSub ? 1.5 : 0.5,
          '&:hover': { opacity: 0.8, borderColor: INTEL_COLOR },
        }}
      >
        <Typography
          noWrap
          sx={{
            fontSize: isSub ? '0.6rem' : '0.63rem',
            fontWeight: isSub ? 400 : 600,
            color: tech.usage_count > 0 ? fg : 'text.disabled',
            fontFamily: 'monospace',
            lineHeight: 1,
          }}
        >
          {tech.technique_id}
        </Typography>
      </Box>
    </Tooltip>
  )
}

export default function MitreHeatmap() {
  const [source] = useState<'attack_v19'>('attack_v19')
  const [selectedGroups, setSelectedGroups] = useState<MitreGroup[]>([])
  const [includeSoftware, setIncludeSoftware] = useState(true)
  const [showSubs, setShowSubs] = useState(true)
  const [selected, setSelected] = useState<MitreHeatmapTechnique | null>(null)

  // Load all groups for the autocomplete
  const { data: groupData } = useQuery({
    queryKey: ['feeds', 'groups', 'all', source],
    queryFn: () => feedsApi.getMitreGroups({ source, deprecated: false, per_page: 200 }),
  })
  const allGroups = groupData?.items ?? []

  const groupIdsParam = selectedGroups.length > 0
    ? selectedGroups.map(g => g.group_id).join(',')
    : undefined

  const { data, isLoading, error } = useQuery({
    queryKey: ['feeds', 'heatmap', source, groupIdsParam ?? 'all', includeSoftware],
    queryFn: () => feedsApi.getMitreHeatmap({
      source,
      group_ids: groupIdsParam,
      include_software: includeSoftware,
    }),
    staleTime: 60_000,
  })

  const tactics = data?.tactic_order ?? []
  const techniques = data?.techniques ?? []

  // Max usage_count across all techniques — for color scaling
  const maxCount = useMemo(
    () => Math.max(...techniques.map(t => t.usage_count), 1),
    [techniques],
  )

  // Per-tactic rows (memoised)
  const tacticRows = useMemo(() => {
    const map: Record<string, MitreHeatmapTechnique[]> = {}
    for (const tac of tactics) {
      map[tac] = buildTacticRows(techniques, tac, showSubs)
    }
    return map
  }, [tactics, techniques, showSubs])

  function handleSelect(tech: MitreHeatmapTechnique) {
    setSelected(prev => prev?.stix_id === tech.stix_id ? null : tech)
  }

  const coveragePct = data
    ? Math.round((data.covered / Math.max(data.total_techniques, 1)) * 100)
    : 0

  return (
    <Box sx={{ p: 3 }}>
      <PageHeader
        title="MITRE ATT&CK Heatmap"
        subtitle="Technique coverage by threat actor group — click any technique to inspect"
        helpSection="mitre-attack"
      />

      {/* ── Controls ── */}
      <Box sx={{ display: 'flex', gap: 1.5, mb: 2, flexWrap: 'wrap', alignItems: 'center' }}>
        <ToggleButtonGroup
          size="small"
          value={source}
          exclusive
          onChange={(_, v) => v && (setSource(v), setSelected(null))}
        >
          <ToggleButton value="attack_v19" sx={{ fontSize: '0.72rem', px: 1.5 }}>v19</ToggleButton>
        </ToggleButtonGroup>

        <Autocomplete
          multiple
          size="small"
          options={allGroups}
          value={selectedGroups}
          onChange={(_, v) => { setSelectedGroups(v); setSelected(null) }}
          getOptionLabel={g => `${g.group_id} — ${g.name}`}
          isOptionEqualToValue={(a, b) => a.group_id === b.group_id}
          renderInput={params => (
            <TextField
              {...params}
              placeholder={selectedGroups.length === 0 ? 'All groups (aggregate view)' : ''}
              sx={{ minWidth: 340 }}
            />
          )}
          renderTags={(value, getTagProps) =>
            value.map((g, i) => (
              <Chip
                {...getTagProps({ index: i })}
                key={g.group_id}
                label={g.group_id}
                size="small"
                sx={{ fontSize: '0.65rem', height: 18 }}
              />
            ))
          }
          sx={{ minWidth: 340 }}
          limitTags={4}
        />

        <FormControlLabel
          control={
            <Switch
              size="small"
              checked={includeSoftware}
              onChange={e => setIncludeSoftware(e.target.checked)}
            />
          }
          label={<Typography variant="caption">Include software</Typography>}
        />

        <FormControlLabel
          control={
            <Switch
              size="small"
              checked={showSubs}
              onChange={e => setShowSubs(e.target.checked)}
            />
          }
          label={<Typography variant="caption">Sub-techniques</Typography>}
        />
      </Box>

      {/* ── Stats bar ── */}
      {data && (
        <Box sx={{ display: 'flex', gap: 3, mb: 2, flexWrap: 'wrap', alignItems: 'center' }}>
          <Box>
            <Typography variant="h6" sx={{ fontWeight: 700, color: INTEL_COLOR, lineHeight: 1 }}>
              {data.covered.toLocaleString()} / {data.total_techniques.toLocaleString()}
            </Typography>
            <Typography variant="caption" color="text.secondary">Techniques covered ({coveragePct}%)</Typography>
          </Box>
          <Box>
            <Typography variant="h6" sx={{ fontWeight: 700, color: INTEL_COLOR, lineHeight: 1 }}>
              {data.selected_actors.toLocaleString()}
            </Typography>
            <Typography variant="caption" color="text.secondary">
              {selectedGroups.length > 0 ? 'Selected actors' : `Actors in scope${includeSoftware ? ' (groups + software)' : ''}`}
            </Typography>
          </Box>
          <Box>
            <Typography variant="h6" sx={{ fontWeight: 700, color: INTEL_COLOR, lineHeight: 1 }}>
              {maxCount}
            </Typography>
            <Typography variant="caption" color="text.secondary">Max actors / technique</Typography>
          </Box>

          {/* Color legend */}
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5, ml: 'auto' }}>
            <Typography variant="caption" color="text.secondary" sx={{ mr: 0.5 }}>Coverage:</Typography>
            {[0, 0.1, 0.3, 0.6, 1].map((ratio, i) => (
              <Tooltip key={i} title={i === 0 ? 'Not covered' : `${Math.round(ratio * maxCount)}+ actors`}>
                <Box sx={{
                  width: 20, height: 14, borderRadius: '2px',
                  backgroundColor: cellBg(Math.round(ratio * maxCount), maxCount),
                  border: '1px solid', borderColor: 'divider',
                }} />
              </Tooltip>
            ))}
            <Typography variant="caption" color="text.secondary" sx={{ ml: 0.5 }}>High</Typography>
          </Box>
        </Box>
      )}

      {isLoading && (
        <Box sx={{ display: 'flex', justifyContent: 'center', py: 8 }}>
          <CircularProgress size={32} />
        </Box>
      )}
      {error && <Alert severity="error" sx={{ mb: 2 }}>Failed to load heatmap data</Alert>}

      {/* ── Main heatmap + detail panel ── */}
      {data && !isLoading && (
        <Box sx={{ display: 'flex', gap: 2, alignItems: 'flex-start' }}>
          {/* Heatmap grid — horizontally scrollable */}
          <Box sx={{ overflowX: 'auto', flex: 1, minWidth: 0 }}>
            <Box sx={{ display: 'flex', gap: '2px', minWidth: tactics.length * (CELL_W + 2) }}>
              {tactics.map(tac => {
                const rows = tacticRows[tac] ?? []
                return (
                  <Box key={tac} sx={{ width: CELL_W, flexShrink: 0 }}>
                    {/* Tactic header */}
                    <Box sx={{
                      height: 32,
                      display: 'flex',
                      alignItems: 'center',
                      px: 0.5,
                      mb: 0.5,
                      backgroundColor: 'action.hover',
                      borderRadius: '4px 4px 0 0',
                      borderBottom: `2px solid ${INTEL_COLOR}`,
                    }}>
                      <Typography sx={{ fontSize: '0.65rem', fontWeight: 700, color: INTEL_COLOR, lineHeight: 1.1 }}>
                        {TACTIC_LABELS[tac] ?? tac}
                      </Typography>
                    </Box>

                    {/* Technique cells */}
                    {rows.map(tech => (
                      <TechCell
                        key={`${tac}-${tech.stix_id}`}
                        tech={tech}
                        maxCount={maxCount}
                        selected={selected?.stix_id === tech.stix_id}
                        onSelect={handleSelect}
                      />
                    ))}

                    {rows.length === 0 && (
                      <Typography variant="caption" color="text.disabled" sx={{ px: 0.5, fontSize: '0.6rem' }}>
                        No data
                      </Typography>
                    )}
                  </Box>
                )
              })}
            </Box>
          </Box>

          {/* ── Detail panel ── */}
          {selected && (
            <Paper variant="outlined" sx={{ width: 300, flexShrink: 0, borderRadius: 2, p: 2, position: 'sticky', top: 24, maxHeight: '80vh', overflowY: 'auto' }}>
              <Box sx={{ display: 'flex', alignItems: 'baseline', gap: 1, mb: 0.5 }}>
                <Typography variant="subtitle2" sx={{ fontFamily: 'monospace', color: INTEL_COLOR, fontWeight: 700 }}>
                  {selected.technique_id}
                </Typography>
                {selected.is_subtechnique && (
                  <Chip label="sub" size="small" sx={{ fontSize: '0.6rem', height: 16 }} />
                )}
              </Box>
              <Typography variant="body2" fontWeight={600} sx={{ mb: 1 }}>{selected.name}</Typography>

              {/* Tactics */}
              <Box sx={{ mb: 1.5 }}>
                {selected.tactics.map(t => (
                  <Chip
                    key={t}
                    label={TACTIC_LABELS[t] ?? t}
                    size="small"
                    sx={{ fontSize: '0.62rem', height: 18, mr: 0.25, mb: 0.25 }}
                  />
                ))}
              </Box>

              {/* Coverage */}
              <Box sx={{ mb: 1.5, p: 1, backgroundColor: `${INTEL_COLOR}18`, borderRadius: 1 }}>
                <Typography variant="caption" display="block" color="text.secondary">
                  Used by
                </Typography>
                <Typography variant="h6" sx={{ fontWeight: 700, color: INTEL_COLOR, lineHeight: 1.2 }}>
                  {selected.usage_count}
                </Typography>
                <Typography variant="caption" color="text.secondary">
                  {selected.usage_count === 1 ? 'actor' : 'actors'} in scope
                </Typography>
              </Box>

              {/* Actor list */}
              {selected.used_by.length > 0 && (
                <Box>
                  <Typography variant="caption" color="text.secondary" display="block" sx={{ mb: 0.5, fontWeight: 600 }}>
                    Actors ({selected.used_by.length}{selected.usage_count > 30 ? '+' : ''}):
                  </Typography>
                  {selected.used_by.map(name => (
                    <Typography
                      key={name}
                      variant="caption"
                      display="block"
                      sx={{ fontSize: '0.7rem', py: 0.1, color: 'text.primary' }}
                    >
                      · {name}
                    </Typography>
                  ))}
                </Box>
              )}

              {selected.usage_count === 0 && (
                <Typography variant="caption" color="text.disabled">
                  Not attributed to any actor in the current scope.
                </Typography>
              )}
            </Paper>
          )}
        </Box>
      )}
    </Box>
  )
}
