// isms-core-platform/frontend-angular/src/app/pages/mitre-campaigns/mitre-campaigns.component.ts
import { Component, inject, signal, computed } from '@angular/core'
import { CommonModule } from '@angular/common'
import { FormsModule } from '@angular/forms'
import { firstValueFrom } from 'rxjs'

import { injectQuery } from '@tanstack/angular-query-experimental'

import { MatTableModule } from '@angular/material/table'
import { MatChipsModule } from '@angular/material/chips'
import { MatTooltipModule } from '@angular/material/tooltip'
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner'
import { MatFormFieldModule } from '@angular/material/form-field'
import { MatInputModule } from '@angular/material/input'
import { MatIconModule } from '@angular/material/icon'
import { MatButtonToggleModule } from '@angular/material/button-toggle'

import { FeedsApiService, MitreCampaign } from '../../api/feeds-api.service'

const PER_PAGE = 50
const INTEL_COLOR = '#FFA726'

@Component({
  selector: 'app-mitre-campaigns',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatTableModule,
    MatChipsModule,
    MatTooltipModule,
    MatProgressSpinnerModule,
    MatFormFieldModule,
    MatInputModule,
    MatIconModule,
    MatButtonToggleModule,
  ],
  template: `
<div class="page-wrap">

  <!-- Header -->
  <div class="page-header">
    <h2 class="page-title">MITRE ATT&amp;CK Campaigns</h2>
    <p class="page-subtitle">
      Targeted intrusion activity clusters — time-bound adversary operations
    </p>
  </div>

  <!-- Total pill -->
  @if (listQuery.data(); as data) {
    <div class="stats-bar">
      <div>
        <div class="stat-value" [style.color]="INTEL_COLOR">{{data.total | number}}</div>
        <div class="stat-label">Campaigns</div>
      </div>
    </div>
  }

  <!-- Filters -->
  <div class="controls-row">
    <mat-button-toggle-group value="attack_v19" class="version-toggle">
      <mat-button-toggle value="attack_v19" class="version-btn">v19</mat-button-toggle>
    </mat-button-toggle-group>

    <mat-form-field appearance="outline" subscriptSizing="dynamic" class="search-field">
      <mat-label>Search</mat-label>
      <mat-icon matPrefix class="search-prefix-icon">search</mat-icon>
      <input matInput [ngModel]="search()" (ngModelChange)="onSearch($event)" placeholder="Search by ID or name…" />
    </mat-form-field>
  </div>

  <!-- Table + detail panel -->
  <div class="content-row">

    <!-- Table panel -->
    <div class="table-panel">

      @if (listQuery.isLoading()) {
        <div class="spinner-center">
          <mat-spinner [diameter]="28" />
        </div>
      }

      @if (listQuery.isError()) {
        <div class="error-msg">Failed to load campaigns.</div>
      }

      @if (!listQuery.isLoading() && listQuery.data()?.total === 0) {
        <div class="empty-msg">
          ATT&amp;CK v19 data not yet available. Check back after the scheduled weekly pull.
        </div>
      }

      @if (!listQuery.isLoading() && (listQuery.data()?.items?.length ?? 0) > 0) {
        <table mat-table [dataSource]="listQuery.data()!.items" class="full-width">

          <ng-container matColumnDef="campaign_id">
            <th mat-header-cell *matHeaderCellDef class="col-hdr col-campaign-id">ID</th>
            <td mat-cell *matCellDef="let c" class="cell-id"
              [style.color]="INTEL_COLOR">{{c.campaign_id}}</td>
          </ng-container>

          <ng-container matColumnDef="name">
            <th mat-header-cell *matHeaderCellDef class="col-hdr">Name</th>
            <td mat-cell *matCellDef="let c" class="cell-name">
              {{c.name}}</td>
          </ng-container>

          <ng-container matColumnDef="first_seen">
            <th mat-header-cell *matHeaderCellDef class="col-hdr col-date">First Seen</th>
            <td mat-cell *matCellDef="let c" class="cell-date">
              {{c.first_seen ?? '—'}}</td>
          </ng-container>

          <ng-container matColumnDef="last_seen">
            <th mat-header-cell *matHeaderCellDef class="col-hdr col-date">Last Seen</th>
            <td mat-cell *matCellDef="let c" class="cell-date">
              {{c.last_seen ?? '—'}}</td>
          </ng-container>

          <ng-container matColumnDef="aliases">
            <th mat-header-cell *matHeaderCellDef class="col-hdr">Aliases</th>
            <td mat-cell *matCellDef="let c" class="col-aliases">
              @if (c.aliases.length > 0) {
                @for (a of c.aliases.slice(0, 2); track a) {
                  <mat-chip class="chip-alias">{{a}}</mat-chip>
                }
                @if (c.aliases.length > 2) {
                  <mat-chip [matTooltip]="c.aliases.slice(2).join(', ')"
                    class="chip-alias">+{{c.aliases.length - 2}}</mat-chip>
                }
              } @else {
                <span class="no-aliases">—</span>
              }
            </td>
          </ng-container>

          <tr mat-header-row *matHeaderRowDef="displayedColumns" class="hdr-row"></tr>
          <tr mat-row *matRowDef="let c; columns: displayedColumns"
            class="data-row"
            [style.background]="selected()?.id === c.id ? 'rgba(184,79,0,0.08)' : ''"
            (click)="onRowClick(c)"></tr>
        </table>

        <!-- Pagination -->
        <div class="pagination-bar">
          <span class="page-count">{{listQuery.data()!.total | number}} campaigns</span>
          <div class="page-nav">
            <span class="page-btn" [class.disabled]="page() <= 1"
              (click)="page() > 1 && setPage(page() - 1)">← Prev</span>
            <span class="page-info">{{page()}} / {{totalPages()}}</span>
            <span class="page-btn" [class.disabled]="page() >= totalPages()"
              (click)="page() < totalPages() && setPage(page() + 1)">Next →</span>
          </div>
        </div>
      }
    </div>

    <!-- Detail panel -->
    @if (selected(); as c) {
      <div class="detail-panel">
        <div class="detail-id" [style.color]="INTEL_COLOR">{{c.campaign_id}}</div>
        <div class="detail-name">{{c.name}}</div>

        <div class="detail-dates-row">
          @if (c.first_seen) {
            <div>
              <div class="detail-meta-label">First seen</div>
              <div class="detail-meta-val">{{c.first_seen}}</div>
            </div>
          }
          @if (c.last_seen) {
            <div>
              <div class="detail-meta-label">Last seen</div>
              <div class="detail-meta-val">{{c.last_seen}}</div>
            </div>
          }
        </div>

        @if (c.aliases.length > 0) {
          <div class="detail-aliases-wrap">
            <div class="detail-meta-label detail-meta-gap">Also known as:</div>
            @for (a of c.aliases; track a) {
              <mat-chip class="chip-alias">{{a}}</mat-chip>
            }
          </div>
        }

        @if (c.description) {
          <div class="detail-description">
            {{c.description.slice(0, 700)}}{{c.description.length > 700 ? '…' : ''}}
          </div>
        }

        @if (c.url) {
          <div class="detail-url-wrap">
            <a [href]="c.url" target="_blank" rel="noopener noreferrer"
              class="detail-url" [style.color]="INTEL_COLOR">
              View on attack.mitre.org →
            </a>
          </div>
        }
      </div>
    }
  </div>
</div>
  `,
  styles: [`
    .mat-mdc-row:hover { background: rgba(0,0,0,0.04); }

    .page-wrap { padding: 24px; }

    .page-header { margin-bottom: 16px; }
    .page-title { margin: 0; font-size: 1.3rem; font-weight: 700; }
    .page-subtitle { margin: 4px 0 0; color: #888; font-size: 0.85rem; }

    .stats-bar { display: flex; gap: 24px; margin-bottom: 16px; }
    .stat-value { font-size: 1.25rem; font-weight: 700; line-height: 1; }
    .stat-label { font-size: 0.72rem; color: #888; }

    .controls-row { display: flex; gap: 12px; margin-bottom: 16px; align-items: center; flex-wrap: wrap; }
    .version-toggle { height: 32px; }
    .version-btn { font-size: 0.72rem; padding: 0 12px; }
    .search-field { width: 240px; }
    .search-prefix-icon { font-size: 16px; line-height: 1; }

    .content-row { display: flex; gap: 16px; }

    .table-panel {
      flex: 1; min-width: 0;
      border: 1px solid var(--mat-sys-outline-variant); border-radius: 8px; overflow: hidden;
      background: var(--mat-sys-surface-container);
    }
    .full-width { width: 100%; }

    .spinner-center { display: flex; justify-content: center; padding: 48px; }
    .error-msg { padding: 16px; color: #d32f2f; font-size: 0.85rem; }
    .empty-msg { padding: 16px; font-size: 0.85rem; color: #888; }

    .col-hdr { font-size: 0.72rem; font-weight: 600; }
    .col-campaign-id { width: 80px; }
    .col-date { width: 100px; }
    .col-aliases { max-width: 200px; }

    .cell-id { font-family: monospace; font-size: 0.75rem; font-weight: 600; }
    .cell-name {
      font-size: 0.78rem; max-width: 200px;
      overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
    }
    .cell-date { font-size: 0.75rem; font-family: monospace; }

    .chip-alias { font-size: 0.62rem; height: 16px; margin: 0 2px 2px 0; }
    .no-aliases { color: #bbb; font-size: 0.75rem; }

    .hdr-row { height: 36px; }
    .data-row { height: 36px; cursor: pointer; }

    .pagination-bar {
      display: flex; justify-content: space-between; align-items: center;
      padding: 8px 16px; border-top: 1px solid var(--mat-sys-outline-variant);
    }
    .page-count { font-size: 0.75rem; color: #888; }
    .page-nav { display: flex; gap: 8px; align-items: center; }
    .page-btn { font-size: 0.75rem; cursor: pointer; color: var(--mat-sys-primary); }
    .page-btn.disabled { color: var(--mat-sys-on-surface-variant); cursor: default; pointer-events: none; }
    .page-info { font-size: 0.75rem; color: #888; }

    .detail-panel {
      width: 320px; flex-shrink: 0;
      border: 1px solid var(--mat-sys-outline-variant); border-radius: 8px;
      padding: 16px; height: fit-content; position: sticky; top: 24px;
      background: var(--mat-sys-surface-container);
    }
    .detail-id { font-family: monospace; font-size: 0.85rem; font-weight: 700; margin-bottom: 4px; }
    .detail-name { font-size: 0.9rem; font-weight: 600; margin-bottom: 8px; }
    .detail-dates-row { display: flex; gap: 16px; margin-bottom: 8px; }
    .detail-meta-label { font-size: 0.72rem; color: #888; }
    .detail-meta-val { font-size: 0.72rem; font-family: monospace; }
    .detail-meta-gap { margin-bottom: 4px; }
    .detail-aliases-wrap { margin-bottom: 8px; }
    .detail-description {
      font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); line-height: 1.5;
      margin-top: 12px; max-height: 300px; overflow-y: auto;
    }
    .detail-url-wrap { margin-top: 8px; }
    .detail-url { font-size: 0.72rem; text-decoration: none; }
  `],
})
export class MitreCampaignsComponent {
  private feedsApi = inject(FeedsApiService)

  readonly INTEL_COLOR = INTEL_COLOR
  readonly displayedColumns = ['campaign_id', 'name', 'first_seen', 'last_seen', 'aliases']

  search = signal('')
  page = signal(1)
  selected = signal<MitreCampaign | null>(null)

  listQuery = injectQuery(() => ({
    queryKey: ['feeds', 'campaigns', 'attack_v19', this.search(), this.page()],
    queryFn: () => firstValueFrom(this.feedsApi.getMitreCampaigns({
      source: 'attack_v19',
      search: this.search() || undefined,
      deprecated: false,
      page: this.page(),
      per_page: PER_PAGE,
    })),
  }))

  totalPages = computed(() => {
    const data = this.listQuery.data()
    return data ? Math.ceil(data.total / PER_PAGE) : 0
  })

  onSearch(v: string) {
    this.search.set(v)
    this.page.set(1)
  }

  setPage(p: number) {
    this.page.set(p)
  }

  onRowClick(c: MitreCampaign) {
    this.selected.set(this.selected()?.id === c.id ? null : c)
  }
}

// isms-core-platform/frontend/src/pages/MitreCampaigns.tsx
import { useState } from 'react'
import {
  Alert, Box, Chip, CircularProgress, InputAdornment, Paper,
  Table, TableBody, TableCell, TableHead, TableRow, TextField,
  ToggleButton, ToggleButtonGroup, Tooltip, Typography,
} from '@mui/material'
import { SearchOutlined } from '@mui/icons-material'
import { useQuery } from '@tanstack/react-query'
import { feedsApi, type MitreCampaign } from '../api/feedsApi'
import PageHeader from '../components/PageHeader'

const PER_PAGE = 50
const INTEL_COLOR = '#B84F00'

export default function MitreCampaigns() {
  const [source] = useState<'attack_v19'>('attack_v19')
  const [search, setSearch] = useState('')
  const [page, setPage] = useState(1)
  const [selected, setSelected] = useState<MitreCampaign | null>(null)

  const { data, isLoading, error } = useQuery({
    queryKey: ['feeds', 'campaigns', source, search, page],
    queryFn: () => feedsApi.getMitreCampaigns({
      source,
      search: search || undefined,
      deprecated: false,
      page,
      per_page: PER_PAGE,
    }),
  })

  const totalPages = data ? Math.ceil(data.total / PER_PAGE) : 0

  function handleSearch(v: string) {
    setSearch(v)
    setPage(1)
  }

  const noData = !isLoading && data?.total === 0

  return (
    <Box sx={{ p: 3 }}>
      <PageHeader
        title="MITRE ATT&CK Campaigns"
        subtitle="Targeted intrusion activity clusters — time-bound adversary operations"
        helpSection="mitre-attack"
      />

      {/* ── Total pill ── */}
      {data && (
        <Box sx={{ display: 'flex', gap: 3, mb: 2.5 }}>
          <Box>
            <Typography variant="h6" sx={{ fontWeight: 700, color: INTEL_COLOR, lineHeight: 1 }}>
              {data.total.toLocaleString()}
            </Typography>
            <Typography variant="caption" color="text.secondary">Campaigns</Typography>
          </Box>
        </Box>
      )}

      {/* ── Filters ── */}
      <Box sx={{ display: 'flex', gap: 1.5, mb: 2, flexWrap: 'wrap', alignItems: 'center' }}>
        <ToggleButtonGroup
          size="small"
          value={source}
          exclusive
          onChange={(_, v) => v && setSource(v)}
        >
          <ToggleButton value="attack_v19" sx={{ fontSize: '0.72rem', px: 1.5 }}>v19</ToggleButton>
        </ToggleButtonGroup>

        <TextField
          size="small"
          placeholder="Search by ID or name…"
          value={search}
          onChange={e => handleSearch(e.target.value)}
          sx={{ width: 240 }}
          InputProps={{
            startAdornment: <InputAdornment position="start"><SearchOutlined sx={{ fontSize: 16 }} /></InputAdornment>,
          }}
        />
      </Box>

      {/* ── Table + detail panel ── */}
      <Box sx={{ display: 'flex', gap: 2 }}>
        <Paper variant="outlined" sx={{ flex: 1, borderRadius: 2, overflow: 'hidden', minWidth: 0 }}>
          {isLoading && (
            <Box sx={{ display: 'flex', justifyContent: 'center', py: 6 }}>
              <CircularProgress size={28} />
            </Box>
          )}
          {error && <Alert severity="error" sx={{ m: 2 }}>Failed to load campaigns</Alert>}
          {noData && (
            <Alert severity="info" sx={{ m: 2 }}>
              {source === 'attack_v19'
                ? 'ATT&CK v19 data not yet available. Check back after the scheduled weekly pull.'
                : 'No campaigns match the current filters.'}
            </Alert>
          )}
          {!isLoading && data && data.items.length > 0 && (
            <>
              <Table size="small" stickyHeader>
                <TableHead>
                  <TableRow>
                    <TableCell sx={{ fontWeight: 600, fontSize: '0.72rem', width: 80 }}>ID</TableCell>
                    <TableCell sx={{ fontWeight: 600, fontSize: '0.72rem' }}>Name</TableCell>
                    <TableCell sx={{ fontWeight: 600, fontSize: '0.72rem', width: 100 }}>First Seen</TableCell>
                    <TableCell sx={{ fontWeight: 600, fontSize: '0.72rem', width: 100 }}>Last Seen</TableCell>
                    <TableCell sx={{ fontWeight: 600, fontSize: '0.72rem' }}>Aliases</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {data.items.map(c => (
                    <TableRow
                      key={c.id}
                      hover
                      selected={selected?.id === c.id}
                      onClick={() => setSelected(selected?.id === c.id ? null : c)}
                      sx={{ cursor: 'pointer' }}
                    >
                      <TableCell sx={{ fontFamily: 'monospace', fontSize: '0.75rem', color: INTEL_COLOR, fontWeight: 600 }}>
                        {c.campaign_id}
                      </TableCell>
                      <TableCell sx={{ fontSize: '0.78rem' }}>
                        <Typography noWrap variant="inherit">{c.name}</Typography>
                      </TableCell>
                      <TableCell sx={{ fontSize: '0.75rem', fontFamily: 'monospace' }}>
                        {c.first_seen ?? '—'}
                      </TableCell>
                      <TableCell sx={{ fontSize: '0.75rem', fontFamily: 'monospace' }}>
                        {c.last_seen ?? '—'}
                      </TableCell>
                      <TableCell sx={{ maxWidth: 200 }}>
                        {c.aliases.length > 0 ? (
                          <Box>
                            {c.aliases.slice(0, 2).map(a => (
                              <Chip key={a} label={a} size="small" variant="outlined"
                                sx={{ fontSize: '0.62rem', height: 16, mr: 0.25, mb: 0.25 }} />
                            ))}
                            {c.aliases.length > 2 && (
                              <Tooltip title={c.aliases.slice(2).join(', ')}>
                                <Chip label={`+${c.aliases.length - 2}`} size="small"
                                  sx={{ fontSize: '0.62rem', height: 16 }} />
                              </Tooltip>
                            )}
                          </Box>
                        ) : (
                          <Typography variant="caption" color="text.disabled">—</Typography>
                        )}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>

              {/* Pagination */}
              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', px: 2, py: 1, borderTop: '1px solid', borderColor: 'divider' }}>
                <Typography variant="caption" color="text.secondary">
                  {data.total.toLocaleString()} campaigns
                </Typography>
                <Box sx={{ display: 'flex', gap: 1, alignItems: 'center' }}>
                  <Typography
                    variant="caption"
                    sx={{ cursor: page > 1 ? 'pointer' : 'default', color: page > 1 ? 'primary.main' : 'text.disabled' }}
                    onClick={() => page > 1 && setPage(p => p - 1)}
                  >
                    ← Prev
                  </Typography>
                  <Typography variant="caption" color="text.secondary">
                    {page} / {totalPages}
                  </Typography>
                  <Typography
                    variant="caption"
                    sx={{ cursor: page < totalPages ? 'pointer' : 'default', color: page < totalPages ? 'primary.main' : 'text.disabled' }}
                    onClick={() => page < totalPages && setPage(p => p + 1)}
                  >
                    Next →
                  </Typography>
                </Box>
              </Box>
            </>
          )}
        </Paper>

        {/* ── Detail panel ── */}
        {selected && (
          <Paper variant="outlined" sx={{ width: 320, flexShrink: 0, borderRadius: 2, p: 2, height: 'fit-content', position: 'sticky', top: 24 }}>
            <Typography variant="subtitle2" sx={{ fontFamily: 'monospace', color: INTEL_COLOR, fontWeight: 700, mb: 0.5 }}>
              {selected.campaign_id}
            </Typography>
            <Typography variant="body2" fontWeight={600} sx={{ mb: 1 }}>{selected.name}</Typography>
            <Box sx={{ display: 'flex', gap: 2, mb: 1 }}>
              {selected.first_seen && (
                <Box>
                  <Typography variant="caption" color="text.secondary" display="block">First seen</Typography>
                  <Typography variant="caption" fontFamily="monospace">{selected.first_seen}</Typography>
                </Box>
              )}
              {selected.last_seen && (
                <Box>
                  <Typography variant="caption" color="text.secondary" display="block">Last seen</Typography>
                  <Typography variant="caption" fontFamily="monospace">{selected.last_seen}</Typography>
                </Box>
              )}
            </Box>
            {selected.aliases.length > 0 && (
              <Box sx={{ mb: 1 }}>
                <Typography variant="caption" color="text.secondary" display="block" sx={{ mb: 0.5 }}>Also known as:</Typography>
                {selected.aliases.map(a => (
                  <Chip key={a} label={a} size="small" variant="outlined"
                    sx={{ fontSize: '0.62rem', height: 16, mr: 0.25, mb: 0.25 }} />
                ))}
              </Box>
            )}
            {selected.description && (
              <Typography variant="caption" color="text.secondary" display="block" sx={{ mt: 1.5, lineHeight: 1.5, maxHeight: 300, overflowY: 'auto' }}>
                {selected.description.slice(0, 700)}{selected.description.length > 700 ? '…' : ''}
              </Typography>
            )}
            {selected.url && (
              <Typography variant="caption" sx={{ mt: 1, display: 'block' }}>
                <a href={selected.url} target="_blank" rel="noopener noreferrer"
                  style={{ color: INTEL_COLOR }}>
                  View on attack.mitre.org →
                </a>
              </Typography>
            )}
          </Paper>
        )}
      </Box>
    </Box>
  )
}
