// isms-core-platform/frontend-angular/src/app/pages/organisations/organisations.component.ts
import { Component, inject, signal, computed, Input, Output, EventEmitter } from '@angular/core'
import { FormsModule } from '@angular/forms'
import { HttpClient } from '@angular/common/http'
import { firstValueFrom } from 'rxjs'

import { injectQuery, injectMutation, injectQueryClient } from '@tanstack/angular-query-experimental'

import { MatCardModule } from '@angular/material/card'
import { MatButtonModule } from '@angular/material/button'
import { MatIconModule } from '@angular/material/icon'
import { MatFormFieldModule } from '@angular/material/form-field'
import { MatInputModule } from '@angular/material/input'
import { MatSelectModule } from '@angular/material/select'
import { MatTooltipModule } from '@angular/material/tooltip'
import { MatChipsModule } from '@angular/material/chips'
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner'
import { MatDialogModule, MatDialog, MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog'

import { AuthService } from '../../core/services/auth.service'
import { OrgApiService } from '../../api/org-api.service'
import { OrganisationRead } from '../../shared/types'
import { PageHeaderComponent } from '../../shared/components/page-header.component'

// ─── Types ────────────────────────────────────────────────────────────────────

interface OrganisationCreate {
  name: string
  slug: string
  description?: string
  governance_mode?: string
  country?: string | null
}

interface OrganisationPatch {
  name?: string
  description?: string
  governance_mode?: string
  country?: string | null
  settings?: Record<string, unknown>
}

// ─── Country options ──────────────────────────────────────────────────────────

const COUNTRY_OPTIONS = [
  { code: '',  label: 'Switzerland (default)' },
  { code: 'fr', label: 'France' },
  { code: 'be', label: 'Belgium' },
  { code: 'lu', label: 'Luxembourg' },
  { code: 'de', label: 'Germany' },
  { code: 'at', label: 'Austria' },
  { code: 'it', label: 'Italy' },
  { code: 'gb', label: 'United Kingdom' },
]

function fmtDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
}

function deriveSlug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 60)
}

// ─── Confirm Dialog ───────────────────────────────────────────────────────────

@Component({
  selector: 'app-org-confirm-dialog',
  standalone: true,
  imports: [MatButtonModule, MatDialogModule],
  template: `
    <h2 mat-dialog-title>{{ data.title }}</h2>
    <mat-dialog-content>{{ data.message }}</mat-dialog-content>
    <mat-dialog-actions>
      <button mat-button [mat-dialog-close]="false">Cancel</button>
      <button mat-raised-button color="warn" [mat-dialog-close]="true">{{ data.confirmLabel ?? 'Confirm' }}</button>
    </mat-dialog-actions>
  `,
})
export class OrgConfirmDialogComponent {
  readonly data = inject<{ title: string; message: string; confirmLabel?: string }>(MAT_DIALOG_DATA)
}

// ─── Alert Dialog ─────────────────────────────────────────────────────────────

@Component({
  selector: 'app-org-alert-dialog',
  standalone: true,
  imports: [MatButtonModule, MatDialogModule],
  template: `
    <h2 mat-dialog-title>Error</h2>
    <mat-dialog-content>{{ data.message }}</mat-dialog-content>
    <mat-dialog-actions>
      <button mat-raised-button color="primary" mat-dialog-close>OK</button>
    </mat-dialog-actions>
  `,
})
export class OrgAlertDialogComponent {
  readonly data = inject<{ message: string }>(MAT_DIALOG_DATA)
}

// ─── Create Org Dialog ────────────────────────────────────────────────────────

@Component({
  selector: 'app-create-org-dialog',
  standalone: true,
  imports: [
    FormsModule,
    MatButtonModule, MatDialogModule, MatFormFieldModule, MatInputModule,
    MatSelectModule, MatIconModule, MatProgressSpinnerModule,
  ],
  template: `
    <h2 mat-dialog-title>
      New Organisation
      <small class="dialog-subtitle">Add a new tenant to the platform</small>
    </h2>

    <mat-dialog-content class="create-org-content">
      @if (errorMsg()) {
        <div class="alert-error">{{ errorMsg() }}</div>
      }

      <mat-form-field appearance="outline" class="form-field-full form-field-mb" subscriptSizing="dynamic">
        <mat-label>Organisation name</mat-label>
        <input matInput [(ngModel)]="form.name" (ngModelChange)="onNameChange($event)"
          placeholder="e.g. Acme Corporation" />
      </mat-form-field>

      <mat-form-field appearance="outline" class="form-field-full form-field-mb" subscriptSizing="dynamic">
        <mat-label>Slug</mat-label>
        <input matInput [(ngModel)]="form.slug" placeholder="e.g. acme-corporation" />
        <mat-hint>Unique identifier — lowercase letters, numbers, hyphens</mat-hint>
      </mat-form-field>

      <mat-form-field appearance="outline" class="form-field-full form-field-mb" subscriptSizing="dynamic">
        <mat-label>Description (optional)</mat-label>
        <textarea matInput [(ngModel)]="form.description" rows="2"></textarea>
      </mat-form-field>

      <mat-form-field appearance="outline" class="form-field-full" subscriptSizing="dynamic">
        <mat-label>Country / Regulatory jurisdiction</mat-label>
        <mat-select [(ngModel)]="form.country">
          @for (o of countryOptions; track o.code) {
            <mat-option [value]="o.code">{{ o.label }}</mat-option>
          }
        </mat-select>
      </mat-form-field>
    </mat-dialog-content>

    <mat-dialog-actions>
      <button mat-button mat-dialog-close>Cancel</button>
      <button mat-raised-button color="primary"
        [disabled]="createMutation.isPending()"
        (click)="submit()">
        {{ createMutation.isPending() ? 'Creating…' : 'Create' }}
      </button>
    </mat-dialog-actions>
  `,
  styles: [`
    .create-org-content { min-width: 480px; padding-top: 16px !important; }
    .dialog-subtitle { display: block; font-size: 0.75rem; font-weight: 400; color: var(--mat-sys-on-surface-variant); margin-top: 2px; }
    .form-field-full { width: 100%; }
    .form-field-mb { margin-bottom: 12px; }
    .alert-error {
      padding: 10px 14px; border-radius: 6px; font-size: 0.85rem; margin-bottom: 12px;
      background: rgba(192,0,0,0.1); border: 1px solid rgba(192,0,0,0.3); color: var(--mat-sys-error);
    }
  `],
})
export class CreateOrgDialogComponent {
  private dialogRef = inject(MatDialogRef<CreateOrgDialogComponent>)
  private http = inject(HttpClient)
  private qc = injectQueryClient()

  readonly countryOptions = COUNTRY_OPTIONS

  form: OrganisationCreate & { country: string } = { name: '', slug: '', description: '', country: '' }
  errorMsg = signal('')

  createMutation = injectMutation(() => ({
    mutationFn: (body: OrganisationCreate) =>
      firstValueFrom(this.http.post<OrganisationRead>('/api/v1/organisation/', body)),
    onSuccess: () => {
      this.qc.invalidateQueries({ queryKey: ['organisations'] })
      this.dialogRef.close()
    },
    onError: () => this.errorMsg.set('Failed to create organisation — check slug is unique.'),
  }))

  onNameChange(name: string): void {
    if (!this.form.slug) {
      this.form.slug = deriveSlug(name)
    }
  }

  submit(): void {
    if (!this.form.name.trim()) { this.errorMsg.set('Name is required.'); return }
    if (!this.form.slug.trim()) { this.errorMsg.set('Slug is required.'); return }
    if (!/^[a-z0-9-]+$/.test(this.form.slug)) {
      this.errorMsg.set('Slug must be lowercase letters, numbers, and hyphens only.')
      return
    }
    this.errorMsg.set('')
    this.createMutation.mutate({
      name: this.form.name,
      slug: this.form.slug,
      description: this.form.description || undefined,
      country: this.form.country || null,
    })
  }
}

// ─── Edit Org Dialog (inline modal) ──────────────────────────────────────────

@Component({
  selector: 'app-edit-org-dialog',
  standalone: true,
  imports: [
    FormsModule,
    MatButtonModule, MatDialogModule, MatFormFieldModule, MatInputModule,
    MatSelectModule, MatIconModule, MatProgressSpinnerModule,
  ],
  template: `
    <h2 mat-dialog-title>Edit Organisation</h2>

    <mat-dialog-content class="edit-org-content">
      @if (errorMsg()) {
        <div class="alert-error">{{ errorMsg() }}</div>
      }

      <mat-form-field appearance="outline" class="form-field-full form-field-mb" subscriptSizing="dynamic">
        <mat-label>Name</mat-label>
        <input matInput [(ngModel)]="form.name" />
      </mat-form-field>

      <mat-form-field appearance="outline" class="form-field-full form-field-mb" subscriptSizing="dynamic">
        <mat-label>Description</mat-label>
        <textarea matInput [(ngModel)]="form.description" rows="2"></textarea>
      </mat-form-field>

      <mat-form-field appearance="outline" class="form-field-full" subscriptSizing="dynamic">
        <mat-label>Country / Regulatory jurisdiction</mat-label>
        <mat-select [(ngModel)]="form.country">
          @for (o of countryOptions; track o.code) {
            <mat-option [value]="o.code">{{ o.label }}</mat-option>
          }
        </mat-select>
      </mat-form-field>
    </mat-dialog-content>

    <mat-dialog-actions>
      <button mat-button mat-dialog-close>Cancel</button>
      <button mat-raised-button color="primary"
        [disabled]="saveMutation.isPending()"
        (click)="save()">
        {{ saveMutation.isPending() ? 'Saving…' : 'Save' }}
      </button>
    </mat-dialog-actions>
  `,
  styles: [`
    .edit-org-content { min-width: 480px; padding-top: 16px !important; }
    .form-field-full { width: 100%; }
    .form-field-mb { margin-bottom: 12px; }
    .alert-error {
      padding: 10px 14px; border-radius: 6px; font-size: 0.85rem; margin-bottom: 12px;
      background: rgba(192,0,0,0.1); border: 1px solid rgba(192,0,0,0.3); color: var(--mat-sys-error);
    }
  `],
})
export class EditOrgDialogComponent {
  private dialogRef = inject(MatDialogRef<EditOrgDialogComponent>)
  readonly data = inject<{ org: OrganisationRead }>(MAT_DIALOG_DATA)

  private http = inject(HttpClient)
  private qc = injectQueryClient()

  readonly countryOptions = COUNTRY_OPTIONS

  form: { name: string; description: string; country: string } = {
    name: this.data.org.name,
    description: this.data.org.description ?? '',
    country: this.data.org.country ?? '',
  }
  errorMsg = signal('')

  saveMutation = injectMutation(() => ({
    mutationFn: (body: OrganisationPatch) =>
      firstValueFrom(this.http.patch<OrganisationRead>(`/api/v1/organisation/${this.data.org.id}`, body)),
    onSuccess: () => {
      this.qc.invalidateQueries({ queryKey: ['organisations'] })
      this.dialogRef.close()
    },
    onError: () => this.errorMsg.set('Failed to update organisation.'),
  }))

  save(): void {
    this.errorMsg.set('')
    this.saveMutation.mutate({
      name: this.form.name,
      description: this.form.description || undefined,
      country: this.form.country || null,
    })
  }
}

// ─── Org Card ─────────────────────────────────────────────────────────────────

@Component({
  selector: 'app-org-card',
  standalone: true,
  imports: [
    MatCardModule, MatButtonModule, MatIconModule, MatTooltipModule, MatChipsModule,
    MatDialogModule,
  ],
  template: `
    <mat-card [style.opacity]="archived() ? '0.55' : '1'" class="org-card">
      <mat-card-content>
        <div class="card-header-row">
          <div class="card-name-row">
            <mat-icon [style.color]="archived() ? 'var(--mat-sys-on-surface-variant)' : '#4472C4'"
              class="org-icon">business</mat-icon>
            <span class="org-name"
              [style.color]="archived() ? 'var(--mat-sys-on-surface-variant)' : 'inherit'">
              {{ org.name }}
            </span>
            @if (archived()) {
              <span class="chip chip-archived">archived</span>
            }
          </div>

          @if (isSuperAdmin) {
            <div class="card-actions-row">
              <button mat-icon-button class="card-action-btn"
                matTooltip="Edit" (click)="openEdit()">
                <mat-icon class="card-action-icon">edit</mat-icon>
              </button>
              <button mat-icon-button class="card-action-btn"
                [matTooltip]="archived() ? 'Restore' : 'Archive'"
                [disabled]="archiveMutation.isPending()"
                (click)="archiveMutation.mutate(undefined)">
                <mat-icon class="card-action-icon">{{ archived() ? 'unarchive' : 'archive' }}</mat-icon>
              </button>
              <button mat-icon-button class="card-action-btn card-action-btn--danger"
                matTooltip="Delete"
                [disabled]="deleteMutation.isPending()"
                (click)="confirmDelete()">
                <mat-icon class="card-action-icon">delete</mat-icon>
              </button>
            </div>
          }
        </div>

        <div class="org-slug">
          {{ org.slug }}
        </div>

        @if (org.description) {
          <div class="org-description">
            {{ org.description }}
          </div>
        }

        <div class="chip-row">
          <span class="chip"
            [style.background]="org.governance_mode === 'platform' ? 'rgba(68,114,196,0.1)' : 'rgba(255,152,0,0.1)'"
            [style.color]="org.governance_mode === 'platform' ? '#4472C4' : '#FF9800'">
            {{ org.governance_mode }}
          </span>
          <span class="chip chip-privacy">{{ org.privacy_role }}</span>
          <span class="chip chip-country">{{ org.country ? org.country.toUpperCase() : 'CH' }}</span>
        </div>

        <div class="org-created-date">
          Created {{ fmtDate(org.created_at) }}
        </div>
      </mat-card-content>
    </mat-card>
  `,
  styles: [`
    .org-card { height: 100%; border: 1px solid var(--mat-sys-outline-variant); }
    .card-header-row { display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 8px; }
    .card-name-row { display: flex; align-items: center; gap: 8px; }
    .org-icon { font-size: 20px; width: 20px; height: 20px; }
    .org-name { font-weight: 600; font-size: 0.9rem; }
    .card-actions-row { display: flex; gap: 2px; }
    .card-action-btn { width: 28px; height: 28px; line-height: 28px; }
    .card-action-btn--danger { color: var(--mat-sys-error); }
    .card-action-icon { font-size: 14px; }
    .org-slug { font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); margin-bottom: 8px; }
    .org-description { font-size: 0.8rem; color: var(--mat-sys-on-surface-variant); margin-bottom: 12px; }
    .chip-row { display: flex; gap: 6px; flex-wrap: wrap; margin-bottom: 12px; }
    .org-created-date { font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); }
    .chip {
      display: inline-block; height: 20px; line-height: 20px;
      padding: 0 8px; border-radius: 10px; font-size: 0.68rem; font-weight: 500;
    }
    .chip-archived { background: rgba(158,158,158,0.15); color: var(--mat-sys-on-surface-variant); }
    .chip-privacy  { background: rgba(112,48,160,0.1); color: #7030A0; }
    .chip-country  { background: rgba(0,150,136,0.1); color: #00897B; }
  `],
})
export class OrgCardComponent {
  @Input() org!: OrganisationRead
  @Input() isSuperAdmin = false

  private http = inject(HttpClient)
  private qc = injectQueryClient()
  private dialog = inject(MatDialog)

  archived = computed(() => !this.org.is_active)

  archiveMutation = injectMutation(() => ({
    mutationFn: () => firstValueFrom(this.http.patch<OrganisationRead>(`/api/v1/organisation/${this.org.id}/archive`, {})),
    onSuccess: () => this.qc.invalidateQueries({ queryKey: ['organisations'] }),
  }))

  deleteMutation = injectMutation(() => ({
    mutationFn: () => firstValueFrom(this.http.delete(`/api/v1/organisation/${this.org.id}`)),
    onSuccess: () => this.qc.invalidateQueries({ queryKey: ['organisations'] }),
    onError: (e: unknown) => {
      const detail = (e as { error?: { detail?: string } })?.error?.detail
      this.dialog.open(OrgAlertDialogComponent, {
        data: { message: detail ?? 'Delete failed — organisation may have users or projects.' },
      })
    },
  }))

  openEdit(): void {
    this.dialog.open(EditOrgDialogComponent, { data: { org: this.org }, width: '560px' })
  }

  confirmDelete(): void {
    const ref = this.dialog.open(OrgConfirmDialogComponent, {
      data: {
        title: 'Delete Organisation',
        message: `Permanently delete "${this.org.name}"? This cannot be undone.`,
        confirmLabel: 'Delete',
      },
    })
    ref.afterClosed().subscribe((ok: boolean) => { if (ok) this.deleteMutation.mutate(undefined) })
  }

  fmtDate(iso: string): string { return fmtDate(iso) }
}

// ─── Main Page ────────────────────────────────────────────────────────────────

@Component({
  selector: 'app-organisations',
  standalone: true,
  imports: [
    MatButtonModule, MatIconModule, MatProgressSpinnerModule, MatChipsModule,
    MatDialogModule,
    PageHeaderComponent, OrgCardComponent,
  ],
  template: `
    <div class="page-wrap">
      <app-page-header
        [title]="'Organisations'"
        [subtitle]="isSuperAdmin() ? 'All tenants on this platform' : 'Your organisation'">
        <div actions class="header-actions">
          <button mat-stroked-button (click)="qc.invalidateQueries({ queryKey: ['organisations'] })">
            <mat-icon>refresh</mat-icon>
            Refresh
          </button>
          @if (isSuperAdmin()) {
            <button mat-raised-button color="primary" (click)="openCreate()">
              <mat-icon>add</mat-icon>
              New Organisation
            </button>
          }
        </div>
      </app-page-header>

      <!-- Access guard -->
      @if (!hasAccess()) {
        <div class="alert-error">Admin or Super Admin role required.</div>
      }

      <!-- Error -->
      @if (orgsQuery.isError()) {
        <div class="alert-error alert-error-mb">Failed to load organisations.</div>
      }

      <!-- Grid -->
      <div class="org-grid">
        @if (orgsQuery.isLoading()) {
          @for (i of [1,2,3]; track i) {
            <div class="org-skel"></div>
          }
        } @else {
          @for (org of orgsQuery.data() ?? []; track org.id) {
            <app-org-card [org]="org" [isSuperAdmin]="isSuperAdmin()" />
          }
        }
      </div>
    </div>

  `,
  styles: [`
    :host { display: block; }

    .page-wrap { padding: 24px; }
    .header-actions { display: flex; gap: 8px; }

    .org-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
      gap: 16px;
      margin-top: 16px;
    }
    .org-skel { height: 160px; border-radius: 4px; background: var(--mat-sys-surface-variant); }

    .alert-error {
      padding: 10px 14px; border-radius: 6px; font-size: 0.875rem; margin-bottom: 16px;
      background: rgba(192,0,0,0.1); border: 1px solid rgba(192,0,0,0.3); color: var(--mat-sys-error);
    }
    .alert-error-mb { margin-bottom: 16px; }
  `],
})
export class OrganisationsComponent {
  private auth = inject(AuthService)
  private orgApi = inject(OrgApiService)
  private http = inject(HttpClient)
  private dialog = inject(MatDialog)
  readonly qc = injectQueryClient()

  isSuperAdmin = computed(() => this.auth.isSuperAdmin())
  hasAccess = computed(() => {
    const role = this.auth.user()?.role
    return role === 'super_admin' || role === 'admin'
  })

  orgsQuery = injectQuery(() => ({
    queryKey: ['organisations', this.isSuperAdmin()],
    queryFn: () => this.isSuperAdmin()
      ? firstValueFrom(this.http.get<OrganisationRead[]>('/api/v1/organisation/all'))
      : firstValueFrom(this.orgApi.get()).then(o => [o]),
    enabled: this.hasAccess(),
  }))

  openCreate(): void {
    this.dialog.open(CreateOrgDialogComponent, { width: '560px' })
  }
}

// isms-core-platform/frontend/src/pages/Organisations.tsx
import { useState } from 'react'
import {
  Alert,
  Box,
  Button,
  Card,
  CardContent,
  Chip,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  Grid,
  IconButton,
  MenuItem,
  Select,
  InputLabel,
  FormControl,
  Skeleton,
  TextField,
  Tooltip,
  Typography,
} from '@mui/material'
import {
  AddOutlined,
  ArchiveOutlined,
  BusinessOutlined,
  DeleteOutlined,
  EditOutlined,
  RefreshOutlined,
  UnarchiveOutlined,
} from '@mui/icons-material'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import dayjs from 'dayjs'
import { orgApi, type OrganisationCreate, type OrganisationPatch } from '../api/orgApi'
import type { OrganisationRead } from '../api/types'
import PageHeader from '../components/PageHeader'
import { useAuth } from '../store/AuthContext'

// ── Country options ────────────────────────────────────────────────────────────

const COUNTRY_OPTIONS = [
  { code: null,  label: 'Switzerland (default)' },
  { code: 'fr',  label: 'France' },
  { code: 'be',  label: 'Belgium' },
  { code: 'lu',  label: 'Luxembourg' },
  { code: 'de',  label: 'Germany' },
  { code: 'at',  label: 'Austria' },
  { code: 'it',  label: 'Italy' },
  { code: 'gb',  label: 'United Kingdom' },
]

// ── Create dialog ──────────────────────────────────────────────────────────────

function CreateOrgDialog({ open, onClose }: { open: boolean; onClose: () => void }) {
  const qc = useQueryClient()
  const [form, setForm] = useState<OrganisationCreate>({ name: '', slug: '' })
  const [error, setError] = useState('')

  const mutation = useMutation({
    mutationFn: (body: OrganisationCreate) => orgApi.create(body),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['organisations'] })
      setForm({ name: '', slug: '' })
      setError('')
      onClose()
    },
    onError: () => setError('Failed to create organisation — check slug is unique.'),
  })

  function handleSubmit() {
    if (!form.name.trim()) { setError('Name is required.'); return }
    if (!form.slug.trim()) { setError('Slug is required.'); return }
    if (!/^[a-z0-9-]+$/.test(form.slug)) { setError('Slug must be lowercase letters, numbers, and hyphens only.'); return }
    mutation.mutate(form)
  }

  function deriveSlug(name: string) {
    return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 60)
  }

  return (
    <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth>
      <DialogTitle sx={{ pb: 0.5 }}>
        New Organisation
        <Typography variant="caption" color="text.secondary" display="block">
          Add a new tenant to the platform
        </Typography>
      </DialogTitle>
      <DialogContent sx={{ pt: '20px !important' }}>
        {error && <Alert severity="error" sx={{ mb: 2, py: 0.5 }}>{error}</Alert>}
        <TextField
          label="Organisation name"
          fullWidth size="small" sx={{ mb: 2 }}
          value={form.name}
          onChange={e => {
            const name = e.target.value
            setForm(f => ({ ...f, name, slug: f.slug || deriveSlug(name) }))
          }}
          placeholder="e.g. Acme Corporation"
        />
        <TextField
          label="Slug"
          fullWidth size="small" sx={{ mb: 2 }}
          value={form.slug}
          onChange={e => setForm(f => ({ ...f, slug: e.target.value }))}
          placeholder="e.g. acme-corporation"
          helperText="Unique identifier — lowercase letters, numbers, hyphens"
        />
        <TextField
          label="Description (optional)"
          fullWidth size="small" multiline rows={2} sx={{ mb: 2 }}
          value={form.description ?? ''}
          onChange={e => setForm(f => ({ ...f, description: e.target.value || undefined }))}
        />
        <FormControl fullWidth size="small">
          <InputLabel>Country / Regulatory jurisdiction</InputLabel>
          <Select
            label="Country / Regulatory jurisdiction"
            value={form.country ?? ''}
            onChange={e => setForm(f => ({ ...f, country: e.target.value || null }))}
          >
            {COUNTRY_OPTIONS.map(o => (
              <MenuItem key={o.code ?? '__ch'} value={o.code ?? ''}>
                {o.label}
              </MenuItem>
            ))}
          </Select>
        </FormControl>
      </DialogContent>
      <DialogActions sx={{ px: 3, pb: 2 }}>
        <Button onClick={onClose} size="small">Cancel</Button>
        <Button variant="contained" size="small" onClick={handleSubmit} disabled={mutation.isPending}>
          Create
        </Button>
      </DialogActions>
    </Dialog>
  )
}

// ── Edit dialog ────────────────────────────────────────────────────────────────

function EditOrgDialog({ org, open, onClose }: { org: OrganisationRead; open: boolean; onClose: () => void }) {
  const qc = useQueryClient()
  const [form, setForm] = useState<OrganisationPatch>({ name: org.name, description: org.description ?? '', country: org.country })
  const [error, setError] = useState('')

  const mutation = useMutation({
    mutationFn: (body: OrganisationPatch) => orgApi.updateById(org.id, body),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['organisations'] })
      setError('')
      onClose()
    },
    onError: () => setError('Failed to update organisation.'),
  })

  return (
    <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth>
      <DialogTitle sx={{ pb: 0.5 }}>Edit Organisation</DialogTitle>
      <DialogContent sx={{ pt: '20px !important' }}>
        {error && <Alert severity="error" sx={{ mb: 2, py: 0.5 }}>{error}</Alert>}
        <TextField
          label="Name" fullWidth size="small" sx={{ mb: 2 }}
          value={form.name ?? ''}
          onChange={e => setForm(f => ({ ...f, name: e.target.value }))}
        />
        <TextField
          label="Description" fullWidth size="small" multiline rows={2} sx={{ mb: 2 }}
          value={form.description ?? ''}
          onChange={e => setForm(f => ({ ...f, description: e.target.value || undefined }))}
        />
        <FormControl fullWidth size="small">
          <InputLabel>Country / Regulatory jurisdiction</InputLabel>
          <Select
            label="Country / Regulatory jurisdiction"
            value={form.country ?? ''}
            onChange={e => setForm(f => ({ ...f, country: e.target.value || null }))}
          >
            {COUNTRY_OPTIONS.map(o => (
              <MenuItem key={o.code ?? '__ch'} value={o.code ?? ''}>
                {o.label}
              </MenuItem>
            ))}
          </Select>
        </FormControl>
      </DialogContent>
      <DialogActions sx={{ px: 3, pb: 2 }}>
        <Button onClick={onClose} size="small">Cancel</Button>
        <Button variant="contained" size="small" onClick={() => mutation.mutate(form)} disabled={mutation.isPending}>
          Save
        </Button>
      </DialogActions>
    </Dialog>
  )
}

// ── Org card ──────────────────────────────────────────────────────────────────

function OrgCard({ org, isSuperAdmin }: { org: OrganisationRead; isSuperAdmin: boolean }) {
  const qc = useQueryClient()
  const [editOpen, setEditOpen] = useState(false)

  const archiveMutation = useMutation({
    mutationFn: () => orgApi.archiveById(org.id),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['organisations'] }),
  })

  const deleteMutation = useMutation({
    mutationFn: () => orgApi.deleteById(org.id),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['organisations'] }),
    onError: (e: { response?: { data?: { detail?: string } } }) =>
      alert(e?.response?.data?.detail ?? 'Delete failed — organisation may have users or projects.'),
  })

  function handleDelete() {
    if (window.confirm(`Permanently delete "${org.name}"? This cannot be undone.`)) {
      deleteMutation.mutate()
    }
  }

  const archived = !org.is_active

  return (
    <>
      <Card variant="outlined" sx={{ height: '100%', opacity: archived ? 0.55 : 1 }}>
        <CardContent>
          <Box sx={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', mb: 1 }}>
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
              <BusinessOutlined sx={{ color: archived ? 'text.disabled' : '#4472C4', fontSize: 20 }} />
              <Typography variant="subtitle2" fontWeight={600} color={archived ? 'text.disabled' : 'text.primary'}>
                {org.name}
              </Typography>
              {archived && <Chip label="archived" size="small" sx={{ height: 16, fontSize: '0.62rem', bgcolor: 'rgba(158,158,158,0.15)', color: 'text.disabled' }} />}
            </Box>
            {isSuperAdmin && (
              <Box sx={{ display: 'flex', gap: 0.25 }}>
                <Tooltip title="Edit">
                  <IconButton size="small" onClick={() => setEditOpen(true)}>
                    <EditOutlined sx={{ fontSize: 14 }} />
                  </IconButton>
                </Tooltip>
                <Tooltip title={archived ? 'Restore' : 'Archive'}>
                  <IconButton size="small" onClick={() => archiveMutation.mutate()} disabled={archiveMutation.isPending}>
                    {archived ? <UnarchiveOutlined sx={{ fontSize: 14 }} /> : <ArchiveOutlined sx={{ fontSize: 14 }} />}
                  </IconButton>
                </Tooltip>
                <Tooltip title="Delete">
                  <IconButton size="small" onClick={handleDelete} disabled={deleteMutation.isPending} sx={{ color: 'error.main' }}>
                    <DeleteOutlined sx={{ fontSize: 14 }} />
                  </IconButton>
                </Tooltip>
              </Box>
            )}
          </Box>

          <Typography variant="caption" color="text.disabled" sx={{ display: 'block', mb: 1 }}>
            {org.slug}
          </Typography>

          {org.description && (
            <Typography variant="body2" color="text.secondary" sx={{ mb: 1.5, fontSize: '0.8rem' }}>
              {org.description}
            </Typography>
          )}

          <Box sx={{ display: 'flex', gap: 0.75, flexWrap: 'wrap', mt: 'auto' }}>
            <Chip
              label={org.governance_mode}
              size="small"
              sx={{ fontSize: '0.68rem', height: 20,
                bgcolor: org.governance_mode === 'platform' ? 'rgba(68,114,196,0.1)' : 'rgba(255,152,0,0.1)',
                color: org.governance_mode === 'platform' ? '#4472C4' : '#FF9800' }}
            />
            <Chip
              label={org.privacy_role}
              size="small"
              sx={{ fontSize: '0.68rem', height: 20, bgcolor: 'rgba(112,48,160,0.1)', color: '#7030A0' }}
            />
            <Chip
              label={org.country ? org.country.toUpperCase() : 'CH'}
              size="small"
              sx={{ fontSize: '0.68rem', height: 20, bgcolor: 'rgba(0,150,136,0.1)', color: '#00897B' }}
            />
          </Box>

          <Typography variant="caption" color="text.disabled" sx={{ display: 'block', mt: 1.5 }}>
            Created {dayjs(org.created_at).format('DD MMM YYYY')}
          </Typography>
        </CardContent>
      </Card>

      {editOpen && <EditOrgDialog org={org} open={editOpen} onClose={() => setEditOpen(false)} />}
    </>
  )
}

// ── Main page ─────────────────────────────────────────────────────────────────

export default function Organisations() {
  const { isSuperAdmin, user } = useAuth()
  const [createOpen, setCreateOpen] = useState(false)
  const qc = useQueryClient()

  const { data: orgs, isLoading, isError } = useQuery({
    queryKey: ['organisations', isSuperAdmin],
    queryFn: () => isSuperAdmin ? orgApi.list() : orgApi.get().then(o => [o]),
  })

  if (!isSuperAdmin && user?.role !== 'admin') {
    return (
      <Box sx={{ p: 3 }}>
        <Alert severity="error">Admin or Super Admin role required.</Alert>
      </Box>
    )
  }

  return (
    <Box sx={{ p: 3 }}>
      <PageHeader
        title="Organisations"
        subtitle={isSuperAdmin ? 'All tenants on this platform' : 'Your organisation'}
        actions={
          <Box sx={{ display: 'flex', gap: 1 }}>
            <Button size="small" startIcon={<RefreshOutlined />} onClick={() => qc.invalidateQueries({ queryKey: ['organisations'] })}>
              Refresh
            </Button>
            {isSuperAdmin && (
              <Button size="small" variant="contained" startIcon={<AddOutlined />} onClick={() => setCreateOpen(true)}>
                New Organisation
              </Button>
            )}
          </Box>
        }
      />

      {isError && <Alert severity="error" sx={{ mb: 2 }}>Failed to load organisations.</Alert>}

      <Grid container spacing={2}>
        {isLoading
          ? Array.from({ length: 3 }).map((_, i) => (
              <Grid item xs={12} sm={6} md={4} key={i}>
                <Skeleton variant="rectangular" height={160} sx={{ borderRadius: 1 }} />
              </Grid>
            ))
          : orgs?.map(org => (
              <Grid item xs={12} sm={6} md={4} key={org.id}>
                <OrgCard org={org} isSuperAdmin={isSuperAdmin} />
              </Grid>
            ))
        }
      </Grid>

      {createOpen && <CreateOrgDialog open={createOpen} onClose={() => setCreateOpen(false)} />}
    </Box>
  )
}
