// isms-core-platform/frontend/src/pages/Report.tsx
import { useState } from 'react'
import { Box, Typography, Table, TableHead, TableBody, TableRow, TableCell, Button, Divider, Chip, Skeleton, ToggleButtonGroup, ToggleButton, useTheme } from '@mui/material'
import { PrintOutlined, FileDownloadOutlined } from '@mui/icons-material'
import { useQuery } from '@tanstack/react-query'
import { dashboardApi } from '../api/dashboard'
import { controlsApi } from '../api/controls'
import { useProduct, PRODUCT_COLORS, PRODUCT_LABELS, type Product } from '../store/ProductContext'

// Actual API shape (the types.ts interface is outdated)
interface GroupRow {
  id: string
  group_code: string
  name: string
  section: string
  section_name: string
  has_framework: boolean   // has policy
  product_family: string
}

// Local shape aliases matching Overview.tsx
interface SectionRow {
  section: string
  section_name: string
  total_controls: number
  framework_covered: number
  operational_covered: number
  framework_pct: number
  operational_pct: number
}

interface RealOverview {
  total_controls: number
  total_policies: number
  total_implementations: number
  total_assessments: number
  total_gaps_open: number
  framework: { coverage_pct: number; has_policy: number; has_ug: number; has_tg: number; has_assessment: number }
  operational: { coverage_pct: number }
  sections: SectionRow[]
}

interface RealReadiness {
  policies_pct: number
  ug_pct: number
  tg_pct: number
  assessments_pct: number
  evidence_pct: number
  gaps_closed_pct: number
  composite_score: number
  status: 'green' | 'amber' | 'red'
}

const STATUS_LABEL: Record<string, string> = { green: 'Compliant', amber: 'Partially Compliant', red: 'Non-Compliant' }
const STATUS_BG_DARK: Record<string, string>  = { green: '#1a3a27',              amber: '#3a2e00',              red: '#3a0000' }
const STATUS_BG_LIGHT: Record<string, string> = { green: 'rgba(46,125,50,0.12)', amber: 'rgba(230,160,0,0.12)', red: 'rgba(192,0,0,0.12)' }
const STATUS_FG_DARK: Record<string, string>  = { green: '#C6EFCE', amber: '#FFEB9C', red: '#FFC7CE' }
const STATUS_FG_LIGHT: Record<string, string> = { green: '#1b5e20', amber: '#7a4800', red: '#9e0000' }

const STANDARD_NAMES: Record<Product, string> = {
  isms:    'ISO/IEC 27001:2022',
  privacy: 'ISO/IEC 27701:2025',
  cloud:   'ISO/IEC 27018:2025',
}

const HEADER_COLORS: Record<Product, string> = {
  isms:    '#4472C4',
  privacy: PRODUCT_COLORS.privacy,
  cloud:   PRODUCT_COLORS.cloud,
}

function pct(v: number) { return `${v.toFixed(0)}%` }

function exportCsv(sections: SectionRow[]) {
  const headers = ['section', 'section_name', 'total_controls', 'framework_covered', 'framework_pct', 'operational_covered', 'operational_pct']
  const rows = sections.map((s) => [
    s.section,
    s.section_name,
    s.total_controls,
    s.framework_covered,
    s.framework_pct.toFixed(1),
    s.operational_covered,
    s.operational_pct.toFixed(1),
  ])
  const csv = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n')
  const today = new Date().toISOString().slice(0, 10).replace(/-/g, '')
  const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' }))
  const a = document.createElement('a')
  a.href = url
  a.download = `isms-report-${today}.csv`
  a.click()
  URL.revokeObjectURL(url)
}

const TH_STYLE = { fontWeight: 700, fontSize: '0.78rem', color: '#1a1a2e', bgcolor: '#e8ecf4', borderBottom: '2px solid #c8d0e0' }
const TD_STYLE = { fontSize: '0.8rem', color: '#1a1a2e', borderBottom: '1px solid #e0e4ec' }

export default function Report() {
  const { palette } = useTheme()
  const isLight = palette.mode === 'light'
  const STATUS_BG = isLight ? STATUS_BG_LIGHT : STATUS_BG_DARK
  const STATUS_FG = isLight ? STATUS_FG_LIGHT : STATUS_FG_DARK
  const { product: activeProduct } = useProduct()
  const [reportProduct, setReportProduct] = useState<Product>(activeProduct)

  const { data: overview, isLoading: ovLoading } = useQuery({
    queryKey: ['dashboard', 'overview'],
    queryFn: dashboardApi.getOverview,
  })
  const { data: readiness, isLoading: rdLoading } = useQuery({
    queryKey: ['dashboard', 'audit-readiness'],
    queryFn: dashboardApi.getAuditReadiness,
  })
  const { data: homeSummary, isLoading: hsLoading } = useQuery({
    queryKey: ['home-summary'],
    queryFn: dashboardApi.getHomeSummary,
    staleTime: 30_000,
  })

  const { data: groupsRaw, isLoading: grLoading } = useQuery({
    queryKey: ['controls', 'list', reportProduct],
    queryFn: () => controlsApi.list({ product_family: reportProduct.toUpperCase() }),
    enabled: reportProduct !== 'isms',
  })
  const groups = (groupsRaw as unknown as GroupRow[] | undefined) ?? []

  const ov = overview as unknown as RealOverview | undefined
  const rd = readiness as unknown as RealReadiness | undefined
  const loading = reportProduct === 'isms' ? (ovLoading || rdLoading) : (hsLoading || grLoading)
  const generatedDate = new Date().toLocaleDateString('en-GB', { year: 'numeric', month: 'long', day: 'numeric' })

  const readinessRows = rd ? [
    { name: 'Policies',     value: rd.policies_pct },
    { name: 'User Guides',  value: rd.ug_pct },
    { name: 'Tech Guides',  value: rd.tg_pct },
    { name: 'Assessments',  value: rd.assessments_pct },
    { name: 'Evidence',     value: rd.evidence_pct },
    { name: 'Gaps Closed',  value: rd.gaps_closed_pct },
  ] : []

  const headerColor = HEADER_COLORS[reportProduct]
  const standardName = STANDARD_NAMES[reportProduct]
  const productSummary = homeSummary?.[reportProduct]

  if (loading) {
    return (
      <Box sx={{ p: 4 }}>
        <Skeleton variant="rectangular" height={80} sx={{ mb: 2 }} />
        <Skeleton variant="rectangular" height={200} sx={{ mb: 2 }} />
        <Skeleton variant="rectangular" height={300} />
      </Box>
    )
  }

  return (
    <Box>
      {/* Action buttons — hidden in print */}
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mb: 3, flexWrap: 'wrap', '@media print': { display: 'none' } }}>
        {/* ISO selector */}
        <ToggleButtonGroup
          value={reportProduct}
          exclusive
          onChange={(_, v) => v && setReportProduct(v)}
          size="small"
        >
          {(['isms', 'privacy', 'cloud'] as Product[]).map((p) => (
            <ToggleButton
              key={p}
              value={p}
              sx={{
                fontSize: '0.72rem',
                px: 1.5,
                '&.Mui-selected': { bgcolor: `${HEADER_COLORS[p]}22`, color: HEADER_COLORS[p], borderColor: `${HEADER_COLORS[p]}55` },
              }}
            >
              {PRODUCT_LABELS[p]}
            </ToggleButton>
          ))}
        </ToggleButtonGroup>

        <Button
          variant="contained"
          startIcon={<PrintOutlined />}
          onClick={() => window.print()}
        >
          Print / Save as PDF
        </Button>
        {reportProduct === 'isms' && (
          <Button
            variant="outlined"
            startIcon={<FileDownloadOutlined />}
            onClick={() => ov && exportCsv(ov.sections)}
            disabled={!ov}
          >
            Export CSV
          </Button>
        )}
      </Box>

      {/* Report body — white background for print */}
      <Box
        sx={{
          bgcolor: 'white',
          color: '#1a1a2e',
          p: { xs: 3, md: 5 },
          borderRadius: 2,
          maxWidth: 900,
          mx: 'auto',
          boxShadow: '0 2px 12px rgba(0,0,0,0.18)',
          '@media print': {
            boxShadow: 'none',
            borderRadius: 0,
            p: 4,
            maxWidth: '100%',
          },
        }}
      >
        {/* Report header */}
        <Box sx={{ mb: 3, pb: 2, borderBottom: `2px solid ${headerColor}` }}>
          <Typography variant="h4" sx={{ color: '#003366', fontWeight: 700, mb: 0.5 }}>
            ISMS CORE — {PRODUCT_LABELS[reportProduct]} Compliance Report
          </Typography>
          <Typography variant="body2" sx={{ color: '#555' }}>
            {standardName} · Generated {generatedDate}
          </Typography>
        </Box>

        {/* ── ISMS full report ── */}
        {reportProduct === 'isms' && (
          <>
            {/* Section 1 — Executive Summary */}
            <Box sx={{ mb: 4 }}>
              <Typography variant="h6" sx={{ color: '#003366', fontWeight: 700, mb: 1.5, textTransform: 'uppercase', letterSpacing: '0.06em', fontSize: '0.85rem' }}>
                1 — Executive Summary
              </Typography>

              {rd && (
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, mb: 2 }}>
                  <Box
                    sx={{
                      px: 2.5, py: 1.5, borderRadius: 2,
                      bgcolor: STATUS_BG[rd.status], border: `1px solid ${STATUS_FG[rd.status]}40`,
                    }}
                  >
                    <Typography sx={{ fontSize: '2rem', fontWeight: 800, color: STATUS_FG[rd.status], lineHeight: 1 }}>
                      {rd.composite_score}%
                    </Typography>
                    <Typography sx={{ fontSize: '0.7rem', color: STATUS_FG[rd.status], opacity: 0.8, mt: 0.25 }}>
                      Composite Score
                    </Typography>
                  </Box>
                  <Box>
                    <Chip
                      label={STATUS_LABEL[rd.status]}
                      size="small"
                      sx={{ bgcolor: STATUS_BG[rd.status], color: STATUS_FG[rd.status], fontWeight: 700, fontSize: '0.8rem', height: 26, mb: 0.5 }}
                    />
                    <Typography variant="body2" sx={{ color: '#555' }}>
                      ISO/IEC 27001:2022 Annex A compliance posture
                    </Typography>
                  </Box>
                </Box>
              )}

              <Table size="small" sx={{ width: 'auto' }}>
                <TableBody>
                  {[
                    { label: 'Control Groups',       value: ov?.total_controls ?? '—' },
                    { label: 'Policies',             value: ov?.total_policies ?? '—' },
                    { label: 'Implementations',      value: ov?.total_implementations ?? '—' },
                    { label: 'Open Gaps',            value: ov?.total_gaps_open ?? '—' },
                    { label: 'Framework Coverage',   value: ov ? pct(ov.framework.coverage_pct) : '—' },
                    { label: 'Operational Coverage', value: ov ? pct(ov.operational.coverage_pct) : '—' },
                  ].map(({ label, value }) => (
                    <TableRow key={label}>
                      <TableCell sx={{ ...TD_STYLE, fontWeight: 600, width: 220 }}>{label}</TableCell>
                      <TableCell sx={TD_STYLE}>{value}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </Box>

            <Divider sx={{ borderColor: '#c8d0e0', mb: 4 }} />

            {/* Section 2 — Coverage by Section */}
            <Box sx={{ mb: 4 }}>
              <Typography variant="h6" sx={{ color: '#003366', fontWeight: 700, mb: 1.5, textTransform: 'uppercase', letterSpacing: '0.06em', fontSize: '0.85rem' }}>
                2 — Coverage by Section
              </Typography>
              <Table size="small">
                <TableHead>
                  <TableRow>
                    <TableCell sx={TH_STYLE}>Section</TableCell>
                    <TableCell sx={TH_STYLE}>Name</TableCell>
                    <TableCell sx={{ ...TH_STYLE, textAlign: 'center' }}>Controls</TableCell>
                    <TableCell sx={{ ...TH_STYLE, textAlign: 'center' }}>Framework %</TableCell>
                    <TableCell sx={{ ...TH_STYLE, textAlign: 'center' }}>Operational %</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {(ov?.sections ?? []).map((s) => (
                    <TableRow key={s.section} sx={{ '&:nth-of-type(even)': { bgcolor: '#f7f9fc' } }}>
                      <TableCell sx={{ ...TD_STYLE, fontFamily: 'monospace', fontWeight: 700 }}>{s.section}</TableCell>
                      <TableCell sx={TD_STYLE}>{s.section_name}</TableCell>
                      <TableCell sx={{ ...TD_STYLE, textAlign: 'center' }}>{s.total_controls}</TableCell>
                      <TableCell sx={{ ...TD_STYLE, textAlign: 'center' }}>{pct(s.framework_pct)}</TableCell>
                      <TableCell sx={{ ...TD_STYLE, textAlign: 'center' }}>{pct(s.operational_pct)}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </Box>

            <Divider sx={{ borderColor: '#c8d0e0', mb: 4 }} />

            {/* Section 3 — Audit Readiness */}
            <Box sx={{ mb: 4 }}>
              <Typography variant="h6" sx={{ color: '#003366', fontWeight: 700, mb: 1.5, textTransform: 'uppercase', letterSpacing: '0.06em', fontSize: '0.85rem' }}>
                3 — Audit Readiness Breakdown
              </Typography>
              <Table size="small" sx={{ width: 'auto', minWidth: 400 }}>
                <TableHead>
                  <TableRow>
                    <TableCell sx={TH_STYLE}>Component</TableCell>
                    <TableCell sx={{ ...TH_STYLE, textAlign: 'center' }}>Score</TableCell>
                    <TableCell sx={{ ...TH_STYLE, textAlign: 'center' }}>Status</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {readinessRows.map(({ name, value }) => (
                    <TableRow key={name} sx={{ '&:nth-of-type(even)': { bgcolor: '#f7f9fc' } }}>
                      <TableCell sx={{ ...TD_STYLE, fontWeight: 600 }}>{name}</TableCell>
                      <TableCell sx={{ ...TD_STYLE, textAlign: 'center' }}>{pct(value)}</TableCell>
                      <TableCell sx={{ ...TD_STYLE, textAlign: 'center' }}>
                        <Chip
                          label={value >= 80 ? 'Good' : value >= 50 ? 'Partial' : 'Attention'}
                          size="small"
                          sx={{
                            bgcolor: value >= 80 ? STATUS_BG.green : value >= 50 ? STATUS_BG.amber : STATUS_BG.red,
                            color:   value >= 80 ? STATUS_FG.green : value >= 50 ? STATUS_FG.amber : STATUS_FG.red,
                            fontSize: '0.65rem',
                            height: 18,
                          }}
                        />
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </Box>

            <Divider sx={{ borderColor: '#c8d0e0', mb: 4 }} />

            {/* Section 4 — Framework vs Operational */}
            <Box sx={{ mb: 4 }}>
              <Typography variant="h6" sx={{ color: '#003366', fontWeight: 700, mb: 1.5, textTransform: 'uppercase', letterSpacing: '0.06em', fontSize: '0.85rem' }}>
                4 — Framework vs Operational Coverage
              </Typography>
              <Table size="small" sx={{ width: 'auto', minWidth: 400 }}>
                <TableHead>
                  <TableRow>
                    <TableCell sx={TH_STYLE}>Product</TableCell>
                    <TableCell sx={{ ...TH_STYLE, textAlign: 'center' }}>Total Controls</TableCell>
                    <TableCell sx={{ ...TH_STYLE, textAlign: 'center' }}>Coverage %</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  <TableRow>
                    <TableCell sx={{ ...TD_STYLE, fontWeight: 600 }}>Framework</TableCell>
                    <TableCell sx={{ ...TD_STYLE, textAlign: 'center' }}>{ov?.total_controls ?? '—'}</TableCell>
                    <TableCell sx={{ ...TD_STYLE, textAlign: 'center' }}>{ov ? pct(ov.framework.coverage_pct) : '—'}</TableCell>
                  </TableRow>
                  <TableRow sx={{ bgcolor: '#f7f9fc' }}>
                    <TableCell sx={{ ...TD_STYLE, fontWeight: 600 }}>Operational</TableCell>
                    <TableCell sx={{ ...TD_STYLE, textAlign: 'center' }}>{ov?.total_controls ?? '—'}</TableCell>
                    <TableCell sx={{ ...TD_STYLE, textAlign: 'center' }}>{ov ? pct(ov.operational.coverage_pct) : '—'}</TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </Box>
          </>
        )}

        {/* ── Privacy / Cloud report ── */}
        {reportProduct !== 'isms' && productSummary && (() => {
          const polPct  = productSummary.groups > 0 ? (productSummary.policies / productSummary.groups) * 100 : 0
          const impPct  = productSummary.groups > 0 ? (productSummary.imps / (productSummary.groups * 2)) * 100 : 0
          const score   = Math.round((polPct + impPct) / 2)
          const rdStatus: 'green' | 'amber' | 'red' = score >= 90 ? 'green' : score >= 60 ? 'amber' : 'red'
          return (
          <>
            {/* Section 1 — Executive Summary */}
            <Box sx={{ mb: 4 }}>
              <Typography variant="h6" sx={{ color: '#003366', fontWeight: 700, mb: 1.5, textTransform: 'uppercase', letterSpacing: '0.06em', fontSize: '0.85rem' }}>
                1 — Executive Summary
              </Typography>

              <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, mb: 2 }}>
                <Box sx={{ px: 2.5, py: 1.5, borderRadius: 2, bgcolor: STATUS_BG[rdStatus], border: `1px solid ${STATUS_FG[rdStatus]}40` }}>
                  <Typography sx={{ fontSize: '2rem', fontWeight: 800, color: STATUS_FG[rdStatus], lineHeight: 1 }}>
                    {score}%
                  </Typography>
                  <Typography sx={{ fontSize: '0.7rem', color: STATUS_FG[rdStatus], opacity: 0.8, mt: 0.25 }}>
                    Composite Score
                  </Typography>
                </Box>
                <Box>
                  <Chip
                    label={STATUS_LABEL[rdStatus]}
                    size="small"
                    sx={{ bgcolor: STATUS_BG[rdStatus], color: STATUS_FG[rdStatus], fontWeight: 700, fontSize: '0.8rem', height: 26, mb: 0.5 }}
                  />
                  <Typography variant="body2" sx={{ color: '#555' }}>
                    {standardName} compliance posture
                  </Typography>
                </Box>
              </Box>

              <Table size="small" sx={{ width: 'auto' }}>
                <TableBody>
                  {[
                    { label: 'Control Groups',        value: productSummary.groups },
                    { label: 'Policies',              value: productSummary.policies },
                    { label: 'Implementation Guides', value: productSummary.imps },
                    { label: 'Policy Coverage',       value: pct(polPct) },
                    { label: 'IMP Coverage',          value: pct(impPct) },
                  ].map(({ label, value }) => (
                    <TableRow key={label}>
                      <TableCell sx={{ ...TD_STYLE, fontWeight: 600, width: 220 }}>{label}</TableCell>
                      <TableCell sx={TD_STYLE}>{value}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </Box>

            <Divider sx={{ borderColor: '#c8d0e0', mb: 4 }} />

            {/* Section 2 — Control Group Coverage */}
            {groups.length > 0 && (() => {
              // Group by section
              const bySection = groups.reduce<Record<string, { sectionName: string; rows: GroupRow[] }>>((acc, g) => {
                if (!acc[g.section]) acc[g.section] = { sectionName: g.section_name, rows: [] }
                acc[g.section].rows.push(g)
                return acc
              }, {})

              return (
                <Box sx={{ mb: 4 }}>
                  <Typography variant="h6" sx={{ color: '#003366', fontWeight: 700, mb: 1.5, textTransform: 'uppercase', letterSpacing: '0.06em', fontSize: '0.85rem' }}>
                    2 — Control Group Coverage
                  </Typography>
                  {Object.entries(bySection).map(([section, { sectionName, rows }]) => (
                    <Box key={section} sx={{ mb: 3 }}>
                      <Typography sx={{ fontWeight: 700, fontSize: '0.78rem', color: '#003366', mb: 0.75, display: 'flex', alignItems: 'center', gap: 1 }}>
                        <span style={{ fontFamily: 'monospace' }}>{section}</span>
                        <span style={{ color: '#555', fontWeight: 400 }}>— {sectionName}</span>
                      </Typography>
                      <Table size="small">
                        <TableHead>
                          <TableRow>
                            <TableCell sx={TH_STYLE}>Code</TableCell>
                            <TableCell sx={TH_STYLE}>Control Group</TableCell>
                            <TableCell sx={{ ...TH_STYLE, textAlign: 'center' }}>Policy</TableCell>
                          </TableRow>
                        </TableHead>
                        <TableBody>
                          {rows.map((g) => (
                            <TableRow key={g.id} sx={{ '&:nth-of-type(even)': { bgcolor: '#f7f9fc' } }}>
                              <TableCell sx={{ ...TD_STYLE, fontFamily: 'monospace', fontWeight: 700, whiteSpace: 'nowrap' }}>{g.group_code}</TableCell>
                              <TableCell sx={TD_STYLE}>{g.name}</TableCell>
                              <TableCell sx={{ ...TD_STYLE, textAlign: 'center' }}>
                                <Chip
                                  label={g.has_framework ? '✓' : '✗'}
                                  size="small"
                                  sx={{
                                    bgcolor: g.has_framework ? STATUS_BG.green : STATUS_BG.red,
                                    color:   g.has_framework ? STATUS_FG.green : STATUS_FG.red,
                                    fontSize: '0.65rem', height: 18, minWidth: 28,
                                  }}
                                />
                              </TableCell>
                            </TableRow>
                          ))}
                        </TableBody>
                      </Table>
                    </Box>
                  ))}
                </Box>
              )
            })()}
          </>
          )
        })()}

        {/* Footer */}
        <Divider sx={{ borderColor: '#c8d0e0', mb: 2 }} />
        <Typography variant="caption" sx={{ color: '#888', display: 'block', textAlign: 'center' }}>
          Generated by ISMS CORE · {standardName} · {generatedDate}
        </Typography>
      </Box>
    </Box>
  )
}

// isms-core-platform/frontend-angular/src/app/pages/report/report.component.ts
import { Component, inject, signal, computed } from '@angular/core'
import { DecimalPipe } from '@angular/common'
import { firstValueFrom } from 'rxjs'

import { injectQuery } from '@tanstack/angular-query-experimental'

import { MatCardModule } from '@angular/material/card'
import { MatButtonModule } from '@angular/material/button'
import { MatIconModule } from '@angular/material/icon'
import { MatChipsModule } from '@angular/material/chips'
import { MatButtonToggleModule } from '@angular/material/button-toggle'
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner'

import { DashboardApiService } from '../../api/dashboard-api.service'
import { ControlsApiService } from '../../api/controls-api.service'
import { ProductService, PRODUCT_COLORS, PRODUCT_LABELS, Product } from '../../core/services/product.service'
import { ProjectService } from '../../core/services/project.service'
import { ThemeService } from '../../core/services/theme.service'
import { PageHeaderComponent } from '../../shared/components/page-header.component'

// ── Types ─────────────────────────────────────────────────────────────────────

interface SectionRow {
  section: string
  section_name: string
  total_controls: number
  framework_covered: number
  operational_covered: number
  framework_pct: number
  operational_pct: number
}

interface RealOverview {
  total_controls: number
  total_policies: number
  total_implementations: number
  total_assessments: number
  total_gaps_open: number
  framework: { coverage_pct: number; has_policy: number; has_ug: number; has_tg: number; has_assessment: number }
  operational: { coverage_pct: number }
  sections: SectionRow[]
}

interface RealReadiness {
  policies_pct: number
  ug_pct: number
  tg_pct: number
  assessments_pct: number
  evidence_pct: number
  gaps_closed_pct: number
  composite_score: number
  status: 'green' | 'amber' | 'red'
}

interface GroupRow {
  id: string
  group_code: string
  name: string
  section: string
  section_name: string
  has_framework: boolean
  has_implementation: boolean
  product_family: string
}

// ── Constants ─────────────────────────────────────────────────────────────────

const STATUS_LABEL: Record<string, string> = {
  green: 'Compliant', amber: 'Partially Compliant', red: 'Non-Compliant',
}
const STATUS_BG_DARK: Record<string, string>  = { green: '#1a3a27', amber: '#3a2e00', red: '#3a0000' }
const STATUS_BG_LIGHT: Record<string, string> = { green: 'rgba(46,125,50,.12)', amber: 'rgba(230,160,0,.12)', red: 'rgba(192,0,0,.12)' }
const STATUS_FG_DARK: Record<string, string>  = { green: '#C6EFCE', amber: '#FFEB9C', red: '#FFC7CE' }
const STATUS_FG_LIGHT: Record<string, string> = { green: '#1b5e20', amber: '#7a4800', red: '#9e0000' }

const STANDARD_NAMES: Record<Product, string> = {
  isms:    'ISO/IEC 27001:2022',
  privacy: 'ISO/IEC 27701:2025',
  cloud:   'ISO/IEC 27018:2025',
  ai:      'ISO/IEC 42001:2023',
}
const HEADER_COLORS: Record<Product, string> = {
  isms:    '#4472C4',
  privacy: PRODUCT_COLORS.privacy,
  cloud:   PRODUCT_COLORS.cloud,
  ai:      PRODUCT_COLORS.ai,
}

function pct(v: number): string { return `${v.toFixed(0)}%` }

// ── Component ─────────────────────────────────────────────────────────────────

@Component({
  selector: 'app-report',
  standalone: true,
  imports: [
    DecimalPipe,
    MatCardModule, MatButtonModule, MatIconModule, MatChipsModule,
    MatButtonToggleModule, MatProgressSpinnerModule,
    PageHeaderComponent,
  ],
  template: `
<div class="report-root">

  <!-- Action bar (hidden in print) -->
  <div class="no-print action-bar">
    <mat-button-toggle-group [value]="reportProduct()" (change)="reportProduct.set($event.value)">
      @for (p of products; track p) {
        <mat-button-toggle [value]="p"
          [style.background]="reportProduct() === p ? headerColor(p) + '22' : undefined"
          [style.color]="reportProduct() === p ? headerColor(p) : undefined"
          class="product-toggle">
          {{ productLabel(p) }}
        </mat-button-toggle>
      }
    </mat-button-toggle-group>

    <button mat-flat-button color="primary" (click)="print()">
      <mat-icon>print</mat-icon> Print / Save as PDF
    </button>

    @if (reportProduct() === 'isms') {
      <button mat-stroked-button (click)="exportCsv()" [disabled]="!overviewQuery.data()">
        <mat-icon>file_download</mat-icon> Export CSV
      </button>
    }
  </div>

  <!-- Report body -->
  @if (isLoading()) {
    <div class="skeleton-wrap">
      @for (h of [80, 200, 300]; track h) {
        <div class="skeleton-block" [style.height.px]="h"></div>
      }
    </div>
  }

  @if (!isLoading()) {
    <div class="report-body">

      <!-- ══ Report header ══ -->
      <div class="report-header" [style.borderBottomColor]="headerColor(reportProduct())">
        <h1 class="report-title">ISMS CORE — {{ productLabel(reportProduct()) }} Compliance Report</h1>
        <div class="report-subtitle">{{ standardName(reportProduct()) }} · Generated {{ generatedDate }}</div>
      </div>

      <!-- ══ ISMS ══ -->
      @if (reportProduct() === 'isms') {
        @let ov = overviewQuery.data();
        @let rd = readinessQuery.data();

        <!-- 1 — Executive Summary -->
        <div class="report-section">
          <h2 class="section-heading">1 — Executive Summary</h2>
          @if (rd) {
            <div class="score-row">
              <div class="score-box" [style.background]="statusBg(rd.status)" [style.borderColor]="statusFg(rd.status) + '40'">
                <div class="score-value" [style.color]="statusFg(rd.status)">{{ rd.composite_score }}%</div>
                <div class="score-label" [style.color]="statusFg(rd.status)">Composite Score</div>
              </div>
              <div>
                <div class="status-chip" [style.background]="statusBg(rd.status)" [style.color]="statusFg(rd.status)">{{ statusLabel(rd.status) }}</div>
                <div class="posture-label">ISO/IEC 27001:2022 Annex A compliance posture</div>
              </div>
            </div>
          }
          <table class="summary-table">
            @for (row of ismsSummaryRows(); track row.label) {
              <tr><td class="td-label">{{ row.label }}</td><td class="td-value">{{ row.value }}</td></tr>
            }
          </table>
        </div>
        <hr class="section-divider">

        <!-- 2 — Coverage by Section -->
        @if (ov) {
          <div class="report-section">
            <h2 class="section-heading">2 — Coverage by Section</h2>
            <table class="data-table data-table--full">
              <thead>
                <tr>
                  <th class="th">Section</th>
                  <th class="th">Name</th>
                  <th class="th th--center">Controls</th>
                  <th class="th th--center">Framework %</th>
                  <th class="th th--center">Operational %</th>
                </tr>
              </thead>
              <tbody>
                @for (s of ov.sections; track s.section; let even = $even) {
                  <tr [class.tr-even]="even">
                    <td class="td td--mono td--bold">{{ s.section }}</td>
                    <td class="td">{{ s.section_name }}</td>
                    <td class="td td--center">{{ s.total_controls }}</td>
                    <td class="td td--center">{{ pct(s.framework_pct) }}</td>
                    <td class="td td--center">{{ pct(s.operational_pct) }}</td>
                  </tr>
                }
              </tbody>
            </table>
          </div>
          <hr class="section-divider">
        }

        <!-- 3 — Audit Readiness -->
        @if (rd) {
          <div class="report-section">
            <h2 class="section-heading">3 — Audit Readiness Breakdown</h2>
            <table class="data-table data-table--min400">
              <thead>
                <tr>
                  <th class="th">Component</th>
                  <th class="th th--center">Score</th>
                  <th class="th th--center">Status</th>
                </tr>
              </thead>
              <tbody>
                @for (r of ismsReadinessRows(); track r.name; let even = $even) {
                  <tr [class.tr-even]="even">
                    <td class="td td--bold">{{ r.name }}</td>
                    <td class="td td--center">{{ pct(r.value) }}</td>
                    <td class="td td--center">
                      <span class="status-badge"
                        [style.background]="statusBg(r.value >= 80 ? 'green' : r.value >= 50 ? 'amber' : 'red')"
                        [style.color]="statusFg(r.value >= 80 ? 'green' : r.value >= 50 ? 'amber' : 'red')">
                        {{ r.value >= 80 ? 'Good' : r.value >= 50 ? 'Partial' : 'Attention' }}
                      </span>
                    </td>
                  </tr>
                }
              </tbody>
            </table>
          </div>
          <hr class="section-divider">
        }

        <!-- 4 — Framework vs Operational -->
        @if (ov) {
          <div class="report-section">
            <h2 class="section-heading">4 — Framework vs Operational Coverage</h2>
            <table class="data-table data-table--min400">
              <thead>
                <tr>
                  <th class="th">Product</th>
                  <th class="th th--center">Total Controls</th>
                  <th class="th th--center">Coverage %</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td class="td td--bold">Framework</td>
                  <td class="td td--center">{{ ov.total_controls }}</td>
                  <td class="td td--center">{{ pct(ov.framework.coverage_pct) }}</td>
                </tr>
                <tr class="tr-even">
                  <td class="td td--bold">Operational</td>
                  <td class="td td--center">{{ ov.total_controls }}</td>
                  <td class="td td--center">{{ pct(ov.operational.coverage_pct) }}</td>
                </tr>
              </tbody>
            </table>
          </div>
        }
      }

      <!-- ══ Privacy / Cloud / AI — unified structure ══ -->
      @if (reportProduct() !== 'isms') {
        @let summary = productSummary();
        @let groups  = groupsQuery.data();

        @if (summary) {
          @let score     = Math.round((summary.pol_coverage_pct + summary.impl_coverage_pct) / 2);
          @let rdStatus  = score >= 90 ? 'green' : score >= 60 ? 'amber' : 'red';

          <!-- 1 — Executive Summary -->
          <div class="report-section">
            <h2 class="section-heading">1 — Executive Summary</h2>
            <div class="score-row">
              <div class="score-box" [style.background]="statusBg(rdStatus)" [style.borderColor]="statusFg(rdStatus) + '40'">
                <div class="score-value" [style.color]="statusFg(rdStatus)">{{ score }}%</div>
                <div class="score-label" [style.color]="statusFg(rdStatus)">Composite Score</div>
              </div>
              <div>
                <div class="status-chip" [style.background]="statusBg(rdStatus)" [style.color]="statusFg(rdStatus)">{{ statusLabel(rdStatus) }}</div>
                <div class="posture-label">{{ standardName(reportProduct()) }} compliance posture</div>
              </div>
            </div>
            <table class="summary-table">
              @for (row of extSummaryRowsComputed(); track row.label) {
                <tr><td class="td-label">{{ row.label }}</td><td class="td-value">{{ row.value }}</td></tr>
              }
            </table>
          </div>
          <hr class="section-divider">

          <!-- 2 — Coverage by Control Group -->
          @if (groups && groups.length > 0) {
            <div class="report-section">
              <h2 class="section-heading">2 — Coverage by Control Group</h2>
              @for (sec of bySection($any(groups)); track sec.section) {
                <div class="section-group">
                  <div class="section-group-header">
                    <span class="mono">{{ sec.section }}</span>
                    <span class="section-group-name">— {{ sec.section_name }}</span>
                  </div>
                  <table class="data-table data-table--full">
                    <thead>
                      <tr>
                        <th class="th th--code">Code</th>
                        <th class="th">Control Group</th>
                        <th class="th th--center th--badge">Policy</th>
                        <th class="th th--center th--badge">Implementation</th>
                      </tr>
                    </thead>
                    <tbody>
                      @for (g of sec.rows; track g.id; let even = $even) {
                        <tr [class.tr-even]="even">
                          <td class="td td--mono td--bold td--nowrap">{{ g.group_code }}</td>
                          <td class="td">{{ g.name }}</td>
                          <td class="td td--center">
                            <span class="status-badge"
                              [style.background]="statusBg(g.has_framework ? 'green' : 'red')"
                              [style.color]="statusFg(g.has_framework ? 'green' : 'red')">
                              {{ g.has_framework ? '✓' : '✗' }}
                            </span>
                          </td>
                          <td class="td td--center">
                            <span class="status-badge"
                              [style.background]="statusBg(g.has_implementation ? 'green' : 'red')"
                              [style.color]="statusFg(g.has_implementation ? 'green' : 'red')">
                              {{ g.has_implementation ? '✓' : '✗' }}
                            </span>
                          </td>
                        </tr>
                      }
                    </tbody>
                  </table>
                </div>
              }
            </div>
            <hr class="section-divider">
          }

          <!-- 3 — Audit Readiness Breakdown -->
          <div class="report-section">
            <h2 class="section-heading">3 — Audit Readiness Breakdown</h2>
            <table class="data-table data-table--min400">
              <thead>
                <tr>
                  <th class="th">Component</th>
                  <th class="th th--center">Score</th>
                  <th class="th th--center">Status</th>
                </tr>
              </thead>
              <tbody>
                @for (r of extReadinessRows(); track r.name; let even = $even) {
                  <tr [class.tr-even]="even">
                    <td class="td td--bold">{{ r.name }}</td>
                    <td class="td td--center">{{ pct(r.value) }}</td>
                    <td class="td td--center">
                      <span class="status-badge"
                        [style.background]="statusBg(r.value >= 80 ? 'green' : r.value >= 50 ? 'amber' : 'red')"
                        [style.color]="statusFg(r.value >= 80 ? 'green' : r.value >= 50 ? 'amber' : 'red')">
                        {{ r.value >= 80 ? 'Good' : r.value >= 50 ? 'Partial' : 'Attention' }}
                      </span>
                    </td>
                  </tr>
                }
              </tbody>
            </table>
          </div>
        }
      }

      <!-- Footer -->
      <hr class="footer-divider">
      <div class="report-footer">
        Generated by ISMS CORE · {{ standardName(reportProduct()) }} · {{ generatedDate }}
      </div>
    </div>
  }
</div>
`,
  styles: [`
    :host { display: block; }

    /* Layout */
    .report-root { padding: 0 4px; }
    .action-bar { display: flex; align-items: center; gap: 12px; margin-bottom: 24px; flex-wrap: wrap; }
    .product-toggle { font-size: .72rem; padding: 0 12px; }

    /* Skeleton loader */
    .skeleton-wrap { padding: 32px; }
    .skeleton-block { background: rgba(255,255,255,.06); border-radius: 8px; margin-bottom: 16px; }

    /* Report body */
    .report-body {
      background: white; color: #1a1a2e; padding: 40px; border-radius: 8px;
      max-width: 900px; margin: 0 auto; box-shadow: 0 2px 12px rgba(0,0,0,.18);
    }

    /* Report header */
    .report-header { margin-bottom: 24px; padding-bottom: 16px; border-bottom: 2px solid; }
    .report-title { color: #003366; font-weight: 700; margin: 0 0 4px; font-size: 1.4rem; }
    .report-subtitle { color: #555; font-size: .82rem; }

    /* Sections */
    .report-section { margin-bottom: 32px; }
    .section-heading {
      color: #003366; font-weight: 700; font-size: .85rem;
      text-transform: uppercase; letter-spacing: .06em; margin: 0 0 12px;
    }
    .section-divider { border: none; border-top: 1px solid #c8d0e0; margin-bottom: 32px; }

    /* Score / status */
    .score-row { display: flex; align-items: center; gap: 16px; margin-bottom: 16px; }
    .score-box { padding: 12px 20px; border-radius: 8px; border: 1px solid; }
    .score-value { font-size: 2rem; font-weight: 800; line-height: 1; }
    .score-label { font-size: .7rem; opacity: .8; margin-top: 2px; }
    .status-chip {
      display: inline-block; padding: 2px 10px; border-radius: 8px;
      font-weight: 700; font-size: .8rem; margin-bottom: 4px;
    }
    .posture-label { font-size: .82rem; color: #555; }

    /* Summary key-value table */
    .summary-table { border-collapse: collapse; font-size: .8rem; }
    .td-label {
      padding: 5px 12px 5px 0; font-weight: 600; color: #1a1a2e;
      min-width: 220px; border-bottom: 1px solid #e0e4ec;
    }
    .td-value { padding: 5px 0; color: #1a1a2e; border-bottom: 1px solid #e0e4ec; }

    /* Data tables */
    .data-table { border-collapse: collapse; font-size: .8rem; }
    .data-table--full { width: 100%; }
    .data-table--min400 { min-width: 400px; }

    .th {
      font-weight: 700; font-size: .78rem; color: #1a1a2e;
      background: #e8ecf4; border-bottom: 2px solid #c8d0e0;
      padding: 6px 12px; text-align: left;
    }
    .th--center { text-align: center; }
    .th--code { width: 110px; }
    .th--badge { width: 90px; }

    .td { font-size: .8rem; color: #1a1a2e; border-bottom: 1px solid #e0e4ec; padding: 6px 12px; }
    .td--center { text-align: center; }
    .td--bold { font-weight: 600; }
    .td--mono { font-family: monospace; }
    .td--nowrap { white-space: nowrap; }
    .tr-even { background: #f7f9fc; }

    /* Badges */
    .status-badge { padding: 1px 6px; border-radius: 6px; font-size: .65rem; font-weight: 600; }
    .policy-badge { padding: 1px 5px; border-radius: 6px; font-size: .65rem; font-weight: 600; }

    /* Section group (privacy/cloud/ai) */
    .section-group { margin-bottom: 24px; }
    .section-group-header { font-weight: 700; font-size: .78rem; color: #003366; margin-bottom: 6px; }
    .section-group-name { color: #555; font-weight: 400; margin-left: 8px; }
    .mono { font-family: monospace; }

    /* Footer */
    .footer-divider { border: none; border-top: 1px solid #c8d0e0; margin-bottom: 16px; }
    .report-footer { text-align: center; font-size: .72rem; color: #888; }

    @media print {
      .no-print { display: none !important; }
      .report-body { box-shadow: none !important; border-radius: 0 !important; max-width: 100% !important; }
    }
  `],
})
export class ReportComponent {
  private dashboard    = inject(DashboardApiService)
  private controls     = inject(ControlsApiService)
  readonly product     = inject(ProductService)
  private projectSvc   = inject(ProjectService)
  private theme        = inject(ThemeService)


  // ── State ──────────────────────────────────────────────────────────────────
  reportProduct  = signal<Product>(this.product.product())
  activeProjectId = computed(() => this.projectSvc.activeProjectId())
  readonly products: Product[] = ['isms', 'privacy', 'cloud', 'ai']
  readonly generatedDate = new Date().toLocaleDateString('en-GB', { year: 'numeric', month: 'long', day: 'numeric' })
  readonly Math = Math

  // Table cell styles (used in template as string interpolation)
  readonly TH = 'font-weight:700;font-size:.78rem;color:#1a1a2e;background:#e8ecf4;border-bottom:2px solid #c8d0e0;padding:6px 12px;text-align:left'
  readonly TD = 'font-size:.8rem;color:#1a1a2e;border-bottom:1px solid #e0e4ec;padding:6px 12px'

  // ── Queries ────────────────────────────────────────────────────────────────
  overviewQuery = injectQuery(() => ({
    queryKey: ['report', 'overview', this.activeProjectId()] as const,
    queryFn: () => firstValueFrom(this.dashboard.getOverview(this.activeProjectId())) as Promise<RealOverview>,
    enabled: this.reportProduct() === 'isms',
  }))

  readinessQuery = injectQuery(() => ({
    queryKey: ['report', 'readiness', this.activeProjectId()] as const,
    queryFn: () => firstValueFrom(this.dashboard.getAuditReadiness(this.activeProjectId())) as Promise<RealReadiness>,
    enabled: this.reportProduct() === 'isms',
  }))

  homeSummaryQuery = injectQuery(() => ({
    queryKey: ['home-summary'],
    queryFn: () => firstValueFrom(this.dashboard.getHomeSummary()),
  }))

  groupsQuery = injectQuery(() => ({
    queryKey: ['controls', 'list', this.reportProduct()],
    queryFn: () => firstValueFrom(this.controls.list({ product_family: this.reportProduct().toUpperCase() })),
    enabled: this.reportProduct() !== 'isms',
  }))

  // ── Computed ───────────────────────────────────────────────────────────────
  isDark = computed(() => this.theme.isDark())

  isLoading = computed((): boolean => {
    if (this.reportProduct() === 'isms') return this.overviewQuery.isLoading() || this.readinessQuery.isLoading()
    return this.homeSummaryQuery.isLoading() || this.groupsQuery.isLoading()
  })

  productSummary = computed(() => {
    const hs = this.homeSummaryQuery.data()
    const p = this.reportProduct()
    if (!hs) return null
    return (hs as any)[p] ?? null
  })

  ismsSummaryRows = computed(() => {
    const ov = this.overviewQuery.data()
    if (!ov) return []
    return [
      { label: 'Control Groups',       value: ov.total_controls ?? '—' },
      { label: 'Policies',             value: ov.total_policies ?? '—' },
      { label: 'Implementations',      value: ov.total_implementations ?? '—' },
      { label: 'Open Gaps',            value: ov.total_gaps_open ?? '—' },
      { label: 'Framework Coverage',   value: pct(ov.framework.coverage_pct) },
      { label: 'Operational Coverage', value: pct(ov.operational.coverage_pct) },
    ]
  })

  extSummaryRowsComputed = computed(() => {
    const s = this.productSummary()
    if (!s) return []
    return [
      { label: 'Control Groups',       value: s.groups },
      { label: 'Policies',             value: s.policies },
      { label: 'Implementations',      value: s.imps },
      { label: 'Open Gaps',            value: s.coverage_gaps },
      { label: 'Policy Coverage',      value: pct(s.pol_coverage_pct) },
      { label: 'Implementation Coverage', value: pct(s.impl_coverage_pct) },
    ]
  })

  ismsReadinessRows = computed(() => {
    const rd = this.readinessQuery.data()
    if (!rd) return []
    return [
      { name: 'Policies',       value: rd.policies_pct },
      { name: 'User Guides',    value: rd.ug_pct },
      { name: 'Tech Guides',    value: rd.tg_pct },
      { name: 'Assessments',    value: rd.assessments_pct },
      { name: 'Evidence',       value: rd.evidence_pct },
      { name: 'Gaps Closed',    value: rd.gaps_closed_pct },
    ]
  })

  extReadinessRows = computed(() => {
    const s = this.productSummary()
    if (!s) return []
    const gapsPct = s.groups > 0 ? Math.round(((s.groups - s.coverage_gaps) / s.groups) * 100) : 100
    return [
      { name: 'Policies',            value: s.pol_coverage_pct },
      { name: 'Implementations',     value: s.impl_coverage_pct },
      { name: 'Evidence',            value: s.evidence_coverage_pct },
      { name: 'Coverage Gaps Closed', value: gapsPct },
    ]
  })

  // ── Helpers ────────────────────────────────────────────────────────────────
  statusBg(s: string): string {
    return this.isDark() ? (STATUS_BG_DARK[s] ?? '#222') : (STATUS_BG_LIGHT[s] ?? 'rgba(0,0,0,.07)')
  }
  statusFg(s: string): string {
    return this.isDark() ? (STATUS_FG_DARK[s] ?? '#fff') : (STATUS_FG_LIGHT[s] ?? '#333')
  }
  statusLabel(s: string): string { return STATUS_LABEL[s] ?? s }
  headerColor(p: Product): string { return HEADER_COLORS[p] ?? '#4472C4' }
  productLabel(p: Product): string { return PRODUCT_LABELS[p] ?? p.toUpperCase() }
  standardName(p: Product): string { return STANDARD_NAMES[p] ?? '' }
  pct = pct

  bySection(groups: GroupRow[]): { section: string; section_name: string; rows: GroupRow[] }[] {
    const map: Record<string, { section: string; section_name: string; rows: GroupRow[] }> = {}
    for (const g of groups) {
      if (!map[g.section]) map[g.section] = { section: g.section, section_name: g.section_name, rows: [] }
      map[g.section].rows.push(g)
    }
    return Object.values(map)
  }

  // ── Actions ────────────────────────────────────────────────────────────────
  print(): void { window.print() }

  exportCsv(): void {
    const ov = this.overviewQuery.data()
    if (!ov) return
    const headers = ['section', 'section_name', 'total_controls', 'framework_covered', 'framework_pct', 'operational_covered', 'operational_pct']
    const rows = ov.sections.map(s => [
      s.section, s.section_name, s.total_controls, s.framework_covered,
      s.framework_pct.toFixed(1), s.operational_covered, s.operational_pct.toFixed(1),
    ])
    const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n')
    const today = new Date().toISOString().slice(0, 10).replace(/-/g, '')
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' }))
    const a = document.createElement('a'); a.href = url; a.download = `isms-report-${today}.csv`; a.click()
    URL.revokeObjectURL(url)
  }
}
