// isms-core-platform/frontend/src/components/Layout.tsx
import { useState } from 'react'
import { Box, Alert, Button, IconButton, Card, CardContent, Typography } from '@mui/material'
import { CloseOutlined, LockOutlined } from '@mui/icons-material'
import { Outlet, useNavigate, useLocation } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import Sidebar, { SIDEBAR_WIDTH, SIDEBAR_MINI_WIDTH } from './Sidebar'
import { getMfaStatus } from '../api/auth'
import { orgApi } from '../api/orgApi'
import { useAuth } from '../store/AuthContext'

function MfaBanner({ mfaEnforced }: { mfaEnforced: boolean }) {
  const { token } = useAuth()
  const navigate = useNavigate()
  const [dismissed, setDismissed] = useState(
    () => sessionStorage.getItem('mfa_banner_dismissed') === 'true'
  )

  const { data } = useQuery({
    queryKey: ['mfa-status'],
    queryFn: () => getMfaStatus(token!),
    enabled: !!token && !dismissed,
    staleTime: 5 * 60_000,
  })

  // Enforced mode — banner handled by Layout blocking screen
  if (mfaEnforced || dismissed || !data || data.mfa_enabled) return null

  return (
    <Alert
      severity="warning"
      action={
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
          <Button color="inherit" size="small" onClick={() => navigate('/system')}>
            Set up now
          </Button>
          <IconButton
            size="small"
            color="inherit"
            onClick={() => {
              sessionStorage.setItem('mfa_banner_dismissed', 'true')
              setDismissed(true)
            }}
          >
            <CloseOutlined fontSize="small" />
          </IconButton>
        </Box>
      }
      sx={{ borderRadius: 0, py: 0.5, flexShrink: 0 }}
    >
      Your account is not protected with two-factor authentication.
    </Alert>
  )
}

export default function Layout() {
  const { token } = useAuth()
  const navigate = useNavigate()
  const location = useLocation()
  const [collapsed, setCollapsed] = useState(
    () => localStorage.getItem('sidebarCollapsed') === 'true'
  )

  function handleToggle() {
    setCollapsed(v => {
      const next = !v
      localStorage.setItem('sidebarCollapsed', String(next))
      return next
    })
  }

  const { data: mfaData } = useQuery({
    queryKey: ['mfa-status'],
    queryFn: () => getMfaStatus(token!),
    enabled: !!token,
    staleTime: 5 * 60_000,
  })

  const { data: orgData } = useQuery({
    queryKey: ['organisation'],
    queryFn: orgApi.get,
    enabled: !!token,
    staleTime: 5 * 60_000,
  })

  const mfaEnforced = Boolean(orgData?.settings?.mfa_required)
  // Default mfaEnabled to true until data loads — avoids brief flash of enforcement screen
  const mfaEnabled = mfaData?.mfa_enabled ?? true
  // Allow /system through so they can actually set up MFA
  const showEnforcement = mfaEnforced && mfaData !== undefined && !mfaEnabled && !location.pathname.startsWith('/system')

  const sidebarProps = { collapsed, onToggle: handleToggle }

  return (
    <Box sx={{ display: 'flex', height: '100vh', overflow: 'hidden', bgcolor: 'background.default' }}>
      <Sidebar {...sidebarProps} />
      <Box
        component="main"
        sx={{
          ml: `${collapsed ? SIDEBAR_MINI_WIDTH : SIDEBAR_WIDTH}px`,
          flex: 1,
          minWidth: 0,
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          transition: 'margin-left 0.2s ease',
        }}
      >
        {showEnforcement ? (
          <Box sx={{ flex: 1, overflowY: 'auto', display: 'flex', alignItems: 'center', justifyContent: 'center', p: 3 }}>
            <Card sx={{ maxWidth: 440, width: '100%' }}>
              <CardContent sx={{ p: 4, textAlign: 'center' }}>
                <LockOutlined sx={{ fontSize: 48, color: 'error.main', mb: 2 }} />
                <Typography variant="h5" sx={{ mb: 1 }}>
                  Two-factor authentication required
                </Typography>
                <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
                  Your organisation requires all accounts to be protected with two-factor authentication before accessing the platform.
                </Typography>
                <Button variant="contained" size="large" onClick={() => navigate('/system')}>
                  Set up two-factor authentication
                </Button>
              </CardContent>
            </Card>
          </Box>
        ) : (
          <>
            <MfaBanner mfaEnforced={mfaEnforced} />
            <Box sx={{ flex: 1, overflowY: 'auto', p: 3 }}>
              <Outlet />
            </Box>
          </>
        )}
      </Box>
    </Box>
  )
}

// isms-core-platform/frontend-angular/src/app/layout/layout.component.ts
import { Component, signal, computed, inject } from '@angular/core'
import { RouterOutlet, Router } from '@angular/router'
import { injectQuery } from '@tanstack/angular-query-experimental'
import { HttpClient } from '@angular/common/http'
import { firstValueFrom } from 'rxjs'
import { MatIconModule } from '@angular/material/icon'
import { MatButtonModule } from '@angular/material/button'
import { MatCardModule } from '@angular/material/card'
import { AuthService } from '../core/services/auth.service'
import { AuthApiService } from '../api/auth-api.service'
import { TokenStoreService } from '../core/services/token-store.service'
import { SidebarComponent, SIDEBAR_WIDTH, SIDEBAR_MINI_WIDTH } from './sidebar/sidebar.component'
import { HealthAlertBannerComponent } from '../shared/components/health-alert-banner.component'

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [RouterOutlet, MatIconModule, MatButtonModule, MatCardModule, SidebarComponent, HealthAlertBannerComponent],
  template: `
    <div class="layout">
      <app-sidebar (collapsedChange)="onCollapsedChange($event)" />

      <main class="layout__main" [style.margin-left.px]="mainMargin()">
        <!-- MFA enforcement screen -->
        @if (showEnforcement()) {
          <div class="layout__enforcement">
            <mat-card class="enforcement-card">
              <mat-card-content>
                <mat-icon class="enforcement-card__icon">lock</mat-icon>
                <h2>Two-factor authentication required</h2>
                <p>Your organisation requires all accounts to be protected with two-factor authentication before accessing the platform.</p>
                <button mat-flat-button color="primary" (click)="router.navigate(['/system'])">
                  Set up two-factor authentication
                </button>
              </mat-card-content>
            </mat-card>
          </div>
        } @else {
          <!-- MFA nudge banner -->
          @if (showMfaBanner()) {
            <div class="mfa-banner">
              <span>Your account is not protected with two-factor authentication.</span>
              <button mat-button color="primary" size="small" (click)="router.navigate(['/system'])">Set up now</button>
              <button mat-icon-button (click)="dismissMfaBanner()"><mat-icon>close</mat-icon></button>
            </div>
          }

          <app-health-alert-banner />

          <div class="layout__content">
            <router-outlet />
          </div>
        }
      </main>
    </div>
  `,
  styles: [`
    .layout {
      display: flex;
      height: 100vh;
      overflow: hidden;
      background: var(--mat-sys-surface);
    }

    .layout__main {
      flex: 1;
      min-width: 0;
      height: 100%;
      display: flex;
      flex-direction: column;
      transition: margin-left 0.2s ease;
      overflow: hidden;
    }

    .layout__content {
      flex: 1;
      overflow-y: auto;
      padding: 24px 24px 48px;
    }

    .layout__enforcement {
      flex: 1;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 24px;
    }

    .enforcement-card {
      max-width: 440px;
      width: 100%;
      text-align: center;
    }
    mat-card-content {
      padding: 32px !important;
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 16px;
    }
    .enforcement-card__icon {
      font-size: 48px; width: 48px; height: 48px;
      color: var(--mat-sys-error);
    }
    .enforcement-card h2 { margin: 0; font-size: 1.25rem; }
    .enforcement-card p { margin: 0; color: var(--mat-sys-on-surface-variant); font-size: 0.875rem; }

    .mfa-banner {
      display: flex; align-items: center; gap: 8px;
      padding: 6px 16px;
      background: var(--mat-sys-warning-container, #3d3200);
      color: var(--mat-sys-on-warning-container, #FFEB9C);
      font-size: 0.875rem;
      flex-shrink: 0;
    }
    .mfa-banner span { flex: 1; }
  `],
})
export class LayoutComponent {
  auth = inject(AuthService)
  router = inject(Router)
  private http = inject(HttpClient)
  private authApi = inject(AuthApiService)
  private tokenStore = inject(TokenStoreService)

  sidebarCollapsed = signal(localStorage.getItem('sidebarCollapsed') === 'true')
  mfaBannerDismissed = signal(sessionStorage.getItem('mfa_banner_dismissed') === 'true')

  mainMargin = computed(() => this.sidebarCollapsed() ? SIDEBAR_MINI_WIDTH : SIDEBAR_WIDTH)

  private mfaQuery = injectQuery(() => ({
    queryKey: ['mfa-status'],
    queryFn: () => this.authApi.getMfaStatus(this.tokenStore.get() ?? ''),
    enabled: !!this.auth.user(),
    staleTime: 5 * 60_000,
  }))

  private orgQuery = injectQuery(() => ({
    queryKey: ['organisation'],
    queryFn: () => firstValueFrom(this.http.get<{ settings: Record<string, unknown> }>('/api/v1/organisation/')),
    enabled: !!this.auth.user(),
    staleTime: 5 * 60_000,
  }))

  mfaEnforced = computed(() => Boolean(this.orgQuery.data()?.settings?.['mfa_required']))
  mfaEnabled = computed(() => this.mfaQuery.data()?.mfa_enabled ?? true)

  showEnforcement = computed(() => {
    if (!this.mfaEnforced()) return false
    if (this.mfaQuery.data() === undefined) return false
    if (this.mfaEnabled()) return false
    return !this.router.url.startsWith('/system')
  })

  showMfaBanner = computed(() => {
    if (this.mfaEnforced()) return false
    if (this.mfaBannerDismissed()) return false
    if (this.mfaQuery.data() === undefined) return false
    return !this.mfaEnabled()
  })

  onCollapsedChange(collapsed: boolean) {
    this.sidebarCollapsed.set(collapsed)
  }

  dismissMfaBanner() {
    sessionStorage.setItem('mfa_banner_dismissed', 'true')
    this.mfaBannerDismissed.set(true)
  }
}
