// isms-core-platform/frontend/src/pages/CollectionDetail.tsx
import { useState } from 'react'
import { useTheme } from '@mui/material/styles'
import { useParams, useNavigate } from 'react-router-dom'
import {
  Box, Button, Card, CardContent, Chip, Collapse, Dialog, DialogActions,
  DialogContent, DialogTitle, IconButton, LinearProgress, Skeleton, Table,
  TableBody, TableCell, TableContainer, TableHead, TableRow, Tooltip,
  Typography, Alert, Checkbox, TextField,
} from '@mui/material'
import {
  ArrowBackOutlined, CalendarTodayOutlined, DeleteOutlined, DownloadOutlined,
  ExpandLessOutlined, ExpandMoreOutlined, PersonAddOutlined, PersonRemoveOutlined,
} from '@mui/icons-material'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { collectionsApi, CollectionMember } from '../api/collectionsApi'
import { assessmentsApi } from '../api/assessmentsApi'
import { client } from '../api/client'
import PageHeader from '../components/PageHeader'

// ── Helpers ─────────────────────────────────────────────────────────────────

function scoreColor(pct: number): string {
  if (pct >= 80) return '#70AD47'
  if (pct >= 50) return '#FFC000'
  return '#FF5252'
}

function statusChipProps(status: string, isLight: boolean) {
  switch (status) {
    case 'complete':    return { label: 'Complete',    bg: isLight ? 'rgba(27,94,32,0.1)'  : 'rgba(198,239,206,0.15)', color: isLight ? '#1b5e20' : '#C6EFCE' }
    case 'in_progress': return { label: 'In Progress', bg: 'rgba(255,192,0,0.12)',          color: '#856404' }
    default:            return { label: 'Not Started', bg: isLight ? 'rgba(0,0,0,0.06)'    : 'rgba(255,255,255,0.06)', color: isLight ? '#555' : '#888' }
  }
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

// ── NC items sub-table ───────────────────────────────────────────────────────

function NcItems({ member }: { member: CollectionMember }) {
  const [open, setOpen] = useState(false)
  if (member.items_non_compliant === 0) return null
  return (
    <Box>
      <Button
        size="small"
        variant="text"
        onClick={() => setOpen(v => !v)}
        endIcon={open ? <ExpandLessOutlined sx={{ fontSize: 14 }} /> : <ExpandMoreOutlined sx={{ fontSize: 14 }} />}
        sx={{ fontSize: '0.7rem', color: '#FF5252', py: 0.25, px: 0.75, minWidth: 0 }}
      >
        {member.items_non_compliant} non-compliant
      </Button>
      <Collapse in={open}>
        <Box sx={{ ml: 1, mt: 0.5, p: 1, bgcolor: 'rgba(255,82,82,0.04)', borderRadius: 1, border: '1px solid rgba(255,82,82,0.1)' }}>
          <Typography variant="caption" color="text.disabled">
            Non-compliant item details visible in the export report.
          </Typography>
        </Box>
      </Collapse>
    </Box>
  )
}

// ── Manage assessments dialog ────────────────────────────────────────────────

function ManageAssessmentsDialog({
  open, onClose, collectionId, collectionProductFamily, currentMemberIds,
}: {
  open: boolean
  onClose: () => void
  collectionId: string
  collectionProductFamily: string
  currentMemberIds: Set<string>
}) {
  const { palette } = useTheme()
  const isLight = palette.mode === 'light'
  const qc = useQueryClient()
  const [search, setSearch] = useState('')

  const { data: allAssessments = [] } = useQuery({
    queryKey: ['assessments-for-collection', collectionProductFamily],
    queryFn: () => assessmentsApi.list({ product_family: collectionProductFamily }),
    enabled: open,
  })

  const addMutation = useMutation({
    mutationFn: (assessmentId: string) => collectionsApi.addAssessment(collectionId, assessmentId),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['collection', collectionId] }),
  })

  const removeMutation = useMutation({
    mutationFn: (assessmentId: string) => collectionsApi.removeAssessment(collectionId, assessmentId),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['collection', collectionId] }),
  })

  const filtered = allAssessments.filter(a => {
    if (!search) return true
    const q = search.toLowerCase()
    return (
      a.document_id.toLowerCase().includes(q) ||
      a.workbook_name.toLowerCase().includes(q) ||
      a.group_code.toLowerCase().includes(q)
    )
  })

  return (
    <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth>
      <DialogTitle>Manage Assessments</DialogTitle>
      <DialogContent sx={{ pt: '8px !important', display: 'flex', flexDirection: 'column', gap: 1.5 }}>
        <TextField
          size="small"
          placeholder="Search assessments…"
          value={search}
          onChange={e => setSearch(e.target.value)}
          fullWidth
        />
        <Box sx={{ maxHeight: 380, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 0.5 }}>
          {filtered.map(a => {
            const inCollection = currentMemberIds.has(a.id)
            return (
              <Box
                key={a.id}
                sx={{
                  display: 'flex', alignItems: 'center', gap: 1, p: 1, borderRadius: 1,
                  border: '1px solid',
                  borderColor: inCollection ? 'rgba(68,114,196,0.3)' : (isLight ? 'rgba(0,0,0,0.1)' : 'rgba(255,255,255,0.07)'),
                  bgcolor: inCollection ? 'rgba(68,114,196,0.06)' : 'transparent',
                }}
              >
                <Checkbox
                  size="small"
                  checked={inCollection}
                  onChange={() => {
                    if (inCollection) removeMutation.mutate(a.id)
                    else addMutation.mutate(a.id)
                  }}
                  sx={{ p: 0.25 }}
                />
                <Box sx={{ flex: 1, minWidth: 0 }}>
                  <Typography variant="caption" sx={{ fontFamily: 'monospace', color: 'primary.light', fontSize: '0.7rem' }}>
                    {a.document_id}
                  </Typography>
                  <Typography variant="body2" noWrap sx={{ lineHeight: 1.3 }}>{a.workbook_name}</Typography>
                  <Typography variant="caption" color="text.disabled">{a.group_code.toUpperCase()} — {a.group_name}</Typography>
                </Box>
                <Chip label={a.product_type} size="small" sx={{ fontSize: '0.6rem', height: 16 }} />
              </Box>
            )
          })}
          {filtered.length === 0 && (
            <Typography variant="body2" color="text.secondary" sx={{ py: 2, textAlign: 'center' }}>
              No assessments found.
            </Typography>
          )}
        </Box>
      </DialogContent>
      <DialogActions>
        <Button onClick={onClose} size="small">Done</Button>
      </DialogActions>
    </Dialog>
  )
}

// ── Main page ────────────────────────────────────────────────────────────────

export default function CollectionDetail() {
  const { palette } = useTheme()
  const isLight = palette.mode === 'light'
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const qc = useQueryClient()
  const [manageOpen, setManageOpen] = useState(false)
  const [downloading, setDownloading] = useState<string | null>(null)

  const { data: coll, isLoading, error } = useQuery({
    queryKey: ['collection', id],
    queryFn: () => collectionsApi.get(id!),
    enabled: !!id,
  })

  async function handleExport(format: 'csv' | 'xlsx' | 'pdf') {
    if (!id) return
    setDownloading(format)
    try {
      const mimeTypes: Record<string, string> = {
        csv: 'text/csv',
        xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        pdf: 'application/pdf',
      }
      const resp = await client.get(collectionsApi.exportUrl(id, format), {
        responseType: 'blob',
      })
      const filename = `collection_${(coll?.name ?? 'export').replace(/\s+/g, '_')}.${format}`
      triggerDownload(new Blob([resp.data], { type: mimeTypes[format] }), filename)
    } catch {
      // silently fail; user can retry
    } finally {
      setDownloading(null)
    }
  }

  if (isLoading) {
    return (
      <Box>
        <Skeleton variant="rectangular" height={60} sx={{ borderRadius: 2, mb: 2 }} />
        <Skeleton variant="rectangular" height={120} sx={{ borderRadius: 2, mb: 2 }} />
        <Skeleton variant="rectangular" height={300} sx={{ borderRadius: 2 }} />
      </Box>
    )
  }

  if (error || !coll) {
    return (
      <Box>
        <Button startIcon={<ArrowBackOutlined />} onClick={() => navigate('/assessments')} sx={{ mb: 2 }}>
          Back to Assessments
        </Button>
        <Alert severity="error">Collection not found or failed to load.</Alert>
      </Box>
    )
  }

  const stats = coll.stats
  const statusProps = statusChipProps(stats.status, isLight)
  const memberIds = new Set(coll.members.map(m => m.assessment_id))

  return (
    <Box>
      <PageHeader
        title={coll.name}
        subtitle={`${coll.product_family}${coll.product_type ? ' / ' + coll.product_type : ''} · Assessment Collection`}
        actions={
          <Box sx={{ display: 'flex', gap: 1 }}>
            <Button size="small" variant="outlined" startIcon={<ArrowBackOutlined />}
              onClick={() => navigate('/assessments')} sx={{ fontSize: '0.75rem' }}>
              Back
            </Button>
            <Button size="small" variant="outlined" startIcon={<PersonAddOutlined />}
              onClick={() => setManageOpen(true)} sx={{ fontSize: '0.75rem' }}>
              Manage Assessments
            </Button>
            <Button size="small" variant="outlined" startIcon={<DownloadOutlined />}
              disabled={!!downloading}
              onClick={() => handleExport('csv')} sx={{ fontSize: '0.75rem' }}>
              {downloading === 'csv' ? 'Exporting…' : 'CSV'}
            </Button>
            <Button size="small" variant="outlined" startIcon={<DownloadOutlined />}
              disabled={!!downloading}
              onClick={() => handleExport('xlsx')} sx={{ fontSize: '0.75rem' }}>
              {downloading === 'xlsx' ? 'Exporting…' : 'XLSX'}
            </Button>
            <Button size="small" variant="contained" startIcon={<DownloadOutlined />}
              disabled={!!downloading}
              onClick={() => handleExport('pdf')} sx={{ fontSize: '0.75rem' }}>
              {downloading === 'pdf' ? 'Exporting…' : 'PDF'}
            </Button>
          </Box>
        }
      />

      {/* ── Stats bar ── */}
      <Card sx={{ mb: 2.5, bgcolor: 'rgba(68,114,196,0.04)', border: '1px solid rgba(68,114,196,0.12)' }}>
        <CardContent sx={{ p: '16px !important' }}>
          <Box sx={{ display: 'flex', gap: 4, flexWrap: 'wrap', alignItems: 'center' }}>

            {/* Status */}
            <Box>
              <Typography variant="caption" color="text.disabled" sx={{ display: 'block', mb: 0.5 }}>Status</Typography>
              <Chip label={statusProps.label} size="small"
                sx={{ bgcolor: statusProps.bg, color: statusProps.color, fontWeight: 700, fontSize: '0.72rem' }} />
            </Box>

            {/* Assessments completion */}
            <Box sx={{ flex: 1, minWidth: 180 }}>
              <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 0.5 }}>
                <Typography variant="caption" color="text.secondary">Completion</Typography>
                <Typography variant="caption" sx={{ color: 'primary.light', fontWeight: 700 }}>
                  {stats.started}/{stats.total} assessments · {stats.completion_pct}%
                </Typography>
              </Box>
              <LinearProgress
                variant="determinate"
                value={Math.min(100, stats.completion_pct)}
                sx={{ height: 6, borderRadius: 3, bgcolor: isLight ? 'rgba(0,0,0,0.08)' : 'rgba(255,255,255,0.06)',
                  '& .MuiLinearProgress-bar': { bgcolor: 'primary.light' } }}
              />
            </Box>

            {/* Compliance score */}
            <Box sx={{ flex: 1, minWidth: 180 }}>
              <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 0.5 }}>
                <Typography variant="caption" color="text.secondary">Compliance Score</Typography>
                <Typography variant="caption" sx={{ color: scoreColor(stats.compliance_pct), fontWeight: 700 }}>
                  {stats.compliance_pct}%
                </Typography>
              </Box>
              <LinearProgress
                variant="determinate"
                value={Math.min(100, stats.compliance_pct)}
                sx={{ height: 6, borderRadius: 3, bgcolor: isLight ? 'rgba(0,0,0,0.08)' : 'rgba(255,255,255,0.06)',
                  '& .MuiLinearProgress-bar': { bgcolor: scoreColor(stats.compliance_pct) } }}
              />
            </Box>

            {/* Counts */}
            <Box sx={{ display: 'flex', gap: 2 }}>
              <Box sx={{ textAlign: 'center' }}>
                <Typography variant="h6" sx={{ color: '#70AD47', fontWeight: 700, lineHeight: 1 }}>{stats.items_compliant}</Typography>
                <Typography variant="caption" color="text.disabled">Compliant</Typography>
              </Box>
              <Box sx={{ textAlign: 'center' }}>
                <Typography variant="h6" sx={{ color: '#FF5252', fontWeight: 700, lineHeight: 1 }}>{stats.items_non_compliant}</Typography>
                <Typography variant="caption" color="text.disabled">Non-Compliant</Typography>
              </Box>
              <Box sx={{ textAlign: 'center' }}>
                <Typography variant="h6" sx={{ color: 'text.secondary', fontWeight: 700, lineHeight: 1 }}>{stats.items_total}</Typography>
                <Typography variant="caption" color="text.disabled">Total Items</Typography>
              </Box>
            </Box>

            {/* Due date */}
            {coll.due_date && (
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
                <CalendarTodayOutlined sx={{ fontSize: 14, color: 'text.disabled' }} />
                <Typography variant="caption" color="text.secondary">Due {coll.due_date}</Typography>
              </Box>
            )}
          </Box>

          {/* Description */}
          {coll.description && (
            <Typography variant="body2" color="text.secondary" sx={{ mt: 1.5, fontStyle: 'italic' }}>
              {coll.description}
            </Typography>
          )}
        </CardContent>
      </Card>

      {/* ── Members table ── */}
      <Box sx={{ mb: 3 }}>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1.5 }}>
          <Typography variant="subtitle2" fontWeight={700} color="primary.light">
            Assessments
          </Typography>
          <Chip label={coll.members.length} size="small" sx={{ fontSize: '0.65rem', height: 18 }} />
        </Box>

        {coll.members.length === 0 ? (
          <Box
            onClick={() => setManageOpen(true)}
            sx={{
              p: 3, borderRadius: 2, textAlign: 'center', cursor: 'pointer',
              border: '1px dashed rgba(68,114,196,0.3)', bgcolor: 'rgba(68,114,196,0.03)',
              '&:hover': { bgcolor: 'rgba(68,114,196,0.07)', borderColor: 'rgba(68,114,196,0.5)' },
            }}
          >
            <PersonAddOutlined sx={{ color: 'text.disabled', mb: 0.5 }} />
            <Typography variant="body2" color="text.secondary">
              No assessments in this collection yet.
            </Typography>
            <Typography variant="caption" color="primary.light" sx={{ mt: 0.5, display: 'block' }}>
              Click to add assessments
            </Typography>
          </Box>
        ) : (
          <TableContainer component={Card}>
            <Table size="small">
              <TableHead>
                <TableRow>
                  <TableCell sx={{ width: 100 }}>Control Group</TableCell>
                  <TableCell>Workbook</TableCell>
                  <TableCell sx={{ width: 80 }}>Product</TableCell>
                  <TableCell sx={{ width: 60, textAlign: 'right' }}>Items</TableCell>
                  <TableCell sx={{ width: 80, textAlign: 'right' }}>Compliant</TableCell>
                  <TableCell sx={{ width: 100, textAlign: 'right' }}>Non-Compliant</TableCell>
                  <TableCell sx={{ width: 90, textAlign: 'right' }}>Score</TableCell>
                  <TableCell sx={{ width: 44 }} />
                </TableRow>
              </TableHead>
              <TableBody>
                {coll.members.map((m: CollectionMember) => (
                  <TableRow key={m.assessment_id} hover>
                    <TableCell>
                      <Typography variant="caption" sx={{ fontFamily: 'monospace', color: 'primary.light', fontWeight: 700 }}>
                        {m.group_code}
                      </Typography>
                      <Typography variant="caption" color="text.disabled" sx={{ display: 'block', fontSize: '0.62rem' }}>
                        {m.group_name}
                      </Typography>
                    </TableCell>
                    <TableCell>
                      <Typography variant="caption" sx={{ fontFamily: 'monospace', color: 'text.disabled', fontSize: '0.68rem' }}>
                        {m.document_id}
                      </Typography>
                      <Typography variant="body2" fontWeight={600} sx={{ lineHeight: 1.3 }}>{m.workbook_name}</Typography>
                      <NcItems member={m} />
                    </TableCell>
                    <TableCell>
                      <Chip label={m.product_type} size="small" sx={{ fontSize: '0.6rem', height: 16 }} />
                    </TableCell>
                    <TableCell align="right">
                      <Typography variant="caption">{m.items_total}</Typography>
                    </TableCell>
                    <TableCell align="right">
                      <Typography variant="caption" sx={{ color: m.items_compliant > 0 ? '#70AD47' : 'text.disabled' }}>
                        {m.items_compliant}
                      </Typography>
                    </TableCell>
                    <TableCell align="right">
                      <Typography variant="caption" sx={{ color: m.items_non_compliant > 0 ? '#FF5252' : 'text.disabled' }}>
                        {m.items_non_compliant}
                      </Typography>
                    </TableCell>
                    <TableCell align="right">
                      {m.items_total > 0 ? (
                        <Typography variant="caption" sx={{ color: scoreColor(m.compliance_pct), fontWeight: 700 }}>
                          {m.compliance_pct}%
                        </Typography>
                      ) : (
                        <Typography variant="caption" color="text.disabled">—</Typography>
                      )}
                    </TableCell>
                    <TableCell>
                      <Tooltip title="Remove from collection">
                        <IconButton
                          size="small"
                          onClick={() => {
                            collectionsApi.removeAssessment(coll.id, m.assessment_id)
                              .then(() => qc.invalidateQueries({ queryKey: ['collection', id] }))
                          }}
                          sx={{ color: 'error.main', opacity: 0.4, '&:hover': { opacity: 1 } }}
                        >
                          <PersonRemoveOutlined sx={{ fontSize: 15 }} />
                        </IconButton>
                      </Tooltip>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        )}
      </Box>

      {/* ── Manage dialog ── */}
      {manageOpen && (
        <ManageAssessmentsDialog
          open={manageOpen}
          onClose={() => {
            setManageOpen(false)
            qc.invalidateQueries({ queryKey: ['collection', id] })
          }}
          collectionId={coll.id}
          collectionProductFamily={coll.product_family}
          currentMemberIds={memberIds}
        />
      )}
    </Box>
  )
}

// isms-core-platform/frontend-angular/src/app/pages/collection-detail/collection-detail.component.ts
import { Component, inject, signal, computed } from '@angular/core'
import { ActivatedRoute, Router } from '@angular/router'
import { FormsModule } from '@angular/forms'
import { firstValueFrom } from 'rxjs'
import { HttpClient } from '@angular/common/http'

import { injectQuery, injectMutation, injectQueryClient } from '@tanstack/angular-query-experimental'

import { MatCardModule } from '@angular/material/card'
import { MatButtonModule } from '@angular/material/button'
import { MatIconModule } from '@angular/material/icon'
import { MatChipsModule } from '@angular/material/chips'
import { MatProgressBarModule } from '@angular/material/progress-bar'
import { MatTableModule } from '@angular/material/table'
import { MatTooltipModule } from '@angular/material/tooltip'
import { MatDialogModule, MatDialog } from '@angular/material/dialog'
import { MatFormFieldModule } from '@angular/material/form-field'
import { MatInputModule } from '@angular/material/input'
import { MatCheckboxModule } from '@angular/material/checkbox'
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner'
import { MatDividerModule } from '@angular/material/divider'

import {
  CollectionsApiService,
  CollectionRead,
  CollectionMember,
  CollectionListItem,
} from '../../api/collections-api.service'
import { ThemeService } from '../../core/services/theme.service'
import { PageHeaderComponent } from '../../shared/components/page-header.component'

// ── Types ─────────────────────────────────────────────────────────────────────

interface AssessmentListItem {
  id: string
  document_id: string
  workbook_name: string
  group_code: string
  group_name: string
  product_type: string
  items_total: number
  items_compliant: number
  items_non_compliant: number
  compliance_pct: number
  overall_score: number | null
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function scoreColor(pct: number): string {
  if (pct >= 80) return '#70AD47'
  if (pct >= 50) return '#FFC000'
  return '#FF5252'
}

function statusConfig(status: string): { label: string; bg: string; color: string } {
  switch (status) {
    case 'complete':    return { label: 'Complete',    bg: 'rgba(198,239,206,0.15)', color: '#C6EFCE' }
    case 'in_progress': return { label: 'In Progress', bg: 'rgba(255,192,0,0.12)',   color: '#856404' }
    default:            return { label: 'Not Started', bg: 'rgba(255,255,255,0.06)', color: '#888' }
  }
}

// ── Component ─────────────────────────────────────────────────────────────────

@Component({
  selector: 'app-collection-detail',
  standalone: true,
  imports: [
    FormsModule,
    MatCardModule, MatButtonModule, MatIconModule, MatChipsModule,
    MatProgressBarModule, MatTableModule, MatTooltipModule,
    MatDialogModule, MatFormFieldModule, MatInputModule,
    MatCheckboxModule, MatProgressSpinnerModule, MatDividerModule,
    PageHeaderComponent,
  ],
  styles: [`
    :host { display: block; padding-bottom: 40px; }

    .stats-card {
      padding: 16px;
      background: rgba(68,114,196,0.04);
      border: 1px solid rgba(68,114,196,0.12);
      border-radius: 8px;
      margin-bottom: 20px;
    }
    .stats-row { display: flex; gap: 32px; flex-wrap: wrap; align-items: center; }

    .bar-wrapper { flex: 1; min-width: 180px; }
    .bar-header { display: flex; justify-content: space-between; margin-bottom: 4px; font-size: 0.78rem; }

    .count-col { text-align: center; }
    .count-val { font-size: 1.1rem; font-weight: 700; line-height: 1; margin-bottom: 2px; }
    .count-label { font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); }

    .section-header {
      display: flex; align-items: center; gap: 8px; margin-bottom: 12px;
    }

    .empty-box {
      padding: 24px; border-radius: 8px; text-align: center; cursor: pointer;
      border: 1px dashed rgba(68,114,196,0.3); background: rgba(68,114,196,0.03);
      transition: background 0.15s, border-color 0.15s;
    }
    .empty-box:hover { background: rgba(68,114,196,0.07); border-color: rgba(68,114,196,0.5); }

    .nc-expand-btn {
      font-size: 0.7rem; color: #FF5252; cursor: pointer; background: none; border: none;
      padding: 2px 6px; display: inline-flex; align-items: center; gap: 4px;
    }
    .nc-box {
      margin-left: 8px; margin-top: 4px; padding: 8px;
      background: rgba(255,82,82,0.04); border-radius: 4px;
      border: 1px solid rgba(255,82,82,0.1);
      font-size: 0.72rem; color: var(--mat-sys-on-surface-variant);
    }

    /* Manage dialog overlay */
    .overlay-backdrop {
      position: fixed; inset: 0; background: rgba(0,0,0,0.5); z-index: 900;
    }
    .manage-dialog {
      position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);
      width: 560px; max-width: 100vw; max-height: 80vh;
      background: var(--mat-sys-surface); border-radius: 8px; z-index: 901;
      display: flex; flex-direction: column; box-shadow: 0 8px 32px rgba(0,0,0,0.4);
    }
    .manage-dialog-header {
      padding: 16px 20px; border-bottom: 1px solid var(--mat-sys-outline-variant);
      font-size: 1rem; font-weight: 700;
    }
    .manage-dialog-body { flex: 1; overflow-y: auto; padding: 12px 16px; }
    .manage-dialog-footer {
      padding: 10px 16px; border-top: 1px solid var(--mat-sys-outline-variant);
      display: flex; justify-content: flex-end;
    }

    .assessment-row {
      display: flex; align-items: center; gap: 8px; padding: 8px;
      border-radius: 4px; border: 1px solid var(--mat-sys-outline-variant);
      margin-bottom: 6px; cursor: pointer;
      transition: background 0.1s, border-color 0.1s;
    }
    .assessment-row.in-collection {
      border-color: rgba(68,114,196,0.3);
      background: rgba(68,114,196,0.06);
    }
    .assessment-row:hover { background: rgba(0,0,0,0.04); }
    .assessment-row.in-collection:hover { background: rgba(68,114,196,0.1); }

    table { width: 100%; }
    .doc-id { font-family: monospace; font-size: 0.7rem; color: var(--mat-sys-on-surface-variant); }

    /* Spinner / error states */
    .spinner-center { display: flex; justify-content: center; padding: 40px; }
    .error-wrap { padding: 16px; }
    .error-box {
      padding: 12px; border-radius: 6px;
      background: rgba(244,67,54,0.1); color: #f44336; margin-top: 12px;
    }

    /* Stats bar extras */
    .status-label { font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); margin-bottom: 4px; }
    .status-chip { font-size: 0.72rem; font-weight: 700; padding: 3px 10px; border-radius: 12px; }
    .bar-completion-label { color: var(--mat-sys-on-surface-variant); }
    .bar-score-label { font-weight: 700; color: var(--mat-sys-primary); }
    .progress-bar { height: 6px; border-radius: 3px; }
    .counts-row { display: flex; gap: 24px; }
    .count-val-compliant { color: #70AD47; }
    .count-val-noncompliant { color: #FF5252; }
    .count-val-total { color: var(--mat-sys-on-surface-variant); }
    .due-date-row { display: flex; align-items: center; gap: 4px; }
    .due-date-text { font-size: 0.78rem; color: var(--mat-sys-on-surface-variant); }
    .description-text { margin-top: 12px; font-size: 0.85rem; color: var(--mat-sys-on-surface-variant); font-style: italic; }

    /* Members table */
    .section-title { font-weight: 700; color: var(--mat-sys-primary); font-size: 0.9rem; }
    .section-count {
      font-size: 0.65rem; padding: 1px 7px; border-radius: 10px;
      background: var(--mat-sys-surface-variant);
    }
    .empty-icon { color: var(--mat-sys-on-surface-variant); display: block; margin-bottom: 4px; }
    .empty-text { color: var(--mat-sys-on-surface-variant); font-size: 0.88rem; }
    .empty-cta { color: var(--mat-sys-primary); font-size: 0.78rem; margin-top: 4px; }
    .group-code { font-family: monospace; font-weight: 700; color: var(--mat-sys-primary); font-size: 0.8rem; }
    .group-name { font-size: 0.62rem; color: var(--mat-sys-on-surface-variant); }
    .workbook-name { font-weight: 600; font-size: 0.85rem; line-height: 1.3; }
    .product-chip {
      font-size: 0.6rem; padding: 1px 6px; border-radius: 10px;
      border: 1px solid var(--mat-sys-outline-variant);
    }
    .cell-right { text-align: right; font-size: 0.78rem; }
    .score-dash { color: var(--mat-sys-on-surface-variant); font-size: 0.78rem; }
    .score-val { font-weight: 700; font-size: 0.78rem; }
    .remove-btn { color: var(--mat-sys-error); opacity: 0.4; }
    .row-default { cursor: default; }

    /* Manage dialog body */
    .manage-search { width: 100%; margin-bottom: 12px; }
    .manage-spinner-wrap { display: flex; justify-content: center; padding: 24px; }
    .manage-empty { text-align: center; padding: 24px; color: var(--mat-sys-on-surface-variant); font-size: 0.88rem; }
    .assess-row-inner { flex: 1; min-width: 0; }
    .assess-workbook { font-size: 0.88rem; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
    .assess-group { font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); }
    .checkbox-no-events { pointer-events: none; }
  `],
  template: `
    @if (collectionQuery.isLoading()) {
      <div class="spinner-center">
        <mat-spinner diameter="36"></mat-spinner>
      </div>
    }

    @if (collectionQuery.error()) {
      <div class="error-wrap">
        <button mat-button (click)="router.navigate(['/assessments'])">
          <mat-icon>arrow_back</mat-icon> Back to Assessments
        </button>
        <div class="error-box">
          Collection not found or failed to load.
        </div>
      </div>
    }

    @if (collectionQuery.data(); as coll) {
      <!-- Page header -->
      <app-page-header
        [title]="coll.name"
        [subtitle]="coll.product_family + (coll.product_type ? ' / ' + coll.product_type : '') + ' · Assessment Collection'">
        <div actions class="actions-row">
          <button mat-stroked-button (click)="router.navigate(['/assessments'])">
            <mat-icon>arrow_back</mat-icon>
            Back
          </button>
          <button mat-stroked-button (click)="manageOpen.set(true)">
            <mat-icon>person_add</mat-icon>
            Manage Assessments
          </button>
          <button mat-stroked-button [disabled]="!!downloading()"
            (click)="handleExport(coll, 'csv')">
            <mat-icon>download</mat-icon>
            {{ downloading() === 'csv' ? 'Exporting…' : 'CSV' }}
          </button>
          <button mat-stroked-button [disabled]="!!downloading()"
            (click)="handleExport(coll, 'xlsx')">
            <mat-icon>download</mat-icon>
            {{ downloading() === 'xlsx' ? 'Exporting…' : 'XLSX' }}
          </button>
          <button mat-raised-button color="primary" [disabled]="!!downloading()"
            (click)="handleExport(coll, 'pdf')">
            <mat-icon>download</mat-icon>
            {{ downloading() === 'pdf' ? 'Exporting…' : 'PDF' }}
          </button>
        </div>
      </app-page-header>

      <!-- Stats bar -->
      <div class="stats-card">
        <div class="stats-row">

          <!-- Status chip -->
          <div>
            <div class="status-label">Status</div>
            <span class="status-chip"
              [style.background]="statusCfg(coll.stats.status).bg"
              [style.color]="statusCfg(coll.stats.status).color">
              {{ statusCfg(coll.stats.status).label }}
            </span>
          </div>

          <!-- Completion progress -->
          <div class="bar-wrapper">
            <div class="bar-header">
              <span class="bar-completion-label">Completion</span>
              <span class="bar-score-label">
                {{ coll.stats.started }}/{{ coll.stats.total }} assessments · {{ coll.stats.completion_pct }}%
              </span>
            </div>
            <mat-progress-bar mode="determinate"
              [value]="coll.stats.completion_pct"
              class="progress-bar">
            </mat-progress-bar>
          </div>

          <!-- Compliance score -->
          <div class="bar-wrapper">
            <div class="bar-header">
              <span class="bar-completion-label">Compliance Score</span>
              <span [style.color]="scoreColor(coll.stats.compliance_pct)" class="score-val">
                {{ coll.stats.compliance_pct }}%
              </span>
            </div>
            <mat-progress-bar mode="determinate"
              [value]="coll.stats.compliance_pct"
              [style.--mat-progress-bar-active-indicator-color]="scoreColor(coll.stats.compliance_pct)"
              class="progress-bar">
            </mat-progress-bar>
          </div>

          <!-- Counts -->
          <div class="counts-row">
            <div class="count-col">
              <div class="count-val count-val-compliant">{{ coll.stats.items_compliant }}</div>
              <div class="count-label">Compliant</div>
            </div>
            <div class="count-col">
              <div class="count-val count-val-noncompliant">{{ coll.stats.items_non_compliant }}</div>
              <div class="count-label">Non-Compliant</div>
            </div>
            <div class="count-col">
              <div class="count-val count-val-total">{{ coll.stats.items_total }}</div>
              <div class="count-label">Total Items</div>
            </div>
          </div>

          <!-- Due date -->
          @if (coll.due_date) {
            <div class="due-date-row">
              <mat-icon class="icon-sm">calendar_today</mat-icon>
              <span class="due-date-text">Due {{ coll.due_date }}</span>
            </div>
          }

        </div>

        <!-- Description -->
        @if (coll.description) {
          <div class="description-text">
            {{ coll.description }}
          </div>
        }
      </div>

      <!-- Members table -->
      <div>
        <div class="section-header">
          <span class="section-title">Assessments</span>
          <span class="section-count">{{ coll.members.length }}</span>
        </div>

        @if (coll.members.length === 0) {
          <div class="empty-box" (click)="manageOpen.set(true)">
            <mat-icon class="empty-icon">person_add</mat-icon>
            <div class="empty-text">
              No assessments in this collection yet.
            </div>
            <div class="empty-cta">
              Click to add assessments
            </div>
          </div>
        } @else {
          <mat-card class="members-card">
            <table mat-table [dataSource]="coll.members">

              <ng-container matColumnDef="control_group">
                <th mat-header-cell *matHeaderCellDef class="mat-column-control_group">Control Group</th>
                <td mat-cell *matCellDef="let m">
                  <div class="group-code">
                    {{ m.group_code }}
                  </div>
                  <div class="group-name">{{ m.group_name }}</div>
                </td>
              </ng-container>

              <ng-container matColumnDef="workbook">
                <th mat-header-cell *matHeaderCellDef>Workbook</th>
                <td mat-cell *matCellDef="let m">
                  <div class="doc-id">{{ m.document_id }}</div>
                  <div class="workbook-name">{{ m.workbook_name }}</div>
                  @if (m.items_non_compliant > 0) {
                    <div>
                      <button class="nc-expand-btn"
                        (click)="toggleNcExpand(m.assessment_id)">
                        <mat-icon class="icon-sm">{{ ncExpanded().has(m.assessment_id) ? 'expand_less' : 'expand_more' }}</mat-icon>
                        {{ m.items_non_compliant }} non-compliant
                      </button>
                      @if (ncExpanded().has(m.assessment_id)) {
                        <div class="nc-box">
                          Non-compliant item details visible in the export report.
                        </div>
                      }
                    </div>
                  }
                </td>
              </ng-container>

              <ng-container matColumnDef="product">
                <th mat-header-cell *matHeaderCellDef class="mat-column-product">Product</th>
                <td mat-cell *matCellDef="let m">
                  <span class="product-chip">{{ m.product_type }}</span>
                </td>
              </ng-container>

              <ng-container matColumnDef="items">
                <th mat-header-cell *matHeaderCellDef class="mat-column-items col-right">Items</th>
                <td mat-cell *matCellDef="let m" class="cell-right">
                  {{ m.items_total }}
                </td>
              </ng-container>

              <ng-container matColumnDef="compliant">
                <th mat-header-cell *matHeaderCellDef class="mat-column-compliant col-right">Compliant</th>
                <td mat-cell *matCellDef="let m" class="cell-right"
                  [style.color]="m.items_compliant > 0 ? '#70AD47' : 'var(--mat-sys-on-surface-variant)'">
                  {{ m.items_compliant }}
                </td>
              </ng-container>

              <ng-container matColumnDef="non_compliant">
                <th mat-header-cell *matHeaderCellDef class="mat-column-non_compliant col-right">Non-Compliant</th>
                <td mat-cell *matCellDef="let m" class="cell-right"
                  [style.color]="m.items_non_compliant > 0 ? '#FF5252' : 'var(--mat-sys-on-surface-variant)'">
                  {{ m.items_non_compliant }}
                </td>
              </ng-container>

              <ng-container matColumnDef="score">
                <th mat-header-cell *matHeaderCellDef class="mat-column-score col-right">Score</th>
                <td mat-cell *matCellDef="let m" class="cell-right">
                  @if (m.items_total > 0) {
                    <span class="score-val"
                      [style.color]="scoreColor(m.compliance_pct)">
                      {{ m.compliance_pct }}%
                    </span>
                  } @else {
                    <span class="score-dash">—</span>
                  }
                </td>
              </ng-container>

              <ng-container matColumnDef="remove">
                <th mat-header-cell *matHeaderCellDef class="mat-column-remove"></th>
                <td mat-cell *matCellDef="let m">
                  <button mat-icon-button matTooltip="Remove from collection"
                    class="remove-btn"
                    [disabled]="removeAssessmentMut.isPending()"
                    (click)="removeAssessmentMut.mutate({ collId: coll.id, assessmentId: m.assessment_id })"
                    (mouseenter)="$event.target && ($any($event.target).closest('button').style.opacity='1')"
                    (mouseleave)="$event.target && ($any($event.target).closest('button').style.opacity='0.4')">
                    <mat-icon class="icon-sm">person_remove</mat-icon>
                  </button>
                </td>
              </ng-container>

              <tr mat-header-row *matHeaderRowDef="memberColumns"></tr>
              <tr mat-row *matRowDef="let row; columns: memberColumns" class="row-default"></tr>
            </table>
          </mat-card>
        }
      </div>
    }

    <!-- ── Manage Assessments Dialog ── -->
    @if (manageOpen()) {
      <div class="overlay-backdrop" (click)="closeManageDialog()"></div>
      <div class="manage-dialog">
        <div class="manage-dialog-header">Manage Assessments</div>

        <div class="manage-dialog-body">
          <mat-form-field appearance="outline" class="manage-search" subscriptSizing="dynamic">
            <mat-label>Search</mat-label>
            <input matInput [(ngModel)]="manageSearch" placeholder="Search assessments…">
          </mat-form-field>

          @if (assessmentsForCollectionQuery.isLoading()) {
            <div class="manage-spinner-wrap">
              <mat-spinner diameter="24"></mat-spinner>
            </div>
          } @else if (filteredAssessments().length === 0) {
            <div class="manage-empty">
              No assessments found.
            </div>
          } @else {
            @for (a of filteredAssessments(); track a.id) {
              @let inColl = currentMemberIds().has(a.id);
              <div class="assessment-row" [class.in-collection]="inColl"
                (click)="toggleAssessment(a.id, inColl)">
                <mat-checkbox [checked]="inColl" (click)="$event.stopPropagation()"
                  (change)="toggleAssessment(a.id, inColl)" class="checkbox-no-events">
                </mat-checkbox>
                <div class="assess-row-inner">
                  <div class="doc-id">{{ a.document_id }}</div>
                  <div class="assess-workbook">
                    {{ a.workbook_name }}
                  </div>
                  <div class="assess-group">
                    {{ a.group_code.toUpperCase() }} — {{ a.group_name }}
                  </div>
                </div>
                <span class="product-chip">{{ a.product_type }}</span>
              </div>
            }
          }
        </div>

        <div class="manage-dialog-footer">
          <button mat-raised-button color="primary" (click)="closeManageDialog()">Done</button>
        </div>
      </div>
    }
  `,
})
export class CollectionDetailComponent {
  private readonly route          = inject(ActivatedRoute)
  readonly router                 = inject(Router)
  private readonly http           = inject(HttpClient)
  private readonly collectionsApi = inject(CollectionsApiService)
  private readonly theme          = inject(ThemeService)
  private readonly qc             = injectQueryClient()

  private readonly collectionId   = signal<string>('')

  constructor() {
    this.route.paramMap.subscribe(p => {
      const id = p.get('id')
      if (id) this.collectionId.set(id)
    })
  }

  // ── Queries ──────────────────────────────────────────────────────────────────

  collectionQuery = injectQuery(() => ({
    queryKey: ['collection', this.collectionId()],
    queryFn:  () => firstValueFrom(this.collectionsApi.get(this.collectionId())),
    enabled:  !!this.collectionId(),
  }))

  assessmentsForCollectionQuery = injectQuery(() => ({
    queryKey: ['assessments-for-collection', this.collectionQuery.data()?.product_family],
    queryFn:  () => {
      const family = this.collectionQuery.data()!.product_family
      return firstValueFrom(this.http.get<AssessmentListItem[]>('/api/v1/assessments', {
        params: { product_family: family }
      }))
    },
    enabled: !!this.collectionQuery.data() && this.manageOpen(),
  }))

  // ── Mutations ────────────────────────────────────────────────────────────────

  addAssessmentMut = injectMutation(() => ({
    mutationFn: (assessmentId: string) =>
      firstValueFrom(this.collectionsApi.addAssessment(this.collectionId(), assessmentId)),
    onSuccess: () => this.qc.invalidateQueries({ queryKey: ['collection', this.collectionId()] }),
  }))

  removeAssessmentMut = injectMutation(() => ({
    mutationFn: (args: { collId: string; assessmentId: string }) =>
      firstValueFrom(this.collectionsApi.removeAssessment(args.collId, args.assessmentId)),
    onSuccess: () => this.qc.invalidateQueries({ queryKey: ['collection', this.collectionId()] }),
  }))

  // ── Local state ──────────────────────────────────────────────────────────────

  downloading   = signal<string | null>(null)
  manageOpen    = signal(false)
  manageSearch  = ''
  ncExpanded    = signal<Set<string>>(new Set())

  memberColumns = ['control_group', 'workbook', 'product', 'items', 'compliant', 'non_compliant', 'score', 'remove']

  // ── Computed ─────────────────────────────────────────────────────────────────

  currentMemberIds = computed(() => {
    const coll = this.collectionQuery.data()
    if (!coll) return new Set<string>()
    return new Set(coll.members.map(m => m.assessment_id))
  })

  filteredAssessments = computed(() => {
    const items = this.assessmentsForCollectionQuery.data() ?? []
    const q     = this.manageSearch.toLowerCase()
    if (!q) return items
    return items.filter(a =>
      a.document_id.toLowerCase().includes(q) ||
      a.workbook_name.toLowerCase().includes(q) ||
      a.group_code.toLowerCase().includes(q))
  })

  // ── Helpers ──────────────────────────────────────────────────────────────────

  scoreColor = scoreColor

  statusCfg = (status: string) => {
    const dark = this.theme.isDark()
    if (status === 'complete') return dark
      ? { label: 'Complete',    bg: 'rgba(198,239,206,0.15)', color: '#C6EFCE' }
      : { label: 'Complete',    bg: 'rgba(46,125,50,0.12)',   color: '#1b5e20' }
    if (status === 'in_progress') return dark
      ? { label: 'In Progress', bg: 'rgba(255,192,0,0.12)',   color: '#856404' }
      : { label: 'In Progress', bg: 'rgba(230,145,0,0.15)',   color: '#7a4800' }
    return dark
      ? { label: 'Not Started', bg: 'rgba(255,255,255,0.06)', color: '#888' }
      : { label: 'Not Started', bg: 'rgba(0,0,0,0.06)',       color: '#555' }
  }

  toggleNcExpand(assessmentId: string) {
    this.ncExpanded.update(s => {
      const n = new Set(s)
      n.has(assessmentId) ? n.delete(assessmentId) : n.add(assessmentId)
      return n
    })
  }

  toggleAssessment(assessmentId: string, isInCollection: boolean) {
    if (isInCollection) this.removeAssessmentMut.mutate({ collId: this.collectionId(), assessmentId })
    else this.addAssessmentMut.mutate(assessmentId)
  }

  closeManageDialog() {
    this.manageOpen.set(false)
    this.qc.invalidateQueries({ queryKey: ['collection', this.collectionId()] })
  }

  async handleExport(coll: CollectionRead, format: 'csv' | 'xlsx' | 'pdf') {
    this.downloading.set(format)
    const mimeTypes: Record<string, string> = {
      csv:  'text/csv',
      xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      pdf:  'application/pdf',
    }
    try {
      const blob = await firstValueFrom(
        this.http.get(this.collectionsApi.exportUrl(coll.id, format), { responseType: 'blob' }))
      const filename = `collection_${coll.name.replace(/\s+/g, '_')}.${format}`
      const url = URL.createObjectURL(blob)
      const a   = document.createElement('a')
      a.href     = url
      a.download = filename
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } catch {
      // silently fail — user can retry
    } finally {
      this.downloading.set(null)
    }
  }
}
