// isms-core-platform/frontend/src/pages/MitreGroups.tsx
import { useState } from 'react'
import {
  Alert, Box, Chip, CircularProgress, InputAdornment, Paper,
  Table, TableBody, TableCell, TableHead, TableRow, TextField,
  ToggleButton, ToggleButtonGroup, Tooltip, Typography,
} from '@mui/material'
import { SearchOutlined } from '@mui/icons-material'
import { useQuery } from '@tanstack/react-query'
import { feedsApi, type MitreGroup } from '../api/feedsApi'
import PageHeader from '../components/PageHeader'

const PER_PAGE = 50
const INTEL_COLOR = '#B84F00'

export default function MitreGroups() {
  const [source] = useState<'attack_v19'>('attack_v19')
  const [search, setSearch] = useState('')
  const [page, setPage] = useState(1)
  const [selected, setSelected] = useState<MitreGroup | null>(null)

  const { data: stats } = useQuery({
    queryKey: ['feeds', 'groups', 'stats'],
    queryFn: feedsApi.getMitreGroupStats,
  })

  const { data, isLoading, error } = useQuery({
    queryKey: ['feeds', 'groups', source, search, page],
    queryFn: () => feedsApi.getMitreGroups({
      source,
      search: search || undefined,
      deprecated: false,
      page,
      per_page: PER_PAGE,
    }),
  })

  const totalPages = data ? Math.ceil(data.total / PER_PAGE) : 0

  function handleSearch(v: string) {
    setSearch(v)
    setPage(1)
  }

  const noData = !isLoading && data?.total === 0

  return (
    <Box sx={{ p: 3 }}>
      <PageHeader
        title="MITRE ATT&CK Groups"
        subtitle="Threat actor intrusion sets — adversary groups tracked by MITRE ATT&CK"
        helpSection="mitre-attack"
      />

      {/* ── Stats row ── */}
      {stats && (
        <Box sx={{ display: 'flex', gap: 3, mb: 2.5, flexWrap: 'wrap' }}>
          {[
            { label: 'Groups', value: stats.total_groups },
            { label: 'Deprecated', value: stats.deprecated_count },
            { label: 'Sources', value: stats.sources.join(', ') },
          ].map(s => (
            <Box key={s.label}>
              <Typography variant="h6" sx={{ fontWeight: 700, color: INTEL_COLOR, lineHeight: 1 }}>
                {typeof s.value === 'number' ? s.value.toLocaleString() : s.value}
              </Typography>
              <Typography variant="caption" color="text.secondary">{s.label}</Typography>
            </Box>
          ))}
        </Box>
      )}

      {/* ── Filters ── */}
      <Box sx={{ display: 'flex', gap: 1.5, mb: 2, flexWrap: 'wrap', alignItems: 'center' }}>
        <ToggleButtonGroup
          size="small"
          value={source}
          exclusive
          onChange={(_, v) => v && setSource(v)}
        >
          <ToggleButton value="attack_v19" sx={{ fontSize: '0.72rem', px: 1.5 }}>v19</ToggleButton>
        </ToggleButtonGroup>

        <TextField
          size="small"
          placeholder="Search by ID or name…"
          value={search}
          onChange={e => handleSearch(e.target.value)}
          sx={{ width: 240 }}
          InputProps={{
            startAdornment: <InputAdornment position="start"><SearchOutlined sx={{ fontSize: 16 }} /></InputAdornment>,
          }}
        />
      </Box>

      {/* ── Table + detail panel ── */}
      <Box sx={{ display: 'flex', gap: 2 }}>
        <Paper variant="outlined" sx={{ flex: 1, borderRadius: 2, overflow: 'hidden', minWidth: 0 }}>
          {isLoading && (
            <Box sx={{ display: 'flex', justifyContent: 'center', py: 6 }}>
              <CircularProgress size={28} />
            </Box>
          )}
          {error && <Alert severity="error" sx={{ m: 2 }}>Failed to load groups</Alert>}
          {noData && (
            <Alert severity="info" sx={{ m: 2 }}>
              {source === 'attack_v19'
                ? 'ATT&CK v19 data not yet available. Check back after the scheduled weekly pull.'
                : 'No groups match the current filters.'}
            </Alert>
          )}
          {!isLoading && data && data.items.length > 0 && (
            <>
              <Table size="small" stickyHeader>
                <TableHead>
                  <TableRow>
                    <TableCell sx={{ fontWeight: 600, fontSize: '0.72rem', width: 80 }}>ID</TableCell>
                    <TableCell sx={{ fontWeight: 600, fontSize: '0.72rem' }}>Name</TableCell>
                    <TableCell sx={{ fontWeight: 600, fontSize: '0.72rem' }}>Aliases</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {data.items.map(g => (
                    <TableRow
                      key={g.id}
                      hover
                      selected={selected?.id === g.id}
                      onClick={() => setSelected(selected?.id === g.id ? null : g)}
                      sx={{ cursor: 'pointer' }}
                    >
                      <TableCell sx={{ fontFamily: 'monospace', fontSize: '0.75rem', color: INTEL_COLOR, fontWeight: 600 }}>
                        {g.group_id}
                      </TableCell>
                      <TableCell sx={{ fontSize: '0.78rem' }}>
                        <Typography noWrap variant="inherit">{g.name}</Typography>
                      </TableCell>
                      <TableCell sx={{ maxWidth: 240 }}>
                        {g.aliases.length > 0 ? (
                          <Box>
                            {g.aliases.slice(0, 3).map(a => (
                              <Chip key={a} label={a} size="small" variant="outlined"
                                sx={{ fontSize: '0.62rem', height: 16, mr: 0.25, mb: 0.25 }} />
                            ))}
                            {g.aliases.length > 3 && (
                              <Tooltip title={g.aliases.slice(3).join(', ')}>
                                <Chip label={`+${g.aliases.length - 3}`} size="small"
                                  sx={{ fontSize: '0.62rem', height: 16 }} />
                              </Tooltip>
                            )}
                          </Box>
                        ) : (
                          <Typography variant="caption" color="text.disabled">—</Typography>
                        )}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>

              {/* Pagination */}
              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', px: 2, py: 1, borderTop: '1px solid', borderColor: 'divider' }}>
                <Typography variant="caption" color="text.secondary">
                  {data.total.toLocaleString()} groups
                </Typography>
                <Box sx={{ display: 'flex', gap: 1, alignItems: 'center' }}>
                  <Typography
                    variant="caption"
                    sx={{ cursor: page > 1 ? 'pointer' : 'default', color: page > 1 ? 'primary.main' : 'text.disabled' }}
                    onClick={() => page > 1 && setPage(p => p - 1)}
                  >
                    ← Prev
                  </Typography>
                  <Typography variant="caption" color="text.secondary">
                    {page} / {totalPages}
                  </Typography>
                  <Typography
                    variant="caption"
                    sx={{ cursor: page < totalPages ? 'pointer' : 'default', color: page < totalPages ? 'primary.main' : 'text.disabled' }}
                    onClick={() => page < totalPages && setPage(p => p + 1)}
                  >
                    Next →
                  </Typography>
                </Box>
              </Box>
            </>
          )}
        </Paper>

        {/* ── Detail panel ── */}
        {selected && (
          <Paper variant="outlined" sx={{ width: 320, flexShrink: 0, borderRadius: 2, p: 2, height: 'fit-content', position: 'sticky', top: 24 }}>
            <Typography variant="subtitle2" sx={{ fontFamily: 'monospace', color: INTEL_COLOR, fontWeight: 700, mb: 0.5 }}>
              {selected.group_id}
            </Typography>
            <Typography variant="body2" fontWeight={600} sx={{ mb: 1 }}>{selected.name}</Typography>
            {selected.aliases.length > 0 && (
              <Box sx={{ mb: 1 }}>
                <Typography variant="caption" color="text.secondary" display="block" sx={{ mb: 0.5 }}>Also known as:</Typography>
                {selected.aliases.map(a => (
                  <Chip key={a} label={a} size="small" variant="outlined"
                    sx={{ fontSize: '0.62rem', height: 16, mr: 0.25, mb: 0.25 }} />
                ))}
              </Box>
            )}
            {selected.description && (
              <Typography variant="caption" color="text.secondary" display="block" sx={{ mt: 1.5, lineHeight: 1.5, maxHeight: 320, overflowY: 'auto' }}>
                {selected.description.slice(0, 700)}{selected.description.length > 700 ? '…' : ''}
              </Typography>
            )}
            {selected.url && (
              <Typography variant="caption" sx={{ mt: 1, display: 'block' }}>
                <a href={selected.url} target="_blank" rel="noopener noreferrer"
                  style={{ color: INTEL_COLOR }}>
                  View on attack.mitre.org →
                </a>
              </Typography>
            )}
          </Paper>
        )}
      </Box>
    </Box>
  )
}

// isms-core-platform/frontend-angular/src/app/pages/mitre-groups/mitre-groups.component.ts
import { Component, inject, signal, computed } from '@angular/core'
import { CommonModule } from '@angular/common'
import { FormsModule } from '@angular/forms'
import { firstValueFrom } from 'rxjs'

import { injectQuery } from '@tanstack/angular-query-experimental'

import { MatTableModule } from '@angular/material/table'
import { MatTooltipModule } from '@angular/material/tooltip'
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner'
import { MatFormFieldModule } from '@angular/material/form-field'
import { MatInputModule } from '@angular/material/input'
import { MatIconModule } from '@angular/material/icon'
import { MatButtonToggleModule } from '@angular/material/button-toggle'

import { FeedsApiService, MitreGroup } from '../../api/feeds-api.service'
import { ThemeService } from '../../core/services/theme.service'

const PER_PAGE = 50
const INTEL_COLOR_DARK  = '#FFA726'
const INTEL_COLOR_LIGHT = '#E65100'

@Component({
  selector: 'app-mitre-groups',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatTableModule,
    MatTooltipModule,
    MatProgressSpinnerModule,
    MatFormFieldModule,
    MatInputModule,
    MatIconModule,
    MatButtonToggleModule,
  ],
  template: `
<div class="grp-page">

  <!-- Header -->
  <div class="grp-header">
    <h2 class="grp-header__title">MITRE ATT&amp;CK Groups</h2>
    <p class="grp-header__sub">
      Threat actor intrusion sets — adversary groups tracked by MITRE ATT&amp;CK
    </p>
  </div>

  <!-- Stats row -->
  @if (statsQuery.data(); as stats) {
    <div class="grp-stats-row">
      <div>
        <div class="grp-stat__val" [style.color]="intelColor">{{stats.total_groups | number}}</div>
        <div class="grp-stat__lbl">Groups</div>
      </div>
      <div>
        <div class="grp-stat__val" [style.color]="intelColor">{{stats.deprecated_count | number}}</div>
        <div class="grp-stat__lbl">Deprecated</div>
      </div>
      <div>
        <div class="grp-stat__val" [style.color]="intelColor">{{stats.sources.join(', ')}}</div>
        <div class="grp-stat__lbl">Sources</div>
      </div>
    </div>
  }

  <!-- Filters -->
  <div class="grp-filters">
    <mat-button-toggle-group value="attack_v19" class="grp-toggle-group">
      <mat-button-toggle value="attack_v19" class="grp-toggle-btn">v19</mat-button-toggle>
    </mat-button-toggle-group>

    <mat-form-field appearance="outline" subscriptSizing="dynamic" class="grp-search-field">
      <mat-label>Search</mat-label>
      <mat-icon matPrefix class="icon-md">search</mat-icon>
      <input matInput [ngModel]="search()" (ngModelChange)="onSearch($event)" placeholder="Search by ID or name…" />
    </mat-form-field>
  </div>

  <!-- Table + detail panel -->
  <div class="grp-layout">

    <!-- Table panel -->
    <div class="grp-table-panel">

      @if (listQuery.isLoading()) {
        <div class="grp-spinner-wrap">
          <mat-spinner [diameter]="28" />
        </div>
      }

      @if (listQuery.isError()) {
        <div class="grp-error">Failed to load groups.</div>
      }

      @if (!listQuery.isLoading() && listQuery.data()?.total === 0) {
        <div class="grp-empty">
          ATT&amp;CK v19 data not yet available. Check back after the scheduled weekly pull.
        </div>
      }

      @if (!listQuery.isLoading() && (listQuery.data()?.items?.length ?? 0) > 0) {
        <table mat-table [dataSource]="listQuery.data()!.items" class="grp-table">

          <ng-container matColumnDef="group_id">
            <th mat-header-cell *matHeaderCellDef class="grp-th">ID</th>
            <td mat-cell *matCellDef="let g" class="grp-cell-id"
              [style.color]="intelColor">{{g.group_id}}</td>
          </ng-container>

          <ng-container matColumnDef="name">
            <th mat-header-cell *matHeaderCellDef class="grp-th">Name</th>
            <td mat-cell *matCellDef="let g" class="grp-cell-name">
              {{g.name}}</td>
          </ng-container>

          <ng-container matColumnDef="aliases">
            <th mat-header-cell *matHeaderCellDef class="grp-th">Aliases</th>
            <td mat-cell *matCellDef="let g" class="grp-cell-aliases">
              @if (g.aliases.length > 0) {
                @for (a of g.aliases.slice(0, 3); track a) {
                  <span class="alias-pill">{{a}}</span>
                }
                @if (g.aliases.length > 3) {
                  <span class="alias-pill" [matTooltip]="g.aliases.slice(3).join(', ')">+{{g.aliases.length - 3}}</span>
                }
              } @else {
                <span class="grp-empty-dash">—</span>
              }
            </td>
          </ng-container>

          <tr mat-header-row *matHeaderRowDef="displayedColumns" class="grp-header-row"></tr>
          <tr mat-row *matRowDef="let g; columns: displayedColumns"
            class="grp-data-row"
            [style.background]="selected()?.id === g.id ? 'rgba(184,79,0,0.08)' : ''"
            (click)="onRowClick(g)"></tr>
        </table>

        <!-- Pagination -->
        <div class="grp-pagination">
          <span class="grp-pagination__count">{{listQuery.data()!.total | number}} groups</span>
          <div class="grp-pagination__nav">
            <span class="grp-pagination__btn" [class.disabled]="page() <= 1"
              (click)="page() > 1 && setPage(page() - 1)">← Prev</span>
            <span class="grp-pagination__info">{{page()}} / {{totalPages()}}</span>
            <span class="grp-pagination__btn" [class.disabled]="page() >= totalPages()"
              (click)="page() < totalPages() && setPage(page() + 1)">Next →</span>
          </div>
        </div>
      }
    </div>

    <!-- Detail panel -->
    @if (selected(); as g) {
      <div class="grp-detail-panel">
        <div class="grp-detail-panel__id" [style.color]="intelColor">{{g.group_id}}</div>
        <div class="grp-detail-panel__name">{{g.name}}</div>

        @if (g.aliases.length > 0) {
          <div class="grp-detail-section">
            <div class="grp-detail-section__label">Also known as:</div>
            @for (a of g.aliases; track a) {
              <span class="alias-pill">{{a}}</span>
            }
          </div>
        }

        @if (g.description) {
          <div class="grp-detail-panel__desc">
            {{g.description.slice(0, 700)}}{{g.description.length > 700 ? '…' : ''}}
          </div>
        }

        @if (g.url) {
          <div class="grp-detail-panel__link-wrap">
            <a [href]="g.url" target="_blank" rel="noopener noreferrer"
              class="grp-detail-panel__link" [style.color]="intelColor">
              View on attack.mitre.org →
            </a>
          </div>
        }
      </div>
    }
  </div>
</div>
  `,
  styles: [`
    .mat-mdc-row:hover { background: rgba(0,0,0,0.04); }

    .grp-page { padding: 24px; }

    .grp-header { margin-bottom: 16px; }
    .grp-header__title { margin: 0; font-size: 1.3rem; font-weight: 700; }
    .grp-header__sub { margin: 4px 0 0; color: var(--mat-sys-on-surface-variant); font-size: 0.85rem; }

    .grp-stats-row { display: flex; gap: 24px; margin-bottom: 16px; flex-wrap: wrap; }
    .grp-stat__val { font-size: 1.25rem; font-weight: 700; line-height: 1; }
    .grp-stat__lbl { font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); }

    .grp-filters { display: flex; gap: 12px; margin-bottom: 16px; align-items: center; flex-wrap: wrap; }
    .grp-toggle-group { height: 32px; }
    .grp-toggle-btn { font-size: 0.72rem; padding: 0 12px; }
    .grp-search-field { width: 240px; }

    .grp-layout { display: flex; gap: 16px; }

    .grp-table-panel { flex: 1; min-width: 0; border: 1px solid var(--mat-sys-outline-variant); border-radius: 8px; overflow: hidden; background: var(--mat-sys-surface-container); }
    .grp-spinner-wrap { display: flex; justify-content: center; padding: 48px; }
    .grp-error { padding: 16px; color: #d32f2f; font-size: 0.85rem; }
    .grp-empty { padding: 16px; font-size: 0.85rem; color: var(--mat-sys-on-surface-variant); }
    .grp-table { width: 100%; }

    .grp-th { font-size: 0.72rem; font-weight: 600; }
    .mat-column-group_id { width: 80px; }

    .grp-cell-id { font-family: monospace; font-size: 0.75rem; font-weight: 600; }
    .grp-cell-name { font-size: 0.78rem; max-width: 200px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
    .grp-cell-aliases { max-width: 240px; }

    .grp-mini-chip { font-size: 0.62rem; height: 16px; margin: 0 2px 2px 0; }
    .grp-empty-dash { color: #bbb; font-size: 0.75rem; }

    .grp-header-row { height: 36px; }
    .grp-data-row { height: 36px; cursor: pointer; }

    .grp-pagination { display: flex; justify-content: space-between; align-items: center; padding: 8px 16px; border-top: 1px solid var(--mat-sys-outline-variant); }
    .grp-pagination__count { font-size: 0.75rem; color: var(--mat-sys-on-surface-variant); }
    .grp-pagination__nav { display: flex; gap: 8px; align-items: center; }
    .grp-pagination__btn { font-size: 0.75rem; cursor: pointer; color: var(--mat-sys-primary); }
    .grp-pagination__btn.disabled { color: var(--mat-sys-on-surface-variant); cursor: default; pointer-events: none; }
    .grp-pagination__info { font-size: 0.75rem; color: var(--mat-sys-on-surface-variant); }

    .grp-detail-panel { width: 320px; flex-shrink: 0; border: 1px solid var(--mat-sys-outline-variant); border-radius: 8px; padding: 16px; height: fit-content; position: sticky; top: 24px; background: var(--mat-sys-surface-container); }
    .grp-detail-panel__id { font-family: monospace; font-size: 0.85rem; font-weight: 700; margin-bottom: 4px; }
    .grp-detail-panel__name { font-size: 0.9rem; font-weight: 600; margin-bottom: 8px; }
    .grp-detail-panel__desc { font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); line-height: 1.5; margin-top: 12px; max-height: 320px; overflow-y: auto; }
    .grp-detail-panel__link-wrap { margin-top: 8px; }
    .grp-detail-panel__link { font-size: 0.72rem; text-decoration: none; }

    .grp-detail-section { margin-bottom: 8px; }
    .grp-detail-section__label { font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); margin-bottom: 4px; }

    .alias-pill {
      display: inline-block; font-size: 0.62rem; padding: 1px 7px; margin: 0 2px 3px 0;
      border-radius: 4px; line-height: 18px; white-space: nowrap;
      background: var(--mat-sys-surface-container-high);
      color: var(--mat-sys-on-surface-variant);
      border: 1px solid var(--mat-sys-outline-variant);
    }
  `],
})
export class MitreGroupsComponent {
  private feedsApi = inject(FeedsApiService)
  private readonly theme = inject(ThemeService)

  get intelColor() { return this.theme.isDark() ? INTEL_COLOR_DARK : INTEL_COLOR_LIGHT }
  readonly displayedColumns = ['group_id', 'name', 'aliases']

  search = signal('')
  page = signal(1)
  selected = signal<MitreGroup | null>(null)

  statsQuery = injectQuery(() => ({
    queryKey: ['feeds', 'groups', 'stats'],
    queryFn: () => firstValueFrom(this.feedsApi.getMitreGroupStats()),
  }))

  listQuery = injectQuery(() => ({
    queryKey: ['feeds', 'groups', 'attack_v19', this.search(), this.page()],
    queryFn: () => firstValueFrom(this.feedsApi.getMitreGroups({
      source: 'attack_v19',
      search: this.search() || undefined,
      deprecated: false,
      page: this.page(),
      per_page: PER_PAGE,
    })),
  }))

  totalPages = computed(() => {
    const data = this.listQuery.data()
    return data ? Math.ceil(data.total / PER_PAGE) : 0
  })

  onSearch(v: string) {
    this.search.set(v)
    this.page.set(1)
  }

  setPage(p: number) {
    this.page.set(p)
  }

  onRowClick(g: MitreGroup) {
    this.selected.set(this.selected()?.id === g.id ? null : g)
  }
}
