// isms-core-platform/frontend/src/pages/FrameworkTracker.tsx
/**
 * Framework Version Tracker
 * Shows all loaded compliance framework datasets, their current version,
 * known update availability, and dataset health metrics.
 */
import { useMemo } from 'react'
import {
  Box,
  Card,
  CardContent,
  Chip,
  Skeleton,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Tooltip,
  Typography,
} from '@mui/material'
import {
  CheckCircleOutlined,
  WarningAmberOutlined,
  InfoOutlined,
  UpdateOutlined,
  OpenInNewOutlined,
} from '@mui/icons-material'
import { useQuery } from '@tanstack/react-query'
import { client } from '../api/client'
import PageHeader from '../components/PageHeader'

interface FrameworkRow {
  id: string
  code: string
  name: string
  version: string | null
  publisher: string | null
  source_url: string | null
  jurisdiction: string | null
  controls_count: number
  loaded_at: string
}

// Known update availability — update this when new versions release.
// pending: version not yet released; available: released, platform not yet updated.
const KNOWN_UPDATES: Record<string, { latest: string; status: 'pending' | 'available'; note: string; eta?: string }> = {
  // Add entries here when a new framework version is released but not yet integrated.
  // Remove once the platform dataset is updated.
  ISO27017: {
    latest: '2025',
    status: 'pending',
    note: 'ISO/IEC 27017:2025 revision in progress — replaces 2015 edition. New control pack planned on release.',
    eta: '~June 2026',
  },
}

// ISO Reference Corpus & Glossary Standards — static registry
interface CorpusStandardRow {
  standard: string
  title: string
  domain: string
  edition: string
  status: 'current' | 'pending'
  note?: string
  eta?: string
}

const CORPUS_STANDARDS: CorpusStandardRow[] = [
  // Pending
  { standard: 'ISO/IEC 27000',      title: 'Information security management — Overview and vocabulary', domain: 'ISMS',             edition: 'FDIS (replacing 2018)', status: 'pending', note: 'FDIS ballot in progress — replaces ISO/IEC 27000:2018 with updated terminology aligned to ISO 27001:2022.', eta: '~June 2026' },
  // Cloud
  { standard: 'ISO/IEC 22123-1:2023', title: 'Cloud computing — Vocabulary', domain: 'Cloud Computing',  edition: '2023', status: 'current' },
  { standard: 'ISO/IEC 22123-2:2023', title: 'Cloud computing — Concepts',   domain: 'Cloud Computing',  edition: '2023', status: 'current' },
  { standard: 'ISO/IEC 22123-3:2023', title: 'Cloud computing — Reference Architecture (CCRA)', domain: 'Cloud Computing', edition: '2023', status: 'current' },
  // AI
  { standard: 'ISO/IEC 42001:2023',  title: 'AI management system (AIMS)',    domain: 'AI Management',    edition: '2023', status: 'current' },
  { standard: 'ISO/IEC 42005:2025',  title: 'AI system impact assessment',    domain: 'AI Management',    edition: '2025', status: 'current' },
  { standard: 'ISO/IEC 22989:2022',  title: 'AI concepts and terminology',    domain: 'AI Management',    edition: '2022', status: 'current' },
  // Infrastructure & IoT
  { standard: 'ISO/IEC 19395:2015',  title: 'Smart data centre resource monitoring', domain: 'Infrastructure', edition: '2015', status: 'current' },
  { standard: 'ISO/IEC 30141:2024',  title: 'IoT reference architecture',     domain: 'IoT',              edition: '2024', status: 'current' },
  { standard: 'ISO/IEC 24091:2019',  title: 'Data centre storage power efficiency', domain: 'Infrastructure', edition: '2019', status: 'current' },
]

const DOMAIN_COLOR: Record<string, string> = {
  'ISMS':             '#455A64',
  'Cloud Computing':  '#0288d1',
  'AI Management':    '#ff6b35',
  'Infrastructure':   '#00897b',
  'IoT':              '#6d4c41',
}

// Jurisdiction → display label
const JURISDICTION_LABEL: Record<string, string> = {
  INT: 'International',
  EU:  'European Union',
  US:  'United States',
  DE:  'Germany',
  CH:  'Switzerland',
  GB:  'United Kingdom',
  BE:  'Belgium',
  LU:  'Luxembourg',
  IT:  'Italy',
  FR:  'France',
  AT:  'Austria',
}

// Jurisdiction → accent colour
const JURISDICTION_COLOR: Record<string, string> = {
  INT: '#455A64',
  EU:  '#1565C0',
  US:  '#B71C1C',
  DE:  '#4E342E',
  CH:  '#C62828',
  GB:  '#1A237E',
  BE:  '#1B5E20',
  LU:  '#4A148C',
  IT:  '#006630',
  FR:  '#0D47A1',
  AT:  '#E65100',
}

function jurisColor(j: string | null) {
  return JURISDICTION_COLOR[j ?? 'INT'] ?? '#455A64'
}

function fmtDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
}

// ── Summary cards ─────────────────────────────────────────────────────────────
function SummaryCard({ label, value, sub, color }: { label: string; value: string | number; sub?: string; color?: string }) {
  return (
    <Card sx={{ flex: 1, minWidth: 140 }}>
      <CardContent sx={{ pb: '12px !important' }}>
        <Typography variant="caption" color="text.secondary" sx={{ fontSize: '0.68rem', textTransform: 'uppercase', letterSpacing: '0.06em' }}>
          {label}
        </Typography>
        <Typography variant="h5" sx={{ fontWeight: 700, color: color ?? 'text.primary', lineHeight: 1.2, mt: 0.5 }}>
          {value}
        </Typography>
        {sub && <Typography variant="caption" color="text.secondary" sx={{ fontSize: '0.65rem' }}>{sub}</Typography>}
      </CardContent>
    </Card>
  )
}

export default function FrameworkTracker() {
  const { data: frameworks, isLoading } = useQuery<FrameworkRow[]>({
    queryKey: ['framework-tracker'],
    queryFn: () => client.get('/frameworks/').then(r => r.data),
  })

  const { grouped, totalControls, updateCount, pendingCount } = useMemo(() => {
    if (!frameworks) return { grouped: {}, totalControls: 0, updateCount: 0, pendingCount: 0 }
    const g: Record<string, FrameworkRow[]> = {}
    let totalControls = 0
    let updateCount = 0
    let pendingCount = 0
    for (const fw of frameworks) {
      const j = fw.jurisdiction ?? 'INT'
      if (!g[j]) g[j] = []
      g[j].push(fw)
      totalControls += fw.controls_count
      const upd = KNOWN_UPDATES[fw.code]
      if (upd?.status === 'available') updateCount++
      if (upd?.status === 'pending') pendingCount++
    }
    return { grouped: g, totalControls, updateCount, pendingCount }
  }, [frameworks])

  const jurisdictionOrder = ['INT', 'EU', 'US', 'CH', 'DE', 'GB', 'BE', 'LU', 'IT', 'FR', 'AT']

  return (
    <Box sx={{ p: 3, maxWidth: 1200 }}>
      <PageHeader
        title="Framework Version Tracker"
        subtitle="Loaded compliance dataset versions, update availability, and dataset health"
      />

      {/* Summary row */}
      <Box sx={{ display: 'flex', gap: 2, mb: 3, flexWrap: 'wrap' }}>
        {isLoading ? (
          [1,2,3,4].map(i => <Skeleton key={i} variant="rectangular" width={140} height={80} sx={{ borderRadius: 1 }} />)
        ) : (
          <>
            <SummaryCard label="Frameworks loaded" value={frameworks?.length ?? 0} />
            <SummaryCard label="Total controls" value={totalControls.toLocaleString()} />
            <SummaryCard
              label="Updates available"
              value={updateCount}
              sub="datasets behind latest release"
              color={updateCount > 0 ? '#FF9800' : '#4CAF50'}
            />
            <SummaryCard
              label="Pending releases"
              value={pendingCount}
              sub="upcoming versions to watch"
              color={pendingCount > 0 ? '#42A5F5' : '#9E9E9E'}
            />
          </>
        )}
      </Box>

      {/* Per-jurisdiction tables */}
      {isLoading && (
        <Skeleton variant="rectangular" height={200} sx={{ borderRadius: 1 }} />
      )}

      {!isLoading && frameworks && jurisdictionOrder
        .filter(j => grouped[j]?.length > 0)
        .map(j => (
          <Box key={j} sx={{ mb: 3 }}>
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1 }}>
              <Box sx={{ width: 4, height: 20, borderRadius: 1, bgcolor: jurisColor(j) }} />
              <Typography variant="body2" sx={{ fontWeight: 700, fontSize: '0.8rem', color: jurisColor(j) }}>
                {JURISDICTION_LABEL[j] ?? j}
              </Typography>
              <Typography variant="caption" color="text.secondary">
                ({grouped[j].length} framework{grouped[j].length !== 1 ? 's' : ''})
              </Typography>
            </Box>

            <TableContainer sx={{ border: '1px solid', borderColor: 'divider', borderRadius: 1 }}>
              <Table size="small">
                <TableHead>
                  <TableRow sx={{ bgcolor: 'background.paper' }}>
                    <TableCell sx={{ fontSize: '0.68rem', fontWeight: 700, color: 'text.secondary', textTransform: 'uppercase' }}>Framework</TableCell>
                    <TableCell sx={{ fontSize: '0.68rem', fontWeight: 700, color: 'text.secondary', textTransform: 'uppercase' }}>Version</TableCell>
                    <TableCell sx={{ fontSize: '0.68rem', fontWeight: 700, color: 'text.secondary', textTransform: 'uppercase' }} align="right">Controls</TableCell>
                    <TableCell sx={{ fontSize: '0.68rem', fontWeight: 700, color: 'text.secondary', textTransform: 'uppercase' }}>Publisher</TableCell>
                    <TableCell sx={{ fontSize: '0.68rem', fontWeight: 700, color: 'text.secondary', textTransform: 'uppercase' }}>Loaded</TableCell>
                    <TableCell sx={{ fontSize: '0.68rem', fontWeight: 700, color: 'text.secondary', textTransform: 'uppercase' }}>Status</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {grouped[j].map(fw => {
                    const upd = KNOWN_UPDATES[fw.code]
                    return (
                      <TableRow key={fw.id} hover sx={{ '&:last-child td': { border: 0 } }}>
                        <TableCell>
                          <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.75 }}>
                            <Typography variant="body2" sx={{ fontWeight: 600, fontSize: '0.78rem' }}>
                              {fw.name}
                            </Typography>
                            {fw.source_url && (
                              <Tooltip title={fw.source_url}>
                                <OpenInNewOutlined
                                  sx={{ fontSize: 13, color: 'text.disabled', cursor: 'pointer', '&:hover': { color: 'primary.main' } }}
                                  onClick={() => window.open(fw.source_url!, '_blank')}
                                />
                              </Tooltip>
                            )}
                          </Box>
                          <Typography variant="caption" color="text.disabled" sx={{ fontSize: '0.62rem' }}>
                            {fw.code}
                          </Typography>
                        </TableCell>
                        <TableCell>
                          <Typography variant="body2" sx={{ fontSize: '0.75rem', fontFamily: 'monospace' }}>
                            {fw.version ?? '—'}
                          </Typography>
                        </TableCell>
                        <TableCell align="right">
                          <Typography variant="body2" sx={{ fontSize: '0.75rem', fontWeight: 600 }}>
                            {fw.controls_count.toLocaleString()}
                          </Typography>
                        </TableCell>
                        <TableCell>
                          <Typography variant="caption" color="text.secondary" sx={{ fontSize: '0.7rem' }}>
                            {fw.publisher ?? '—'}
                          </Typography>
                        </TableCell>
                        <TableCell>
                          <Typography variant="caption" color="text.secondary" sx={{ fontSize: '0.7rem' }}>
                            {fmtDate(fw.loaded_at)}
                          </Typography>
                        </TableCell>
                        <TableCell>
                          {!upd && (
                            <Chip
                              icon={<CheckCircleOutlined sx={{ fontSize: 13 }} />}
                              label="Current"
                              size="small"
                              sx={{ height: 18, fontSize: '0.6rem', bgcolor: 'rgba(76,175,80,0.1)', color: '#4CAF50', '& .MuiChip-icon': { color: '#4CAF50' } }}
                            />
                          )}
                          {upd?.status === 'available' && (
                            <Tooltip title={upd.note}>
                              <Chip
                                icon={<WarningAmberOutlined sx={{ fontSize: 13 }} />}
                                label={`Update: ${upd.latest}`}
                                size="small"
                                sx={{ height: 18, fontSize: '0.6rem', bgcolor: 'rgba(255,152,0,0.1)', color: '#FF9800', '& .MuiChip-icon': { color: '#FF9800' } }}
                              />
                            </Tooltip>
                          )}
                          {upd?.status === 'pending' && (
                            <Tooltip title={`${upd.note}${upd.eta ? ` ETA: ${upd.eta}` : ''}`}>
                              <Chip
                                icon={<UpdateOutlined sx={{ fontSize: 13 }} />}
                                label={`Pending: ${upd.latest}${upd.eta ? ` (${upd.eta})` : ''}`}
                                size="small"
                                sx={{ height: 18, fontSize: '0.6rem', bgcolor: 'rgba(66,165,245,0.1)', color: '#42A5F5', '& .MuiChip-icon': { color: '#42A5F5' } }}
                              />
                            </Tooltip>
                          )}
                        </TableCell>
                      </TableRow>
                    )
                  })}
                </TableBody>
              </Table>
            </TableContainer>
          </Box>
        ))
      }

      {/* ISO Reference Corpus & Glossary Standards */}
      <Box sx={{ mt: 4, mb: 1 }}>
        <Typography variant="subtitle2" sx={{ fontWeight: 700, mb: 0.5 }}>
          ISO Reference Corpus &amp; Glossary Standards
        </Typography>
        <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 2 }}>
          ISO/IEC normative texts indexed in the reference corpus and exposed via the Glossary page.
        </Typography>
        <TableContainer sx={{ border: '1px solid', borderColor: 'divider', borderRadius: 1 }}>
          <Table size="small">
            <TableHead>
              <TableRow sx={{ bgcolor: 'background.paper' }}>
                <TableCell sx={{ fontSize: '0.68rem', fontWeight: 700, color: 'text.secondary', textTransform: 'uppercase' }}>Standard</TableCell>
                <TableCell sx={{ fontSize: '0.68rem', fontWeight: 700, color: 'text.secondary', textTransform: 'uppercase' }}>Title</TableCell>
                <TableCell sx={{ fontSize: '0.68rem', fontWeight: 700, color: 'text.secondary', textTransform: 'uppercase' }}>Domain</TableCell>
                <TableCell sx={{ fontSize: '0.68rem', fontWeight: 700, color: 'text.secondary', textTransform: 'uppercase' }}>Edition</TableCell>
                <TableCell sx={{ fontSize: '0.68rem', fontWeight: 700, color: 'text.secondary', textTransform: 'uppercase' }}>Status</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {CORPUS_STANDARDS.map(s => (
                <TableRow key={s.standard} hover sx={{ '&:last-child td': { border: 0 } }}>
                  <TableCell>
                    <Typography variant="body2" sx={{ fontWeight: 600, fontSize: '0.78rem', fontFamily: 'monospace' }}>
                      {s.standard}
                    </Typography>
                  </TableCell>
                  <TableCell>
                    <Typography variant="body2" sx={{ fontSize: '0.75rem' }}>{s.title}</Typography>
                  </TableCell>
                  <TableCell>
                    <Chip
                      label={s.domain}
                      size="small"
                      sx={{
                        height: 18, fontSize: '0.6rem',
                        bgcolor: `${DOMAIN_COLOR[s.domain] ?? '#455A64'}22`,
                        color: DOMAIN_COLOR[s.domain] ?? '#455A64',
                        fontWeight: 600,
                      }}
                    />
                  </TableCell>
                  <TableCell>
                    <Typography variant="body2" sx={{ fontSize: '0.75rem', fontFamily: 'monospace' }}>
                      {s.edition}
                    </Typography>
                  </TableCell>
                  <TableCell>
                    {s.status === 'current' && (
                      <Chip
                        icon={<CheckCircleOutlined sx={{ fontSize: 13 }} />}
                        label="Current"
                        size="small"
                        sx={{ height: 18, fontSize: '0.6rem', bgcolor: 'rgba(76,175,80,0.1)', color: '#4CAF50', '& .MuiChip-icon': { color: '#4CAF50' } }}
                      />
                    )}
                    {s.status === 'pending' && (
                      <Tooltip title={`${s.note ?? ''}${s.eta ? ` ETA: ${s.eta}` : ''}`}>
                        <Chip
                          icon={<UpdateOutlined sx={{ fontSize: 13 }} />}
                          label={`Pending${s.eta ? ` (${s.eta})` : ''}`}
                          size="small"
                          sx={{ height: 18, fontSize: '0.6rem', bgcolor: 'rgba(66,165,245,0.1)', color: '#42A5F5', '& .MuiChip-icon': { color: '#42A5F5' } }}
                        />
                      </Tooltip>
                    )}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </Box>

      <Typography variant="caption" color="text.disabled" sx={{ fontSize: '0.62rem', display: 'block', mt: 2 }}>
        <InfoOutlined sx={{ fontSize: 12, verticalAlign: 'middle', mr: 0.5 }} />
        Compliance datasets loaded from <code>datasets/data/*.json</code> on backend startup.
        ISO corpus seed files live in <code>datasets/data/iso-reference/</code>.
        Update availability tracked in <code>FrameworkTracker.tsx</code> → <code>KNOWN_UPDATES</code> and <code>CORPUS_STANDARDS</code>.
      </Typography>
    </Box>
  )
}

// isms-core-platform/frontend/src/app/pages/framework-tracker/framework-tracker.component.ts
import { Component, inject, computed } from '@angular/core'
import { HttpClient } from '@angular/common/http'
import { firstValueFrom } from 'rxjs'

import { injectQuery } from '@tanstack/angular-query-experimental'

import { MatCardModule } from '@angular/material/card'
import { MatTableModule } from '@angular/material/table'
import { MatTooltipModule } from '@angular/material/tooltip'
import { MatIconModule } from '@angular/material/icon'
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner'
import { MatChipsModule } from '@angular/material/chips'

import { PageHeaderComponent } from '../../shared/components/page-header.component'

// ─── Types ────────────────────────────────────────────────────────────────────

interface FrameworkRow {
  id: string
  code: string
  name: string
  version: string | null
  publisher: string | null
  source_url: string | null
  jurisdiction: string | null
  controls_count: number
  loaded_at: string
}

interface KnownUpdate {
  latest: string
  status: 'pending' | 'available'
  note: string
  eta?: string
}

interface CorpusStandardRow {
  standard: string
  title: string
  domain: string
  edition: string
  status: 'current' | 'pending'
  note?: string
  eta?: string
}

// ─── Static data ──────────────────────────────────────────────────────────────

const KNOWN_UPDATES: Record<string, KnownUpdate> = {
  ISO27017: {
    latest: '2025',
    status: 'pending',
    note: 'ISO/IEC 27017:2025 revision in progress — replaces 2015 edition. New control pack planned on release.',
    eta: '~June 2026',
  },
}

const CORPUS_STANDARDS: CorpusStandardRow[] = [
  { standard: 'ISO/IEC 27000',       title: 'Information security management — Overview and vocabulary', domain: 'ISMS',            edition: 'FDIS (replacing 2018)', status: 'pending', note: 'FDIS ballot in progress — replaces ISO/IEC 27000:2018 with updated terminology aligned to ISO 27001:2022.', eta: '~June 2026' },
  { standard: 'ISO/IEC 22123-1:2023', title: 'Cloud computing — Vocabulary',                              domain: 'Cloud Computing', edition: '2023',              status: 'current' },
  { standard: 'ISO/IEC 22123-2:2023', title: 'Cloud computing — Concepts',                                domain: 'Cloud Computing', edition: '2023',              status: 'current' },
  { standard: 'ISO/IEC 22123-3:2023', title: 'Cloud computing — Reference Architecture (CCRA)',           domain: 'Cloud Computing', edition: '2023',              status: 'current' },
  { standard: 'ISO/IEC 42001:2023',   title: 'AI management system (AIMS)',                               domain: 'AI Management',   edition: '2023',              status: 'current' },
  { standard: 'ISO/IEC 42005:2025',   title: 'AI system impact assessment',                               domain: 'AI Management',   edition: '2025',              status: 'current' },
  { standard: 'ISO/IEC 22989:2022',   title: 'AI concepts and terminology',                               domain: 'AI Management',   edition: '2022',              status: 'current' },
  { standard: 'ISO/IEC 19395:2015',   title: 'Smart data centre resource monitoring',                     domain: 'Infrastructure',  edition: '2015',              status: 'current' },
  { standard: 'ISO/IEC 30141:2024',   title: 'IoT reference architecture',                                domain: 'IoT',             edition: '2024',              status: 'current' },
  { standard: 'ISO/IEC 24091:2019',   title: 'Data centre storage power efficiency',                      domain: 'Infrastructure',  edition: '2019',              status: 'current' },
]

const DOMAIN_COLOR: Record<string, string> = {
  'ISMS':            '#455A64',
  'Cloud Computing': '#0288d1',
  'AI Management':   '#ff6b35',
  'Infrastructure':  '#00897b',
  'IoT':             '#6d4c41',
}

const JURISDICTION_LABEL: Record<string, string> = {
  INT: 'International', EU: 'European Union', US: 'United States',
  DE: 'Germany', CH: 'Switzerland', GB: 'United Kingdom',
  BE: 'Belgium', LU: 'Luxembourg', IT: 'Italy', FR: 'France', AT: 'Austria',
}

const JURISDICTION_COLOR: Record<string, string> = {
  INT: '#455A64', EU: '#1565C0', US: '#B71C1C', DE: '#4E342E',
  CH:  '#C62828', GB: '#1A237E', BE: '#1B5E20', LU: '#4A148C',
  IT:  '#006630', FR: '#0D47A1', AT: '#E65100',
}

const JURISDICTION_ORDER = ['INT', 'EU', 'US', 'CH', 'DE', 'GB', 'BE', 'LU', 'IT', 'FR', 'AT']

function jurisColor(j: string | null): string {
  return JURISDICTION_COLOR[j ?? 'INT'] ?? '#455A64'
}

function fmtDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
}

// ─── Component ────────────────────────────────────────────────────────────────

@Component({
  selector: 'app-framework-tracker',
  standalone: true,
  imports: [
    MatCardModule, MatTableModule, MatTooltipModule,
    MatIconModule, MatProgressSpinnerModule, MatChipsModule,
    PageHeaderComponent,
  ],
  template: `
    <div class="page-wrap">
      <app-page-header
        title="Framework Version Tracker"
        subtitle="Loaded compliance dataset versions, update availability, and dataset health" />

      <!-- Summary cards -->
      <div class="summary-row">
        @if (fwQuery.isLoading()) {
          @for (i of [1,2,3,4]; track i) {
            <div class="summary-skel"></div>
          }
        } @else {
          <mat-card class="summary-card">
            <mat-card-content>
              <span class="card-label">Frameworks loaded</span>
              <span class="card-value">{{ fwQuery.data()?.length ?? 0 }}</span>
            </mat-card-content>
          </mat-card>
          <mat-card class="summary-card">
            <mat-card-content>
              <span class="card-label">Total controls</span>
              <span class="card-value">{{ totalControls().toLocaleString() }}</span>
            </mat-card-content>
          </mat-card>
          <mat-card class="summary-card">
            <mat-card-content>
              <span class="card-label">Updates available</span>
              <span class="card-value"
                [style.color]="updateCount() > 0 ? '#FF9800' : '#4CAF50'">{{ updateCount() }}</span>
              <span class="card-sub">datasets behind latest release</span>
            </mat-card-content>
          </mat-card>
          <mat-card class="summary-card">
            <mat-card-content>
              <span class="card-label">Pending releases</span>
              <span class="card-value"
                [style.color]="pendingCount() > 0 ? '#42A5F5' : '#9E9E9E'">{{ pendingCount() }}</span>
              <span class="card-sub">upcoming versions to watch</span>
            </mat-card-content>
          </mat-card>
        }
      </div>

      <!-- Loading skeleton for table -->
      @if (fwQuery.isLoading()) {
        <div class="table-skel"></div>
      }

      <!-- Per-jurisdiction tables -->
      @if (!fwQuery.isLoading() && fwQuery.data()) {
        @for (j of visibleJurisdictions(); track j) {
          <div class="juris-section">
            <div class="juris-header">
              <div class="juris-bar" [style.background]="jurisColor(j)"></div>
              <span class="juris-label" [style.color]="jurisColor(j)">
                {{ jurisdictionLabel(j) }}
              </span>
              <span class="juris-count">
                ({{ grouped()[j]?.length }} framework{{ grouped()[j]?.length !== 1 ? 's' : '' }})
              </span>
            </div>

            <div class="table-container">
              <table mat-table [dataSource]="grouped()[j] ?? []" class="full-table">

                <!-- Framework column -->
                <ng-container matColumnDef="framework">
                  <th mat-header-cell *matHeaderCellDef class="col-header">Framework</th>
                  <td mat-cell *matCellDef="let fw">
                    <div class="fw-name-row">
                      <span class="fw-name">{{ fw.name }}</span>
                      @if (fw.source_url) {
                        <mat-icon
                          class="icon-sm icon-link"
                          [matTooltip]="fw.source_url"
                          (click)="openUrl(fw.source_url)">open_in_new</mat-icon>
                      }
                    </div>
                    <span class="fw-code">{{ fw.code }}</span>
                  </td>
                </ng-container>

                <!-- Version column -->
                <ng-container matColumnDef="version">
                  <th mat-header-cell *matHeaderCellDef class="col-header">Version</th>
                  <td mat-cell *matCellDef="let fw">
                    <span class="mono-text">{{ fw.version ?? '—' }}</span>
                  </td>
                </ng-container>

                <!-- Controls column -->
                <ng-container matColumnDef="controls">
                  <th mat-header-cell *matHeaderCellDef class="col-header col-right">Controls</th>
                  <td mat-cell *matCellDef="let fw" class="col-right">
                    <span class="controls-count">{{ fw.controls_count.toLocaleString() }}</span>
                  </td>
                </ng-container>

                <!-- Publisher column -->
                <ng-container matColumnDef="publisher">
                  <th mat-header-cell *matHeaderCellDef class="col-header">Publisher</th>
                  <td mat-cell *matCellDef="let fw">
                    <span class="dim-text">{{ fw.publisher ?? '—' }}</span>
                  </td>
                </ng-container>

                <!-- Loaded column -->
                <ng-container matColumnDef="loaded">
                  <th mat-header-cell *matHeaderCellDef class="col-header">Loaded</th>
                  <td mat-cell *matCellDef="let fw">
                    <span class="dim-text">{{ fmtDate(fw.loaded_at) }}</span>
                  </td>
                </ng-container>

                <!-- Status column -->
                <ng-container matColumnDef="status">
                  <th mat-header-cell *matHeaderCellDef class="col-header">Status</th>
                  <td mat-cell *matCellDef="let fw">
                    @if (!knownUpdate(fw.code)) {
                      <span class="chip chip-current">
                        <mat-icon class="icon-xs icon-inline">check_circle</mat-icon>
                        Current
                      </span>
                    }
                    @if (knownUpdate(fw.code)?.status === 'available') {
                      <span class="chip chip-warn" [matTooltip]="knownUpdate(fw.code)!.note">
                        <mat-icon class="icon-xs icon-inline">warning</mat-icon>
                        Update: {{ knownUpdate(fw.code)!.latest }}
                      </span>
                    }
                    @if (knownUpdate(fw.code)?.status === 'pending') {
                      <span class="chip chip-pending"
                        [matTooltip]="knownUpdate(fw.code)!.note + (knownUpdate(fw.code)!.eta ? ' ETA: ' + knownUpdate(fw.code)!.eta : '')">
                        <mat-icon class="icon-xs icon-inline">update</mat-icon>
                        Pending: {{ knownUpdate(fw.code)!.latest }}{{ knownUpdate(fw.code)!.eta ? ' (' + knownUpdate(fw.code)!.eta + ')' : '' }}
                      </span>
                    }
                  </td>
                </ng-container>

                <tr mat-header-row *matHeaderRowDef="fwColumns"></tr>
                <tr mat-row *matRowDef="let row; columns: fwColumns" class="hover-row"></tr>
              </table>
            </div>
          </div>
        }
      }

      <!-- ISO Reference Corpus -->
      <div class="corpus-section">
        <div class="corpus-heading">ISO Reference Corpus &amp; Glossary Standards</div>
        <div class="corpus-subtitle">
          ISO/IEC normative texts indexed in the reference corpus and exposed via the Glossary page.
        </div>

        <div class="table-container">
          <table mat-table [dataSource]="corpusStandards" class="full-table">

            <!-- Standard -->
            <ng-container matColumnDef="standard">
              <th mat-header-cell *matHeaderCellDef class="col-header">Standard</th>
              <td mat-cell *matCellDef="let s">
                <span class="std-code">{{ s.standard }}</span>
              </td>
            </ng-container>

            <!-- Title -->
            <ng-container matColumnDef="title">
              <th mat-header-cell *matHeaderCellDef class="col-header">Title</th>
              <td mat-cell *matCellDef="let s">
                <span class="std-title">{{ s.title }}</span>
              </td>
            </ng-container>

            <!-- Domain -->
            <ng-container matColumnDef="domain">
              <th mat-header-cell *matHeaderCellDef class="col-header">Domain</th>
              <td mat-cell *matCellDef="let s">
                <span class="domain-chip"
                  [style.background]="domainColor(s.domain) + '22'"
                  [style.color]="domainColor(s.domain)">
                  {{ s.domain }}
                </span>
              </td>
            </ng-container>

            <!-- Edition -->
            <ng-container matColumnDef="edition">
              <th mat-header-cell *matHeaderCellDef class="col-header">Edition</th>
              <td mat-cell *matCellDef="let s">
                <span class="mono-text">{{ s.edition }}</span>
              </td>
            </ng-container>

            <!-- Status -->
            <ng-container matColumnDef="status">
              <th mat-header-cell *matHeaderCellDef class="col-header">Status</th>
              <td mat-cell *matCellDef="let s">
                @if (s.status === 'current') {
                  <span class="chip chip-current">
                    <mat-icon class="icon-xs icon-inline">check_circle</mat-icon>
                    Current
                  </span>
                }
                @if (s.status === 'pending') {
                  <span class="chip chip-pending"
                    [matTooltip]="(s.note ?? '') + (s.eta ? ' ETA: ' + s.eta : '')">
                    <mat-icon class="icon-xs icon-inline">update</mat-icon>
                    Pending{{ s.eta ? ' (' + s.eta + ')' : '' }}
                  </span>
                }
              </td>
            </ng-container>

            <tr mat-header-row *matHeaderRowDef="corpusColumns"></tr>
            <tr mat-row *matRowDef="let row; columns: corpusColumns" class="hover-row"></tr>
          </table>
        </div>
      </div>

      <div class="footer-note">
        <mat-icon class="icon-xs">info</mat-icon>
        Compliance datasets loaded from <code>datasets/data/*.json</code> on backend startup.
        ISO corpus seed files live in <code>datasets/data/iso-reference/</code>.
        Update availability tracked in <code>FrameworkTracker</code> → <code>KNOWN_UPDATES</code> and <code>CORPUS_STANDARDS</code>.
      </div>
    </div>
  `,
  styles: [`
    :host { display: block; }

    .page-wrap { padding: 24px; max-width: 1200px; }

    .summary-row { display: flex; gap: 16px; margin-top: 16px; margin-bottom: 24px; flex-wrap: wrap; }
    .summary-card { flex: 1; min-width: 140px; }
    .summary-card mat-card-content { padding-bottom: 12px !important; display: flex; flex-direction: column; }
    .card-label {
      font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.06em;
      color: var(--mat-sys-on-surface-variant); margin-bottom: 4px;
    }
    .card-value { font-size: 1.5rem; font-weight: 700; line-height: 1.2; }
    .card-sub { font-size: 0.65rem; color: var(--mat-sys-on-surface-variant); margin-top: 2px; }

    .summary-skel { flex: 1; min-width: 140px; height: 80px; border-radius: 4px; background: var(--mat-sys-surface-variant); }
    .table-skel { height: 200px; border-radius: 4px; background: var(--mat-sys-surface-variant); margin-bottom: 24px; }

    .juris-section { margin-bottom: 24px; }
    .juris-header { display: flex; align-items: center; gap: 8px; margin-bottom: 8px; }
    .juris-count { font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); }
    .juris-bar { width: 4px; height: 20px; border-radius: 2px; }
    .juris-label { font-size: 0.8rem; font-weight: 700; }

    .full-table { width: 100%; }

    .table-container {
      border: 1px solid var(--mat-sys-outline-variant);
      border-radius: 4px;
      overflow: hidden;
      background: var(--mat-sys-surface-container);
    }
    .col-header {
      font-size: 0.68rem !important; font-weight: 700 !important;
      text-transform: uppercase; color: var(--mat-sys-on-surface-variant) !important;
      letter-spacing: 0.04em;
    }
    .col-right { text-align: right; }
    .hover-row:hover { background: var(--mat-sys-surface-variant); }
    .hover-row:last-child td { border-bottom: none; }

    .fw-name-row { display: flex; align-items: center; gap: 6px; }
    .fw-name { display: block; font-weight: 600; font-size: 0.78rem; }
    .fw-code { display: block; font-size: 0.62rem; color: var(--mat-sys-on-surface-variant); font-family: monospace; }
    .mono-text { font-family: monospace; font-size: 0.75rem; }
    .dim-text { font-size: 0.7rem; color: var(--mat-sys-on-surface-variant); }
    .controls-count { font-size: 0.75rem; font-weight: 600; }

    .icon-xs { font-size: 11px !important; height: 11px !important; width: 11px !important; line-height: 11px !important; }
    .icon-inline { vertical-align: middle; margin-right: 3px; }
    .icon-link { color: var(--mat-sys-on-surface-variant); cursor: pointer; }

    .chip {
      display: inline-flex; align-items: center;
      height: 18px; padding: 0 6px; border-radius: 9px;
      font-size: 0.6rem; font-weight: 600; white-space: nowrap;
    }
    .chip-current { background: rgba(0,199,82,0.1); color: #00c752; }
    .chip-warn    { background: rgba(255,152,0,0.1);  color: #FF9800; }
    .chip-pending { background: rgba(66,165,245,0.1); color: #42A5F5; }

    .domain-chip {
      display: inline-block; height: 18px; line-height: 18px;
      padding: 0 6px; border-radius: 9px;
      font-size: 0.6rem; font-weight: 600;
    }

    .corpus-section { margin-top: 32px; margin-bottom: 8px; }
    .corpus-heading { font-size: 0.95rem; font-weight: 700; margin-bottom: 4px; }
    .corpus-subtitle { font-size: 0.78rem; color: var(--mat-sys-on-surface-variant); margin-bottom: 16px; }
    .std-code { font-family: monospace; font-weight: 600; font-size: 0.78rem; }
    .std-title { font-size: 0.75rem; }

    .footer-note {
      font-size: 0.62rem; color: var(--mat-sys-on-surface-variant);
      margin-top: 16px; display: flex; align-items: center; gap: 4px;
    }
  `],
})
export class FrameworkTrackerComponent {
  private http = inject(HttpClient)

  readonly fwColumns = ['framework', 'version', 'controls', 'publisher', 'loaded', 'status']
  readonly corpusColumns = ['standard', 'title', 'domain', 'edition', 'status']
  readonly corpusStandards = CORPUS_STANDARDS

  fwQuery = injectQuery(() => ({
    queryKey: ['framework-tracker'],
    queryFn: () => firstValueFrom(this.http.get<FrameworkRow[]>('/api/v1/frameworks/')),
  }))

  grouped = computed((): Record<string, FrameworkRow[]> => {
    const fws = this.fwQuery.data() ?? []
    const g: Record<string, FrameworkRow[]> = {}
    for (const fw of fws) {
      const j = fw.jurisdiction ?? 'INT'
      if (!g[j]) g[j] = []
      g[j].push(fw)
    }
    return g
  })

  visibleJurisdictions = computed(() =>
    JURISDICTION_ORDER.filter(j => (this.grouped()[j]?.length ?? 0) > 0)
  )

  totalControls = computed(() =>
    (this.fwQuery.data() ?? []).reduce((sum, fw) => sum + fw.controls_count, 0)
  )

  updateCount = computed(() =>
    (this.fwQuery.data() ?? []).filter(fw => KNOWN_UPDATES[fw.code]?.status === 'available').length
  )

  pendingCount = computed(() =>
    (this.fwQuery.data() ?? []).filter(fw => KNOWN_UPDATES[fw.code]?.status === 'pending').length
  )

  knownUpdate(code: string): KnownUpdate | undefined {
    return KNOWN_UPDATES[code]
  }

  jurisColor(j: string): string { return jurisColor(j) }
  jurisdictionLabel(j: string): string { return JURISDICTION_LABEL[j] ?? j }
  fmtDate(iso: string): string { return fmtDate(iso) }
  domainColor(d: string): string { return DOMAIN_COLOR[d] ?? '#455A64' }

  openUrl(url: string | null): void {
    if (url) window.open(url, '_blank')
  }
}
