// isms-core-platform/frontend/src/pages/Home.tsx
import { useState } from 'react'
import { Box, Chip, Typography, Skeleton, LinearProgress, Tooltip, TextField, InputAdornment, IconButton } from '@mui/material'
import {
  ShieldOutlined,
  LockPersonOutlined,
  CloudOutlined,
  VerifiedOutlined,
  ExploreOutlined,
  CodeOutlined,
  SummarizeOutlined,
  GppMaybeOutlined,
  AdminPanelSettingsOutlined,
  MonitorHeartOutlined,
  ArrowForwardOutlined,
  CheckCircleOutlined,
  RadioButtonUncheckedOutlined,
  SearchOutlined,
  ElectricalServicesOutlined,
  GridViewOutlined,
  AccountBalanceOutlined,
  SecurityOutlined,
  PolicyOutlined,
  FolderOpenOutlined,
  BuildOutlined,
  InsightsOutlined,
  HandshakeOutlined,
  HealthAndSafetyOutlined,
  PsychologyOutlined,
  BugReportOutlined,
  WarningAmberOutlined,
  StreamOutlined,
  ErrorOutlineOutlined,
} from '@mui/icons-material'
import { useQuery } from '@tanstack/react-query'
import { useNavigate } from 'react-router-dom'
import { dashboardApi, type HomeSummary } from '../api/dashboard'
import { projectsApi } from '../api/projectsApi'
import { feedsApi } from '../api/feedsApi'
import { useProduct, PRODUCT_COLORS, PRODUCT_LABELS } from '../store/ProductContext'
import { useAuth } from '../store/AuthContext'
import { useProject } from '../store/ProjectContext'

const PLATFORM_TOOLS = [
  { label: 'Projects',     path: '/projects',     icon: <FolderOpenOutlined sx={{ fontSize: 17 }} /> },
  { label: 'QA',           path: '/qa',           icon: <VerifiedOutlined sx={{ fontSize: 17 }} /> },
  { label: 'Search',       path: '/search',       icon: <SearchOutlined sx={{ fontSize: 17 }} /> },
  { label: 'Compass',      path: '/compass',      icon: <ExploreOutlined sx={{ fontSize: 17 }} /> },
  { label: 'Generators',   path: '/generators',   icon: <CodeOutlined sx={{ fontSize: 17 }} /> },
  { label: 'Connectors',   path: '/connectors',   icon: <ElectricalServicesOutlined sx={{ fontSize: 17 }} /> },
  { label: 'Report',       path: '/report',       icon: <SummarizeOutlined sx={{ fontSize: 17 }} /> },
  { label: 'Risk',         path: '/risk',         icon: <GppMaybeOutlined sx={{ fontSize: 17 }} /> },
  { label: 'Remediation',  path: '/remediation',  icon: <BuildOutlined sx={{ fontSize: 17 }} /> },
  { label: 'KPI Metrics',  path: '/metrics',      icon: <InsightsOutlined sx={{ fontSize: 17 }} /> },
  { label: 'TPRM',         path: '/tprm',         icon: <HandshakeOutlined sx={{ fontSize: 17 }} /> },
  { label: 'BIA',          path: '/bia',           icon: <HealthAndSafetyOutlined sx={{ fontSize: 17 }} /> },
  { label: 'EBIOS RM',     path: '/ebios',        icon: <PsychologyOutlined sx={{ fontSize: 17 }} /> },
  { label: 'Admin',        path: '/admin',        icon: <AdminPanelSettingsOutlined sx={{ fontSize: 17 }} /> },
  { label: 'System',       path: '/system',       icon: <MonitorHeartOutlined sx={{ fontSize: 17 }} /> },
]

const COMPLIANCE_TOOLS = [
  { label: 'NIST CSF 2.0',   path: '/nist-csf',     icon: <GridViewOutlined sx={{ fontSize: 17 }} /> },
  { label: 'NIST AI RMF',   path: '/nist-ai-rmf',  icon: <PolicyOutlined sx={{ fontSize: 17 }} /> },
  { label: 'NIS2',            path: '/nis2',     icon: <ShieldOutlined sx={{ fontSize: 17 }} /> },
  { label: 'DORA',            path: '/dora',     icon: <AccountBalanceOutlined sx={{ fontSize: 17 }} /> },
  { label: 'CIS Controls',   path: '/cis',      icon: <SecurityOutlined sx={{ fontSize: 17 }} /> },
  { label: 'BSI Grundschutz', path: '/bsi',      icon: <ShieldOutlined sx={{ fontSize: 17 }} /> },
  { label: 'CSRM (NCSC CH)', path: '/csrm',     icon: <LockPersonOutlined sx={{ fontSize: 17 }} /> },
  { label: 'TISAX',           path: '/tisax',    icon: <VerifiedOutlined sx={{ fontSize: 17 }} /> },
  { label: 'Swiss nDSG',     path: '/ndsg',     icon: <LockPersonOutlined sx={{ fontSize: 17 }} /> },
  { label: 'EU CRA',          path: '/cra',      icon: <SecurityOutlined sx={{ fontSize: 17 }} /> },
  { label: 'EU AI Act',       path: '/ai-act',   icon: <PolicyOutlined sx={{ fontSize: 17 }} /> },
  { label: 'EU Cloud Sov.',  path: '/eu-cloud-sov', icon: <CloudOutlined sx={{ fontSize: 17 }} /> },
  { label: 'COBIT 2019',    path: '/cobit',         icon: <AccountBalanceOutlined sx={{ fontSize: 17 }} /> },
]

const PRODUCT_STANDARDS = {
  isms:    'ISO/IEC 27001:2022',
  privacy: 'ISO/IEC 27701:2025',
  cloud:   'ISO/IEC 27018:2025',
}

const PRODUCT_ICONS = {
  isms:    <ShieldOutlined />,
  privacy: <LockPersonOutlined />,
  cloud:   <CloudOutlined />,
}

function Num({ value, color, loading }: { value?: number; color: string; loading: boolean }) {
  if (loading) return <Skeleton variant="text" width={32} height={32} />
  return (
    <Typography variant="h5" sx={{ fontWeight: 700, color, lineHeight: 1, fontSize: '1.4rem' }}>
      {value ?? '—'}
    </Typography>
  )
}

function CoverageBar({ label, pct, color, loading }: { label: string; pct?: number; color: string; loading: boolean }) {
  return (
    <Box sx={{ mb: 0.9 }}>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 0.3 }}>
        <Typography variant="caption" sx={{ fontSize: '0.69rem', color: 'text.secondary' }}>{label}</Typography>
        {loading
          ? <Skeleton variant="text" width={30} />
          : <Typography variant="caption" sx={{ fontSize: '0.69rem', fontWeight: 600, color }}>{pct ?? 0}%</Typography>
        }
      </Box>
      {loading
        ? <Skeleton variant="rectangular" height={5} sx={{ borderRadius: 3 }} />
        : <LinearProgress
            variant="determinate"
            value={Math.min(pct ?? 0, 100)}
            sx={{
              height: 5, borderRadius: 3,
              bgcolor: `${color}20`,
              '& .MuiLinearProgress-bar': { bgcolor: color, borderRadius: 3 },
            }}
          />
      }
    </Box>
  )
}

function StatusDot({ ok, label, loading }: { ok: boolean; label: string; loading: boolean }) {
  if (loading) return <Skeleton variant="text" width={120} height={20} sx={{ mb: 0.5 }} />
  return (
    <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.75, mb: 0.5 }}>
      {ok
        ? <CheckCircleOutlined sx={{ fontSize: 13, color: '#70AD47' }} />
        : <RadioButtonUncheckedOutlined sx={{ fontSize: 13, color: 'text.disabled' }} />
      }
      <Typography variant="caption" sx={{ fontSize: '0.71rem', color: ok ? 'text.primary' : 'text.disabled' }}>
        {label}
      </Typography>
    </Box>
  )
}

function ProductCard({
  product,
  loading,
  onClick,
  children,
}: {
  product: 'isms' | 'privacy' | 'cloud'
  loading: boolean
  onClick: () => void
  children: React.ReactNode
}) {
  const color = PRODUCT_COLORS[product]
  return (
    <Box
      onClick={onClick}
      sx={{
        p: 2, borderRadius: 2, cursor: 'pointer', height: '100%',
        border: `1px solid ${color}28`,
        borderLeft: `4px solid ${color}`,
        bgcolor: `${color}07`,
        transition: 'all 0.15s',
        display: 'flex', flexDirection: 'column',
        '&:hover': { bgcolor: `${color}12`, borderColor: `${color}55` },
      }}
    >
      {/* Header */}
      <Box sx={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', mb: 2 }}>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <Box sx={{ color, fontSize: 20, display: 'flex' }}>{PRODUCT_ICONS[product]}</Box>
          <Box>
            <Typography variant="subtitle2" sx={{ fontWeight: 700, color, lineHeight: 1.2, fontSize: '0.85rem' }}>
              {PRODUCT_LABELS[product]}
            </Typography>
            <Typography variant="caption" sx={{ color: 'text.disabled', fontSize: '0.63rem' }}>
              {PRODUCT_STANDARDS[product]}
            </Typography>
          </Box>
        </Box>
        <ArrowForwardOutlined sx={{ fontSize: 15, color: 'text.disabled', mt: 0.25 }} />
      </Box>

      {children}
    </Box>
  )
}

const FAMILY_COLOR: Record<string, string> = {
  ISMS: '#4472C4', PRIVACY: '#70309f', CLOUD: '#0099cc',
}
const TOTAL_CG: Record<string, number> = { ISMS: 53, PRIVACY: 21, CLOUD: 12 }

export default function Home() {
  const navigate = useNavigate()
  const { user } = useAuth()
  const { setProduct } = useProduct()
  const { activeProjectsMap } = useProject()
  const activeProjectsList = (['ISMS', 'PRIVACY', 'CLOUD'] as const)
    .map(f => activeProjectsMap[f])
    .filter((p): p is NonNullable<typeof p> => !!p)
  const [searchQuery, setSearchQuery] = useState('')

  function handleSearch() {
    const q = searchQuery.trim()
    if (q.length >= 2) navigate(`/search?q=${encodeURIComponent(q)}`)
  }

  const { data: summary, isLoading } = useQuery({
    queryKey: ['home-summary'],
    queryFn: dashboardApi.getHomeSummary,
    staleTime: 30_000,
    retry: 2,
  })

  const { data: kevStats }    = useQuery({ queryKey: ['feeds', 'kev', 'stats'],    queryFn: feedsApi.getKevStats,      staleTime: 5 * 60_000 })
  const { data: indexStats }  = useQuery({ queryKey: ['nvd', 'index-stats'],       queryFn: feedsApi.getNvdIndexStats, staleTime: 5 * 60_000 })
  const { data: attackStats } = useQuery({ queryKey: ['feeds', 'attack', 'stats'], queryFn: feedsApi.getAttackStats,   staleTime: 5 * 60_000 })
  const { data: feedStatus }  = useQuery({ queryKey: ['feeds', 'status'],          queryFn: feedsApi.getStatus,        staleTime: 5 * 60_000 })

  const failedFeeds  = (feedStatus?.feeds ?? []).filter(f => f.last_status === 'error')
  const anyFeedError = failedFeeds.length > 0


  const now = new Date()
  const dateStr = now.toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })

  function goTo(product: 'isms' | 'privacy' | 'cloud') {
    setProduct(product)
    navigate('/overview')
  }

  const ismsColor = PRODUCT_COLORS.isms
  const privColor = PRODUCT_COLORS.privacy
  const cloudColor = PRODUCT_COLORS.cloud

  return (
    <Box sx={{
      height: 'calc(100vh - 48px)',
      display: 'flex',
      flexDirection: 'column',
      gap: 2,
      overflow: 'hidden',
    }}>
      {/* Header */}
      <Box sx={{ display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', flexShrink: 0 }}>
        <Box>
          <Typography variant="h5" sx={{ fontWeight: 700, lineHeight: 1, mb: 0.3, fontSize: '1.2rem' }}>
            ISMS CORE Platform
          </Typography>
          <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '0.74rem' }}>
            Information Security &amp; Privacy Compliance — {dateStr}
          </Typography>
        </Box>
        {user && (
          <Typography variant="caption" sx={{ color: 'text.disabled', fontSize: '0.68rem' }}>
            {user.email}
          </Typography>
        )}
      </Box>

      {/* Search bar */}
      <Box sx={{ flexShrink: 0 }}>
        <TextField
          fullWidth
          placeholder="Search policies and implementation guides across all standards…"
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
          size="small"
          InputProps={{
            startAdornment: (
              <InputAdornment position="start">
                <SearchOutlined fontSize="small" sx={{ color: 'text.disabled' }} />
              </InputAdornment>
            ),
            endAdornment: (
              <InputAdornment position="end">
                <IconButton size="small" onClick={handleSearch} disabled={searchQuery.trim().length < 2}>
                  <SearchOutlined fontSize="small" />
                </IconButton>
              </InputAdornment>
            ),
          }}
          sx={{
            '& .MuiOutlinedInput-root': {
              bgcolor: 'background.paper',
              fontSize: '0.88rem',
            },
          }}
        />
      </Box>

      {/* 3 product cards */}
      <Box sx={{ display: 'flex', gap: 2, flexShrink: 0 }}>

        {/* ISMS — wider (50%) */}
        <Box sx={{ flex: '0 0 48%' }}>
          <ProductCard product="isms" loading={isLoading} onClick={() => goTo('isms')}>
            {/* Stats row */}
            <Box sx={{ display: 'flex', gap: 2.5, mb: 2 }}>
              <Box>
                <Num value={summary?.isms.groups} color={ismsColor} loading={isLoading} />
                <Typography variant="caption" sx={{ fontSize: '0.63rem', color: 'text.secondary' }}>Control Groups</Typography>
              </Box>
              <Box>
                <Num value={summary?.isms.policies} color={ismsColor} loading={isLoading} />
                <Typography variant="caption" sx={{ fontSize: '0.63rem', color: 'text.secondary' }}>Policies</Typography>
              </Box>
              <Box>
                <Num value={summary?.isms.imps} color={ismsColor} loading={isLoading} />
                <Typography variant="caption" sx={{ fontSize: '0.63rem', color: 'text.secondary' }}>Impl. Guides</Typography>
              </Box>
              <Box>
                <Num
                  value={summary?.isms.open_gaps}
                  color={(summary?.isms.open_gaps ?? 0) > 0 ? '#FFC000' : '#70AD47'}
                  loading={isLoading}
                />
                <Typography variant="caption" sx={{ fontSize: '0.63rem', color: 'text.secondary' }}>Open Gaps</Typography>
              </Box>
            </Box>

            {/* Coverage bars */}
            <CoverageBar label="Framework coverage" pct={summary?.isms.fw_coverage_pct} color={ismsColor} loading={isLoading} />
            <CoverageBar label="Operational coverage" pct={summary?.isms.op_coverage_pct} color="#70AD47" loading={isLoading} />
          </ProductCard>
        </Box>

        {/* Privacy */}
        <Box sx={{ flex: 1 }}>
          <ProductCard product="privacy" loading={isLoading} onClick={() => goTo('privacy')}>
            <Box sx={{ display: 'flex', gap: 2.5, mb: 2 }}>
              <Box>
                <Num value={summary?.privacy.groups} color={privColor} loading={isLoading} />
                <Typography variant="caption" sx={{ fontSize: '0.63rem', color: 'text.secondary' }}>Control Groups</Typography>
              </Box>
              <Box>
                <Num value={summary?.privacy.policies} color={privColor} loading={isLoading} />
                <Typography variant="caption" sx={{ fontSize: '0.63rem', color: 'text.secondary' }}>Policies</Typography>
              </Box>
              <Box>
                <Num value={summary?.privacy.imps} color={privColor} loading={isLoading} />
                <Typography variant="caption" sx={{ fontSize: '0.63rem', color: 'text.secondary' }}>Impl. Guides</Typography>
              </Box>
            </Box>
            <StatusDot ok={(summary?.privacy.policies ?? 0) > 0} label={`Policies (${summary?.privacy.policies ?? '…'})`} loading={isLoading} />
            <StatusDot ok={(summary?.privacy.imps ?? 0) > 0} label={`Implementation Guides (${summary?.privacy.imps ?? '…'})`} loading={isLoading} />
          </ProductCard>
        </Box>

        {/* Cloud */}
        <Box sx={{ flex: 1 }}>
          <ProductCard product="cloud" loading={isLoading} onClick={() => goTo('cloud')}>
            <Box sx={{ display: 'flex', gap: 2.5, mb: 2 }}>
              <Box>
                <Num value={summary?.cloud.groups} color={cloudColor} loading={isLoading} />
                <Typography variant="caption" sx={{ fontSize: '0.63rem', color: 'text.secondary' }}>Control Groups</Typography>
              </Box>
              <Box>
                <Num value={summary?.cloud.policies} color={cloudColor} loading={isLoading} />
                <Typography variant="caption" sx={{ fontSize: '0.63rem', color: 'text.secondary' }}>Policies</Typography>
              </Box>
              <Box>
                <Num value={summary?.cloud.imps} color={cloudColor} loading={isLoading} />
                <Typography variant="caption" sx={{ fontSize: '0.63rem', color: 'text.secondary' }}>Impl. Guides</Typography>
              </Box>
            </Box>
            <StatusDot ok={(summary?.cloud.policies ?? 0) > 0} label={`Policies (${summary?.cloud.policies ?? '…'})`} loading={isLoading} />
            <StatusDot ok={(summary?.cloud.imps ?? 0) > 0} label={`Implementation Guides (${summary?.cloud.imps ?? '…'})`} loading={isLoading} />
          </ProductCard>
        </Box>

      </Box>

      {/* Connector summary bar */}
      <Box
        onClick={() => navigate('/connectors')}
        sx={{
          flexShrink: 0,
          display: 'flex', alignItems: 'center', gap: 2.5,
          px: 2, py: 1, borderRadius: 1.5, cursor: 'pointer',
          border: '1px solid', borderColor: 'divider',
          bgcolor: 'background.paper',
          transition: 'all 0.12s',
          '&:hover': { borderColor: 'text.secondary', bgcolor: 'action.hover' },
        }}
      >
        <ElectricalServicesOutlined sx={{ fontSize: 18, color: 'text.secondary', flexShrink: 0 }} />
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.75 }}>
          {isLoading
            ? <Skeleton variant="text" width={16} height={22} />
            : <Typography variant="subtitle2" sx={{ fontWeight: 700, fontSize: '1rem', lineHeight: 1, color: (summary?.connectors?.active ?? 0) > 0 ? '#70AD47' : 'text.disabled' }}>
                {summary?.connectors?.active ?? 0}
              </Typography>
          }
          <Typography variant="caption" sx={{ fontSize: '0.7rem', color: 'text.secondary' }}>Active Connectors</Typography>
        </Box>
        <Box sx={{ width: '1px', height: 18, bgcolor: 'divider' }} />
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.75 }}>
          {isLoading
            ? <Skeleton variant="text" width={24} height={22} />
            : <Typography variant="subtitle2" sx={{ fontWeight: 700, fontSize: '1rem', lineHeight: 1, color: 'text.primary' }}>
                {summary?.connectors?.evidence_items ?? 0}
              </Typography>
          }
          <Typography variant="caption" sx={{ fontSize: '0.7rem', color: 'text.secondary' }}>Evidence Items</Typography>
        </Box>
        <Box sx={{ flex: 1 }} />
        <ArrowForwardOutlined sx={{ fontSize: 14, color: 'text.disabled' }} />
      </Box>

      {/* Intelligence summary bar */}
      <Box
        sx={{
          flexShrink: 0,
          display: 'flex', alignItems: 'center', gap: 2,
          px: 2, py: 1, borderRadius: 1.5,
          border: '1px solid', borderColor: 'divider',
          bgcolor: 'background.paper',
        }}
      >
        <StreamOutlined sx={{ fontSize: 16, color: '#B84F00', flexShrink: 0 }} />
        <Typography variant="caption" sx={{ fontSize: '0.63rem', textTransform: 'uppercase', letterSpacing: '0.08em', color: '#B84F00', fontWeight: 600, flexShrink: 0 }}>
          Intelligence
        </Typography>
        <Box sx={{ width: '1px', height: 18, bgcolor: 'divider' }} />

        {/* CVE Index */}
        <Box
          onClick={() => navigate('/cve-explorer')}
          sx={{ display: 'flex', alignItems: 'center', gap: 0.75, cursor: 'pointer', '&:hover': { opacity: 0.75 } }}
        >
          <BugReportOutlined sx={{ fontSize: 15, color: '#c62828' }} />
          <Typography variant="caption" sx={{ fontSize: '0.72rem', fontWeight: 700, color: '#c62828', lineHeight: 1 }}>
            {indexStats?.cve_total ? indexStats.cve_total.toLocaleString() : '—'}
          </Typography>
          <Typography variant="caption" sx={{ fontSize: '0.68rem', color: 'text.secondary' }}>CVEs</Typography>
        </Box>
        <Box sx={{ width: '1px', height: 18, bgcolor: 'divider' }} />

        {/* CISA KEV */}
        <Box
          onClick={() => navigate('/threat-feeds')}
          sx={{ display: 'flex', alignItems: 'center', gap: 0.75, cursor: 'pointer', '&:hover': { opacity: 0.75 } }}
        >
          <WarningAmberOutlined sx={{ fontSize: 15, color: '#e65100' }} />
          <Typography variant="caption" sx={{ fontSize: '0.72rem', fontWeight: 700, color: '#e65100', lineHeight: 1 }}>
            {kevStats?.total_entries ? kevStats.total_entries.toLocaleString() : '—'}
          </Typography>
          <Typography variant="caption" sx={{ fontSize: '0.68rem', color: 'text.secondary' }}>KEV</Typography>
        </Box>
        <Box sx={{ width: '1px', height: 18, bgcolor: 'divider' }} />

        {/* MITRE ATT&CK */}
        <Box
          onClick={() => navigate('/mitre-attack')}
          sx={{ display: 'flex', alignItems: 'center', gap: 0.75, cursor: 'pointer', '&:hover': { opacity: 0.75 } }}
        >
          <SecurityOutlined sx={{ fontSize: 15, color: '#B84F00' }} />
          <Typography variant="caption" sx={{ fontSize: '0.72rem', fontWeight: 700, color: '#B84F00', lineHeight: 1 }}>
            {attackStats ? (attackStats.total_techniques + attackStats.total_subtechniques).toLocaleString() : '—'}
          </Typography>
          <Typography variant="caption" sx={{ fontSize: '0.68rem', color: 'text.secondary' }}>ATT&CK</Typography>
        </Box>
        <Box sx={{ width: '1px', height: 18, bgcolor: 'divider' }} />

        {/* Feed Status */}
        <Box
          onClick={() => navigate('/threat-feeds')}
          sx={{ display: 'flex', alignItems: 'center', gap: 0.75, cursor: 'pointer', '&:hover': { opacity: 0.75 } }}
        >
          {anyFeedError
            ? <ErrorOutlineOutlined sx={{ fontSize: 15, color: '#c62828' }} />
            : <CheckCircleOutlined sx={{ fontSize: 15, color: '#70AD47' }} />
          }
          <Typography variant="caption" sx={{ fontSize: '0.72rem', fontWeight: 700, color: anyFeedError ? '#c62828' : '#70AD47', lineHeight: 1 }}>
            {anyFeedError ? `${failedFeeds.length} error${failedFeeds.length > 1 ? 's' : ''}` : 'All OK'}
          </Typography>
          <Typography variant="caption" sx={{ fontSize: '0.68rem', color: 'text.secondary' }}>Feeds</Typography>
        </Box>

        <Box sx={{ flex: 1 }} />
        <ArrowForwardOutlined sx={{ fontSize: 14, color: 'text.disabled' }} onClick={() => navigate('/threat-feeds')} />
      </Box>

      {/* Active project rows — one per active family */}
      {activeProjectsList.length > 0 && (
        <Box sx={{ flexShrink: 0, display: 'flex', flexDirection: 'column', gap: 0.75 }}>
          {activeProjectsList.map(proj => {
            const fam = proj.product_family
            const color = FAMILY_COLOR[fam] ?? '#4472C4'
            const total = TOTAL_CG[fam] ?? 53
            const polPct = Math.min(100, Math.round((proj.policy_count / Math.max(1, total)) * 100))
            return (
              <Box
                key={proj.id}
                onClick={() => navigate(`/projects/${proj.id}`)}
                sx={{
                  px: 2, py: 1.25, borderRadius: 1.5, cursor: 'pointer',
                  border: '1px solid', borderColor: `${color}50`,
                  borderLeft: `4px solid ${color}`,
                  bgcolor: `${color}07`,
                  transition: 'all 0.12s',
                  '&:hover': { bgcolor: `${color}12` },
                }}
              >
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
                  <FolderOpenOutlined sx={{ fontSize: 18, color, flexShrink: 0 }} />
                  <Box sx={{ flex: 1, minWidth: 0 }}>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 0.3 }}>
                      <Typography variant="caption" sx={{ fontWeight: 700, fontSize: '0.8rem', color, lineHeight: 1 }}>
                        {proj.name}
                      </Typography>
                      <Chip label="Selected" size="small" sx={{ height: 16, fontSize: '0.58rem', bgcolor: `${color}20`, color }} />
                      <Typography variant="caption" sx={{ fontSize: '0.68rem', color: 'text.disabled' }}>
                        {proj.organisation_name ?? ''}
                      </Typography>
                    </Box>
                    <LinearProgress
                      variant="determinate"
                      value={polPct}
                      sx={{ height: 3, borderRadius: 2, bgcolor: `${color}18`, '& .MuiLinearProgress-bar': { bgcolor: color } }}
                    />
                  </Box>
                  <Box sx={{ display: 'flex', gap: 2, flexShrink: 0 }}>
                    {[
                      { label: 'Policies', val: proj.policy_count },
                      { label: 'IMPs', val: proj.implementation_count },
                      { label: 'SCRs', val: proj.checklist_count },
                    ].map(({ label, val }) => (
                      <Box key={label} sx={{ textAlign: 'center' }}>
                        <Typography sx={{ fontWeight: 700, fontSize: '0.95rem', color, lineHeight: 1 }}>{val}</Typography>
                        <Typography variant="caption" sx={{ fontSize: '0.6rem', color: 'text.secondary' }}>{label}</Typography>
                      </Box>
                    ))}
                  </Box>
                  <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5, flexShrink: 0 }}>
                    <Typography variant="caption" sx={{ fontSize: '0.68rem', color: 'text.secondary' }}>
                      {Math.min(proj.policy_count, total)}/{total} control groups
                    </Typography>
                    <ArrowForwardOutlined sx={{ fontSize: 14, color: 'text.disabled' }} />
                  </Box>
                </Box>
              </Box>
            )
          })}
        </Box>
      )}

      {/* Platform tools */}
      <Box sx={{ flexShrink: 0 }}>
        <Typography variant="caption" sx={{ color: 'text.disabled', fontSize: '0.63rem', textTransform: 'uppercase', letterSpacing: '0.08em', display: 'block', mb: 0.75 }}>
          Platform Tools
        </Typography>
        <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap' }}>
          {PLATFORM_TOOLS.map((tool) => (
            <Tooltip key={tool.path} title={tool.label}>
              <Box
                onClick={() => navigate(tool.path)}
                sx={{
                  display: 'flex', alignItems: 'center', gap: 0.75,
                  px: 1.5, py: 0.7, borderRadius: 1.5, cursor: 'pointer',
                  border: '1px solid', borderColor: 'divider',
                  bgcolor: 'background.paper',
                  transition: 'all 0.12s',
                  '&:hover': { borderColor: 'text.secondary', bgcolor: 'action.hover' },
                }}
              >
                <Box sx={{ color: 'text.secondary', display: 'flex' }}>{tool.icon}</Box>
                <Typography variant="caption" sx={{ fontSize: '0.73rem', color: 'text.secondary', fontWeight: 500 }}>
                  {tool.label}
                </Typography>
              </Box>
            </Tooltip>
          ))}
        </Box>
      </Box>

      {/* Compliance tools */}
      <Box sx={{ flexShrink: 0 }}>
        <Typography variant="caption" sx={{ color: 'text.disabled', fontSize: '0.63rem', textTransform: 'uppercase', letterSpacing: '0.08em', display: 'block', mb: 0.75 }}>
          Compliance Assessments
        </Typography>
        <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap' }}>
          {COMPLIANCE_TOOLS.map((tool) => (
            <Tooltip key={tool.path} title={tool.label}>
              <Box
                onClick={() => navigate(tool.path)}
                sx={{
                  display: 'flex', alignItems: 'center', gap: 0.75,
                  px: 1.5, py: 0.7, borderRadius: 1.5, cursor: 'pointer',
                  border: '1px solid', borderColor: 'divider',
                  bgcolor: 'background.paper',
                  transition: 'all 0.12s',
                  '&:hover': { borderColor: 'text.secondary', bgcolor: 'action.hover' },
                }}
              >
                <Box sx={{ color: 'text.secondary', display: 'flex' }}>{tool.icon}</Box>
                <Typography variant="caption" sx={{ fontSize: '0.73rem', color: 'text.secondary', fontWeight: 500 }}>
                  {tool.label}
                </Typography>
              </Box>
            </Tooltip>
          ))}
        </Box>
      </Box>

    </Box>
  )
}

// isms-core-platform/frontend-angular/src/app/pages/home/home.component.ts
import { Component, inject, signal, computed } from '@angular/core'
import { Router } from '@angular/router'
import { FormsModule } from '@angular/forms'
import { firstValueFrom } from 'rxjs'
import { injectQuery } from '@tanstack/angular-query-experimental'

import { DecimalPipe } from '@angular/common'
import { MatFormFieldModule } from '@angular/material/form-field'
import { MatInputModule } from '@angular/material/input'
import { MatIconModule } from '@angular/material/icon'
import { MatButtonModule } from '@angular/material/button'
import { MatProgressBarModule } from '@angular/material/progress-bar'
import { MatTooltipModule } from '@angular/material/tooltip'
import { MatChipsModule } from '@angular/material/chips'

import { DashboardApiService } from '../../api/dashboard-api.service'
import { FeedsApiService } from '../../api/feeds-api.service'
import { ProductService, PRODUCT_COLORS, PRODUCT_LABELS, PRODUCT_SUBTITLES } from '../../core/services/product.service'
import { ProjectService } from '../../core/services/project.service'
import { AuthService } from '../../core/services/auth.service'

const PLATFORM_TOOLS = [
  { label: 'Projects',    path: '/projects',    icon: 'folder_open' },
  { label: 'QA',          path: '/qa',           icon: 'verified' },
  { label: 'Search',      path: '/search',       icon: 'search' },
  { label: 'Compass',     path: '/compass',      icon: 'explore' },
  { label: 'Generators',  path: '/generators',   icon: 'code' },
  { label: 'Connectors',  path: '/connectors',   icon: 'electrical_services' },
  { label: 'Report',      path: '/report',       icon: 'summarize' },
  { label: 'Risk',        path: '/risk',         icon: 'gpp_maybe' },
  { label: 'Remediation', path: '/remediation',  icon: 'build' },
  { label: 'KPI Metrics', path: '/metrics',      icon: 'insights' },
  { label: 'TPRM',        path: '/tprm',         icon: 'handshake' },
  { label: 'BIA',         path: '/bia',          icon: 'health_and_safety' },
  { label: 'EBIOS RM',    path: '/ebios',        icon: 'psychology' },
  { label: 'Admin',       path: '/admin',        icon: 'admin_panel_settings' },
  { label: 'System',      path: '/system',       icon: 'monitor_heart' },
]

const COMPLIANCE_TOOLS = [
  { label: 'NIST CSF 2.0',       path: '/nist-csf',                        icon: 'grid_view' },
  { label: 'NIST AI RMF',        path: '/compliance/NIST-AI-RMF',          icon: 'policy' },
  { label: 'NIST 800-53 R5',     path: '/compliance/NIST-SP-800-53',       icon: 'security' },
  { label: 'NIS2',               path: '/compliance/NIS2',                 icon: 'shield' },
  { label: 'DORA',               path: '/compliance/DORA',                 icon: 'account_balance' },
  { label: 'CIS Controls',       path: '/compliance/CIS-CSC',              icon: 'security' },
  { label: 'BSI Grundschutz',    path: '/compliance/BSI-GRUNDSCHUTZ',      icon: 'shield' },
  { label: 'CSRM (NCSC CH)',     path: '/csrm',                            icon: 'lock_person' },
  { label: 'TISAX',              path: '/compliance/TISAX',                icon: 'verified' },
  { label: 'Swiss nDSG',         path: '/compliance/NDSG',                 icon: 'lock_person' },
  { label: 'EU CRA',             path: '/compliance/EU-CRA',               icon: 'security' },
  { label: 'EU AI Act',          path: '/compliance/EU-AI-ACT',            icon: 'policy' },
  { label: 'EU Cloud Sov.',      path: '/compliance/EU-CLOUD-SOVEREIGNTY', icon: 'cloud' },
  { label: 'COBIT 2019',         path: '/compliance/COBIT-2019',           icon: 'account_balance' },
  { label: 'CSA CCM v4.1',       path: '/compliance/CSA-CCM',              icon: 'cloud' },
  { label: 'CSA AICM',           path: '/compliance/CSA-AICM',             icon: 'policy' },
]

const PRODUCT_FAMILIES = ['ISMS', 'PRIVACY', 'CLOUD'] as const

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [
    FormsModule, DecimalPipe,
    MatFormFieldModule, MatInputModule, MatIconModule,
    MatButtonModule, MatProgressBarModule, MatTooltipModule, MatChipsModule,
  ],
  template: `
<div class="home">

  <!-- Header -->
  <div class="home__header">
    <div class="home__header-left">
      <h5 class="home__title">ISMS CORE Platform</h5>
      <span class="home__date">{{ today }}</span>
    </div>
    <span class="home__user">{{ auth.user()?.email }}</span>
  </div>

  <!-- Search bar -->
  <div class="home__search">
    <mat-form-field appearance="outline" subscriptSizing="dynamic" class="home__search-field">
      <mat-label>Search</mat-label>
      <mat-icon matPrefix>search</mat-icon>
      <input matInput
        placeholder="Search policies, controls, implementations…"
        [(ngModel)]="searchQuery"
        (keydown.enter)="doSearch()" />
      <button mat-icon-button matSuffix (click)="doSearch()" [disabled]="!searchQuery">
        <mat-icon>arrow_forward</mat-icon>
      </button>
    </mat-form-field>
  </div>

  <!-- Product cards -->
  <div class="home__products">

    <!-- ISMS card (wider) -->
    <div class="product-card product-card--isms"
         [style.border-top-color]="ismsColor"
         (click)="selectProduct('isms')">
      <div class="product-card__header">
        <span class="product-card__label" [style.color]="ismsColor">ISMS</span>
        <span class="product-card__subtitle">ISO 27001:2022 + Amd.1</span>
      </div>
      @if (ismsStats()) {
        <div class="product-card__stats">
          <div class="stat">
            <div class="stat__value">{{ ismsStats()!.groups }}</div>
            <div class="stat__label">Groups</div>
          </div>
          <div class="stat">
            <div class="stat__value">{{ ismsStats()!.policies }}</div>
            <div class="stat__label">Policies</div>
          </div>
          <div class="stat">
            <div class="stat__value">{{ ismsStats()!.imps }}</div>
            <div class="stat__label">IMPs</div>
          </div>
          <div class="stat" [class.stat--warn]="ismsStats()!.open_gaps > 0" [class.stat--ok]="ismsStats()!.open_gaps === 0">
            <div class="stat__value">{{ ismsStats()!.open_gaps }}</div>
            <div class="stat__label">Open Gaps</div>
          </div>
        </div>
        <div class="product-card__bars">
          <div class="bar-row">
            <span class="bar-row__label">Framework</span>
            <mat-progress-bar mode="determinate" [value]="ismsStats()!.fw_coverage_pct"
              [style.--mat-progress-bar-active-indicator-color]="'#327df4'"
              [style.--mat-progress-bar-track-color]="'rgba(50,125,244,0.18)'" />
            <span class="bar-row__pct">{{ ismsStats()!.fw_coverage_pct | number:'1.0-0' }}%</span>
          </div>
          <div class="bar-row">
            <span class="bar-row__label">Operational</span>
            <mat-progress-bar mode="determinate" [value]="ismsStats()!.op_coverage_pct"
              [style.--mat-progress-bar-active-indicator-color]="'#00c752'"
              [style.--mat-progress-bar-track-color]="'rgba(0,199,82,0.18)'" />
            <span class="bar-row__pct">{{ ismsStats()!.op_coverage_pct | number:'1.0-0' }}%</span>
          </div>
        </div>
      } @else {
        <div class="product-card__loading">—</div>
      }
    </div>

    <!-- Privacy card -->
    <div class="product-card"
         [style.border-top-color]="privacyColor"
         (click)="selectProduct('privacy')">
      <div class="product-card__header">
        <span class="product-card__label" [style.color]="privacyColor">PRIVACY</span>
        <span class="product-card__subtitle">ISO 27701:2025 Ed. 2</span>
      </div>
      @if (privacyStats()) {
        <div class="product-card__stats product-card__stats--col">
          <div class="stat-row">
            <span class="stat-row__label">Control Groups</span>
            <span class="stat-row__value">{{ privacyStats()!.groups }}</span>
          </div>
          <div class="stat-row">
            <span class="stat-row__label">Policies</span>
            <span class="stat-row__value">{{ privacyStats()!.policies }}</span>
          </div>
          <div class="stat-row">
            <span class="stat-row__label">Implementations</span>
            <span class="stat-row__value">{{ privacyStats()!.imps }}</span>
          </div>
        </div>
        <div class="product-card__dots">
          <div class="dot-row">
            <span class="dot" [style.background]="privacyColor"></span>
            <span class="dot-row__label">ISO 27701:2025</span>
          </div>
          <div class="dot-row">
            <span class="dot" [style.background]="privacyColor"></span>
            <span class="dot-row__label">Controller + Processor</span>
          </div>
        </div>
      } @else {
        <div class="product-card__loading">—</div>
      }
    </div>

    <!-- Cloud card -->
    <div class="product-card"
         [style.border-top-color]="cloudColor"
         (click)="selectProduct('cloud')">
      <div class="product-card__header">
        <span class="product-card__label" [style.color]="cloudColor">CLOUD</span>
        <span class="product-card__subtitle">ISO 27018:2025</span>
      </div>
      @if (cloudStats()) {
        <div class="product-card__stats product-card__stats--col">
          <div class="stat-row">
            <span class="stat-row__label">Control Groups</span>
            <span class="stat-row__value">{{ cloudStats()!.groups }}</span>
          </div>
          <div class="stat-row">
            <span class="stat-row__label">Policies</span>
            <span class="stat-row__value">{{ cloudStats()!.policies }}</span>
          </div>
          <div class="stat-row">
            <span class="stat-row__label">Implementations</span>
            <span class="stat-row__value">{{ cloudStats()!.imps }}</span>
          </div>
        </div>
        <div class="product-card__dots">
          <div class="dot-row">
            <span class="dot" [style.background]="cloudColor"></span>
            <span class="dot-row__label">ISO 27018:2025</span>
          </div>
          <div class="dot-row">
            <span class="dot" [style.background]="cloudColor"></span>
            <span class="dot-row__label">Cloud PII Processor</span>
          </div>
        </div>
      } @else {
        <div class="product-card__loading">—</div>
      }
    </div>

    <!-- AI card -->
    <div class="product-card"
         [style.border-top-color]="aiColor"
         (click)="selectProduct('ai')">
      <div class="product-card__header">
        <span class="product-card__label" [style.color]="aiColor">AI</span>
        <span class="product-card__subtitle">ISO 42001:2023</span>
      </div>
      @if (aiStats()) {
        <div class="product-card__stats product-card__stats--col">
          <div class="stat-row">
            <span class="stat-row__label">Control Groups</span>
            <span class="stat-row__value">{{ aiStats()!.groups }}</span>
          </div>
          <div class="stat-row">
            <span class="stat-row__label">Policies</span>
            <span class="stat-row__value">{{ aiStats()!.policies }}</span>
          </div>
          <div class="stat-row">
            <span class="stat-row__label">Implementations</span>
            <span class="stat-row__value">{{ aiStats()!.imps }}</span>
          </div>
        </div>
        <div class="product-card__dots">
          <div class="dot-row">
            <span class="dot" [style.background]="aiColor"></span>
            <span class="dot-row__label">ISO 42001:2023</span>
          </div>
          <div class="dot-row">
            <span class="dot" [style.background]="aiColor"></span>
            <span class="dot-row__label">AI Management System</span>
          </div>
        </div>
      } @else {
        <div class="product-card__loading">—</div>
      }
    </div>

  </div>

  <!-- Connector bar -->
  <div class="info-bar info-bar--connector" (click)="router.navigate(['/connectors'])">
    <mat-icon class="info-bar__icon">electrical_services</mat-icon>
    <span class="info-bar__label">Connectors</span>
    @if (connectorStats()) {
      <span class="info-bar__badge">{{ connectorStats()!.active }} active</span>
      <span class="info-bar__sep">·</span>
      <span class="info-bar__text">{{ connectorStats()!.evidence_items | number }} evidence items collected</span>
    } @else {
      <span class="info-bar__text">—</span>
    }
    <mat-icon class="info-bar__chevron">chevron_right</mat-icon>
  </div>

  <!-- Intelligence bar -->
  <div class="intel-bar">
    <div class="intel-item" (click)="router.navigate(['/cve-explorer'])">
      <mat-icon class="intel-item__icon">bug_report</mat-icon>
      <div class="intel-item__content">
        <div class="intel-item__value">
          @if (nvdStats()) { {{ nvdStats()!.cve_total | number }} } @else { — }
        </div>
        <div class="intel-item__label">CVEs Indexed</div>
      </div>
    </div>
    <div class="intel-sep"></div>
    <div class="intel-item" (click)="router.navigate(['/threat-feeds'])">
      <mat-icon class="intel-item__icon">warning</mat-icon>
      <div class="intel-item__content">
        <div class="intel-item__value">
          @if (kevStats()) { {{ kevStats()!.total_entries | number }} } @else { — }
        </div>
        <div class="intel-item__label">CISA KEV Entries</div>
      </div>
    </div>
    <div class="intel-sep"></div>
    <div class="intel-item" (click)="router.navigate(['/mitre-attack'])">
      <mat-icon class="intel-item__icon">track_changes</mat-icon>
      <div class="intel-item__content">
        <div class="intel-item__value">
          @if (attackStats()) { {{ attackStats()!.total_techniques + attackStats()!.total_subtechniques | number }} } @else { — }
        </div>
        <div class="intel-item__label">ATT&CK Techniques</div>
      </div>
    </div>
    <div class="intel-sep"></div>
    <div class="intel-item intel-item--feeds">
      <mat-icon class="intel-item__icon">rss_feed</mat-icon>
      <div class="intel-item__content">
        <div class="intel-item__value">
          @if (feedStatus()) {
            {{ feedStatus()!.feeds.filter(f => f.last_status === 'success').length }}
            /
            {{ feedStatus()!.feeds.length }}
          } @else { — }
        </div>
        <div class="intel-item__label">Feeds OK</div>
      </div>
    </div>
  </div>

  <!-- Active project rows -->
  @for (family of projectFamilies; track family) {
    @if (project.getActiveProject(family); as proj) {
      <div class="project-row" (click)="router.navigate(['/projects', proj.id])">
        <mat-icon class="project-row__icon">folder_open</mat-icon>
        <div class="project-row__info">
          <span class="project-row__family">{{ family }}</span>
          <span class="project-row__name">{{ proj.name }}</span>
        </div>
        <span class="project-row__status" [class]="'status-' + proj.status.toLowerCase()">{{ proj.status }}</span>
        <mat-progress-bar mode="determinate" [value]="50" color="primary" class="project-row__bar" />
        <mat-icon class="project-row__chevron">chevron_right</mat-icon>
      </div>
    }
  }

  <!-- Platform Tools -->
  <div class="tools-section">
    <div class="tools-section__heading">Platform Tools</div>
    <div class="tools-section__chips">
      @for (tool of platformTools; track tool.path) {
        <div class="tool-chip" (click)="router.navigate([tool.path])">
          <mat-icon class="tool-chip__icon">{{ tool.icon }}</mat-icon>
          <span>{{ tool.label }}</span>
        </div>
      }
    </div>
  </div>

  <!-- Compliance Assessments -->
  <div class="tools-section">
    <div class="tools-section__heading">Compliance Assessments</div>
    <div class="tools-section__chips">
      @for (tool of complianceTools; track tool.path) {
        <div class="tool-chip" (click)="router.navigate([tool.path])">
          <mat-icon class="tool-chip__icon">{{ tool.icon }}</mat-icon>
          <span>{{ tool.label }}</span>
        </div>
      }
    </div>
  </div>

</div>
  `,
  styles: [`
    .home {
      display: flex;
      flex-direction: column;
      gap: 12px;
      height: 100%;
      overflow-y: auto;
      box-sizing: border-box;
    }

    /* Header */
    .home__header {
      display: flex;
      align-items: center;
      justify-content: space-between;
    }
    .home__header-left {
      display: flex;
      flex-direction: column;
      gap: 2px;
    }
    .home__title {
      margin: 0;
      font-size: 1.25rem;
      font-weight: 600;
      color: var(--mat-sys-on-surface);
    }
    .home__date {
      font-size: 0.75rem;
      color: var(--mat-sys-on-surface-variant);
    }
    .home__user {
      font-size: 0.75rem;
      color: var(--mat-sys-on-surface-variant);
    }

    /* Search */
    .home__search { width: 100%; }
    .home__search-field { width: 100%; }

    /* Product cards */
    .home__products {
      display: flex;
      gap: 12px;
      align-items: stretch;
    }
    .product-card {
      flex: 1;
      background: var(--mat-sys-surface-container);
      border-radius: 8px;
      border-top: 3px solid transparent;
      padding: 12px;
      cursor: pointer;
      transition: background 0.15s;
      display: flex;
      flex-direction: column;
      gap: 8px;
    }
    .product-card--isms { flex: 0 0 48%; }
    .product-card:hover { background: var(--mat-sys-surface-container-high); }

    .product-card__header {
      display: flex;
      flex-direction: column;
      gap: 2px;
    }
    .product-card__label {
      font-size: 0.7rem;
      font-weight: 700;
      letter-spacing: 0.08em;
      text-transform: uppercase;
    }
    .product-card__subtitle {
      font-size: 0.7rem;
      color: var(--mat-sys-on-surface-variant);
    }
    .product-card__loading {
      color: var(--mat-sys-on-surface-variant);
      font-size: 1.2rem;
    }

    /* Stats grid */
    .product-card__stats {
      display: flex;
      gap: 12px;
    }
    .product-card__stats--col {
      flex-direction: column;
      gap: 4px;
    }
    .stat {
      display: flex;
      flex-direction: column;
      align-items: center;
    }
    .stat__value {
      font-size: 1.4rem;
      font-weight: 600;
      color: var(--mat-sys-on-surface);
    }
    .stat__label {
      font-size: 0.65rem;
      color: var(--mat-sys-on-surface-variant);
      text-align: center;
    }
    .stat--warn .stat__value { color: #e65100; }
    .stat--ok .stat__value { color: #00c752; }

    .stat-row {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .stat-row__label {
      font-size: 0.7rem;
      color: var(--mat-sys-on-surface-variant);
    }
    .stat-row__value {
      font-size: 0.85rem;
      font-weight: 600;
      color: var(--mat-sys-on-surface);
    }

    /* Progress bars */
    .product-card__bars {
      display: flex;
      flex-direction: column;
      gap: 6px;
      margin-top: 4px;
    }
    .bar-row {
      display: flex;
      align-items: center;
      gap: 6px;
    }
    .bar-row__label {
      font-size: 0.65rem;
      color: var(--mat-sys-on-surface-variant);
      width: 68px;
      flex-shrink: 0;
    }
    .bar-row mat-progress-bar { flex: 1; }
    .bar-row__pct {
      font-size: 0.65rem;
      color: var(--mat-sys-on-surface-variant);
      width: 32px;
      text-align: right;
      flex-shrink: 0;
    }

    /* Status dots */
    .product-card__dots {
      display: flex;
      flex-direction: column;
      gap: 4px;
      margin-top: 4px;
    }
    .dot-row {
      display: flex;
      align-items: center;
      gap: 6px;
    }
    .dot {
      width: 8px;
      height: 8px;
      border-radius: 50%;
      flex-shrink: 0;
    }
    .dot--green  { background: #4caf50; }
    .dot--blue   { background: #4472C4; }
    .dot--teal   { background: #00897B; }
    .dot--orange { background: #ff6b35; }
    .dot-row__label {
      font-size: 0.7rem;
      color: var(--mat-sys-on-surface-variant);
    }

    /* Info bar (connectors) */
    .info-bar {
      display: flex;
      align-items: center;
      gap: 8px;
      background: var(--mat-sys-surface-container);
      border-radius: 8px;
      padding: 10px 14px;
      cursor: pointer;
      transition: background 0.15s;
    }
    .info-bar:hover { background: var(--mat-sys-surface-container-high); }
    .info-bar--connector { border-left: 3px solid #4472C4; }
    .info-bar__icon { color: var(--mat-sys-on-surface-variant); font-size: 18px; }
    .info-bar__label { font-size: 0.8rem; font-weight: 600; color: var(--mat-sys-on-surface); }
    .info-bar__badge {
      font-size: 0.7rem;
      background: #4472C4;
      color: #fff;
      border-radius: 10px;
      padding: 1px 8px;
    }
    .info-bar__sep { color: var(--mat-sys-on-surface-variant); }
    .info-bar__text { font-size: 0.8rem; color: var(--mat-sys-on-surface-variant); flex: 1; }
    .info-bar__chevron { color: var(--mat-sys-on-surface-variant); margin-left: auto; }

    /* Intelligence bar */
    .intel-bar {
      display: flex;
      align-items: stretch;
      background: var(--mat-sys-surface-container);
      border-radius: 8px;
      overflow: hidden;
    }
    .intel-item {
      display: flex;
      align-items: center;
      gap: 8px;
      padding: 10px 16px;
      cursor: pointer;
      flex: 1;
      transition: background 0.15s;
    }
    .intel-item:hover { background: var(--mat-sys-surface-container-high); }
    .intel-item--feeds { cursor: default; }
    .intel-item--feeds:hover { background: transparent; }
    .intel-item__icon { color: var(--mat-sys-primary); font-size: 20px; }
    .intel-item__value { font-size: 1rem; font-weight: 600; color: var(--mat-sys-on-surface); }
    .intel-item__label { font-size: 0.65rem; color: var(--mat-sys-on-surface-variant); }
    .intel-item__content { display: flex; flex-direction: column; }
    .intel-sep { width: 1px; background: var(--mat-sys-outline-variant); margin: 8px 0; flex-shrink: 0; }

    /* Project rows */
    .project-row {
      display: flex;
      align-items: center;
      gap: 10px;
      background: var(--mat-sys-surface-container);
      border-radius: 8px;
      padding: 10px 14px;
      cursor: pointer;
      transition: background 0.15s;
    }
    .project-row:hover { background: var(--mat-sys-surface-container-high); }
    .project-row__icon { color: var(--mat-sys-primary); font-size: 18px; }
    .project-row__info { display: flex; flex-direction: column; flex: 1; min-width: 0; }
    .project-row__family { font-size: 0.65rem; font-weight: 700; letter-spacing: 0.06em; text-transform: uppercase; color: var(--mat-sys-on-surface-variant); }
    .project-row__name { font-size: 0.85rem; font-weight: 500; color: var(--mat-sys-on-surface); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
    .project-row__status { font-size: 0.65rem; padding: 2px 8px; border-radius: 10px; background: var(--mat-sys-surface-container-high); color: var(--mat-sys-on-surface-variant); flex-shrink: 0; }
    .project-row__bar { width: 100px; flex-shrink: 0; }
    .project-row__chevron { color: var(--mat-sys-on-surface-variant); font-size: 18px; }

    /* Tools sections */
    .tools-section { display: flex; flex-direction: column; gap: 8px; }
    .tools-section__heading {
      font-size: 0.7rem;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.08em;
      color: var(--mat-sys-on-surface-variant);
    }
    .tools-section__chips {
      display: flex;
      flex-wrap: wrap;
      gap: 6px;
    }
    .tool-chip {
      display: flex;
      align-items: center;
      gap: 4px;
      padding: 4px 12px;
      border-radius: 16px;
      background: var(--mat-sys-surface-container);
      cursor: pointer;
      font-size: 0.78rem;
      color: var(--mat-sys-on-surface);
      transition: background 0.15s;
      border: 1px solid var(--mat-sys-outline-variant);
    }
    .tool-chip:hover { background: var(--mat-sys-surface-container-high); }
    .tool-chip__icon { font-size: 14px; width: 14px; height: 14px; }
  `],
})
export class HomeComponent {
  readonly router  = inject(Router)
  readonly auth    = inject(AuthService)
  readonly product = inject(ProductService)
  readonly project = inject(ProjectService)

  private dashApi  = inject(DashboardApiService)
  private feedsApi = inject(FeedsApiService)

  readonly platformTools   = PLATFORM_TOOLS
  readonly complianceTools = COMPLIANCE_TOOLS
  readonly projectFamilies = PRODUCT_FAMILIES

  searchQuery = ''

  readonly today = new Date().toLocaleDateString('en-GB', {
    weekday: 'long', day: 'numeric', month: 'long', year: 'numeric',
  })

  readonly ismsColor    = PRODUCT_COLORS['isms']
  readonly privacyColor = PRODUCT_COLORS['privacy']
  readonly cloudColor   = PRODUCT_COLORS['cloud']
  readonly aiColor      = PRODUCT_COLORS['ai']

  private summaryQuery = injectQuery(() => ({
    queryKey: ['home-summary'],
    queryFn: () => firstValueFrom(this.dashApi.getHomeSummary()),
    staleTime: 30_000,
  }))

  private kevQuery = injectQuery(() => ({
    queryKey: ['kev-stats'],
    queryFn: () => firstValueFrom(this.feedsApi.getKevStats()),
    staleTime: 60_000,
  }))

  private nvdQuery = injectQuery(() => ({
    queryKey: ['nvd-index-stats'],
    queryFn: () => firstValueFrom(this.feedsApi.getNvdIndexStats()),
    staleTime: 60_000,
  }))

  private attackQuery = injectQuery(() => ({
    queryKey: ['attack-stats'],
    queryFn: () => firstValueFrom(this.feedsApi.getAttackStats()),
    staleTime: 60_000,
  }))

  private feedStatusQuery = injectQuery(() => ({
    queryKey: ['feed-status'],
    queryFn: () => firstValueFrom(this.feedsApi.getStatus()),
    staleTime: 30_000,
  }))

  readonly ismsStats      = computed(() => this.summaryQuery.data()?.isms ?? null)
  readonly privacyStats   = computed(() => this.summaryQuery.data()?.privacy ?? null)
  readonly cloudStats     = computed(() => this.summaryQuery.data()?.cloud ?? null)
  readonly aiStats        = computed(() => this.summaryQuery.data()?.ai ?? null)
  readonly connectorStats = computed(() => this.summaryQuery.data()?.connectors ?? null)
  readonly kevStats       = computed(() => this.kevQuery.data() ?? null)
  readonly nvdStats       = computed(() => this.nvdQuery.data() ?? null)
  readonly attackStats    = computed(() => this.attackQuery.data() ?? null)
  readonly feedStatus     = computed(() => this.feedStatusQuery.data() ?? null)

  selectProduct(p: 'isms' | 'privacy' | 'cloud' | 'ai'): void {
    this.product.setProduct(p)
    this.router.navigate(['/overview'])
  }

  doSearch(): void {
    const q = this.searchQuery.trim()
    if (!q) return
    this.router.navigate(['/search'], { queryParams: { q } })
  }
}
