// isms-core-platform/frontend/src/pages/ThreatExposure.tsx
import { useTheme } from '@mui/material/styles'
import { useQuery } from '@tanstack/react-query'
import {
  Alert, Box, Chip, CircularProgress, Divider, Paper,
  Table, TableBody, TableCell, TableHead, TableRow, Tooltip, Typography,
} from '@mui/material'
import {
  CrisisAlertOutlined, CheckCircleOutlined, WarningAmberOutlined,
} from '@mui/icons-material'
import PageHeader from '../components/PageHeader'
import { client } from '../api/client'

// ── Types ────────────────────────────────────────────────────────────────────

interface ExposedControl {
  control_code: string
  control_name: string | null
  framework_status: string | null
  assessment_score: number | null
  gap: boolean
}

interface ExposureTechnique {
  mitre_tid: string
  ioc_count: number
  sources: string[]
  iso_controls: ExposedControl[]
  max_gap_score: number | null
}

interface ThreatExposureResponse {
  technique_count: number
  affected_controls: number
  gap_controls: number
  items: ExposureTechnique[]
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function scoreColor(score: number | null, gap: boolean): string {
  if (score === null) return '#9e9e9e'
  if (score >= 70)   return '#2e7d32'
  if (score >= 40)   return '#ed6c02'
  return '#d32f2f'
}

function statusLabel(status: string | null, score: number | null): string {
  if (score !== null) return `${score.toFixed(0)}%`
  if (!status) return 'Not assessed'
  return status.replace('_', ' ')
}

function ControlChip({ ctrl }: { ctrl: ExposedControl }) {
  const color = scoreColor(ctrl.assessment_score, ctrl.gap)
  const label = ctrl.assessment_score != null
    ? `${ctrl.control_code} · ${ctrl.assessment_score.toFixed(0)}%`
    : ctrl.control_code
  const tip = ctrl.control_name
    ? `${ctrl.control_name} — ${statusLabel(ctrl.framework_status, ctrl.assessment_score)}`
    : statusLabel(ctrl.framework_status, ctrl.assessment_score)

  return (
    <Tooltip title={tip} arrow>
      <Chip
        label={label}
        size="small"
        sx={{
          fontSize: '0.62rem',
          height: 18,
          bgcolor: color,
          color: '#fff',
          fontFamily: 'monospace',
          cursor: 'default',
        }}
      />
    </Tooltip>
  )
}

function SummaryBar({ data }: { data: ThreatExposureResponse }) {
  const { palette } = useTheme()
  const isLight = palette.mode === 'light'
  const items = [
    { label: 'Active techniques', value: data.technique_count, color: '#b71c1c' },
    { label: 'Affected controls', value: data.affected_controls, color: '#e65100' },
    { label: 'Gaps identified',   value: data.gap_controls,    color: '#d32f2f' },
  ]
  return (
    <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap' }}>
      {items.map(({ label, value, color }) => (
        <Paper key={label} variant="outlined" sx={{ p: 2, flex: 1, minWidth: 160, textAlign: 'center' }}>
          <Typography variant="h4" fontWeight={800} sx={{ color }}>{value}</Typography>
          <Typography variant="caption" color="text.secondary">{label}</Typography>
        </Paper>
      ))}
    </Box>
  )
}

// ── Page ─────────────────────────────────────────────────────────────────────

export default function ThreatExposure() {
  const { data, isLoading, isError } = useQuery<ThreatExposureResponse>({
    queryKey: ['threat-exposure'],
    queryFn: () => client.get<ThreatExposureResponse>('/threat-intel/exposure').then(r => r.data),
    staleTime: 5 * 60 * 1000,
  })

  return (
    <Box sx={{ p: 3, display: 'flex', flexDirection: 'column', gap: 2.5 }}>
      <PageHeader
        title="Threat Exposure"
        subtitle="Active MITRE techniques from TI feeds mapped to ISO 27001 controls — gaps highlighted"
      />

      {isLoading && (
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, py: 4 }}>
          <CircularProgress size={20} />
          <Typography variant="body2" color="text.secondary">Correlating TI feeds with crosswalk…</Typography>
        </Box>
      )}

      {isError && (
        <Alert severity="error">Failed to load exposure data — threat-intel profile may not be active.</Alert>
      )}

      {data && data.technique_count === 0 && (
        <Alert severity="info" icon={<CheckCircleOutlined />}>
          No MITRE technique correlations found — either no IOCs with technique IDs are in the feeds, or the threat-intel profile is not active.
        </Alert>
      )}

      {data && data.technique_count > 0 && (
        <>
          <SummaryBar data={data} />

          <Paper variant="outlined">
            <Box sx={{ px: 2, pt: 1.5, pb: 1, display: 'flex', alignItems: 'center', gap: 1 }}>
              <CrisisAlertOutlined sx={{ fontSize: 18, color: '#b71c1c' }} />
              <Typography variant="subtitle2" fontWeight={700} sx={{ fontSize: '0.85rem' }}>
                Technique → Control Mapping
              </Typography>
              <Box sx={{ flex: 1 }} />
              <Typography variant="caption" color="text.secondary">
                Controls coloured by assessment score · grey = not assessed
              </Typography>
            </Box>
            <Divider />
            <Table size="small">
              <TableHead>
                <TableRow>
                  <TableCell sx={{ fontWeight: 700, fontSize: '0.72rem', width: 110 }}>Technique</TableCell>
                  <TableCell sx={{ fontWeight: 700, fontSize: '0.72rem', width: 80 }}>IOC count</TableCell>
                  <TableCell sx={{ fontWeight: 700, fontSize: '0.72rem', width: 200 }}>Sources</TableCell>
                  <TableCell sx={{ fontWeight: 700, fontSize: '0.72rem' }}>ISO 27001 controls</TableCell>
                  <TableCell sx={{ fontWeight: 700, fontSize: '0.72rem', width: 80 }}>Gaps</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {data.items.map(item => {
                  const gapCount = item.iso_controls.filter(c => c.gap).length
                  return (
                    <TableRow key={item.mitre_tid} sx={gapCount > 0 ? { bgcolor: 'rgba(211,47,47,0.04)' } : {}}>
                      <TableCell>
                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
                          {gapCount > 0 && <WarningAmberOutlined sx={{ fontSize: 14, color: '#d32f2f' }} />}
                          <Typography variant="caption" sx={{ fontFamily: 'monospace', fontWeight: 600 }}>
                            {item.mitre_tid}
                          </Typography>
                        </Box>
                      </TableCell>
                      <TableCell>
                        <Typography variant="caption" fontWeight={600}>{item.ioc_count.toLocaleString()}</Typography>
                      </TableCell>
                      <TableCell>
                        <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5 }}>
                          {item.sources.slice(0, 4).map(s => (
                            <Chip key={s} label={s.replace('_misp', ' MISP')} size="small"
                              sx={{ fontSize: '0.6rem', height: 16 }} />
                          ))}
                        </Box>
                      </TableCell>
                      <TableCell>
                        <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5 }}>
                          {item.iso_controls.map(ctrl => (
                            <ControlChip key={ctrl.control_code} ctrl={ctrl} />
                          ))}
                        </Box>
                      </TableCell>
                      <TableCell>
                        {gapCount > 0
                          ? <Chip label={gapCount} size="small" sx={{ fontSize: '0.65rem', height: 18, bgcolor: '#d32f2f', color: '#fff', fontWeight: 700 }} />
                          : <CheckCircleOutlined sx={{ fontSize: 16, color: '#2e7d32' }} />
                        }
                      </TableCell>
                    </TableRow>
                  )
                })}
              </TableBody>
            </Table>
          </Paper>
        </>
      )}
    </Box>
  )
}

// isms-core-platform/frontend-angular/src/app/pages/threat-exposure/threat-exposure.component.ts
import { Component, inject, computed } from '@angular/core'
import { ThemeService } from '../../core/services/theme.service'
import { firstValueFrom } from 'rxjs'
import { injectQuery } from '@tanstack/angular-query-experimental'

import { MatIconModule } from '@angular/material/icon'
import { MatTooltipModule } from '@angular/material/tooltip'
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner'

import { ThreatExposureApiService, ExposedControl, ExposureTechnique } from '../../api/threat-exposure-api.service'
import { PageHeaderComponent } from '../../shared/components/page-header.component'

function scoreColor(score: number | null, isDark: boolean): string {
  if (score === null) return isDark ? 'rgba(255,255,255,0.15)' : 'rgba(0,0,0,0.08)'
  if (score >= 70) return '#00c752'
  if (score >= 40) return '#ff9800'
  return '#f44336'
}
function scoreTextColor(score: number | null, isDark: boolean): string {
  if (score === null) return isDark ? '#d9d9d9' : '#424242'
  return '#fff'
}
function statusLabel(status: string | null, score: number | null): string {
  if (score !== null) return `${score.toFixed(0)}%`
  if (!status) return 'Not assessed'
  return status.replace('_', ' ')
}

@Component({
  selector: 'app-threat-exposure',
  standalone: true,
  imports: [
    PageHeaderComponent,
    MatIconModule, MatTooltipModule, MatProgressSpinnerModule,
  ],
  template: `
<div class="te-page">
  <app-page-header
    title="Threat Exposure"
    subtitle="Active MITRE techniques from TI feeds mapped to ISO 27001 controls — gaps highlighted"
  />

  @if (exposureQuery.isLoading()) {
    <div class="loading-row">
      <mat-spinner diameter="20" />
      <span class="dim">Correlating TI feeds with crosswalk…</span>
    </div>
  }

  @if (exposureQuery.isError()) {
    <div class="isms-alert isms-alert--error">
      <mat-icon>error</mat-icon>
      Failed to load exposure data — threat-intel profile may not be active.
    </div>
  }

  @if (exposureQuery.data()?.technique_count === 0) {
    <div class="isms-alert isms-alert--info">
      <mat-icon>check_circle</mat-icon>
      No MITRE technique correlations found — either no IOCs with technique IDs are in the feeds,
      or the threat-intel profile is not active.
    </div>
  }

  @if (exposureQuery.data(); as data) {
    @if (data.technique_count > 0) {

      <div class="summary-cards">
        <div class="summary-card">
          <span class="summary-val summary-val--red">{{ data.technique_count }}</span>
          <span class="summary-lbl">Active techniques</span>
        </div>
        <div class="summary-card">
          <span class="summary-val summary-val--amber">{{ data.affected_controls }}</span>
          <span class="summary-lbl">Affected controls</span>
        </div>
        <div class="summary-card">
          <span class="summary-val summary-val--amber">{{ data.gap_controls }}</span>
          <span class="summary-lbl">Gaps identified</span>
        </div>
      </div>

      <div class="mitre-table-box">
        <div class="table-header">
          <div class="table-header__left">
            <mat-icon class="icon-md te-alert-icon">crisis_alert</mat-icon>
            <span class="table-header__title">Technique → Control Mapping</span>
          </div>
          <span class="dim">Controls coloured by assessment score · grey = not assessed</span>
        </div>
        <table class="mitre-table">
          <thead><tr>
            <th class="col-tid">Technique</th>
            <th class="col-ioc">IOC Count</th>
            <th class="col-src">Sources</th>
            <th>ISO 27001 Controls</th>
            <th class="col-gaps">Gaps</th>
          </tr></thead>
          <tbody>
            @for (item of data.items; track item.mitre_tid) {
              <tr [class.row-gap]="gapCount(item) > 0">
                <td>
                  <div class="tid-cell">
                    @if (gapCount(item) > 0) { <mat-icon class="warn-icon">warning_amber</mat-icon> }
                    <span class="mono bold">{{ item.mitre_tid }}</span>
                  </div>
                </td>
                <td><span class="bold">{{ item.ioc_count.toLocaleString() }}</span></td>
                <td>
                  <div class="chip-wrap">
                    @for (s of item.sources.slice(0, 4); track s) {
                      <span class="src-chip">{{ s.replace('_misp', ' MISP') }}</span>
                    }
                  </div>
                </td>
                <td>
                  <div class="chip-wrap">
                    @for (ctrl of item.iso_controls; track ctrl.control_code) {
                      <span class="ctrl-chip"
                        [style.background]="scoreColor(ctrl.assessment_score)"
                        [style.color]="scoreTextColor(ctrl.assessment_score)"
                        [matTooltip]="ctrlTooltip(ctrl)">
                        {{ ctrlLabel(ctrl) }}
                      </span>
                    }
                  </div>
                </td>
                <td>
                  @if (gapCount(item) > 0) {
                    <span class="gap-chip">{{ gapCount(item) }}</span>
                  } @else {
                    <mat-icon class="te-ok-icon">check_circle</mat-icon>
                  }
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    }
  }
</div>
  `,
  styles: [`
    .te-page { display: flex; flex-direction: column; gap: 16px; }

    .loading-row { display: flex; align-items: center; gap: 12px; padding: 32px 0; }

    .summary-cards {
      display: grid; grid-template-columns: repeat(auto-fill, minmax(160px, 1fr)); gap: 12px;
    }
    .summary-card {
      border: 1px solid var(--mat-sys-outline-variant); border-radius: 8px;
      padding: 14px; text-align: center;
      display: flex; flex-direction: column; align-items: center; gap: 4px;
      background: var(--mat-sys-surface-container);
    }
    .summary-val        { font-size: 2rem; font-weight: 800; line-height: 1; }
    .summary-val--red   { color: #f44336; }
    .summary-val--amber { color: #ff9800; }
    .summary-lbl { font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); }

    .table-header {
      padding: 8px 14px; border-bottom: 1px solid var(--mat-sys-outline-variant);
      display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 4px;
    }
    .table-header__left  { display: flex; align-items: center; gap: 6px; }
    .table-header__title { font-size: 0.85rem; font-weight: 700; }
    .te-alert-icon { color: #f44336; }
    .te-ok-icon    { font-size: 16px; height: 16px; width: 16px; color: #00c752; }

    .row-gap { background: rgba(211,47,47,0.04); }
    .col-tid  { width: 110px; }
    .col-ioc  { width: 80px; }
    .col-src  { width: 200px; }
    .col-gaps { width: 70px; }

    .tid-cell  { display: flex; align-items: center; gap: 4px; }
    .warn-icon { font-size: 14px; width: 14px; height: 14px; color: #f44336; }

    .chip-wrap { display: flex; flex-wrap: wrap; gap: 3px; }
    .src-chip {
      display: inline-block; font-size: 0.6rem; padding: 1px 5px; border-radius: 8px;
      background: var(--mat-sys-surface-container-high); color: var(--mat-sys-on-surface-variant);
    }
    .ctrl-chip {
      display: inline-block; font-size: 0.62rem; padding: 1px 5px;
      border-radius: 8px; font-family: monospace; cursor: default;
    }
    .gap-chip {
      display: inline-block; font-size: 0.65rem; font-weight: 700;
      padding: 2px 7px; border-radius: 8px; background: #ff9800; color: #fff;
    }

    .mono { font-family: monospace; }
    .bold { font-weight: 600; }
    .dim  { font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); }
  `],
})
export class ThreatExposureComponent {
  private exposureApi = inject(ThreatExposureApiService)
  private readonly theme = inject(ThemeService)

  readonly scoreColor     = (score: number | null) => scoreColor(score, this.theme.isDark())
  readonly scoreTextColor = (score: number | null) => scoreTextColor(score, this.theme.isDark())

  readonly exposureQuery = injectQuery(() => ({
    queryKey: ['threat-exposure'],
    queryFn:  () => firstValueFrom(this.exposureApi.get()),
    staleTime: 5 * 60_000,
  }))

  gapCount(item: ExposureTechnique): number {
    return item.iso_controls.filter(c => c.gap).length
  }
  ctrlLabel(ctrl: ExposedControl): string {
    return ctrl.assessment_score != null
      ? `${ctrl.control_code} · ${ctrl.assessment_score.toFixed(0)}%`
      : ctrl.control_code
  }
  ctrlTooltip(ctrl: ExposedControl): string {
    const score = statusLabel(ctrl.framework_status, ctrl.assessment_score)
    return ctrl.control_name ? `${ctrl.control_name} — ${score}` : score
  }
}
