// isms-core-platform/frontend/src/app/shared/components/health-alert-banner.component.ts
import { Component, signal, computed, inject } from '@angular/core'
import { injectQuery } from '@tanstack/angular-query-experimental'
import { HttpClient } from '@angular/common/http'
import { firstValueFrom } from 'rxjs'
import { MatIconModule } from '@angular/material/icon'
import { MatButtonModule } from '@angular/material/button'

interface HealthAlert {
  type: string
  severity: string
  message: string
  detected_at: string
  entity: string | null
}

const TYPE_LABELS: Record<string, string> = {
  feed_failure:      'Feed',
  connector_failure: 'Connector',
  opensearch_down:   'OpenSearch',
  db_error:          'Database',
}

@Component({
  selector: 'app-health-alert-banner',
  standalone: true,
  imports: [MatIconModule, MatButtonModule],
  template: `
    @if (!dismissed() && (query.data()?.length ?? 0) > 0) {
      <div class="health-banner">
        <mat-icon class="health-banner__icon">error_outline</mat-icon>
        <div class="health-banner__body">
          <div class="health-banner__title">
            {{ errorCount() }} platform health issue{{ errorCount() !== 1 ? 's' : '' }} detected in the last 24h
            @for (alert of query.data()!; track alert.type) {
              <span class="health-badge">{{ typeLabel(alert.type) }}</span>
            }
          </div>
          @if (expanded()) {
            <div class="health-banner__detail">
              @for (alert of query.data()!; track alert.type + alert.entity) {
                <div class="health-banner__row">
                  <span class="health-banner__time">{{ fmtTime(alert.detected_at) }}</span>
                  <span class="health-badge">{{ typeLabel(alert.type) }}</span>
                  <span>{{ alert.message }}</span>
                </div>
              }
            </div>
          }
        </div>
        <div class="health-banner__actions">
          <button mat-icon-button (click)="expanded.set(!expanded())">
            <mat-icon>{{ expanded() ? 'expand_less' : 'expand_more' }}</mat-icon>
          </button>
          <button mat-icon-button (click)="dismiss()">
            <mat-icon>close</mat-icon>
          </button>
        </div>
      </div>
    }
  `,
  styles: [`
    .health-banner {
      display: flex;
      align-items: flex-start;
      gap: 8px;
      padding: 8px 16px;
      background: var(--mat-sys-error-container, #4e0002);
      color: var(--mat-sys-on-error-container, #ffb4ab);
      flex-shrink: 0;
    }
    .health-banner__icon { margin-top: 2px; font-size: 18px; height: 18px; width: 18px; }
    .health-banner__body { flex: 1; font-size: 0.875rem; }
    .health-banner__title { font-weight: 600; line-height: 1.4; display: flex; align-items: center; flex-wrap: wrap; gap: 4px; }
    .health-banner__actions { display: flex; align-items: center; gap: 2px; }
    .health-banner__detail { margin-top: 6px; display: flex; flex-direction: column; gap: 4px; }
    .health-banner__row { display: flex; align-items: flex-start; gap: 8px; font-size: 0.8rem; }
    .health-banner__time { opacity: 0.7; white-space: nowrap; }
    .health-badge {
      display: inline-flex; align-items: center; padding: 0 5px; height: 16px;
      border-radius: 8px; font-size: 0.65rem; background: rgba(255,255,255,0.2); color: inherit;
    }
  `],
})
export class HealthAlertBannerComponent {
  private http = inject(HttpClient)
  dismissed = signal(
    sessionStorage.getItem('health_banner_dismissed_at') === new Date().toDateString()
  )
  expanded = signal(false)

  query = injectQuery(() => ({
    queryKey: ['health', 'alerts'],
    queryFn: () => firstValueFrom(this.http.get<HealthAlert[]>('/api/v1/health/alerts')),
    staleTime: 5 * 60_000,
    refetchInterval: 5 * 60_000,
    enabled: !this.dismissed(),
  }))

  errorCount = computed(() => (this.query.data() ?? []).filter(a => a.severity === 'error').length)

  typeLabel(type: string) { return TYPE_LABELS[type] ?? type }

  fmtTime(iso: string) {
    try { return new Date(iso).toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' }) }
    catch { return '' }
  }

  dismiss() {
    sessionStorage.setItem('health_banner_dismissed_at', new Date().toDateString())
    this.dismissed.set(true)
  }
}

// isms-core-platform/frontend/src/components/HealthAlertBanner.tsx
import { useState } from 'react'
import { Alert, Box, Chip, Collapse, IconButton, Typography } from '@mui/material'
import {
  CloseOutlined, ExpandLessOutlined, ExpandMoreOutlined,
  ErrorOutlineOutlined,
} from '@mui/icons-material'
import { useQuery } from '@tanstack/react-query'
import { client } from '../api/client'

interface HealthAlert {
  type: string
  severity: string
  message: string
  detected_at: string
  entity: string | null
}

const TYPE_LABELS: Record<string, string> = {
  feed_failure:      'Feed',
  connector_failure: 'Connector',
  opensearch_down:   'OpenSearch',
  db_error:          'Database',
}

function fmtTime(iso: string) {
  try {
    return new Date(iso).toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' })
  } catch {
    return ''
  }
}

export default function HealthAlertBanner() {
  const [dismissed, setDismissed] = useState(
    () => sessionStorage.getItem('health_banner_dismissed_at') === new Date().toDateString()
  )
  const [expanded, setExpanded] = useState(false)

  const { data: alerts } = useQuery<HealthAlert[]>({
    queryKey: ['health', 'alerts'],
    queryFn: () => client.get<HealthAlert[]>('/health/alerts').then(r => r.data),
    staleTime: 5 * 60_000,   // re-check every 5 minutes
    refetchInterval: 5 * 60_000,
  })

  if (dismissed || !alerts || alerts.length === 0) return null

  const errorCount = alerts.filter(a => a.severity === 'error').length

  return (
    <Alert
      severity="error"
      icon={<ErrorOutlineOutlined fontSize="small" />}
      sx={{ borderRadius: 0, py: 0.5, flexShrink: 0, alignItems: 'flex-start' }}
      action={
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.3, mt: 0.2 }}>
          <IconButton size="small" color="inherit" onClick={() => setExpanded(e => !e)}>
            {expanded ? <ExpandLessOutlined fontSize="small" /> : <ExpandMoreOutlined fontSize="small" />}
          </IconButton>
          <IconButton
            size="small"
            color="inherit"
            onClick={() => {
              sessionStorage.setItem('health_banner_dismissed_at', new Date().toDateString())
              setDismissed(true)
            }}
          >
            <CloseOutlined fontSize="small" />
          </IconButton>
        </Box>
      }
    >
      <Box>
        <Typography variant="body2" fontWeight={600} sx={{ lineHeight: 1.4 }}>
          {errorCount} platform health issue{errorCount !== 1 ? 's' : ''} detected in the last 24h
          {' '}
          {alerts.map(a => (
            <Chip
              key={`${a.type}-${a.entity}`}
              label={TYPE_LABELS[a.type] ?? a.type}
              size="small"
              sx={{ fontSize: '0.65rem', height: 16, ml: 0.4, bgcolor: 'rgba(255,255,255,0.15)', color: 'inherit' }}
            />
          ))}
        </Typography>

        <Collapse in={expanded}>
          <Box sx={{ mt: 0.8 }}>
            {alerts.map((alert, i) => (
              <Box key={i} sx={{ display: 'flex', gap: 1, mb: 0.5, alignItems: 'flex-start' }}>
                <Typography variant="caption" sx={{ color: 'inherit', opacity: 0.7, whiteSpace: 'nowrap', mt: 0.1 }}>
                  {fmtTime(alert.detected_at)}
                </Typography>
                <Chip
                  label={TYPE_LABELS[alert.type] ?? alert.type}
                  size="small"
                  sx={{ fontSize: '0.65rem', height: 16, flexShrink: 0, bgcolor: 'rgba(255,255,255,0.2)', color: 'inherit' }}
                />
                <Typography variant="caption" sx={{ color: 'inherit', lineHeight: 1.5 }}>
                  {alert.message}
                </Typography>
              </Box>
            ))}
          </Box>
        </Collapse>
      </Box>
    </Alert>
  )
}
