// isms-core-platform/frontend/src/pages/Projects.tsx
import { useState } from 'react'
import {
  Alert,
  Box,
  Button,
  Card,
  CardActionArea,
  CardContent,
  Chip,
  Collapse,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  FormControl,
  Grid,
  IconButton,
  InputLabel,
  LinearProgress,
  MenuItem,
  Select,
  Skeleton,
  TextField,
  ToggleButton,
  ToggleButtonGroup,
  Tooltip,
  Typography,
} from '@mui/material'
import {
  AddOutlined,
  ArrowForwardOutlined,
  DeleteOutlined,
  ExpandMoreOutlined,
  FolderOpenOutlined,
  RestoreFromTrashOutlined,
  ShieldOutlined,
  LockPersonOutlined,
  CloudOutlined,
} from '@mui/icons-material'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useNavigate } from 'react-router-dom'
import dayjs from 'dayjs'
import { projectsApi, type ProjectCreate, type ProjectRead, type DocVars } from '../api/projectsApi'
import PageHeader from '../components/PageHeader'
import { useProject } from '../store/ProjectContext'

const FAMILY_COLOR: Record<string, string> = {
  ISMS:    '#4472C4',
  PRIVACY: '#70309f',
  CLOUD:   '#0099cc',
}

const FAMILY_ICON: Record<string, React.ReactNode> = {
  ISMS:    <ShieldOutlined sx={{ fontSize: 15 }} />,
  PRIVACY: <LockPersonOutlined sx={{ fontSize: 15 }} />,
  CLOUD:   <CloudOutlined sx={{ fontSize: 15 }} />,
}

const STATUS_COLOR: Record<string, string> = {
  active:   '#4CAF50',
  inactive: '#FF9800',
  draft:    '#64B5F6',
  archived: '#9E9E9E',
}

const TOTAL_CG: Record<string, number> = { ISMS: 53, PRIVACY: 21, CLOUD: 12 }

// ── Create dialog ─────────────────────────────────────────────────────────────
const EMPTY_DOC_VARS: DocVars = { ciso_name: '', ceo_name: '', dpo_name: '', legal_entity: '', effective_date: '', review_date: '', classification: 'Internal' }

function CreateProjectDialog({ open, onClose }: { open: boolean; onClose: () => void }) {
  const qc = useQueryClient()
  const [form, setForm] = useState<ProjectCreate>({ name: '', product_family: 'ISMS', project_subtype: 'fw', description: '' })
  const [docVars, setDocVars] = useState<DocVars>(EMPTY_DOC_VARS)
  const [showDocVars, setShowDocVars] = useState(true)
  const [error, setError] = useState('')

  const mutation = useMutation({
    mutationFn: (body: ProjectCreate) => projectsApi.create(body),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['projects'] })
      setForm({ name: '', product_family: 'ISMS', project_subtype: 'fw', description: '' })
      setDocVars(EMPTY_DOC_VARS)
      setShowDocVars(false)
      setError('')
      onClose()
    },
    onError: () => setError('Failed to create project — try again.'),
  })

  function handleSubmit() {
    if (!form.name.trim()) { setError('Project name is required.'); return }
    if (!docVars.ciso_name?.trim()) { setError('CISO name is required.'); return }
    if (!docVars.effective_date?.trim()) { setError('Effective date is required.'); return }
    const dv: DocVars = Object.fromEntries(Object.entries(docVars).filter(([, v]) => v)) as DocVars
    mutation.mutate({ ...form, doc_vars: Object.keys(dv).length ? dv : undefined })
  }

  const setDv = (k: keyof DocVars, v: string) => setDocVars(f => ({ ...f, [k]: v }))

  return (
    <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth>
      <DialogTitle sx={{ pb: 0.5 }}>
        New Project
        <Typography variant="caption" color="text.secondary" display="block">
          Create a workspace for a specific product and organisation
        </Typography>
      </DialogTitle>
      <DialogContent sx={{ pt: '20px !important' }}>
        {error && <Alert severity="error" sx={{ mb: 2, py: 0.5 }}>{error}</Alert>}
        <TextField
          label="Project name"
          fullWidth size="small" sx={{ mb: 2 }}
          value={form.name}
          onChange={e => setForm(f => ({ ...f, name: e.target.value }))}
          placeholder="e.g. Acme Corp ISMS 2026"
        />
        <FormControl fullWidth size="small" sx={{ mb: form.product_family === 'ISMS' ? 1.5 : 2 }}>
          <InputLabel>Product</InputLabel>
          <Select
            label="Product"
            value={form.product_family}
            onChange={e => setForm(f => ({ ...f, product_family: e.target.value, project_subtype: e.target.value === 'ISMS' ? 'fw' : undefined }))}
          >
            <MenuItem value="ISMS">ISMS — ISO 27001:2022</MenuItem>
            <MenuItem value="PRIVACY">Privacy — ISO 27701:2025</MenuItem>
            <MenuItem value="CLOUD">Cloud — ISO 27018:2025</MenuItem>
          </Select>
        </FormControl>
        {form.product_family === 'ISMS' && (
          <Box sx={{ mb: 2 }}>
            <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 0.75, fontSize: '0.72rem' }}>
              ISMS variant
            </Typography>
            <ToggleButtonGroup
              size="small" exclusive
              value={form.project_subtype ?? 'fw'}
              onChange={(_, v) => { if (v) setForm(f => ({ ...f, project_subtype: v })) }}
            >
              <ToggleButton value="fw" sx={{ px: 2, fontSize: '0.72rem' }}>Framework (FW)</ToggleButton>
              <ToggleButton value="op" sx={{ px: 2, fontSize: '0.72rem' }}>Operational (OP)</ToggleButton>
            </ToggleButtonGroup>
            <Typography variant="caption" color="text.disabled" sx={{ display: 'block', mt: 0.5, fontSize: '0.67rem' }}>
              FW = ISO 27001 policies &amp; IMPs · OP = adds SCR checklists
            </Typography>
          </Box>
        )}
        <TextField
          label="Description (optional)"
          fullWidth size="small" multiline rows={2} sx={{ mb: 2 }}
          value={form.description}
          onChange={e => setForm(f => ({ ...f, description: e.target.value }))}
        />

        {/* Document variables (collapsible) */}
        <Box
          onClick={() => setShowDocVars(v => !v)}
          sx={{ display: 'flex', alignItems: 'center', gap: 1, cursor: 'pointer', mb: showDocVars ? 1.5 : 0, '&:hover': { opacity: 0.8 } }}
        >
          <ExpandMoreOutlined sx={{ fontSize: 16, color: 'text.secondary', transition: 'transform 0.2s', transform: showDocVars ? 'rotate(0)' : 'rotate(-90deg)' }} />
          <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '0.75rem', fontWeight: 500 }}>
            Document Variables
          </Typography>
          <Typography variant="caption" sx={{ color: '#FF9800', fontSize: '0.68rem', fontWeight: 500 }}>
            CISO name + date required
          </Typography>
          <Typography variant="caption" color="text.disabled" sx={{ fontSize: '0.68rem' }}>
            — pre-filled into all policy &amp; IMP headers when added to this project
          </Typography>
        </Box>
        <Collapse in={showDocVars}>
          <Box sx={{ pl: 2, borderLeft: '2px solid', borderColor: 'divider', mb: 1 }}>
            <Typography variant="caption" color="text.disabled" sx={{ display: 'block', mb: 1.5, fontSize: '0.68rem' }}>
              These values replace <code>[CISO name]</code>, <code>[DPO name]</code>, <code>[Date to be set]</code> etc. in library documents when they are added to this project.
            </Typography>
            <Box sx={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 1.5, mb: 1.5 }}>
              <TextField label="CISO name *" size="small" fullWidth value={docVars.ciso_name ?? ''}
                onChange={e => setDv('ciso_name', e.target.value)} placeholder="e.g. Jane Smith" />
              <TextField label="CEO name" size="small" fullWidth value={docVars.ceo_name ?? ''}
                onChange={e => setDv('ceo_name', e.target.value)} placeholder="e.g. John Smith" />
              <TextField label="DPO name" size="small" fullWidth value={docVars.dpo_name ?? ''}
                onChange={e => setDv('dpo_name', e.target.value)} placeholder="e.g. John Doe" />
              <TextField label="Legal entity name" size="small" fullWidth value={docVars.legal_entity ?? ''}
                onChange={e => setDv('legal_entity', e.target.value)} placeholder="e.g. Acme Corporation Ltd." />
              <TextField label="Effective date *" size="small" fullWidth value={docVars.effective_date ?? ''}
                onChange={e => setDv('effective_date', e.target.value)}
                placeholder="DD.MM.YYYY or YYYY-MM-DD"
                helperText="e.g. 01.01.2026" />
              <TextField label="Next review date" size="small" fullWidth value={docVars.review_date ?? ''}
                onChange={e => setDv('review_date', e.target.value)}
                placeholder="DD.MM.YYYY or YYYY-MM-DD"
                helperText="e.g. 01.01.2027" />
            </Box>
            <TextField label="Classification" size="small" sx={{ minWidth: 180 }} value={docVars.classification ?? ''}
              onChange={e => setDv('classification', e.target.value)} placeholder="Internal" />
          </Box>
        </Collapse>
      </DialogContent>
      <DialogActions sx={{ px: 3, pb: 2 }}>
        <Button onClick={onClose} disabled={mutation.isPending}>Cancel</Button>
        <Button variant="contained" onClick={handleSubmit} disabled={mutation.isPending}>
          Create
        </Button>
      </DialogActions>
    </Dialog>
  )
}

// ── Archive dialog (soft-delete) ──────────────────────────────────────────────
function ArchiveProjectDialog({
  projectId, projectName, open, onClose,
}: { projectId: string; projectName: string; open: boolean; onClose: () => void }) {
  const qc = useQueryClient()
  const mutation = useMutation({
    mutationFn: () => projectsApi.update(projectId, { status: 'archived' }),
    onSuccess: () => { qc.invalidateQueries({ queryKey: ['projects'] }); onClose() },
  })
  return (
    <Dialog open={open} onClose={onClose} maxWidth="xs" fullWidth>
      <DialogTitle>Archive project?</DialogTitle>
      <DialogContent>
        <Typography variant="body2" gutterBottom>
          <strong>{projectName}</strong> will be moved to the Archived filter.
          All policies, implementations and checklists are preserved.
        </Typography>
        <Typography variant="body2" color="text.secondary">
          You can restore it at any time by setting its status back to active.
        </Typography>
      </DialogContent>
      <DialogActions sx={{ px: 3, pb: 2 }}>
        <Button onClick={onClose}>Cancel</Button>
        <Button variant="contained" color="warning" onClick={() => mutation.mutate()} disabled={mutation.isPending}>
          Archive
        </Button>
      </DialogActions>
    </Dialog>
  )
}

// ── Permanent delete dialog (archived projects only) ──────────────────────────
function DeleteProjectDialog({
  projectId, projectName, open, onClose,
}: { projectId: string; projectName: string; open: boolean; onClose: () => void }) {
  const qc = useQueryClient()
  const mutation = useMutation({
    mutationFn: () => projectsApi.delete(projectId),
    onSuccess: () => { qc.invalidateQueries({ queryKey: ['projects'] }); onClose() },
  })
  return (
    <Dialog open={open} onClose={onClose} maxWidth="xs" fullWidth>
      <DialogTitle>Permanently delete project?</DialogTitle>
      <DialogContent>
        <Typography variant="body2" gutterBottom>
          <strong>{projectName}</strong> and all its policies, implementations and checklists will be permanently deleted.
          This cannot be undone.
        </Typography>
        <Typography variant="body2" color="text.secondary">
          Assessments, gaps and evidence linked to this project will be unlinked but not deleted.
        </Typography>
      </DialogContent>
      <DialogActions sx={{ px: 3, pb: 2 }}>
        <Button onClick={onClose}>Cancel</Button>
        <Button variant="contained" color="error" onClick={() => mutation.mutate()} disabled={mutation.isPending}>
          Delete permanently
        </Button>
      </DialogActions>
    </Dialog>
  )
}

// ── Project card ──────────────────────────────────────────────────────────────
function ProjectCard({ project }: { project: ProjectRead }) {
  const navigate = useNavigate()
  const qc = useQueryClient()
  const { getActiveProject, setActiveProject } = useProject()
  const [archiveOpen, setArchiveOpen] = useState(false)
  const [deleteOpen, setDeleteOpen] = useState(false)
  const fam = project.product_family
  const isSelected = getActiveProject(fam)?.id === project.id
  const color = FAMILY_COLOR[fam] ?? '#4472C4'
  const total = TOTAL_CG[fam] ?? 53
  const statusColor = STATUS_COLOR[project.status] ?? '#9E9E9E'

  const polPct = Math.min(100, Math.round((project.policy_count / Math.max(1, total)) * 100))

  const isArchived = project.status === 'archived'

  const statusToggle = useMutation({
    mutationFn: (newStatus: string) => projectsApi.update(project.id, { status: newStatus }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['projects'] }),
  })

  function handleRestore(e: React.MouseEvent) {
    e.stopPropagation()
    statusToggle.mutate('draft')
  }

  function handleToggleActive(e: React.MouseEvent) {
    e.stopPropagation()
    if (isSelected) {
      // Deselect → mark inactive
      setActiveProject(fam, null)
      statusToggle.mutate('inactive')
    } else {
      // Select → mark active
      setActiveProject(fam, project)
      statusToggle.mutate('active')
    }
  }

  return (
    <>
      <Card sx={{
        height: '100%',
        border: '1px solid',
        borderColor: isSelected ? `${color}80` : 'divider',
        '&:hover': { borderColor: `${color}60` },
        transition: 'border-color 0.15s',
        boxShadow: isSelected ? `0 0 0 1px ${color}40` : 'none',
      }}>
        <CardActionArea onClick={() => navigate(`/projects/${project.id}`)}>
          <CardContent sx={{ pb: '8px !important' }}>
            {/* Header row */}
            <Box sx={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', mb: 1.5 }}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <Box sx={{ color, display: 'flex' }}><FolderOpenOutlined sx={{ fontSize: 22 }} /></Box>
                <Box>
                  <Typography variant="subtitle2" sx={{ fontWeight: 700, lineHeight: 1.2, fontSize: '0.88rem' }}>
                    {project.name}
                  </Typography>
                  <Typography variant="caption" color="text.secondary" sx={{ fontSize: '0.72rem' }}>
                    {project.organisation_name ?? '—'}
                  </Typography>
                </Box>
              </Box>
              <Box sx={{ display: 'flex', gap: 0.5, flexShrink: 0 }}>
                <Chip
                  label={fam}
                  size="small"
                  icon={FAMILY_ICON[fam] as any}
                  sx={{ height: 20, fontSize: '0.64rem', bgcolor: `${color}18`, color, border: `1px solid ${color}40`, '& .MuiChip-icon': { color } }}
                />
                <Chip
                  label={project.status}
                  size="small"
                  sx={{ height: 20, fontSize: '0.64rem', bgcolor: `${statusColor}18`, color: statusColor }}
                />
              </Box>
            </Box>

            {/* Counts */}
            <Box sx={{ display: 'flex', gap: 2, mb: 1.5 }}>
              {[
                { label: 'Policies', val: project.policy_count },
                { label: 'Implementations', val: project.implementation_count },
                { label: 'Checklists', val: project.checklist_count },
              ].map(({ label, val }) => (
                <Box key={label} sx={{ textAlign: 'center' }}>
                  <Typography variant="h6" sx={{ fontWeight: 700, fontSize: '1.1rem', color, lineHeight: 1 }}>{val}</Typography>
                  <Typography variant="caption" color="text.secondary" sx={{ fontSize: '0.65rem' }}>{label}</Typography>
                </Box>
              ))}
            </Box>

            {/* Completeness bar */}
            <Box sx={{ mb: 0.5 }}>
              <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 0.3 }}>
                <Typography variant="caption" sx={{ fontSize: '0.65rem', color: 'text.secondary' }}>
                  Control groups with policies
                </Typography>
                <Typography variant="caption" sx={{ fontSize: '0.65rem', color }}>
                  {Math.min(project.policy_count, total)}/{total}
                </Typography>
              </Box>
              <LinearProgress
                variant="determinate"
                value={polPct}
                sx={{ height: 4, borderRadius: 2, bgcolor: `${color}18`, '& .MuiLinearProgress-bar': { bgcolor: color } }}
              />
            </Box>

            {/* Footer — date on left, action buttons + arrow on right */}
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mt: 1.5 }}>
              <Typography variant="caption" color="text.disabled" sx={{ fontSize: '0.65rem' }}>
                Created {dayjs(project.created_at).format('D MMM YYYY')}
              </Typography>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
                {isSelected && (
                  <Chip label="Selected" size="small" sx={{ height: 18, fontSize: '0.6rem', bgcolor: `${color}20`, color }} />
                )}
                <Tooltip title={isSelected ? 'Deactivate (set inactive)' : 'Set as active project'}>
                  <IconButton
                    size="small"
                    onClick={handleToggleActive}
                    disabled={statusToggle.isPending}
                    sx={{ color: isSelected ? color : 'text.disabled', '&:hover': { color }, p: 0.4 }}
                  >
                    <FolderOpenOutlined sx={{ fontSize: 16 }} />
                  </IconButton>
                </Tooltip>
                {isArchived ? (
                  <>
                    <Tooltip title="Restore project (set to draft)">
                      <IconButton
                        size="small"
                        onClick={handleRestore}
                        disabled={statusToggle.isPending}
                        sx={{ color: 'text.disabled', '&:hover': { color: 'success.main' }, p: 0.4 }}
                      >
                        <RestoreFromTrashOutlined sx={{ fontSize: 16 }} />
                      </IconButton>
                    </Tooltip>
                    <Tooltip title="Delete permanently">
                      <IconButton
                        size="small"
                        onClick={e => { e.stopPropagation(); setDeleteOpen(true) }}
                        sx={{ color: 'text.disabled', '&:hover': { color: 'error.main' }, p: 0.4 }}
                      >
                        <DeleteOutlined sx={{ fontSize: 16 }} />
                      </IconButton>
                    </Tooltip>
                  </>
                ) : (
                  <Tooltip title="Archive project">
                    <IconButton
                      size="small"
                      onClick={e => { e.stopPropagation(); setArchiveOpen(true) }}
                      sx={{ color: 'text.disabled', '&:hover': { color: 'warning.main' }, p: 0.4 }}
                    >
                      <DeleteOutlined sx={{ fontSize: 16 }} />
                    </IconButton>
                  </Tooltip>
                )}
                <ArrowForwardOutlined sx={{ fontSize: 14, color: 'text.disabled' }} />
              </Box>
            </Box>
          </CardContent>
        </CardActionArea>
      </Card>

      <ArchiveProjectDialog
        projectId={project.id}
        projectName={project.name}
        open={archiveOpen}
        onClose={() => setArchiveOpen(false)}
      />
      <DeleteProjectDialog
        projectId={project.id}
        projectName={project.name}
        open={deleteOpen}
        onClose={() => setDeleteOpen(false)}
      />
    </>
  )
}

// ── Main page ──────────────────────────────────────────────────────────────────
export default function Projects() {
  const [createOpen, setCreateOpen] = useState(false)
  const [familyFilter, setFamilyFilter] = useState<string>('ALL')
  const [statusFilter, setStatusFilter] = useState<string>('active')

  const { data, isLoading } = useQuery({
    queryKey: ['projects', familyFilter, statusFilter],
    queryFn: () => projectsApi.list({
      product_family: familyFilter === 'ALL' ? undefined : familyFilter,
      status: statusFilter === 'ALL' ? undefined : statusFilter,
    }),
  })

  const families = ['ALL', 'ISMS', 'PRIVACY', 'CLOUD']
  const statuses = ['ALL', 'active', 'inactive', 'draft', 'archived']

  return (
    <Box>
      <PageHeader
        title="Projects"
        subtitle="Compliance workspaces — each project tracks policies, implementations and evidence for one organisation"
        actions={
          <Button variant="contained" startIcon={<AddOutlined />} size="small" onClick={() => setCreateOpen(true)}>
            New Project
          </Button>
        }
      />

      {/* Filters */}
      <Box sx={{ display: 'flex', gap: 1.5, mb: 3, flexWrap: 'wrap', alignItems: 'center' }}>
        <Box sx={{ display: 'flex', gap: 0.5 }}>
          {families.map(f => {
            const active = familyFilter === f
            const color = FAMILY_COLOR[f] ?? '#6B7A99'
            return (
              <Chip
                key={f}
                label={f}
                size="small"
                onClick={() => setFamilyFilter(f)}
                sx={{
                  height: 26, fontSize: '0.72rem', cursor: 'pointer',
                  bgcolor: active ? `${color}20` : 'transparent',
                  color: active ? color : 'text.secondary',
                  border: '1px solid',
                  borderColor: active ? `${color}60` : 'rgba(255,255,255,0.12)',
                  '&:hover': { bgcolor: `${color}12` },
                }}
              />
            )
          })}
        </Box>
        <Box sx={{ display: 'flex', gap: 0.5 }}>
          {statuses.map(s => {
            const active = statusFilter === s
            const color = STATUS_COLOR[s] ?? '#6B7A99'
            return (
              <Chip
                key={s}
                label={s}
                size="small"
                onClick={() => setStatusFilter(s)}
                sx={{
                  height: 26, fontSize: '0.72rem', cursor: 'pointer',
                  bgcolor: active ? `${color}20` : 'transparent',
                  color: active ? color : 'text.secondary',
                  border: '1px solid',
                  borderColor: active ? `${color}60` : 'rgba(255,255,255,0.12)',
                  '&:hover': { bgcolor: `${color}12` },
                }}
              />
            )
          })}
        </Box>
      </Box>

      {/* Cards grid */}
      {isLoading ? (
        <Grid container spacing={2}>
          {[...Array(6)].map((_, i) => (
            <Grid item xs={12} sm={6} md={4} key={i}>
              <Skeleton variant="rounded" height={180} />
            </Grid>
          ))}
        </Grid>
      ) : !data?.length ? (
        <Box sx={{ textAlign: 'center', py: 8 }}>
          <FolderOpenOutlined sx={{ fontSize: 48, color: 'text.disabled', mb: 1.5 }} />
          <Typography variant="h6" color="text.secondary" sx={{ mb: 0.5 }}>No projects yet</Typography>
          <Typography variant="body2" color="text.disabled" sx={{ mb: 2 }}>
            Create your first project to start building your compliance workspace
          </Typography>
          <Button variant="contained" startIcon={<AddOutlined />} onClick={() => setCreateOpen(true)}>
            New Project
          </Button>
        </Box>
      ) : (
        <Grid container spacing={2}>
          {data.map(p => (
            <Grid item xs={12} sm={6} md={4} key={p.id}>
              <ProjectCard project={p} />
            </Grid>
          ))}
        </Grid>
      )}

      <CreateProjectDialog open={createOpen} onClose={() => setCreateOpen(false)} />
    </Box>
  )
}

// isms-core-platform/frontend/src/app/pages/projects/projects.component.ts
import { Component, inject, signal, computed } from '@angular/core'
import { Router } from '@angular/router'
import { FormsModule } from '@angular/forms'
import { firstValueFrom } from 'rxjs'

import { injectQuery, injectMutation, injectQueryClient } from '@tanstack/angular-query-experimental'

import { MatCardModule } from '@angular/material/card'
import { MatButtonModule } from '@angular/material/button'
import { MatFormFieldModule } from '@angular/material/form-field'
import { MatInputModule } from '@angular/material/input'
import { MatSelectModule } from '@angular/material/select'
import { MatDialogModule, MatDialog } from '@angular/material/dialog'
import { MatIconModule } from '@angular/material/icon'
import { MatChipsModule } from '@angular/material/chips'
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner'
import { MatTooltipModule } from '@angular/material/tooltip'

import { ProjectsApiService, ProjectCreate } from '../../api/projects-api.service'
import { ProjectService } from '../../core/services/project.service'
import { AuthService } from '../../core/services/auth.service'
import { PageHeaderComponent } from '../../shared/components/page-header.component'
import { ProjectRead } from '../../shared/types'

// ── Constants ─────────────────────────────────────────────────────────────────

const FAMILY_COLOR: Record<string, string> = {
  ISMS:    '#4472C4',
  PRIVACY: '#ba68c8',
  CLOUD:   '#29b6f6',
  AI:      '#ffa726',
}

const FAMILY_ICON: Record<string, string> = {
  ISMS:    'shield',
  PRIVACY: 'lock_person',
  CLOUD:   'cloud',
  AI:      'psychology',
}

const STATUS_COLOR: Record<string, string> = {
  active:   '#00c752',
  inactive: '#FF9800',
  draft:    '#64B5F6',
  archived: '#9E9E9E',
}

const TOTAL_CG: Record<string, number> = {
  ISMS: 53, PRIVACY: 21, CLOUD: 12, AI: 10,
}

const FAMILIES = ['ALL', 'ISMS', 'PRIVACY', 'CLOUD', 'AI']
const STATUSES = ['ALL', 'active', 'inactive', 'draft', 'archived']

function famColor(fam: string): string {
  return FAMILY_COLOR[fam] ?? '#6B7A99'
}
function famIcon(fam: string): string {
  return FAMILY_ICON[fam] ?? 'folder'
}
function statusColor(s: string): string {
  return STATUS_COLOR[s] ?? '#9E9E9E'
}

function formatDate(iso: string | null): string {
  if (!iso) return '—'
  const d = new Date(iso)
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })
}

// ── Create Project Dialog ──────────────────────────────────────────────────────

@Component({
  selector: 'app-create-project-dialog',
  standalone: true,
  imports: [
    FormsModule,
    MatButtonModule, MatDialogModule, MatFormFieldModule,
    MatInputModule, MatSelectModule, MatIconModule,
    MatProgressSpinnerModule,
  ],
  template: `
    <h2 mat-dialog-title>
      New Project
      <small class="dialog-subtitle">
        Create a workspace for a specific product and organisation
      </small>
    </h2>

    <mat-dialog-content>
      @if (error()) {
        <div class="alert-error">{{ error() }}</div>
      }

      <mat-form-field appearance="outline" class="full">
        <mat-label>Project name *</mat-label>
        <input matInput [(ngModel)]="form.name" placeholder="e.g. Acme Corp ISMS 2026" />
      </mat-form-field>

      <mat-form-field appearance="outline" class="full">
        <mat-label>Product</mat-label>
        <mat-select [(ngModel)]="form.product_family" (ngModelChange)="onFamilyChange()">
          <mat-option value="ISMS">ISMS — ISO 27001:2022</mat-option>
          <mat-option value="PRIVACY">Privacy — ISO 27701:2025</mat-option>
          <mat-option value="CLOUD">Cloud — ISO 27018:2025</mat-option>
          <mat-option value="AI">AI — ISO 42001:2023</mat-option>
        </mat-select>
      </mat-form-field>

      <mat-form-field appearance="outline" class="full">
        <mat-label>Description (optional)</mat-label>
        <textarea matInput [(ngModel)]="form.description" rows="2"></textarea>
      </mat-form-field>

      <!-- Organisation selector available for super_admin via admin API -->
      @if (isSuperAdmin) {
        <div class="super-admin-note">
          <mat-icon class="icon-sm">info</mat-icon>
          Super-admin: project will be created for your organisation. Use the admin panel to reassign.
        </div>
      }
    </mat-dialog-content>

    <mat-dialog-actions align="end">
      <button mat-button [disabled]="createMutation.isPending()" mat-dialog-close>Cancel</button>
      <button mat-raised-button color="primary"
              [disabled]="createMutation.isPending()"
              (click)="submit()">
        {{ createMutation.isPending() ? 'Creating…' : 'Create' }}
      </button>
    </mat-dialog-actions>
  `,
  styles: [`
    .full { width: 100%; margin-bottom: 4px; }
    .alert-error {
      background: rgba(192,0,0,0.1);
      border: 1px solid rgba(192,0,0,0.3);
      color: var(--mat-sys-error);
      border-radius: 4px;
      padding: 8px 12px;
      font-size: 0.85rem;
      margin-bottom: 12px;
    }
    mat-dialog-content { display: flex; flex-direction: column; padding-top: 16px !important; }
    .dialog-subtitle {
      display: block;
      font-size: 0.75rem;
      font-weight: 400;
      color: var(--mat-sys-on-surface-variant);
      margin-top: 2px;
    }
    .super-admin-note {
      font-size: 0.75rem;
      color: var(--mat-sys-on-surface-variant);
      margin-bottom: 8px;
      display: flex;
      align-items: center;
      gap: 4px;
    }
  `],
})
export class CreateProjectDialogComponent {
  private projApi = inject(ProjectsApiService)
  private dialog  = inject(MatDialog)

  isSuperAdmin = false
  onCreated: () => void = () => {}

  form: ProjectCreate = { name: '', product_family: 'ISMS' }
  error = signal('')

  readonly createMutation = injectMutation(() => ({
    mutationFn: (body: ProjectCreate) => firstValueFrom(this.projApi.create(body)),
    onSuccess: () => {
      this.onCreated()
      this.dialog.closeAll()
    },
    onError: () => this.error.set('Failed to create project — try again.'),
  }))

  onFamilyChange(): void {
    // nothing extra needed — form binding handles it
  }

  submit(): void {
    if (!this.form.name.trim()) {
      this.error.set('Project name is required.')
      return
    }
    this.createMutation.mutate({ ...this.form })
  }
}

// ── Confirm Archive Dialog ─────────────────────────────────────────────────────

@Component({
  selector: 'app-archive-project-dialog',
  standalone: true,
  imports: [MatButtonModule, MatDialogModule, MatProgressSpinnerModule],
  template: `
    <h2 mat-dialog-title>Archive project?</h2>
    <mat-dialog-content>
      <p><strong>{{ projectName }}</strong> will be moved to the Archived filter.
         All policies, implementations and checklists are preserved.</p>
      <p class="note-text">
        You can restore it at any time by setting its status back to active.
      </p>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button mat-dialog-close>Cancel</button>
      <button mat-raised-button color="warn"
              [disabled]="archiveMutation.isPending()"
              (click)="archive()">
        Archive
      </button>
    </mat-dialog-actions>
  `,
  styles: [`.note-text { font-size: 0.85rem; color: var(--mat-sys-on-surface-variant); }`],
})
export class ArchiveProjectDialogComponent {
  private projApi = inject(ProjectsApiService)
  private dialog  = inject(MatDialog)

  projectId   = ''
  projectName = ''
  onArchived: () => void = () => {}

  readonly archiveMutation = injectMutation(() => ({
    mutationFn: () => firstValueFrom(this.projApi.update(this.projectId, { status: 'archived' })),
    onSuccess: () => { this.onArchived(); this.dialog.closeAll() },
  }))

  archive(): void { this.archiveMutation.mutate(undefined) }
}

// ── Confirm Delete Dialog ──────────────────────────────────────────────────────

@Component({
  selector: 'app-delete-project-dialog',
  standalone: true,
  imports: [MatButtonModule, MatDialogModule],
  template: `
    <h2 mat-dialog-title>Permanently delete project?</h2>
    <mat-dialog-content>
      <p><strong>{{ projectName }}</strong> and all its policies, implementations and checklists
         will be permanently deleted. This cannot be undone.</p>
      <p class="note-text">
        Assessments, gaps and evidence linked to this project will be unlinked but not deleted.
      </p>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button mat-dialog-close>Cancel</button>
      <button mat-raised-button color="warn"
              [disabled]="deleteMutation.isPending()"
              (click)="doDelete()">
        Delete permanently
      </button>
    </mat-dialog-actions>
  `,
  styles: [`.note-text { font-size: 0.85rem; color: var(--mat-sys-on-surface-variant); }`],
})
export class DeleteProjectDialogComponent {
  private projApi = inject(ProjectsApiService)
  private dialog  = inject(MatDialog)

  projectId   = ''
  projectName = ''
  onDeleted: () => void = () => {}

  readonly deleteMutation = injectMutation(() => ({
    mutationFn: () => firstValueFrom(this.projApi.delete(this.projectId)),
    onSuccess: () => { this.onDeleted(); this.dialog.closeAll() },
  }))

  doDelete(): void { this.deleteMutation.mutate(undefined) }
}

// ── Main Projects Component ────────────────────────────────────────────────────

@Component({
  selector: 'app-projects',
  standalone: true,
  imports: [
    FormsModule,
    MatCardModule, MatButtonModule, MatFormFieldModule,
    MatInputModule, MatSelectModule, MatDialogModule,
    MatIconModule, MatChipsModule, MatProgressSpinnerModule, MatTooltipModule,
    PageHeaderComponent,
  ],
  template: `
<div class="projects-page">

  <app-page-header
    title="Projects"
    subtitle="Compliance workspaces — each project tracks policies, implementations and evidence for one organisation"
  >
    <div actions>
      <button mat-raised-button color="primary" (click)="openCreate()">
        <mat-icon>add</mat-icon>
        New Project
      </button>
    </div>
  </app-page-header>

  <!-- Filters -->
  <div class="filters">
    <div class="filter-group">
      @for (fam of families; track fam) {
        <button class="filter-chip"
                [class.filter-chip--active]="familyFilter() === fam"
                [style.--chip-color]="famColor(fam)"
                (click)="familyFilter.set(fam)">
          @if (fam !== 'ALL') {
            <mat-icon class="filter-chip-icon">{{ famIcon(fam) }}</mat-icon>
          }
          {{ fam }}
        </button>
      }
    </div>
    <div class="filter-sep"></div>
    <div class="filter-group">
      @for (st of statuses; track st) {
        <button class="filter-chip"
                [class.filter-chip--active]="statusFilter() === st"
                [style.--chip-color]="statusColor(st)"
                (click)="statusFilter.set(st)">
          {{ st }}
        </button>
      }
    </div>
  </div>

  <!-- Loading -->
  @if (projectsQuery.isLoading()) {
    <div class="projects-grid">
      @for (n of [1,2,3,4,5,6]; track n) {
        <div class="skeleton-card"></div>
      }
    </div>
  }

  <!-- Error -->
  @if (projectsQuery.isError()) {
    <div class="empty-state">
      <mat-icon color="warn">error_outline</mat-icon>
      <span>Failed to load projects.</span>
    </div>
  }

  <!-- Empty state -->
  @if (projectsQuery.isSuccess() && (projectsQuery.data()?.length ?? 0) === 0) {
    <div class="empty-state">
      <mat-icon>folder_open</mat-icon>
      <div>
        <div class="empty-title">
          No projects yet
        </div>
        <div class="empty-subtitle">
          Create your first project to start building your compliance workspace.
        </div>
        <button mat-raised-button color="primary" (click)="openCreate()">
          <mat-icon>add</mat-icon>
          New Project
        </button>
      </div>
    </div>
  }

  <!-- Project cards -->
  @if (projectsQuery.isSuccess() && (projectsQuery.data()?.length ?? 0) > 0) {
    <div class="projects-grid">
      @for (p of projectsQuery.data()!; track p.id) {
        <mat-card class="project-card"
                  [class.project-card--selected]="isSelected(p)"
                  [style.--card-color]="famColor(p.product_family)">
          <mat-card-content (click)="router.navigate(['/projects', p.id])">
            <!-- Header row -->
            <div class="pc-header">
              <div class="pc-header__left">
                <mat-icon class="pc-family-icon" [style.color]="famColor(p.product_family)">
                  {{ famIcon(p.product_family) }}
                </mat-icon>
                <div>
                  <div class="pc-name">{{ p.name }}</div>
                  <div class="pc-org">{{ p.organisation_name ?? '—' }}</div>
                </div>
              </div>
              <div class="pc-chips">
                <span class="mini-chip"
                      [style.background]="famColor(p.product_family) + '20'"
                      [style.color]="famColor(p.product_family)"
                      [style.border-color]="famColor(p.product_family) + '50'">
                  <mat-icon class="icon-sm chip-icon">{{ famIcon(p.product_family) }}</mat-icon>
                  {{ p.product_family }}
                </span>
                <span class="mini-chip"
                      [style.background]="statusColor(p.status) + '20'"
                      [style.color]="statusColor(p.status)"
                      [style.border-color]="statusColor(p.status) + '40'">
                  {{ p.status }}
                </span>
              </div>
            </div>

            <!-- Counts row -->
            <div class="pc-counts">
              <div class="pc-count">
                <span class="pc-count__num" [style.color]="famColor(p.product_family)">
                  {{ $any(p).policy_count ?? 0 }}
                </span>
                <span class="pc-count__lbl">Policies</span>
              </div>
              <div class="pc-count">
                <span class="pc-count__num" [style.color]="famColor(p.product_family)">
                  {{ $any(p).implementation_count ?? 0 }}
                </span>
                <span class="pc-count__lbl">Implementations</span>
              </div>
              <div class="pc-count">
                <span class="pc-count__num" [style.color]="famColor(p.product_family)">
                  {{ $any(p).checklist_count ?? 0 }}
                </span>
                <span class="pc-count__lbl">Checklists</span>
              </div>
            </div>

            <!-- Completeness bar -->
            <div class="pc-bar-wrap">
              <div class="pc-bar-label">
                <span>Control groups with policies</span>
                <span [style.color]="famColor(p.product_family)">
                  {{ minVal($any(p).policy_count ?? 0, totalCg(p.product_family)) }}/{{ totalCg(p.product_family) }}
                </span>
              </div>
              <div class="progress-track">
                <div class="progress-fill"
                     [style.width.%]="polPct(p)"
                     [style.background]="famColor(p.product_family)">
                </div>
              </div>
            </div>
          </mat-card-content>

          <!-- Footer row (outside click area to avoid navigate) -->
          <div class="pc-footer" (click)="$event.stopPropagation()">
            <span class="pc-date">Created {{ formatDate(p.created_at) }}</span>
            <div class="pc-actions">
              @if (isSelected(p)) {
                <span class="mini-chip mini-chip--selected"
                      [style.background]="famColor(p.product_family) + '20'"
                      [style.color]="famColor(p.product_family)">
                  Selected
                </span>
              }

              <!-- Toggle active -->
              <button mat-icon-button
                      [matTooltip]="isSelected(p) ? 'Deactivate' : 'Set as active project'"
                      [style.color]="isSelected(p) ? famColor(p.product_family) : ''"
                      (click)="toggleActive(p)">
                <mat-icon class="icon-md">folder_open</mat-icon>
              </button>

              @if (p.status === 'archived') {
                <!-- Restore -->
                <button mat-icon-button matTooltip="Restore project (set to draft)"
                        (click)="restoreProject(p)">
                  <mat-icon class="icon-md">restore_from_trash</mat-icon>
                </button>
                <!-- Permanent delete -->
                <button mat-icon-button matTooltip="Delete permanently"
                        (click)="openDelete(p)">
                  <mat-icon class="icon-md">delete</mat-icon>
                </button>
              } @else {
                <!-- Archive -->
                <button mat-icon-button matTooltip="Archive project"
                        (click)="openArchive(p)">
                  <mat-icon class="icon-md">archive</mat-icon>
                </button>
              }

              <mat-icon class="pc-arrow-icon"
                        (click)="router.navigate(['/projects', p.id])">
                arrow_forward
              </mat-icon>
            </div>
          </div>
        </mat-card>
      }
    </div>
  }

</div>

  `,
  styles: [`
    .projects-page {
      display: flex;
      flex-direction: column;
      gap: 16px;
      height: 100%;
      overflow-y: auto;
      box-sizing: border-box;
    }

    /* ── Filters ── */
    .filters {
      display: flex;
      align-items: center;
      gap: 8px;
      flex-wrap: wrap;
    }
    .filter-group { display: flex; gap: 4px; flex-wrap: wrap; }
    .filter-sep {
      width: 1px;
      height: 24px;
      background: var(--mat-sys-outline-variant);
      flex-shrink: 0;
    }
    .filter-chip {
      display: inline-flex; align-items: center; gap: 4px;
      height: 26px;
      padding: 0 10px;
      border-radius: 13px;
      border: 1px solid var(--mat-sys-outline-variant);
      background: transparent;
      color: var(--mat-sys-on-surface-variant);
      font-size: 0.72rem;
      cursor: pointer;
      transition: background 0.12s, border-color 0.12s, color 0.12s;
    }
    .filter-chip:hover { background: rgba(var(--chip-color-rgb, 100,100,100),0.08); }
    .filter-chip-icon { font-size: 14px; width: 14px; height: 14px; line-height: 1; }
    .filter-chip--active {
      background: color-mix(in srgb, var(--chip-color, #4472C4) 16%, transparent);
      color: var(--chip-color, #4472C4);
      border-color: color-mix(in srgb, var(--chip-color, #4472C4) 50%, transparent);
    }

    /* ── Grid ── */
    .projects-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
      gap: 12px;
    }

    /* ── Skeleton ── */
    .skeleton-card {
      height: 190px;
      border-radius: 8px;
      background: var(--mat-sys-surface-container-high);
      animation: pulse 1.5s ease-in-out infinite;
    }
    @keyframes pulse { 0%,100% { opacity:1 } 50% { opacity:0.45 } }

    /* ── Project card ── */
    .project-card {
      display: flex;
      flex-direction: column;
      border: 1px solid var(--mat-sys-outline-variant) !important;
      transition: border-color 0.15s, box-shadow 0.15s;
    }
    .project-card:hover {
      border-color: color-mix(in srgb, var(--card-color, #4472C4) 40%, transparent) !important;
    }
    .project-card--selected {
      border-color: color-mix(in srgb, var(--card-color, #4472C4) 60%, transparent) !important;
      box-shadow: 0 0 0 1px color-mix(in srgb, var(--card-color, #4472C4) 30%, transparent) !important;
    }
    .project-card mat-card-content {
      padding: 12px !important;
      cursor: pointer;
      flex: 1;
    }

    /* ── Card content ── */
    .pc-header {
      display: flex;
      align-items: flex-start;
      justify-content: space-between;
      margin-bottom: 12px;
    }
    .pc-header__left { display: flex; align-items: flex-start; gap: 8px; }
    .pc-family-icon { font-size: 22px; width: 22px; height: 22px; flex-shrink: 0; margin-top: 2px; }
    .pc-name { font-size: 0.88rem; font-weight: 700; line-height: 1.2; color: var(--mat-sys-on-surface); }
    .pc-org { font-size: 0.72rem; color: var(--mat-sys-on-surface-variant); margin-top: 2px; }

    .pc-chips { display: flex; flex-direction: column; gap: 4px; align-items: flex-end; }
    .mini-chip {
      display: inline-flex;
      align-items: center;
      padding: 0 6px;
      height: 18px;
      border-radius: 9px;
      border: 1px solid;
      font-size: 0.62rem;
      font-weight: 600;
      white-space: nowrap;
    }
    .mini-chip--selected { font-size: 0.6rem; }

    .pc-counts { display: flex; gap: 16px; margin-bottom: 10px; }
    .pc-count { text-align: center; }
    .pc-count__num { display: block; font-size: 1.1rem; font-weight: 700; line-height: 1; }
    .pc-count__lbl { display: block; font-size: 0.65rem; color: var(--mat-sys-on-surface-variant); margin-top: 2px; }

    .pc-bar-wrap { display: flex; flex-direction: column; gap: 3px; }
    .pc-bar-label {
      display: flex; justify-content: space-between;
      font-size: 0.65rem; color: var(--mat-sys-on-surface-variant);
    }
    .progress-track {
      height: 4px; border-radius: 2px;
      background: var(--mat-sys-surface-container-high);
      overflow: hidden;
    }
    .progress-fill { height: 100%; border-radius: 2px; transition: width 0.3s; }

    /* ── Footer ── */
    .pc-footer {
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 6px 12px 8px;
      border-top: 1px solid var(--mat-sys-outline-variant);
    }
    .pc-date { font-size: 0.65rem; color: var(--mat-sys-on-surface-variant); }
    .pc-actions { display: flex; align-items: center; gap: 2px; }

    /* ── Empty state ── */
    .empty-state {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      gap: 12px;
      padding: 64px 24px;
      text-align: center;
      color: var(--mat-sys-on-surface-variant);
    }
    .empty-state mat-icon { font-size: 48px; width: 48px; height: 48px; opacity: 0.4; }
    .empty-title { font-size: 1rem; font-weight: 600; color: var(--mat-sys-on-surface); margin-bottom: 4px; }
    .empty-subtitle { font-size: 0.85rem; color: var(--mat-sys-on-surface-variant); margin-bottom: 16px; }
    .chip-icon { font-size: 11px; width: 11px; height: 11px; margin-right: 2px; }
    .pc-arrow-icon { font-size: 14px; width: 14px; height: 14px; color: var(--mat-sys-on-surface-variant); opacity: 0.4; }
  `],
})
export class ProjectsComponent {
  readonly router = inject(Router)
  private projApi = inject(ProjectsApiService)
  private projSvc = inject(ProjectService)
  private authSvc = inject(AuthService)
  private dialog  = inject(MatDialog)

  readonly familyFilter = signal('ALL')
  readonly statusFilter = signal('active')

  readonly families = FAMILIES
  readonly statuses = STATUSES

  // ── Query client for invalidation ───────────────────────────────────────────
  private qc = injectQueryClient()

  // ── Projects list query ──────────────────────────────────────────────────────
  readonly projectsQuery = injectQuery(() => ({
    queryKey: ['projects', this.familyFilter(), this.statusFilter()],
    queryFn: () => firstValueFrom(this.projApi.list({
      product_family: this.familyFilter() === 'ALL' ? undefined : this.familyFilter(),
      status:         this.statusFilter() === 'ALL' ? undefined : this.statusFilter(),
    })),
    staleTime: 30_000,
  }))

  // ── Status toggle mutation ───────────────────────────────────────────────────
  readonly statusMutation = injectMutation(() => ({
    mutationFn: ({ id, status }: { id: string; status: string }) =>
      firstValueFrom(this.projApi.update(id, { status })),
    onSuccess: () => this.qc.invalidateQueries({ queryKey: ['projects'] }),
  }))

  // ── Helpers ──────────────────────────────────────────────────────────────────
  famColor(fam: string):   string { return famColor(fam) }
  famIcon(fam: string):    string { return famIcon(fam) }
  statusColor(st: string): string { return statusColor(st) }
  formatDate(iso: string | null): string { return formatDate(iso) }

  totalCg(fam: string): number { return TOTAL_CG[fam] ?? 53 }
  minVal(a: number, b: number): number { return Math.min(a, b) }

  polPct(p: ProjectRead): number {
    const count = (p as any).policy_count ?? 0
    const total = TOTAL_CG[p.product_family] ?? 53
    return Math.min(100, Math.round((count / Math.max(1, total)) * 100))
  }

  isSelected(p: ProjectRead): boolean {
    return this.projSvc.getActiveProject(p.product_family)?.id === p.id
  }

  // ── Actions ──────────────────────────────────────────────────────────────────
  openCreate(): void {
    const ref = this.dialog.open(CreateProjectDialogComponent, { maxWidth: '520px', width: '100%' })
    const instance = ref.componentInstance
    instance.isSuperAdmin = this.authSvc.isSuperAdmin()
    instance.onCreated = () => this.qc.invalidateQueries({ queryKey: ['projects'] })
  }

  toggleActive(p: ProjectRead): void {
    const fam = p.product_family
    if (this.isSelected(p)) {
      this.projSvc.setActiveProject(fam, null)
    } else {
      this.projSvc.setActiveProject(fam, p)
    }
  }

  restoreProject(p: ProjectRead): void {
    this.statusMutation.mutate({ id: p.id, status: 'draft' })
  }

  openArchive(p: ProjectRead): void {
    const ref = this.dialog.open(ArchiveProjectDialogComponent, { maxWidth: '420px', width: '100%' })
    const inst = ref.componentInstance
    inst.projectId   = p.id
    inst.projectName = p.name
    inst.onArchived  = () => this.qc.invalidateQueries({ queryKey: ['projects'] })
  }

  openDelete(p: ProjectRead): void {
    const ref = this.dialog.open(DeleteProjectDialogComponent, { maxWidth: '420px', width: '100%' })
    const inst = ref.componentInstance
    inst.projectId  = p.id
    inst.projectName = p.name
    inst.onDeleted  = () => this.qc.invalidateQueries({ queryKey: ['projects'] })
  }
}
